package com.sami.app.sales.service;

import com.sami.app.common.exception.*; import com.sami.app.common.tenancy.TenantContext; import com.sami.app.crm.repository.CustomerRepository;
import com.sami.app.inventory.publicapi.InventoryStockOperations; import com.sami.app.inventory.publicapi.InventoryStockOperations.CustomerReturnCommand; import com.sami.app.inventory.publicapi.InventoryStockOperations.ReservationCommand; import com.sami.app.inventory.publicapi.InventoryStockOperations.StockLine;
import com.sami.app.product.domain.Product; import com.sami.app.product.repository.ProductRepository; import com.sami.app.sales.domain.*; import com.sami.app.sales.dto.SalesDtos.*; import com.sami.app.sales.event.SaleDomainEvent; import com.sami.app.sales.repository.*; import com.sami.app.security.CurrentActor;
import lombok.RequiredArgsConstructor; import org.springframework.beans.factory.annotation.Value; import org.springframework.context.ApplicationEventPublisher; import org.springframework.data.domain.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.math.*; import java.time.*; import java.util.*;

@Service @RequiredArgsConstructor
public class SalesService {
 private final SaleRepository sales; private final SaleNumberRepository numbers; private final SaleReturnNumberRepository returnNumbers; private final SaleDiscountRepository discounts; private final SaleAuditRepository audits; private final SaleReturnRepository returns; private final LostSaleRepository lostSales; private final SaleAiRecommendationRepository aiRecommendations;
 private final ProductRepository products; private final CustomerRepository customers; private final TenantContext tenantContext; private final InventoryStockOperations inventory; private final JdbcTemplate jdbc; private final ApplicationEventPublisher events; private final List<com.sami.app.sales.spi.SalesRecommendationProvider> recommendationProviders;
 @Value("${app.sales.max-unapproved-discount-percent:10}") private BigDecimal maxUnapprovedDiscountPercent;
 @Value("${app.sales.minimum-profit-percent:5}") private BigDecimal minimumProfitPercent;
 @Value("${app.sales.commission-profit-percent:2}") private BigDecimal commissionProfitPercent;

 @Transactional(readOnly=true) public Page<SaleResponse> list(Pageable pageable,ReportFilter filter){Long t=tenantContext.requireTenantId();return sales.findAll(spec(t,filter),pageable).map(SaleResponse::from);}
 @Transactional(readOnly=true) public SaleResponse get(Long id){return SaleResponse.from(find(id));}
 @Transactional public SaleResponse create(SaleRequest r){Long t=tenantContext.requireTenantId();validateScope(t,r.companyId(),r.branchId());
  if(r.idempotencyKey()!=null){var prior=sales.findByTenantIdAndIdempotencyKey(t,r.idempotencyKey());if(prior.isPresent())return SaleResponse.from(prior.get());}
  requireCustomer(t,r.customerId()); Sale s=Sale.builder().tenantId(t).companyId(r.companyId()).branchId(r.branchId()).invoiceNumber(nextNumber(t)).idempotencyKey(r.idempotencyKey()).customerId(r.customerId()).sellerId(requireActor()).saleType(r.saleType().toUpperCase(Locale.ROOT)).status(SaleStatus.DRAFT).currency(r.currency()==null?"IRR":r.currency().toUpperCase(Locale.ROOT)).notes(r.notes()).createdBy(CurrentActor.id()).createdByEmail(CurrentActor.email()).build();
  applyItems(s,r.items()); applyServices(s,r.services()); recalculate(s); sales.saveAndFlush(s); audit(s,"CREATED",null,Map.of("invoiceNumber",s.getInvoiceNumber())); publish(s,"CREATED",Map.of()); return SaleResponse.from(s); }
 @Transactional public SaleResponse update(Long id,SaleRequest r){Sale s=find(id); requireStatus(s,SaleStatus.DRAFT); if(r.expectedVersion()!=null&&!r.expectedVersion().equals(s.getVersion()))throw conflict(); validateScope(s.getTenantId(),r.companyId(),r.branchId());requireCustomer(s.getTenantId(),r.customerId());
  Map<String,Object> before=snapshot(s);s.setCompanyId(r.companyId());s.setBranchId(r.branchId());s.setCustomerId(r.customerId());s.setSaleType(r.saleType().toUpperCase(Locale.ROOT));s.setCurrency(r.currency()==null?"IRR":r.currency().toUpperCase(Locale.ROOT));s.setNotes(r.notes());applyItems(s,r.items());applyServices(s,r.services());recalculate(s);audit(s,"UPDATED",before,snapshot(s));return SaleResponse.from(s); }
 @Transactional public SaleResponse requestDiscount(Long id,DiscountRequest r){Sale s=find(id);requireStatus(s,SaleStatus.DRAFT);String type=r.type().toUpperCase(Locale.ROOT);if(!Set.of("AMOUNT","PERCENT","VIP","CAMPAIGN","COUPON","GIFT").contains(type))throw new ApiException(ErrorCode.BAD_REQUEST,"Unsupported discount type");recalculate(s);BigDecimal requested=money(r.amount());if("PERCENT".equals(type)){if(requested.compareTo(BigDecimal.valueOf(100))>0)throw new ApiException(ErrorCode.BAD_REQUEST,"Discount percent cannot exceed 100");requested=money(s.getSubtotal().multiply(requested).divide(BigDecimal.valueOf(100),2,RoundingMode.HALF_UP));}if(requested.compareTo(s.getFinalAmount())>0)throw new ApiException(ErrorCode.BAD_REQUEST,"Discount cannot exceed sale amount");String status=needsApproval(s,requested)?"PENDING":"APPROVED";SaleDiscount d=SaleDiscount.builder().sale(s).tenantId(s.getTenantId()).discountType(type).amount(requested).reason(r.reason()).status(status).requestedBy(CurrentActor.id()).approvedBy("APPROVED".equals(status)?CurrentActor.id():null).decidedAt("APPROVED".equals(status)?Instant.now():null).build();discounts.save(d);if("APPROVED".equals(status)){s.setDiscountTotal(money(s.getDiscountTotal().add(requested)));finishTotals(s);}audit(s,"DISCOUNT_REQUESTED",null,Map.of("amount",d.getAmount(),"status",status));return SaleResponse.from(s);}
 @Transactional public SaleResponse decideDiscount(Long saleId,Long discountId,DecisionRequest r){Sale s=find(saleId);SaleDiscount d=discounts.findByIdAndTenantId(discountId,s.getTenantId()).filter(x->x.getSale().getId().equals(saleId)).orElseThrow(()->ResourceNotFoundException.of("Sale discount",discountId));if(!"PENDING".equals(d.getStatus()))throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Discount is not pending");d.setStatus(r.approved()?"APPROVED":"REJECTED");d.setApprovedBy(CurrentActor.id());d.setDecidedAt(Instant.now());if(r.approved()){s.setDiscountTotal(money(s.getDiscountTotal().add(d.getAmount())));finishTotals(s);}audit(s,r.approved()?"DISCOUNT_APPROVED":"DISCOUNT_REJECTED",null,Map.of("discountId",discountId));return SaleResponse.from(s);}
 @Transactional public SaleResponse addPayment(Long id,PaymentRequest r){Sale s=find(id);if(s.getStatus()!=SaleStatus.DRAFT&&s.getStatus()!=SaleStatus.CONFIRMED)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Sale cannot accept payments");String method=r.method().toUpperCase(Locale.ROOT);if(!Set.of("CASH","CARD","TRANSFER","CHEQUE","WALLET","INSTALLMENT").contains(method))throw new ApiException(ErrorCode.BAD_REQUEST,"Unsupported payment method");BigDecimal existing=s.getPayments().stream().filter(p->!"FAILED".equals(p.getStatus())&&!"REVERSED".equals(p.getStatus())).map(p->p.getAmount().subtract(p.getReversedAmount())).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal amount=money(r.amount());if(existing.add(amount).compareTo(s.getFinalAmount())>0)throw new ApiException(ErrorCode.BAD_REQUEST,"Payments cannot exceed the final amount");String status=Set.of("CHEQUE","INSTALLMENT").contains(method)?"PENDING":"CAPTURED";SalePayment p=SalePayment.builder().sale(s).tenantId(s.getTenantId()).method(method).status(status).amount(amount).referenceNo(r.referenceNo()).providerReference(r.providerReference()).createdBy(CurrentActor.id()).build();s.getPayments().add(p);audit(s,"PAYMENT_ADDED",null,Map.of("method",method,"amount",p.getAmount(),"status",status));return SaleResponse.from(s);}
 @Transactional public SaleResponse confirm(Long id){Sale s=find(id);requireStatus(s,SaleStatus.DRAFT);if(discounts.existsBySaleIdAndTenantIdAndStatus(id,s.getTenantId(),"PENDING"))throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Discount approval is pending");BigDecimal margin=s.getFinalAmount().signum()==0?BigDecimal.ZERO:s.getProfit().multiply(BigDecimal.valueOf(100)).divide(s.getFinalAmount(),2,RoundingMode.HALF_UP);if(margin.compareTo(minimumProfitPercent)<0&&!discounts.existsBySaleIdAndTenantIdAndStatus(id,s.getTenantId(),"APPROVED"))throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Low-profit sale requires manager approval");reserveStock(s);s.setStatus(SaleStatus.CONFIRMED);s.setConfirmedAt(Instant.now());audit(s,"CONFIRMED",null,snapshot(s));publish(s,"CONFIRMED",Map.of("amount",s.getFinalAmount()));return SaleResponse.from(s);}
 @Transactional public SaleResponse complete(Long id){Sale s=find(id);requireStatus(s,SaleStatus.CONFIRMED);BigDecimal paid=s.getPayments().stream().filter(p->"CAPTURED".equals(p.getStatus())).map(SalePayment::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add);if(paid.compareTo(s.getFinalAmount())!=0)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Captured payments must equal the final amount");issueStock(s);s.setStatus(SaleStatus.COMPLETED);s.setCompletedAt(Instant.now());postAccounting(s,"SALE",s.getFinalAmount(),null);audit(s,"COMPLETED",null,snapshot(s));publish(s,"COMPLETED",Map.of("amount",s.getFinalAmount()));return SaleResponse.from(s);}
 @Transactional public SaleResponse cancel(Long id,CancelRequest r){Sale s=find(id);if(s.getStatus()==SaleStatus.CANCELLED||s.getStatus()==SaleStatus.RETURNED)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Sale is already terminal");if(s.getStatus()==SaleStatus.COMPLETED||s.getStatus()==SaleStatus.PARTIALLY_RETURNED)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Completed sales must be returned");if(s.getStatus()==SaleStatus.CONFIRMED)releaseStock(s);reversePayments(s,s.getFinalAmount());s.setStatus(SaleStatus.CANCELLED);s.setCancelledAt(Instant.now());s.setCancellationReason(r.reason());audit(s,"CANCELLED",null,Map.of("reason",r.reason()));publish(s,"CANCELLED",Map.of());return SaleResponse.from(s);}
 @Transactional public SaleResponse createReturn(Long id,ReturnRequest r){Sale s=find(id);if(s.getStatus()!=SaleStatus.COMPLETED&&s.getStatus()!=SaleStatus.PARTIALLY_RETURNED)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Only completed sales can be returned");String refund=r.refundMethod().toUpperCase(Locale.ROOT);if(!Set.of("CASH","CARD","TRANSFER","WALLET").contains(refund))throw new ApiException(ErrorCode.BAD_REQUEST,"Unsupported refund method");SaleReturn ret=SaleReturn.builder().sale(s).tenantId(s.getTenantId()).returnNumber(nextReturnNumber(s.getTenantId())).reason(r.reason()).refundMethod(refund).totalAmount(BigDecimal.ZERO).createdBy(CurrentActor.id()).build();returns.saveAndFlush(ret);BigDecimal total=BigDecimal.ZERO;Set<Long> seen=new HashSet<>();for(ReturnLine line:r.items()){if(!seen.add(line.saleItemId()))throw new ApiException(ErrorCode.BAD_REQUEST,"Duplicate return item");SaleItem item=s.getItems().stream().filter(i->i.getId().equals(line.saleItemId())).findFirst().orElseThrow(()->ResourceNotFoundException.of("Sale item",line.saleItemId()));BigDecimal remaining=item.getQuantity().subtract(item.getReturnedQuantity());if(line.quantity().compareTo(remaining)>0)throw new ApiException(ErrorCode.BAD_REQUEST,"Return quantity exceeds remaining quantity");BigDecimal amount=item.getLineTotal().multiply(line.quantity()).divide(item.getQuantity(),2,RoundingMode.HALF_UP);item.setReturnedQuantity(item.getReturnedQuantity().add(line.quantity()));ret.getItems().add(SaleReturnItem.builder().saleReturn(ret).saleItem(item).quantity(line.quantity()).amount(amount).build());restoreStock(s,ret,item,line.quantity());total=total.add(amount);}ret.setTotalAmount(total);returns.save(ret);reversePayments(s,total);postAccounting(s,"RETURN",total,null);boolean all=s.getItems().stream().allMatch(i->i.getReturnedQuantity().compareTo(i.getQuantity())==0);s.setStatus(all?SaleStatus.RETURNED:SaleStatus.PARTIALLY_RETURNED);audit(s,"RETURNED",null,Map.of("returnNumber",ret.getReturnNumber(),"amount",total));publish(s,"RETURNED",Map.of("amount",total));return SaleResponse.from(s);}
 @Transactional(readOnly=true) public List<AuditResponse> audit(Long id){Sale s=find(id);return audits.findBySaleIdAndTenantIdOrderByOccurredAtDesc(id,s.getTenantId()).stream().map(AuditResponse::from).toList();}
 @Transactional(readOnly=true) public List<DiscountResponse> discountHistory(Long id){Sale s=find(id);return discounts.findBySaleIdAndTenantIdOrderByRequestedAtAsc(id,s.getTenantId()).stream().map(DiscountResponse::from).toList();}
 @Transactional(readOnly=true) public DashboardResponse dashboard(){Long t=tenantContext.requireTenantId();BigDecimal[] sums=jdbc.queryForObject("select coalesce(sum(final_amount) filter(where status in ('COMPLETED','PARTIALLY_RETURNED','RETURNED')),0),coalesce(sum(profit) filter(where status in ('COMPLETED','PARTIALLY_RETURNED','RETURNED')),0) from sales where tenant_id=?",(rs,n)->new BigDecimal[]{rs.getBigDecimal(1),rs.getBigDecimal(2)},t);return new DashboardResponse(sales.countByTenantIdAndStatus(t,SaleStatus.DRAFT),sales.countByTenantIdAndStatus(t,SaleStatus.CONFIRMED),sales.countByTenantIdAndStatus(t,SaleStatus.COMPLETED),sales.countByTenantIdAndStatus(t,SaleStatus.CANCELLED),sums[0],sums[1]);}
 @Transactional(readOnly=true) public SalesReportResponse report(ReportFilter filter){Long t=tenantContext.requireTenantId();List<Object> args=new ArrayList<>(List.of(t));String where=reportWhere(filter,args,"s");Object[] values=args.toArray();Map<String,Object> totals=jdbc.queryForMap("select coalesce(sum(s.final_amount) filter(where s.status in ('COMPLETED','PARTIALLY_RETURNED','RETURNED')),0) revenue,coalesce(sum(s.profit) filter(where s.status in ('COMPLETED','PARTIALLY_RETURNED','RETURNED')),0) profit,coalesce(sum(s.discount_total),0) discounts,count(*) invoices from sales s where "+where,values);BigDecimal revenue=(BigDecimal)totals.get("revenue"),profit=(BigDecimal)totals.get("profit"),discountTotal=(BigDecimal)totals.get("discounts");long invoices=((Number)totals.get("invoices")).longValue();BigDecimal average=invoices==0?BigDecimal.ZERO:money(revenue.divide(BigDecimal.valueOf(invoices),2,RoundingMode.HALF_UP));BigDecimal discountRate=revenue.add(discountTotal).signum()==0?BigDecimal.ZERO:money(discountTotal.multiply(BigDecimal.valueOf(100)).divide(revenue.add(discountTotal),2,RoundingMode.HALF_UP));Long returned=jdbc.queryForObject("select count(*) from sales s where "+where+" and s.status in ('PARTIALLY_RETURNED','RETURNED')",Long.class,values);BigDecimal returnRate=invoices==0?BigDecimal.ZERO:money(BigDecimal.valueOf(returned==null?0:returned).multiply(BigDecimal.valueOf(100)).divide(BigDecimal.valueOf(invoices),2,RoundingMode.HALF_UP));Long lost=jdbc.queryForObject("select count(*) from lost_sales where tenant_id=?",Long.class,t);return new SalesReportResponse(revenue,profit,average,discountRate,returnRate,invoices,lost==null?0:lost,metricQuery("select to_char(s.created_at,'YYYY-MM-DD') label,coalesce(sum(s.final_amount),0) value,count(*) count from sales s where "+where+" group by 1 order by 1",values),metricQuery("select p.method label,coalesce(sum(p.amount-p.reversed_amount),0) value,count(*) count from sale_payments p join sales s on s.id=p.sale_id where "+where+" group by p.method order by value desc",values),metricQuery("select i.product_name label,coalesce(sum(i.line_total),0) value,count(*) count from sale_items i join sales s on s.id=i.sale_id where "+where+" group by i.product_name order by value desc limit 10",values),metricQuery("select coalesce(u.email,s.seller_id::text) label,coalesce(sum(s.final_amount),0) value,count(*) count from sales s left join users u on u.id=s.seller_id where "+where+" group by 1 order by value desc limit 10",values));}
 @Transactional(readOnly=true) public byte[] exportCsv(ReportFilter filter){Long t=tenantContext.requireTenantId();StringBuilder out=new StringBuilder("\uFEFFInvoice,Status,Type,Amount,Profit,Created\r\n");for(Sale s:sales.findAll(spec(t,filter),PageRequest.of(0,10000,Sort.by(Sort.Direction.DESC,"createdAt"))))out.append(csv(s.getInvoiceNumber())).append(',').append(s.getStatus()).append(',').append(csv(s.getSaleType())).append(',').append(s.getFinalAmount()).append(',').append(s.getProfit()).append(',').append(s.getCreatedAt()).append("\r\n");return out.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8);}
 @Transactional(readOnly=true) public List<AccountingEntryResponse> accounting(Long id){Sale s=find(id);return jdbc.query("select id,entry_type,account_code,debit,credit,reference_no,posted_at from sale_accounting_entries where tenant_id=? and sale_id=? order by posted_at,id",(rs,n)->new AccountingEntryResponse(rs.getLong("id"),rs.getString("entry_type"),rs.getString("account_code"),rs.getBigDecimal("debit"),rs.getBigDecimal("credit"),rs.getString("reference_no"),rs.getTimestamp("posted_at").toInstant()),s.getTenantId(),s.getId());}
 @Transactional(readOnly=true) public Page<LostSaleResponse> lostSales(Pageable pageable){return lostSales.findByTenantIdOrderByOccurredAtDesc(tenantContext.requireTenantId(),pageable).map(LostSaleResponse::from);}
 @Transactional public LostSaleResponse recordLostSale(LostSaleRequest r){Long t=tenantContext.requireTenantId();validateScope(t,r.companyId(),r.branchId());if(r.customerId()!=null)requireCustomer(t,r.customerId());if(r.productId()!=null)requireTenantRow("products",r.productId(),t);LostSale row=lostSales.save(LostSale.builder().tenantId(t).companyId(r.companyId()).branchId(r.branchId()).customerId(r.customerId()).productId(r.productId()).sellerId(requireActor()).reasonCode(r.reasonCode().toUpperCase(Locale.ROOT)).notes(r.notes()).expectedAmount(money(r.expectedAmount()==null?BigDecimal.ZERO:r.expectedAmount())).occurredAt(r.occurredAt()==null?Instant.now():r.occurredAt()).build());events.publishEvent(new SaleDomainEvent(t,r.companyId(),r.branchId(),null,null,"LOST_SALE_RECORDED",Map.of("reason",row.getReasonCode()),CurrentActor.id(),Instant.now()));return LostSaleResponse.from(row);}
 @Transactional public AiResponse recommend(AiRequest request){Long t=tenantContext.requireTenantId();if(request.saleId()!=null)find(request.saleId());Map<String,Object> context=request.context()==null?Map.of():request.context();var provider=recommendationProviders.stream().findFirst();Map<String,Object> result=provider.map(p->p.recommend(request.type(),context)).orElseGet(()->Map.of("status","UNAVAILABLE","message","No Sales AI provider is registered"));SaleAiRecommendation row=aiRecommendations.save(SaleAiRecommendation.builder().tenantId(t).saleId(request.saleId()).recommendationType(request.type().toUpperCase(Locale.ROOT)).requestData(context).resultData(result).modelKey(provider.map(com.sami.app.sales.spi.SalesRecommendationProvider::key).orElse(null)).createdBy(CurrentActor.id()).build());return new AiResponse(row.getId(),provider.isPresent(),row.getModelKey(),result);}

 private Sale find(Long id){return sales.findByIdAndTenantId(id,tenantContext.requireTenantId()).orElseThrow(()->ResourceNotFoundException.of("Sale",id));}
 private org.springframework.data.jpa.domain.Specification<Sale> spec(Long tenantId,ReportFilter f){org.springframework.data.jpa.domain.Specification<Sale> result=(root,q,cb)->cb.equal(root.get("tenantId"),tenantId);if(f==null)return result;if(f.from()!=null)result=result.and((root,q,cb)->cb.greaterThanOrEqualTo(root.get("createdAt"),f.from()));if(f.to()!=null)result=result.and((root,q,cb)->cb.lessThan(root.get("createdAt"),f.to()));if(f.branchId()!=null)result=result.and((root,q,cb)->cb.equal(root.get("branchId"),f.branchId()));if(f.sellerId()!=null)result=result.and((root,q,cb)->cb.equal(root.get("sellerId"),f.sellerId()));if(f.status()!=null&&!f.status().isBlank()){SaleStatus value=parseStatus(f.status());result=result.and((root,q,cb)->cb.equal(root.get("status"),value));}if(f.saleType()!=null&&!f.saleType().isBlank())result=result.and((root,q,cb)->cb.equal(root.get("saleType"),f.saleType().toUpperCase(Locale.ROOT)));return result;}
 private String reportWhere(ReportFilter f,List<Object> args,String alias){StringBuilder out=new StringBuilder(alias+".tenant_id=?");if(f==null)return out.toString();if(f.from()!=null){out.append(" and ").append(alias).append(".created_at>=?");args.add(java.sql.Timestamp.from(f.from()));}if(f.to()!=null){out.append(" and ").append(alias).append(".created_at<?");args.add(java.sql.Timestamp.from(f.to()));}if(f.branchId()!=null){out.append(" and ").append(alias).append(".branch_id=?");args.add(f.branchId());}if(f.sellerId()!=null){out.append(" and ").append(alias).append(".seller_id=?");args.add(f.sellerId());}if(f.status()!=null&&!f.status().isBlank()){out.append(" and ").append(alias).append(".status=?");args.add(parseStatus(f.status()).name());}if(f.saleType()!=null&&!f.saleType().isBlank()){out.append(" and ").append(alias).append(".sale_type=?");args.add(f.saleType().toUpperCase(Locale.ROOT));}return out.toString();}
 private List<MetricPoint> metricQuery(String sql,Object[] args){return jdbc.query(sql,(rs,n)->new MetricPoint(rs.getString("label"),rs.getBigDecimal("value"),rs.getLong("count")),args);}
 private SaleStatus parseStatus(String value){try{return SaleStatus.valueOf(value.toUpperCase(Locale.ROOT));}catch(IllegalArgumentException ex){throw new ApiException(ErrorCode.BAD_REQUEST,"Unsupported sale status");}}
 private void applyItems(Sale s,List<ItemRequest> lines){s.getItems().clear();for(ItemRequest r:lines){Product p=products.findById(r.productId()).orElseThrow(()->ResourceNotFoundException.of("Product",r.productId()));requireTenantRow("products",p.getId(),s.getTenantId());BigDecimal q=r.quantity();BigDecimal price=money(r.unitPrice()),cost=money(r.costPrice()==null?BigDecimal.ZERO:r.costPrice()),disc=money(r.discount()==null?BigDecimal.ZERO:r.discount()),tax=money(r.tax()==null?BigDecimal.ZERO:r.tax());BigDecimal line=money(price.multiply(q).subtract(disc).add(tax));s.getItems().add(SaleItem.builder().sale(s).tenantId(s.getTenantId()).productId(p.getId()).productSku(p.getSku()).productName(p.getName()).serialNumber(blank(r.serialNumber())).imei(blank(r.imei())).quantity(q).unitPrice(price).costPrice(cost).discount(disc).tax(tax).lineTotal(line).profit(money(line.subtract(cost.multiply(q)))).build());}}
 private void applyServices(Sale s,List<ServiceRequest> lines){s.getServices().clear();if(lines==null)return;for(ServiceRequest r:lines)s.getServices().add(SaleServiceLine.builder().sale(s).tenantId(s.getTenantId()).serviceType(r.serviceType().toUpperCase(Locale.ROOT)).description(r.description()).price(money(r.price())).cost(money(r.cost()==null?BigDecimal.ZERO:r.cost())).employeeId(r.employeeId()).build());}
 private void recalculate(Sale s){BigDecimal subtotal=s.getItems().stream().map(i->i.getUnitPrice().multiply(i.getQuantity())).reduce(BigDecimal.ZERO,BigDecimal::add).add(s.getServices().stream().map(SaleServiceLine::getPrice).reduce(BigDecimal.ZERO,BigDecimal::add));BigDecimal itemDisc=s.getItems().stream().map(SaleItem::getDiscount).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal approved=s.getId()==null?BigDecimal.ZERO:discounts.findBySaleIdAndTenantIdOrderByRequestedAtAsc(s.getId(),s.getTenantId()).stream().filter(d->Set.of("APPROVED","NOT_REQUIRED").contains(d.getStatus())).map(SaleDiscount::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal tax=s.getItems().stream().map(SaleItem::getTax).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal cost=s.getItems().stream().map(i->i.getCostPrice().multiply(i.getQuantity())).reduce(BigDecimal.ZERO,BigDecimal::add).add(s.getServices().stream().map(SaleServiceLine::getCost).reduce(BigDecimal.ZERO,BigDecimal::add));s.setSubtotal(money(subtotal));s.setTaxTotal(money(tax));s.setCostTotal(money(cost));s.setDiscountTotal(money(itemDisc.add(approved)));finishTotals(s);}
 private void finishTotals(Sale s){s.setFinalAmount(money(s.getSubtotal().subtract(s.getDiscountTotal()).add(s.getTaxTotal())).max(BigDecimal.ZERO));s.setProfit(money(s.getFinalAmount().subtract(s.getCostTotal())));s.setCommissionAmount(money(s.getProfit().max(BigDecimal.ZERO).multiply(commissionProfitPercent).divide(BigDecimal.valueOf(100),2,RoundingMode.HALF_UP)));}
 private boolean needsApproval(Sale s,BigDecimal amount){if(s.getSubtotal().signum()==0)return amount.signum()>0;BigDecimal pct=amount.multiply(BigDecimal.valueOf(100)).divide(s.getSubtotal(),2,RoundingMode.HALF_UP);BigDecimal margin=s.getFinalAmount().signum()==0?BigDecimal.ZERO:s.getProfit().multiply(BigDecimal.valueOf(100)).divide(s.getFinalAmount(),2,RoundingMode.HALF_UP);return pct.compareTo(maxUnapprovedDiscountPercent)>0||margin.compareTo(minimumProfitPercent)<0;}
 private void validateScope(Long t,Long c,Long b){Integer ok=jdbc.queryForObject("select count(*) from branches b join companies c on c.id=b.company_id where b.id=? and c.id=? and b.tenant_id=? and c.tenant_id=? and b.is_active and c.is_active",Integer.class,b,c,t,t);if(ok==null||ok!=1)throw new ApiException(ErrorCode.ACCESS_DENIED,"Company/branch is outside the trusted tenant");}
 private void requireCustomer(Long t,Long id){if(!customers.existsById(id))throw ResourceNotFoundException.of("Customer",id);requireTenantRow("customers",id,t);}
 private void requireTenantRow(String table,Long id,Long t){Integer n=jdbc.queryForObject("select count(*) from "+table+" where id=? and tenant_id=?",Integer.class,id,t);if(n==null||n!=1)throw new ApiException(ErrorCode.ACCESS_DENIED,"Cross-tenant reference is not permitted");}
 private String nextNumber(Long t){int y=Year.now(ZoneOffset.UTC).getValue();SaleNumber n=numbers.findByTenantIdAndSequenceYear(t,y).orElseGet(()->numbers.saveAndFlush(SaleNumber.builder().tenantId(t).sequenceYear(y).nextValue(1).build()));long value=n.getNextValue();n.setNextValue(value+1);return "SAL-%d-%06d".formatted(y,value);}
 private String nextReturnNumber(Long t){SaleReturnNumber n=returnNumbers.findForUpdate(t).orElseGet(()->returnNumbers.saveAndFlush(SaleReturnNumber.builder().tenantId(t).nextValue(1L).build()));long value=n.getNextValue();n.setNextValue(value+1);return "RET-%d-%06d".formatted(Year.now(ZoneOffset.UTC).getValue(),value);}
 private void reserveStock(Sale s){inventory.reserve(new ReservationCommand(s.getCompanyId(),s.getBranchId(),"SALE",s.getId(),s.getItems().stream().map(i->new StockLine(i.getId(),i.getProductId(),i.getQuantity(),i.getSerialNumber(),i.getImei())).toList()));}
 private void releaseStock(Sale s){inventory.release("SALE",s.getId(),"Sale cancelled");}
 private void issueStock(Sale s){inventory.issue("SALE",s.getId());}
 private void restoreStock(Sale s,SaleReturn ret,SaleItem i,BigDecimal q){inventory.customerReturn(new CustomerReturnCommand(s.getCompanyId(),s.getBranchId(),"SALE_RETURN",ret.getId(),List.of(new StockLine(i.getId(),i.getProductId(),q,i.getSerialNumber(),i.getImei()))));}
 private void reversePayments(Sale s,BigDecimal amount){BigDecimal left=amount;for(SalePayment p:s.getPayments()){if(left.signum()<=0)break;BigDecimal available=p.getAmount().subtract(p.getReversedAmount());BigDecimal take=available.min(left);p.setReversedAmount(p.getReversedAmount().add(take));p.setStatus(p.getReversedAmount().compareTo(p.getAmount())==0?"REVERSED":"PARTIALLY_REVERSED");left=left.subtract(take);}}
 private void postAccounting(Sale s,String type,BigDecimal amount,Long reversed){boolean sale="SALE".equals(type);String ref=s.getInvoiceNumber()+"-"+type;jdbc.update("insert into sale_accounting_entries(tenant_id,sale_id,entry_type,account_code,debit,credit,reference_no,reversed_entry_id) values(?,?,?,?,?,?,?,?)",s.getTenantId(),s.getId(),type,"CASH_OR_RECEIVABLE",sale?amount:BigDecimal.ZERO,sale?BigDecimal.ZERO:amount,ref,reversed);jdbc.update("insert into sale_accounting_entries(tenant_id,sale_id,entry_type,account_code,debit,credit,reference_no,reversed_entry_id) values(?,?,?,?,?,?,?,?)",s.getTenantId(),s.getId(),type,"SALES_REVENUE",sale?BigDecimal.ZERO:amount,sale?amount:BigDecimal.ZERO,ref,reversed);}
 private void audit(Sale s,String action,Map<String,Object> oldV,Map<String,Object> newV){audits.save(SaleAuditHistory.builder().sale(s).tenantId(s.getTenantId()).action(action).actorId(CurrentActor.id()).actorEmail(CurrentActor.email()).oldValue(oldV).newValue(newV).build());}
 private void publish(Sale s,String action,Map<String,Object> detail){events.publishEvent(new SaleDomainEvent(s.getTenantId(),s.getCompanyId(),s.getBranchId(),s.getId(),s.getInvoiceNumber(),action,detail,CurrentActor.id(),Instant.now()));}
 private Map<String,Object> snapshot(Sale s){return Map.of("status",s.getStatus().name(),"customerId",s.getCustomerId(),"finalAmount",s.getFinalAmount(),"version",s.getVersion()==null?0:s.getVersion());}
 private void requireStatus(Sale s,SaleStatus status){if(s.getStatus()!=status)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Sale must be "+status);}
 private long requireActor(){return Optional.ofNullable(CurrentActor.id()).orElseThrow(()->new ApiException(ErrorCode.UNAUTHENTICATED));}
 private BigDecimal money(BigDecimal v){return v.setScale(2,RoundingMode.HALF_UP);}
 private String blank(String v){return v==null||v.isBlank()?null:v.trim();}
 private ApiException conflict(){return new ApiException(ErrorCode.RESOURCE_CONFLICT,"Sale was modified; reload and retry");}
 private String csv(String value){return '"'+value.replace("\"","\"\"")+'"';}
}
