package com.sami.app.sales.service;

import com.sami.app.common.exception.*; import com.sami.app.common.tenancy.TenantContext; import com.sami.app.crm.repository.CustomerRepository;
import com.sami.app.product.domain.Product; import com.sami.app.product.repository.ProductRepository; import com.sami.app.sales.domain.*; import com.sami.app.sales.dto.SalesDtos.*; import com.sami.app.sales.event.SaleDomainEvent; import com.sami.app.sales.repository.*; import com.sami.app.security.CurrentActor;
import lombok.RequiredArgsConstructor; import org.springframework.beans.factory.annotation.Value; import org.springframework.context.ApplicationEventPublisher; import org.springframework.data.domain.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.math.*; import java.time.*; import java.util.*;

@Service @RequiredArgsConstructor
public class SalesService {
 private final SaleRepository sales; private final SaleNumberRepository numbers; private final SaleDiscountRepository discounts; private final SaleAuditRepository audits; private final SaleReturnRepository returns;
 private final ProductRepository products; private final CustomerRepository customers; private final TenantContext tenantContext; private final JdbcTemplate jdbc; private final ApplicationEventPublisher events;
 @Value("${app.sales.max-unapproved-discount-percent:10}") private BigDecimal maxUnapprovedDiscountPercent;
 @Value("${app.sales.minimum-profit-percent:5}") private BigDecimal minimumProfitPercent;
 @Value("${app.sales.commission-profit-percent:2}") private BigDecimal commissionProfitPercent;

 @Transactional(readOnly=true) public Page<SaleResponse> list(Pageable pageable){Long t=tenantContext.requireTenantId();return sales.findByTenantId(t,pageable).map(SaleResponse::from);}
 @Transactional(readOnly=true) public SaleResponse get(Long id){return SaleResponse.from(find(id));}
 @Transactional public SaleResponse create(SaleRequest r){Long t=tenantContext.requireTenantId();validateScope(t,r.companyId(),r.branchId());
  if(r.idempotencyKey()!=null){var prior=sales.findByTenantIdAndIdempotencyKey(t,r.idempotencyKey());if(prior.isPresent())return SaleResponse.from(prior.get());}
  requireCustomer(t,r.customerId()); Sale s=Sale.builder().tenantId(t).companyId(r.companyId()).branchId(r.branchId()).invoiceNumber(nextNumber(t)).idempotencyKey(r.idempotencyKey()).customerId(r.customerId()).sellerId(requireActor()).saleType(r.saleType().toUpperCase(Locale.ROOT)).status(SaleStatus.DRAFT).currency(r.currency()==null?"IRR":r.currency().toUpperCase(Locale.ROOT)).notes(r.notes()).createdBy(CurrentActor.id()).createdByEmail(CurrentActor.email()).build();
  applyItems(s,r.items()); applyServices(s,r.services()); recalculate(s); sales.saveAndFlush(s); audit(s,"CREATED",null,Map.of("invoiceNumber",s.getInvoiceNumber())); publish(s,"CREATED",Map.of()); return SaleResponse.from(s); }
 @Transactional public SaleResponse update(Long id,SaleRequest r){Sale s=find(id); requireStatus(s,SaleStatus.DRAFT); if(r.expectedVersion()!=null&&!r.expectedVersion().equals(s.getVersion()))throw conflict(); validateScope(s.getTenantId(),r.companyId(),r.branchId());requireCustomer(s.getTenantId(),r.customerId());
  Map<String,Object> before=snapshot(s);s.setCompanyId(r.companyId());s.setBranchId(r.branchId());s.setCustomerId(r.customerId());s.setSaleType(r.saleType().toUpperCase(Locale.ROOT));s.setCurrency(r.currency()==null?"IRR":r.currency().toUpperCase(Locale.ROOT));s.setNotes(r.notes());applyItems(s,r.items());applyServices(s,r.services());recalculate(s);audit(s,"UPDATED",before,snapshot(s));return SaleResponse.from(s); }
 @Transactional public SaleResponse requestDiscount(Long id,DiscountRequest r){Sale s=find(id);requireStatus(s,SaleStatus.DRAFT);recalculate(s);BigDecimal requested=money(r.amount());String status=needsApproval(s,requested)?"PENDING":"NOT_REQUIRED";SaleDiscount d=SaleDiscount.builder().sale(s).tenantId(s.getTenantId()).discountType(r.type().toUpperCase(Locale.ROOT)).amount(requested).reason(r.reason()).status(status).requestedBy(CurrentActor.id()).build();discounts.save(d);s.setDiscountTotal(money(s.getDiscountTotal().add(requested)));finishTotals(s);audit(s,"DISCOUNT_REQUESTED",null,Map.of("amount",d.getAmount(),"status",status));return SaleResponse.from(s);}
 @Transactional public SaleResponse decideDiscount(Long saleId,Long discountId,DecisionRequest r){Sale s=find(saleId);SaleDiscount d=discounts.findByIdAndTenantId(discountId,s.getTenantId()).filter(x->x.getSale().getId().equals(saleId)).orElseThrow(()->ResourceNotFoundException.of("Sale discount",discountId));if(!"PENDING".equals(d.getStatus()))throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Discount is not pending");d.setStatus(r.approved()?"APPROVED":"REJECTED");d.setApprovedBy(CurrentActor.id());d.setDecidedAt(Instant.now());if(!r.approved()){s.setDiscountTotal(BigDecimal.ZERO);recalculate(s);}audit(s,r.approved()?"DISCOUNT_APPROVED":"DISCOUNT_REJECTED",null,Map.of("discountId",discountId));return SaleResponse.from(s);}
 @Transactional public SaleResponse addPayment(Long id,PaymentRequest r){Sale s=find(id);if(s.getStatus()==SaleStatus.CANCELLED||s.getStatus()==SaleStatus.RETURNED)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Sale cannot accept payments");String method=r.method().toUpperCase(Locale.ROOT);if(!Set.of("CASH","CARD","TRANSFER","CHEQUE","WALLET","INSTALLMENT").contains(method))throw new ApiException(ErrorCode.BAD_REQUEST,"Unsupported payment method");String status=Set.of("CHEQUE","INSTALLMENT").contains(method)?"PENDING":"CAPTURED";SalePayment p=SalePayment.builder().sale(s).tenantId(s.getTenantId()).method(method).status(status).amount(money(r.amount())).referenceNo(r.referenceNo()).providerReference(r.providerReference()).createdBy(CurrentActor.id()).build();s.getPayments().add(p);audit(s,"PAYMENT_ADDED",null,Map.of("method",method,"amount",p.getAmount(),"status",status));return SaleResponse.from(s);}
 @Transactional public SaleResponse confirm(Long id){Sale s=find(id);requireStatus(s,SaleStatus.DRAFT);if(discounts.existsBySaleIdAndTenantIdAndStatus(id,s.getTenantId(),"PENDING"))throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Discount approval is pending");reserveStock(s);s.setStatus(SaleStatus.CONFIRMED);s.setConfirmedAt(Instant.now());audit(s,"CONFIRMED",null,snapshot(s));publish(s,"CONFIRMED",Map.of("amount",s.getFinalAmount()));return SaleResponse.from(s);}
 @Transactional public SaleResponse complete(Long id){Sale s=find(id);requireStatus(s,SaleStatus.CONFIRMED);BigDecimal paid=s.getPayments().stream().filter(p->"CAPTURED".equals(p.getStatus())).map(SalePayment::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add);if(paid.compareTo(s.getFinalAmount())!=0)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Captured payments must equal the final amount");issueStock(s);s.setStatus(SaleStatus.COMPLETED);s.setCompletedAt(Instant.now());postAccounting(s,"SALE",s.getFinalAmount(),null);audit(s,"COMPLETED",null,snapshot(s));publish(s,"COMPLETED",Map.of("amount",s.getFinalAmount()));return SaleResponse.from(s);}
 @Transactional public SaleResponse cancel(Long id,CancelRequest r){Sale s=find(id);if(s.getStatus()==SaleStatus.CANCELLED||s.getStatus()==SaleStatus.RETURNED)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Sale is already terminal");if(s.getStatus()==SaleStatus.COMPLETED||s.getStatus()==SaleStatus.PARTIALLY_RETURNED)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Completed sales must be returned");if(s.getStatus()==SaleStatus.CONFIRMED)releaseStock(s);reversePayments(s,s.getFinalAmount());s.setStatus(SaleStatus.CANCELLED);s.setCancelledAt(Instant.now());s.setCancellationReason(r.reason());audit(s,"CANCELLED",null,Map.of("reason",r.reason()));publish(s,"CANCELLED",Map.of());return SaleResponse.from(s);}
 @Transactional public SaleResponse createReturn(Long id,ReturnRequest r){Sale s=find(id);if(s.getStatus()!=SaleStatus.COMPLETED&&s.getStatus()!=SaleStatus.PARTIALLY_RETURNED)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Only completed sales can be returned");SaleReturn ret=SaleReturn.builder().sale(s).tenantId(s.getTenantId()).returnNumber(s.getInvoiceNumber()+"-R"+(returns.count()+1)).reason(r.reason()).refundMethod(r.refundMethod().toUpperCase(Locale.ROOT)).totalAmount(BigDecimal.ZERO).createdBy(CurrentActor.id()).build();BigDecimal total=BigDecimal.ZERO;for(ReturnLine line:r.items()){SaleItem item=s.getItems().stream().filter(i->i.getId().equals(line.saleItemId())).findFirst().orElseThrow(()->ResourceNotFoundException.of("Sale item",line.saleItemId()));BigDecimal remaining=item.getQuantity().subtract(item.getReturnedQuantity());if(line.quantity().compareTo(remaining)>0)throw new ApiException(ErrorCode.BAD_REQUEST,"Return quantity exceeds remaining quantity");BigDecimal amount=item.getLineTotal().multiply(line.quantity()).divide(item.getQuantity(),2,RoundingMode.HALF_UP);item.setReturnedQuantity(item.getReturnedQuantity().add(line.quantity()));ret.getItems().add(SaleReturnItem.builder().saleReturn(ret).saleItem(item).quantity(line.quantity()).amount(amount).build());restoreStock(s,item,line.quantity());total=total.add(amount);}ret.setTotalAmount(total);returns.save(ret);reversePayments(s,total);postAccounting(s,"RETURN",total,null);boolean all=s.getItems().stream().allMatch(i->i.getReturnedQuantity().compareTo(i.getQuantity())==0);s.setStatus(all?SaleStatus.RETURNED:SaleStatus.PARTIALLY_RETURNED);audit(s,"RETURNED",null,Map.of("returnNumber",ret.getReturnNumber(),"amount",total));publish(s,"RETURNED",Map.of("amount",total));return SaleResponse.from(s);}
 @Transactional(readOnly=true) public List<AuditResponse> audit(Long id){Sale s=find(id);return audits.findBySaleIdAndTenantIdOrderByOccurredAtDesc(id,s.getTenantId()).stream().map(AuditResponse::from).toList();}
 @Transactional(readOnly=true) public DashboardResponse dashboard(){Long t=tenantContext.requireTenantId();BigDecimal[] sums=jdbc.queryForObject("select coalesce(sum(final_amount) filter(where status in ('COMPLETED','PARTIALLY_RETURNED','RETURNED')),0),coalesce(sum(profit) filter(where status in ('COMPLETED','PARTIALLY_RETURNED','RETURNED')),0) from sales where tenant_id=?",(rs,n)->new BigDecimal[]{rs.getBigDecimal(1),rs.getBigDecimal(2)},t);return new DashboardResponse(sales.countByTenantIdAndStatus(t,SaleStatus.DRAFT),sales.countByTenantIdAndStatus(t,SaleStatus.CONFIRMED),sales.countByTenantIdAndStatus(t,SaleStatus.COMPLETED),sales.countByTenantIdAndStatus(t,SaleStatus.CANCELLED),sums[0],sums[1]);}
 @Transactional(readOnly=true) public byte[] exportCsv(){Long t=tenantContext.requireTenantId();StringBuilder out=new StringBuilder("\uFEFFInvoice,Status,Type,Amount,Profit,Created\r\n");for(Sale s:sales.findByTenantId(t,PageRequest.of(0,10000,Sort.by(Sort.Direction.DESC,"createdAt"))))out.append(csv(s.getInvoiceNumber())).append(',').append(s.getStatus()).append(',').append(csv(s.getSaleType())).append(',').append(s.getFinalAmount()).append(',').append(s.getProfit()).append(',').append(s.getCreatedAt()).append("\r\n");return out.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8);}

 private Sale find(Long id){return sales.findByIdAndTenantId(id,tenantContext.requireTenantId()).orElseThrow(()->ResourceNotFoundException.of("Sale",id));}
 private void applyItems(Sale s,List<ItemRequest> lines){s.getItems().clear();for(ItemRequest r:lines){Product p=products.findById(r.productId()).orElseThrow(()->ResourceNotFoundException.of("Product",r.productId()));requireTenantRow("products",p.getId(),s.getTenantId());BigDecimal q=r.quantity();BigDecimal price=money(r.unitPrice()),cost=money(r.costPrice()==null?BigDecimal.ZERO:r.costPrice()),disc=money(r.discount()==null?BigDecimal.ZERO:r.discount()),tax=money(r.tax()==null?BigDecimal.ZERO:r.tax());BigDecimal line=money(price.multiply(q).subtract(disc).add(tax));s.getItems().add(SaleItem.builder().sale(s).tenantId(s.getTenantId()).productId(p.getId()).productSku(p.getSku()).productName(p.getName()).serialNumber(blank(r.serialNumber())).imei(blank(r.imei())).quantity(q).unitPrice(price).costPrice(cost).discount(disc).tax(tax).lineTotal(line).profit(money(line.subtract(cost.multiply(q)))).build());}}
 private void applyServices(Sale s,List<ServiceRequest> lines){s.getServices().clear();if(lines==null)return;for(ServiceRequest r:lines)s.getServices().add(SaleServiceLine.builder().sale(s).tenantId(s.getTenantId()).serviceType(r.serviceType().toUpperCase(Locale.ROOT)).description(r.description()).price(money(r.price())).cost(money(r.cost()==null?BigDecimal.ZERO:r.cost())).employeeId(r.employeeId()).build());}
 private void recalculate(Sale s){BigDecimal subtotal=s.getItems().stream().map(i->i.getUnitPrice().multiply(i.getQuantity())).reduce(BigDecimal.ZERO,BigDecimal::add).add(s.getServices().stream().map(SaleServiceLine::getPrice).reduce(BigDecimal.ZERO,BigDecimal::add));BigDecimal itemDisc=s.getItems().stream().map(SaleItem::getDiscount).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal tax=s.getItems().stream().map(SaleItem::getTax).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal cost=s.getItems().stream().map(i->i.getCostPrice().multiply(i.getQuantity())).reduce(BigDecimal.ZERO,BigDecimal::add).add(s.getServices().stream().map(SaleServiceLine::getCost).reduce(BigDecimal.ZERO,BigDecimal::add));s.setSubtotal(money(subtotal));s.setTaxTotal(money(tax));s.setCostTotal(money(cost));s.setDiscountTotal(money(itemDisc));finishTotals(s);}
 private void finishTotals(Sale s){s.setFinalAmount(money(s.getSubtotal().subtract(s.getDiscountTotal()).add(s.getTaxTotal())).max(BigDecimal.ZERO));s.setProfit(money(s.getFinalAmount().subtract(s.getCostTotal())));s.setCommissionAmount(money(s.getProfit().max(BigDecimal.ZERO).multiply(commissionProfitPercent).divide(BigDecimal.valueOf(100),2,RoundingMode.HALF_UP)));}
 private boolean needsApproval(Sale s,BigDecimal amount){if(s.getSubtotal().signum()==0)return amount.signum()>0;BigDecimal pct=amount.multiply(BigDecimal.valueOf(100)).divide(s.getSubtotal(),2,RoundingMode.HALF_UP);BigDecimal margin=s.getFinalAmount().signum()==0?BigDecimal.ZERO:s.getProfit().multiply(BigDecimal.valueOf(100)).divide(s.getFinalAmount(),2,RoundingMode.HALF_UP);return pct.compareTo(maxUnapprovedDiscountPercent)>0||margin.compareTo(minimumProfitPercent)<0;}
 private void validateScope(Long t,Long c,Long b){Integer ok=jdbc.queryForObject("select count(*) from branches b join companies c on c.id=b.company_id where b.id=? and c.id=? and b.tenant_id=? and c.tenant_id=? and b.is_active and c.is_active",Integer.class,b,c,t,t);if(ok==null||ok!=1)throw new ApiException(ErrorCode.ACCESS_DENIED,"Company/branch is outside the trusted tenant");}
 private void requireCustomer(Long t,Long id){if(!customers.existsById(id))throw ResourceNotFoundException.of("Customer",id);requireTenantRow("customers",id,t);}
 private void requireTenantRow(String table,Long id,Long t){Integer n=jdbc.queryForObject("select count(*) from "+table+" where id=? and tenant_id=?",Integer.class,id,t);if(n==null||n!=1)throw new ApiException(ErrorCode.ACCESS_DENIED,"Cross-tenant reference is not permitted");}
 private String nextNumber(Long t){int y=Year.now(ZoneOffset.UTC).getValue();SaleNumber n=numbers.findByTenantIdAndSequenceYear(t,y).orElseGet(()->numbers.saveAndFlush(SaleNumber.builder().tenantId(t).sequenceYear(y).nextValue(1).build()));long value=n.getNextValue();n.setNextValue(value+1);return "SAL-%d-%06d".formatted(y,value);}
 private void reserveStock(Sale s){for(SaleItem i:s.getItems()){Product p=products.findById(i.getProductId()).orElseThrow();if(BigDecimal.valueOf(p.getStockQuantity()).compareTo(i.getQuantity())<0)throw new ApiException(ErrorCode.RESOURCE_CONFLICT,"Insufficient stock for "+i.getProductSku());jdbc.update("insert into sales_stock_movements(tenant_id,sale_id,sale_item_id,movement_type,quantity,actor_id) values(?,?,?,'RESERVE',?,?)",s.getTenantId(),s.getId(),i.getId(),i.getQuantity(),CurrentActor.id());}}
 private void releaseStock(Sale s){for(SaleItem i:s.getItems())jdbc.update("insert into sales_stock_movements(tenant_id,sale_id,sale_item_id,movement_type,quantity,actor_id) values(?,?,?,'RELEASE',?,?)",s.getTenantId(),s.getId(),i.getId(),i.getQuantity(),CurrentActor.id());}
 private void issueStock(Sale s){for(SaleItem i:s.getItems()){Product p=products.findById(i.getProductId()).orElseThrow();int q=i.getQuantity().intValueExact();if(p.getStockQuantity()<q)throw new ApiException(ErrorCode.RESOURCE_CONFLICT,"Stock changed; reload sale");p.setStockQuantity(p.getStockQuantity()-q);jdbc.update("insert into sales_stock_movements(tenant_id,sale_id,sale_item_id,movement_type,quantity,actor_id) values(?,?,?,'ISSUE',?,?)",s.getTenantId(),s.getId(),i.getId(),i.getQuantity(),CurrentActor.id());}}
 private void restoreStock(Sale s,SaleItem i,BigDecimal q){Product p=products.findById(i.getProductId()).orElseThrow();p.setStockQuantity(p.getStockQuantity()+q.intValueExact());jdbc.update("insert into sales_stock_movements(tenant_id,sale_id,sale_item_id,movement_type,quantity,actor_id) values(?,?,?,'RETURN',?,?)",s.getTenantId(),s.getId(),i.getId(),q,CurrentActor.id());}
 private void reversePayments(Sale s,BigDecimal amount){BigDecimal left=amount;for(SalePayment p:s.getPayments()){if(left.signum()<=0)break;BigDecimal available=p.getAmount().subtract(p.getReversedAmount());BigDecimal take=available.min(left);p.setReversedAmount(p.getReversedAmount().add(take));p.setStatus(p.getReversedAmount().compareTo(p.getAmount())==0?"REVERSED":"PARTIALLY_REVERSED");left=left.subtract(take);}}
 private void postAccounting(Sale s,String type,BigDecimal amount,Long reversed){boolean sale="SALE".equals(type);String ref=s.getInvoiceNumber()+"-"+type;jdbc.update("insert into sale_accounting_entries(tenant_id,sale_id,entry_type,account_code,debit,credit,reference_no,reversed_entry_id) values(?,?,?,?,?,?,?,?)",s.getTenantId(),s.getId(),type,"CASH_OR_RECEIVABLE",sale?amount:BigDecimal.ZERO,sale?BigDecimal.ZERO:amount,ref,reversed);jdbc.update("insert into sale_accounting_entries(tenant_id,sale_id,entry_type,account_code,debit,credit,reference_no,reversed_entry_id) values(?,?,?,?,?,?,?,?)",s.getTenantId(),s.getId(),type,"SALES_REVENUE",sale?BigDecimal.ZERO:amount,sale?amount:BigDecimal.ZERO,ref,reversed);}
 private void audit(Sale s,String action,Map<String,Object> oldV,Map<String,Object> newV){audits.save(SaleAuditHistory.builder().sale(s).tenantId(s.getTenantId()).action(action).actorId(CurrentActor.id()).actorEmail(CurrentActor.email()).oldValue(oldV).newValue(newV).build());}
 private void publish(Sale s,String action,Map<String,Object> detail){events.publishEvent(new SaleDomainEvent(s.getTenantId(),s.getCompanyId(),s.getBranchId(),s.getId(),s.getInvoiceNumber(),action,detail,CurrentActor.id(),Instant.now()));}
 private Map<String,Object> snapshot(Sale s){return Map.of("status",s.getStatus().name(),"customerId",s.getCustomerId(),"finalAmount",s.getFinalAmount(),"version",s.getVersion()==null?0:s.getVersion());}
 private void requireStatus(Sale s,SaleStatus status){if(s.getStatus()!=status)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Sale must be "+status);}
 private long requireActor(){return Optional.ofNullable(CurrentActor.id()).orElseThrow(()->new ApiException(ErrorCode.UNAUTHENTICATED));}
 private BigDecimal money(BigDecimal v){return v.setScale(2,RoundingMode.HALF_UP);}
 private String blank(String v){return v==null||v.isBlank()?null:v.trim();}
 private ApiException conflict(){return new ApiException(ErrorCode.RESOURCE_CONFLICT,"Sale was modified; reload and retry");}
 private String csv(String value){return '"'+value.replace("\"","\"\"")+'"';}
}
