package com.sami.app.treasury.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.sami.app.common.api.PageResponse;
import com.sami.app.common.exception.*;
import com.sami.app.common.tenancy.TenantContext;
import com.sami.app.security.CurrentActor;
import com.sami.app.treasury.domain.*;
import com.sami.app.treasury.dto.TreasuryDtos.*;
import com.sami.app.treasury.event.TreasuryDomainEvent;
import com.sami.app.treasury.repository.*;
import lombok.RequiredArgsConstructor;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.data.domain.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import java.util.function.Function;

/** Tenant-scoped treasury operations. Completion writes immutable movements; cancellation writes a reversal. */
@Service @RequiredArgsConstructor
public class TreasuryService {
 private final TenantContext tenants; private final TreasuryAccountRepository accounts; private final TreasuryTransactionRepository transactions;
 private final TreasuryMovementRepository movements; private final TreasuryChequeRepository cheques; private final TreasuryDailyClosingRepository closings;
 private final TreasuryAccountTypeRepository accountTypes; private final TreasuryTransactionTypeRepository transactionTypes; private final TreasuryTransactionStatusRepository transactionStatuses;
 private final TreasuryChequeStatusRepository chequeStatuses; private final TreasuryCategoryRepository categories; private final JdbcTemplate jdbc; private final ApplicationEventPublisher events;
 private final ObjectMapper objectMapper;

 @Transactional(readOnly=true) public List<AccountResponse> accounts(){return accounts.findByTenantIdOrderByNameAsc(tenant()).stream().map(AccountResponse::from).toList();}
 @Transactional(readOnly=true) public List<AccountTypeResponse> accountTypes(){return visible(accountTypes.findByTenantIdIsNullOrTenantIdOrderByDisplayOrderAsc(tenant()),TreasuryAccountType::getCode,TreasuryAccountType::getTenantId).stream().map(AccountTypeResponse::from).toList();}
 @Transactional(readOnly=true) public List<TransactionTypeResponse> transactionTypes(){return visible(transactionTypes.findByTenantIdIsNullOrTenantIdOrderByDisplayOrderAsc(tenant()),TreasuryTransactionType::getCode,TreasuryTransactionType::getTenantId).stream().map(TransactionTypeResponse::from).toList();}
 @Transactional(readOnly=true) public List<TransactionStatusResponse> transactionStatuses(){return visible(transactionStatuses.findByTenantIdIsNullOrTenantIdOrderByDisplayOrderAsc(tenant()),TreasuryTransactionStatus::getCode,TreasuryTransactionStatus::getTenantId).stream().map(TransactionStatusResponse::from).toList();}
 @Transactional(readOnly=true) public List<ChequeStatusResponse> chequeStatuses(){return visible(chequeStatuses.findByTenantIdIsNullOrTenantIdOrderByDisplayOrderAsc(tenant()),TreasuryChequeStatus::getCode,TreasuryChequeStatus::getTenantId).stream().map(ChequeStatusResponse::from).toList();}
 @Transactional(readOnly=true) public List<CategoryResponse> categories(){return categories.findByTenantIdOrderByKindAscDisplayOrderAsc(tenant()).stream().map(CategoryResponse::from).toList();}
 @Transactional public AccountResponse createAccount(AccountRequest r){ assertAccountCode(r.code(),null); TreasuryAccountType t=type(r.accountTypeId()); validateBank(t,r.bankName()); TreasuryAccount a=TreasuryAccount.builder().tenantId(tenant()).accountType(t).code(norm(r.code())).name(r.name()).currencyCode(currency(r.currencyCode())).openingBalance(r.openingBalance()).currentBalance(r.openingBalance()).allowNegativeBalance(r.allowNegativeBalance()||t.isAllowsNegativeBalance()).responsibleUserId(r.responsibleUserId()).bankName(r.bankName()).bankBranch(r.bankBranch()).iban(r.iban()).accountNumber(r.accountNumber()).cardNumber(r.cardNumber()).accountHolder(r.accountHolder()).description(r.description()).active(r.active()).build(); a=accounts.save(a); audit(a.getId(),"ACCOUNT_CREATED",null,Map.of("code",a.getCode(),"openingBalance",a.getOpeningBalance())); event("ACCOUNT_CREATED","ACCOUNT",a.getId(),Map.of("code",a.getCode())); return AccountResponse.from(a); }
 @Transactional public AccountResponse updateAccount(Long id,AccountRequest r){ TreasuryAccount a=account(id); assertAccountCode(r.code(),id); TreasuryAccountType t=type(r.accountTypeId()); validateBank(t,r.bankName()); boolean hasMovements=a.getCurrentBalance().compareTo(a.getOpeningBalance())!=0; if(hasMovements&&a.getOpeningBalance().compareTo(r.openingBalance())!=0) throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Opening balance cannot change after movements exist"); a.setAccountType(t);a.setCode(norm(r.code()));a.setName(r.name());a.setCurrencyCode(currency(r.currencyCode()));a.setOpeningBalance(r.openingBalance()); if(!hasMovements)a.setCurrentBalance(r.openingBalance());a.setAllowNegativeBalance(r.allowNegativeBalance()||t.isAllowsNegativeBalance());a.setResponsibleUserId(r.responsibleUserId());a.setBankName(r.bankName());a.setBankBranch(r.bankBranch());a.setIban(r.iban());a.setAccountNumber(r.accountNumber());a.setCardNumber(r.cardNumber());a.setAccountHolder(r.accountHolder());a.setDescription(r.description());a.setActive(r.active()); audit(a.getId(),"ACCOUNT_UPDATED",null,Map.of("code",a.getCode())); return AccountResponse.from(a); }
 @Transactional(readOnly=true) public PageResponse<TransactionResponse> transactions(int page,int size){return PageResponse.from(transactions.findByTenantIdOrderByOccurredAtDescIdDesc(tenant(),PageRequest.of(Math.max(page,0),Math.min(Math.max(size,1),100))).map(TransactionResponse::from));}
 @Transactional public TransactionResponse createTransaction(TransactionRequest r){ TreasuryTransactionType type=transactionType(r.transactionTypeId()); validateTransactionShape(type,r); TreasuryTransaction t=TreasuryTransaction.builder().tenantId(tenant()).transactionNumber(nextNumber()).transactionType(type).status(status(TreasuryTransactionStatus::isDraftState,"draft")).category(r.categoryId()==null?null:category(r.categoryId())).sourceAccount(r.sourceAccountId()==null?null:account(r.sourceAccountId())).destinationAccount(r.destinationAccountId()==null?null:account(r.destinationAccountId())).amount(r.amount()).currencyCode(currency(r.currencyCode())).occurredAt(r.occurredAt()).referenceModule(r.referenceModule()).referenceNumber(r.referenceNumber()).description(r.description()).createdBy(CurrentActor.id()).build(); t=transactions.save(t);audit(t.getId(),"TRANSACTION_CREATED",null,Map.of("number",t.getTransactionNumber(),"amount",t.getAmount()));event("TRANSACTION_CREATED","TRANSACTION",t.getId(),Map.of("number",t.getTransactionNumber()));return TransactionResponse.from(t); }
 /** Public application operation used by approved modules; treasury remains the sole movement owner. */
 @Transactional public Long recordOutflow(Long accountId,BigDecimal amount,Instant occurredAt,String referenceModule,String referenceNumber,String description){TreasuryTransactionType type=visible(transactionTypes.findByTenantIdIsNullOrTenantIdOrderByDisplayOrderAsc(tenant()),TreasuryTransactionType::getCode,TreasuryTransactionType::getTenantId).stream().filter(x->"expense".equalsIgnoreCase(x.getCode())&&x.isActive()).findFirst().orElseThrow(()->new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Treasury expense transaction type is not configured"));TreasuryTransaction t=TreasuryTransaction.builder().tenantId(tenant()).transactionNumber(nextNumber()).transactionType(type).status(status(TreasuryTransactionStatus::isApprovedState,"approved")).sourceAccount(account(accountId)).amount(amount).currencyCode("IRR").occurredAt(occurredAt).referenceModule(referenceModule).referenceNumber(referenceNumber).description(description).createdBy(CurrentActor.id()).approvedBy(CurrentActor.id()).approvedAt(Instant.now()).build();transactions.save(t);post(t);t.setStatus(status(TreasuryTransactionStatus::isCompletedState,"completed"));t.setCompletedAt(Instant.now());audit(t.getId(),"TRANSACTION_COMPLETED",null,Map.of("number",t.getTransactionNumber(),"amount",t.getAmount(),"source",referenceModule));event("TRANSACTION_COMPLETED","TRANSACTION",t.getId(),Map.of("number",t.getTransactionNumber()));return t.getId();}
 @Transactional public TransactionResponse updateTransaction(Long id,TransactionRequest r){ TreasuryTransaction t=transaction(id);if(!t.getStatus().isAllowsEditing())throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Only editable treasury transactions can be changed");TreasuryTransactionType type=transactionType(r.transactionTypeId());validateTransactionShape(type,r);t.setTransactionType(type);t.setCategory(r.categoryId()==null?null:category(r.categoryId()));t.setSourceAccount(r.sourceAccountId()==null?null:account(r.sourceAccountId()));t.setDestinationAccount(r.destinationAccountId()==null?null:account(r.destinationAccountId()));t.setAmount(r.amount());t.setCurrencyCode(currency(r.currencyCode()));t.setOccurredAt(r.occurredAt());t.setReferenceModule(r.referenceModule());t.setReferenceNumber(r.referenceNumber());t.setDescription(r.description());audit(t.getId(),"TRANSACTION_UPDATED",null,Map.of("number",t.getTransactionNumber()));return TransactionResponse.from(t);}
 @Transactional public TransactionResponse submit(Long id){TreasuryTransaction t=transaction(id);require(t.getStatus().isDraftState(),"Only draft transactions can be submitted");t.setStatus(status(TreasuryTransactionStatus::isPendingState,"pending"));event("TRANSACTION_SUBMITTED","TRANSACTION",id,Map.of());return TransactionResponse.from(t);}
 @Transactional public TransactionResponse approve(Long id){TreasuryTransaction t=transaction(id);require(t.getStatus().isPendingState(),"Only pending transactions can be approved");t.setStatus(status(TreasuryTransactionStatus::isApprovedState,"approved"));t.setApprovedBy(CurrentActor.id());t.setApprovedAt(Instant.now());event("TRANSACTION_APPROVED","TRANSACTION",id,Map.of());return TransactionResponse.from(t);}
 @Transactional public TransactionResponse complete(Long id){TreasuryTransaction t=transaction(id);require(t.getStatus().isApprovedState()||t.getStatus().isDraftState(),"Only approved or draft transactions can be completed"); post(t);t.setStatus(status(TreasuryTransactionStatus::isCompletedState,"completed"));t.setCompletedAt(Instant.now());audit(id,"TRANSACTION_COMPLETED",null,Map.of("number",t.getTransactionNumber(),"amount",t.getAmount()));event("TRANSACTION_COMPLETED","TRANSACTION",id,Map.of("number",t.getTransactionNumber()));return TransactionResponse.from(t);}
 @Transactional public TransactionResponse reject(Long id){TreasuryTransaction t=transaction(id);require(t.getStatus().isPendingState(),"Only pending transactions can be rejected");t.setStatus(status(TreasuryTransactionStatus::isRejectedState,"rejected"));event("TRANSACTION_REJECTED","TRANSACTION",id,Map.of());return TransactionResponse.from(t);}
 @Transactional public TransactionResponse cancel(Long id){TreasuryTransaction original=transaction(id);if(original.getStatus().isCompletedState()){if(transactions.existsByTenantIdAndReversalOfId(tenant(),id))throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Transaction already reversed");TreasuryTransaction reversal=TreasuryTransaction.builder().tenantId(tenant()).transactionNumber(nextNumber()).transactionType(original.getTransactionType()).status(status(TreasuryTransactionStatus::isApprovedState,"approved")).category(original.getCategory()).sourceAccount(original.getDestinationAccount()).destinationAccount(original.getSourceAccount()).amount(original.getAmount()).currencyCode(original.getCurrencyCode()).occurredAt(Instant.now()).referenceModule("treasury").referenceNumber(original.getTransactionNumber()).description("Reversal of "+original.getTransactionNumber()).createdBy(CurrentActor.id()).reversalOf(original).build();transactions.save(reversal);post(reversal);reversal.setStatus(status(TreasuryTransactionStatus::isCompletedState,"completed"));reversal.setCompletedAt(Instant.now());}else require(!original.getStatus().isTerminal(),"Terminal transactions cannot be cancelled");original.setStatus(status(TreasuryTransactionStatus::isCancelledState,"cancelled"));original.setCancelledAt(Instant.now());audit(id,"TRANSACTION_CANCELLED",null,Map.of("number",original.getTransactionNumber()));event("TRANSACTION_CANCELLED","TRANSACTION",id,Map.of());return TransactionResponse.from(original);}
 @Transactional(readOnly=true) public PageResponse<MovementResponse> movements(Long accountId,int page,int size){account(accountId);return PageResponse.from(movements.findByTenantIdAndAccountIdOrderByOccurredAtDescIdDesc(tenant(),accountId,PageRequest.of(Math.max(0,page),Math.min(Math.max(1,size),100))).map(MovementResponse::from));}
 @Transactional(readOnly=true) public PageResponse<ChequeResponse> cheques(int page,int size){return PageResponse.from(cheques.findByTenantIdOrderByDueDateAscIdDesc(tenant(),PageRequest.of(Math.max(page,0),Math.min(Math.max(size,1),100))).map(ChequeResponse::from));}
 @Transactional public ChequeResponse createCheque(ChequeRequest r){assertCheque(r,null);TreasuryCheque c=mapCheque(TreasuryCheque.builder().tenantId(tenant()).build(),r);c=cheques.save(c);audit(c.getId(),"CHEQUE_CREATED",null,Map.of("number",c.getChequeNumber()));event("CHEQUE_CREATED","CHEQUE",c.getId(),Map.of());return ChequeResponse.from(c);}
 @Transactional public ChequeResponse updateCheque(Long id,ChequeRequest r){TreasuryCheque c=cheque(id);assertCheque(r,id);mapCheque(c,r);audit(id,"CHEQUE_UPDATED",null,Map.of("number",c.getChequeNumber()));return ChequeResponse.from(c);}
 @Transactional public ChequeResponse updateChequeStatus(Long id,ChequeStatusUpdate r){TreasuryCheque c=cheque(id);TreasuryChequeStatus s=chequeStatus(r.statusId());if(!s.isActive())throw new ApiException(ErrorCode.VALIDATION_FAILED,"Cheque status is inactive");c.setStatus(s);c.setStatusChangedAt(Instant.now());audit(id,"CHEQUE_STATUS_UPDATED",null,Map.of("status",s.getCode()));event("CHEQUE_STATUS_UPDATED","CHEQUE",id,Map.of("status",s.getCode()));return ChequeResponse.from(c);}
 @Transactional public DailyClosingResponse close(DailyClosingRequest r){TreasuryAccount a=account(r.accountId());if(closings.existsByTenantIdAndAccountIdAndClosingDate(tenant(),a.getId(),r.closingDate()))throw new ApiException(ErrorCode.RESOURCE_CONFLICT,"This account has already been closed for this date");TreasuryDailyClosing c=closings.save(TreasuryDailyClosing.builder().tenantId(tenant()).account(a).closingDate(r.closingDate()).expectedBalance(a.getCurrentBalance()).declaredBalance(r.declaredBalance()).differenceAmount(r.declaredBalance().subtract(a.getCurrentBalance())).note(r.note()).closedBy(CurrentActor.id()).build());audit(c.getId(),"DAILY_CLOSING_CREATED",null,Map.of("difference",c.getDifferenceAmount()));return DailyClosingResponse.from(c);}
 @Transactional(readOnly=true) public DashboardResponse dashboard(){Long tenantId=tenant();List<TreasuryAccount> values=accounts.findByTenantIdOrderByNameAsc(tenantId);BigDecimal total=values.stream().filter(a->"IRR".equals(a.getCurrencyCode())).map(TreasuryAccount::getCurrentBalance).reduce(BigDecimal.ZERO,BigDecimal::add);return new DashboardResponse(values.size(),transactions.countByTenantId(tenantId),cheques.countByTenantId(tenantId),total,"IRR");}
 private TreasuryCheque mapCheque(TreasuryCheque c,ChequeRequest r){c.setDirection(r.direction());c.setChequeNumber(r.chequeNumber().trim());c.setBankName(r.bankName().trim());c.setNormalizedBankName(normBank(r.bankName()));c.setBankBranch(r.bankBranch());c.setAmount(r.amount());c.setCurrencyCode(currency(r.currencyCode()));c.setOwnerName(r.ownerName());c.setRecipientName(r.recipientName());c.setIssueDate(r.issueDate());c.setDueDate(r.dueDate());c.setStatus(chequeStatus(r.statusId()));c.setTreasuryAccount(r.treasuryAccountId()==null?null:account(r.treasuryAccountId()));c.setTransaction(r.transactionId()==null?null:transaction(r.transactionId()));c.setImageFileId(r.imageFileId());c.setDescription(r.description());return c;}
 private void post(TreasuryTransaction t){Long source=t.getSourceAccount()==null?null:t.getSourceAccount().getId(),destination=t.getDestinationAccount()==null?null:t.getDestinationAccount().getId();Set<Long> ids=new TreeSet<>();if(source!=null)ids.add(source);if(destination!=null)ids.add(destination);List<TreasuryAccount> locked=accounts.lockByTenantIdAndIdIn(tenant(),ids);if(locked.size()!=ids.size())throw new ApiException(ErrorCode.ACCESS_DENIED,"Treasury account is unavailable");Map<Long,TreasuryAccount> byId=new HashMap<>();locked.forEach(a->byId.put(a.getId(),a));if(source!=null)postMovement(t,byId.get(source),t.getAmount().negate());if(destination!=null)postMovement(t,byId.get(destination),t.getAmount());}
 private void postMovement(TreasuryTransaction t,TreasuryAccount a,BigDecimal delta){BigDecimal next=a.getCurrentBalance().add(delta);if(next.signum()<0&&!a.isAllowNegativeBalance())throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Treasury account has insufficient balance");a.setCurrentBalance(next);movements.save(TreasuryMovement.builder().tenantId(tenant()).transaction(t).account(a).amount(delta).balanceAfter(next).occurredAt(t.getOccurredAt()).build());}
 private void validateTransactionShape(TreasuryTransactionType type,TransactionRequest r){if(type.getDirection()==TreasuryTransactionType.Direction.INFLOW && r.destinationAccountId()==null)throw new ApiException(ErrorCode.VALIDATION_FAILED,"Inflow requires a destination account");if(type.getDirection()==TreasuryTransactionType.Direction.OUTFLOW && r.sourceAccountId()==null)throw new ApiException(ErrorCode.VALIDATION_FAILED,"Outflow requires a source account");if(type.getDirection()==TreasuryTransactionType.Direction.TRANSFER&&(r.sourceAccountId()==null||r.destinationAccountId()==null||r.sourceAccountId().equals(r.destinationAccountId())))throw new ApiException(ErrorCode.VALIDATION_FAILED,"Transfer requires two different accounts");}
 private void assertCheque(ChequeRequest r,Long except){String bank=normBank(r.bankName());boolean exists=except==null?cheques.existsByTenantIdAndDirectionAndNormalizedBankNameAndChequeNumber(tenant(),r.direction(),bank,r.chequeNumber().trim()):cheques.existsByTenantIdAndDirectionAndNormalizedBankNameAndChequeNumberAndIdNot(tenant(),r.direction(),bank,r.chequeNumber().trim(),except);if(exists)throw new ApiException(ErrorCode.RESOURCE_CONFLICT,"Cheque number already exists for this bank and direction");}
 private TreasuryAccount account(Long id){return accounts.findByIdAndTenantId(id,tenant()).orElseThrow(()->ResourceNotFoundException.of("Treasury account",id));} private TreasuryTransaction transaction(Long id){return transactions.findByIdAndTenantId(id,tenant()).orElseThrow(()->ResourceNotFoundException.of("Treasury transaction",id));} private TreasuryCheque cheque(Long id){return cheques.findByIdAndTenantId(id,tenant()).orElseThrow(()->ResourceNotFoundException.of("Treasury cheque",id));}
 private TreasuryAccountType type(Long id){return visible(accountTypes.findByTenantIdIsNullOrTenantIdOrderByDisplayOrderAsc(tenant()),TreasuryAccountType::getCode,TreasuryAccountType::getTenantId).stream().filter(x->x.getId().equals(id)&&x.isActive()).findFirst().orElseThrow(()->ResourceNotFoundException.of("Treasury account type",id));}
 private TreasuryTransactionType transactionType(Long id){return visible(transactionTypes.findByTenantIdIsNullOrTenantIdOrderByDisplayOrderAsc(tenant()),TreasuryTransactionType::getCode,TreasuryTransactionType::getTenantId).stream().filter(x->x.getId().equals(id)&&x.isActive()).findFirst().orElseThrow(()->ResourceNotFoundException.of("Treasury transaction type",id));}
 private TreasuryTransactionStatus status(Function<TreasuryTransactionStatus,Boolean> flag,String label){return visible(transactionStatuses.findByTenantIdIsNullOrTenantIdOrderByDisplayOrderAsc(tenant()),TreasuryTransactionStatus::getCode,TreasuryTransactionStatus::getTenantId).stream().filter(TreasuryTransactionStatus::isActive).filter(flag::apply).findFirst().orElseThrow(()->new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Treasury "+label+" status is not configured"));}
 private TreasuryChequeStatus chequeStatus(Long id){return visible(chequeStatuses.findByTenantIdIsNullOrTenantIdOrderByDisplayOrderAsc(tenant()),TreasuryChequeStatus::getCode,TreasuryChequeStatus::getTenantId).stream().filter(x->x.getId().equals(id)).findFirst().orElseThrow(()->ResourceNotFoundException.of("Treasury cheque status",id));}
 private TreasuryCategory category(Long id){return categories.findById(id).filter(x->x.getTenantId().equals(tenant())).orElseThrow(()->ResourceNotFoundException.of("Treasury category",id));}
 private <T> List<T> visible(List<T> values,Function<T,String> code,Function<T,Long> owner){Map<String,T> effective=new LinkedHashMap<>();values.stream().filter(v->owner.apply(v)==null).forEach(v->effective.put(code.apply(v).toLowerCase(Locale.ROOT),v));values.stream().filter(v->owner.apply(v)!=null).forEach(v->effective.put(code.apply(v).toLowerCase(Locale.ROOT),v));return List.copyOf(effective.values());}
 private void validateBank(TreasuryAccountType t,String bank){if(t.isRequiresBankDetails()&&(bank==null||bank.isBlank()))throw new ApiException(ErrorCode.VALIDATION_FAILED,"Bank name is required for this account type");} private void assertAccountCode(String code,Long except){boolean exists=except==null?accounts.existsByTenantIdAndCodeIgnoreCase(tenant(),code):accounts.existsByTenantIdAndCodeIgnoreCaseAndIdNot(tenant(),code,except);if(exists)throw new ApiException(ErrorCode.RESOURCE_CONFLICT,"Treasury account code already exists");}
 private String nextNumber(){return "TRS-"+Year.now().getValue()+"-"+UUID.randomUUID().toString().substring(0,8).toUpperCase(Locale.ROOT);}
 private Long tenant(){return tenants.requireTenantId();} private String norm(String value){return value.trim().toLowerCase(Locale.ROOT);} private String normBank(String value){return value.trim().replaceAll("\\s+"," ").toLowerCase(Locale.ROOT);} private String currency(String c){return c==null||c.isBlank()?"IRR":c.toUpperCase(Locale.ROOT);} private void require(boolean ok,String message){if(!ok)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,message);}
 private void audit(Long id,String action,Map<String,Object> oldValue,Map<String,Object> newValue){jdbc.update("insert into treasury_audit_log(tenant_id,entity_type,entity_id,action,old_values,new_values,actor_id,actor_email) values(?,?,?, ?,cast(? as jsonb),cast(? as jsonb),?,?)",tenant(),"TREASURY",id,action,json(oldValue),json(newValue),CurrentActor.id(),CurrentActor.email());} private String json(Map<String,Object> value){if(value==null)return null;try{return objectMapper.writeValueAsString(value);}catch(JsonProcessingException ex){throw new IllegalStateException("Unable to serialize treasury audit data",ex);}} private void event(String type,String entity,Long id,Map<String,Object> detail){events.publishEvent(new TreasuryDomainEvent(tenant(),type,entity,id,detail,CurrentActor.id(),Instant.now()));}
}
