package com.sami.app.sales.order;

import com.sami.app.common.exception.*;
import com.sami.app.common.tenancy.TenantContext;
import com.sami.app.contact.publicapi.ContactCustomerRoleLookup;
import com.sami.app.inventory.publicapi.InventoryStockOperations;
import com.sami.app.inventory.publicapi.InventoryStockOperations.*;
import com.sami.app.organization.service.OrganizationScopeService;
import com.sami.app.product.repository.ProductRepository;
import com.sami.app.sales.publicapi.QuotationConversionSource;
import com.sami.app.sales.publicapi.QuotationConversionSource.QuotationSnapshot;
import com.sami.app.security.CurrentActor;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import java.math.*;
import java.time.*;
import java.util.*;
import static com.sami.app.sales.order.SalesOrderDtos.*;

@Service @RequiredArgsConstructor
public class SalesOrderService {
    private final TenantContext tenants; private final OrganizationScopeService scope;
    private final ContactCustomerRoleLookup contacts; private final ProductRepository products;
    private final SalesOrderRepository orders; private final SalesOrderAuditRepository audits;
    private final InventoryStockOperations inventory; private final QuotationConversionSource quotations;
    private final SalesOrderProperties properties;

    @Transactional public Response create(Request r) { Long tenant=tenants.requireTenantId(); scope.requireScope(r.companyId(),r.branchId()); Long contact=contacts.requireContactIdForCustomer(r.customerId()); SalesOrder o=SalesOrder.builder().tenantId(tenant).companyId(r.companyId()).branchId(r.branchId()).customerId(r.customerId()).contactId(contact).orderNumber(number()).status(SalesOrderStatus.DRAFT).currency(currency(r.currency())).notes(r.notes()).createdBy(CurrentActor.id()).createdByEmail(CurrentActor.email()).build(); apply(o,r); orders.saveAndFlush(o); audit(o,"CREATED",null,snapshot(o)); return Response.from(o); }
    @Transactional public Response convert(Long sourceId) { QuotationSnapshot q=quotations.requireIssuedQuotation(sourceId); scope.requireScope(q.companyId(),q.branchId()); SalesOrder o=SalesOrder.builder().tenantId(q.tenantId()).companyId(q.companyId()).branchId(q.branchId()).customerId(q.customerId()).contactId(q.contactId()).sourceDocumentId(q.quotationId()).orderNumber(number()).status(SalesOrderStatus.DRAFT).currency(q.currency()).createdBy(CurrentActor.id()).createdByEmail(CurrentActor.email()).build(); for(var l:q.lines()) o.getLines().add(SalesOrderLine.builder().order(o).tenantId(o.getTenantId()).sourceLineId(l.sourceLineId()).productId(l.productId()).productSku(l.productSku()).productName(l.productName()).quantity(l.quantity()).unitPrice(l.unitPrice()).discount(l.discount()).lineTotal(l.lineTotal()).build()); totals(o); orders.saveAndFlush(o); audit(o,"CONVERTED_FROM_QUOTATION",null,Map.of("sourceDocumentId",sourceId)); return Response.from(o); }
    @Transactional public List<Response> list(Long companyId,Long branchId){scope.requireScope(companyId,branchId);return orders.findByTenantIdAndCompanyIdAndBranchIdOrderByCreatedAtDesc(tenants.requireTenantId(),companyId,branchId).stream().map(Response::from).toList();}
    @Transactional public Response get(Long id){return Response.from(find(id));}
    @Transactional public Response update(Long id,Request r){SalesOrder o=find(id); if(r.expectedVersion()!=null&&!r.expectedVersion().equals(o.getVersion()))throw new ApiException(ErrorCode.RESOURCE_CONFLICT,"Order was modified; reload and retry"); scope.requireScope(r.companyId(),r.branchId()); if(o.getStatus()==SalesOrderStatus.CANCELLED)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Cancelled orders cannot be edited"); if(o.getStatus()==SalesOrderStatus.CONFIRMED){requireCorrectionWindow(o); if(!sameCommercialValues(o,r))throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Confirmed order commercial values cannot be corrected after confirmation"); o.setNotes(r.notes()); audit(o,"CORRECTED",null,snapshot(o)); return Response.from(o);} if(!o.getCompanyId().equals(r.companyId())||!o.getBranchId().equals(r.branchId()))throw new ApiException(ErrorCode.ACCESS_DENIED,"Order scope cannot be changed"); o.setCustomerId(r.customerId());o.setContactId(contacts.requireContactIdForCustomer(r.customerId()));o.setCurrency(currency(r.currency()));o.setNotes(r.notes());apply(o,r);audit(o,"UPDATED",null,snapshot(o));return Response.from(o);}
    @Transactional public Response confirm(Long id){SalesOrder o=find(id);if(o.getStatus()!=SalesOrderStatus.DRAFT)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Only draft orders can be confirmed"); List<StockLine> lines=o.getLines().stream().map(l->new StockLine(l.getId(),l.getProductId(),l.getQuantity(),null,null)).toList(); ReservationResult result=inventory.reserveAvailable(new ReservationCommand(o.getCompanyId(),o.getBranchId(),"SALES_ORDER",o.getId(),lines)); Map<Long,ReservationAllocation> byLine=result.allocations().stream().collect(java.util.stream.Collectors.toMap(ReservationAllocation::sourceLineId,a->a)); o.getLines().forEach(l->{ReservationAllocation a=byLine.get(l.getId());if(a!=null){l.setReservedQuantity(a.reservedQuantity());l.setBackorderedQuantity(a.backorderedQuantity());}});o.setStatus(SalesOrderStatus.CONFIRMED);o.setConfirmedAt(Instant.now());audit(o,"CONFIRMED",null,snapshot(o));return Response.from(o);}
    @Transactional public Response cancel(Long id){SalesOrder o=find(id);if(o.getStatus()==SalesOrderStatus.CANCELLED)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Order is already cancelled");if(o.getStatus()==SalesOrderStatus.CONFIRMED)inventory.release("SALES_ORDER",o.getId(),"Order cancelled");o.setStatus(SalesOrderStatus.CANCELLED);o.setCancelledAt(Instant.now());audit(o,"CANCELLED",null,snapshot(o));return Response.from(o);}
    @Transactional public List<AuditResponse> history(Long id){SalesOrder o=find(id);return audits.findByOrderIdAndTenantIdOrderByOccurredAtDesc(id,o.getTenantId()).stream().map(AuditResponse::from).toList();}
    private SalesOrder find(Long id){return orders.findByIdAndTenantId(id,tenants.requireTenantId()).map(o->{scope.requireScope(o.getCompanyId(),o.getBranchId());return o;}).orElseThrow(()->ResourceNotFoundException.of("Sales order",id));}
    private void apply(SalesOrder o,Request r){o.getLines().clear();for(LineRequest x:r.lines()){var p=products.findByIdAndTenantId(x.productId(),o.getTenantId()).orElseThrow(()->ResourceNotFoundException.of("Product",x.productId()));BigDecimal amount=money(x.unitPrice().multiply(x.quantity())),discount=money(x.discount()==null?BigDecimal.ZERO:x.discount());if(discount.compareTo(amount)>0)throw new ApiException(ErrorCode.VALIDATION_FAILED,"Line discount cannot exceed line amount");o.getLines().add(SalesOrderLine.builder().order(o).tenantId(o.getTenantId()).productId(p.getId()).productSku(p.getSku()).productName(p.getName()).quantity(x.quantity()).unitPrice(money(x.unitPrice())).discount(discount).lineTotal(money(amount.subtract(discount))).build());}totals(o);}
    private void totals(SalesOrder o){BigDecimal subtotal=o.getLines().stream().map(l->l.getUnitPrice().multiply(l.getQuantity())).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal discount=o.getLines().stream().map(SalesOrderLine::getDiscount).reduce(BigDecimal.ZERO,BigDecimal::add);o.setSubtotal(money(subtotal));o.setDiscountTotal(money(discount));o.setFinalAmount(money(subtotal.subtract(discount)));}
    private boolean sameCommercialValues(SalesOrder o,Request r){if(!Objects.equals(o.getCustomerId(),r.customerId())||!Objects.equals(o.getCurrency(),currency(r.currency()))||o.getLines().size()!=r.lines().size())return false;for(int i=0;i<o.getLines().size();i++){SalesOrderLine l=o.getLines().get(i);LineRequest x=r.lines().get(i);if(!Objects.equals(l.getProductId(),x.productId())||l.getQuantity().compareTo(x.quantity())!=0||l.getUnitPrice().compareTo(x.unitPrice())!=0||l.getDiscount().compareTo(x.discount()==null?BigDecimal.ZERO:x.discount())!=0)return false;}return true;}
    private void requireCorrectionWindow(SalesOrder o){if(!Objects.equals(CurrentActor.id(),o.getCreatedBy()))throw new ApiException(ErrorCode.ACCESS_DENIED,"Only the order creator may correct this order");if(o.getCreatedAt()==null||Instant.now().isAfter(o.getCreatedAt().plus(properties.correctionWindow())))throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Order correction window has expired");}
    private void audit(SalesOrder o,String action,Map<String,Object> old,Map<String,Object> next){audits.save(SalesOrderAudit.builder().order(o).tenantId(o.getTenantId()).action(action).actorId(CurrentActor.id()).actorEmail(CurrentActor.email()).oldValue(old).newValue(next).build());}
    private Map<String,Object> snapshot(SalesOrder o){return Map.of("status",o.getStatus().name(),"number",o.getOrderNumber(),"finalAmount",o.getFinalAmount(),"sourceDocumentId",Objects.toString(o.getSourceDocumentId(),""));}
    private String number(){return "ORD-%d-%06d".formatted(Year.now(ZoneOffset.UTC).getValue(),orders.nextNumber());} private String currency(String x){return x==null||x.isBlank()?"IRR":x.toUpperCase(Locale.ROOT);} private BigDecimal money(BigDecimal x){return x.setScale(2,RoundingMode.HALF_UP);}
}
