<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { goodsReceiptsApi } from '@/api/goodsReceipts'
import { purchaseOrdersApi } from '@/api/purchaseOrders'
import { inventoryApi } from '@/api/inventory'
const rows = ref<any[]>([])
const selectedReceipt = ref<any>(null)
const loading = ref(false)
const error = ref('')
const orders = ref<any[]>([]); const warehouses = ref<any[]>([]); const dialog = ref(false); const selectedOrder = ref<any>(null); const warehouseId = ref<number|null>(null); const receiptLines = ref<any[]>([]); const saving = ref(false)
async function load() {
  loading.value = true
  try { const [receipts,purchaseOrders,availableWarehouses]=await Promise.all([goodsReceiptsApi.list(),purchaseOrdersApi.list(),inventoryApi.warehouses()]); rows.value=receipts; orders.value = purchaseOrders.filter((o:any) => o.status === 'APPROVED'); warehouses.value=availableWarehouses.filter((w:any)=>w.active) }
  catch { error.value = 'Unable to load goods receipts' }
  finally { loading.value = false }
}
onMounted(load)
async function openDetail(id:number){try{selectedReceipt.value=await goodsReceiptsApi.get(id)}catch{error.value='Unable to load receipt detail'}}
async function chooseOrder(o:any){if(!o)return; selectedOrder.value=await purchaseOrdersApi.get(o.id); receiptLines.value=(selectedOrder.value.lines||[]).map((l:any)=>({purchaseOrderLineId:l.id,productId:l.product_id,variantId:l.variant_id,orderedQuantity:l.quantity,receivedQuantity:0,unitCost:l.unit_price,serialNumber:'',imei:'',hamtaActivationCode:''})) ;dialog.value=true}
async function save(){if(saving.value)return;if(!selectedOrder.value||!warehouseId.value||receiptLines.value.some(l=>!l.receivedQuantity||l.receivedQuantity<=0||l.receivedQuantity>l.orderedQuantity)){error.value='Enter valid received quantities';return}const invalidSerial=receiptLines.value.some(l=>(l.serialNumber||l.imei)&&l.receivedQuantity!==1);if(invalidSerial){error.value='A single serial/IMEI entry requires received quantity 1';return}saving.value=true;try{await goodsReceiptsApi.create({companyId:selectedOrder.value.company_id,branchId:selectedOrder.value.branch_id,purchaseOrderId:selectedOrder.value.id,warehouseId:warehouseId.value,lines:receiptLines.value.map((l:any)=>({purchaseOrderLineId:l.purchaseOrderLineId,productId:l.productId,receivedQuantity:l.receivedQuantity,unitCost:l.unitCost,serials:(l.serialNumber||l.imei)?[{serialNumber:l.serialNumber||undefined,imei:l.imei||undefined,hamtaActivationCode:l.hamtaActivationCode||undefined}]:[]}))});dialog.value=false;await load()}catch(e){error.value='Goods receipt was rejected by the server'}finally{saving.value=false}}
</script>
<template><section class="pa-4"><div class="d-flex justify-space-between"><h2 class="text-h6">Goods Receipts</h2><div><v-btn color="primary" class="mr-2" :disabled="!orders.length" @click="chooseOrder(orders[0])">Receive Approved PO</v-btn><v-btn icon="mdi-refresh" :loading="loading" @click="load"/></div></div><v-alert v-if="error" type="error">{{error}}</v-alert><v-progress-linear v-if="loading" indeterminate/><v-list v-else><v-list-item v-for="r in rows" :key="r.id" :title="r.receipt_number" :subtitle="`${r.status} · PO ${r.purchase_order_id}`" @click="openDetail(r.id)"/><v-list-item v-if="!rows.length" title="No goods receipts"/></v-list><v-dialog v-model="dialog" max-width="900"><v-card><v-card-title>Receive Purchase Order</v-card-title><v-card-text><v-select v-model="selectedOrder" :items="orders" item-title="order_number" return-object label="Purchase Order" @update:model-value="chooseOrder"/><v-select v-model="warehouseId" :items="warehouses" item-title="name" item-value="id" label="Warehouse"/><div v-for="line in receiptLines" :key="line.purchaseOrderLineId" class="mb-4"><div class="text-body-2 mb-2">Product {{line.productId}}<span v-if="line.variantId"> · Variant {{line.variantId}}</span> · Ordered {{line.orderedQuantity}}</div><div class="d-flex flex-wrap ga-2"><v-text-field v-model.number="line.receivedQuantity" type="number" min="0" :max="line.orderedQuantity" label="Received"/><v-text-field v-model="line.serialNumber" label="Serial number"/><v-text-field v-model="line.imei" label="IMEI"/><v-text-field v-model="line.hamtaActivationCode" label="HAMTA activation code"/></div></div></v-card-text><v-card-actions><v-spacer/><v-btn @click="dialog=false">Cancel</v-btn><v-btn color="primary" :loading="saving" @click="save">Confirm receipt</v-btn></v-card-actions></v-card></v-dialog><v-dialog :model-value="!!selectedReceipt" max-width="700" @update:model-value="selectedReceipt=null"><v-card v-if="selectedReceipt"><v-card-title>{{selectedReceipt.receipt_number}}</v-card-title><v-card-text><div>Status: {{selectedReceipt.status}}</div><div>Purchase Order: {{selectedReceipt.purchase_order_id}}</div><div>Supplier: {{selectedReceipt.supplier_id}}</div><div>Company / Branch: {{selectedReceipt.company_id}} / {{selectedReceipt.branch_id}}</div><div>Date: {{selectedReceipt.received_at}}</div><v-divider class="my-3"/><div v-for="line in selectedReceipt.lines" :key="line.id">Product {{line.product_id}}<span v-if="line.variant_id"> · Variant {{line.variant_id}}</span> · Received {{line.received_quantity}} · Unit cost {{line.unit_cost}}</div></v-card-text></v-card></v-dialog></section></template>
