<script setup lang="ts">
import { onMounted, ref, computed } from 'vue'
import { purchaseOrdersApi, type PurchaseOrder, type PurchaseOrderLine } from '@/api/purchaseOrders'
import { suppliersApi } from '@/api/suppliers'
import { productsApi } from '@/api/products'
import { organizationContextApi } from '@/api/organizationContext'
const orders=ref<PurchaseOrder[]>([]), suppliers=ref<any[]>([]), products=ref<any[]>([]), loading=ref(false), saving=ref(false), error=ref(''), dialog=ref(false), selected=ref<PurchaseOrder|null>(null)
const ctx=ref<any>(null), supplier=ref<number|null>(null), notes=ref(''), lines=ref<PurchaseOrderLine[]>([{productId:0,quantity:1,unitPrice:0}])
const total=computed(()=>lines.value.reduce((s,l)=>s+l.quantity*l.unitPrice,0))
async function load(){loading.value=true;try{orders.value=await purchaseOrdersApi.list(); const [s,p,c]=await Promise.all([suppliersApi.list({size:200}),productsApi.list({size:200,active:true}),organizationContextApi.current()]);suppliers.value=s.content;products.value=p.content;ctx.value=c}catch(e){error.value='Unable to load purchase orders'}finally{loading.value=false}}
function add(){lines.value.push({productId:0,quantity:1,unitPrice:0})}
async function create(){if(!ctx.value?.companyId||!ctx.value?.branchId||!supplier.value||lines.value.some(l=>!l.productId||l.quantity<=0)){error.value='Complete company, branch, supplier and lines';return} saving.value=true;try{await purchaseOrdersApi.create(ctx.value.companyId,ctx.value.branchId,supplier.value,lines.value,notes.value||undefined);dialog.value=false;await load()}catch(e){error.value='Could not create purchase order'}finally{saving.value=false}}
async function action(id:number,kind:'submit'|'approve'|'cancel'){try{await purchaseOrdersApi[kind](id);await load()}catch(e){error.value='Action rejected by server'}}
onMounted(load)
</script>
<template><section class="pa-4"><div class="d-flex align-center justify-space-between mb-3"><h2 class="text-h6">Purchase Orders</h2><div><v-btn class="mr-2" color="primary" @click="dialog=true">Create</v-btn><v-btn icon="mdi-refresh" variant="tonal" :loading="loading" aria-label="Refresh" @click="load"/></div></div><v-alert v-if="error" type="error" class="mb-3">{{error}}</v-alert><v-progress-linear v-if="loading" indeterminate/><v-list v-else><v-list-item v-for="o in orders" :key="o.id" :title="o.order_number" :subtitle="`${o.status} · ${o.total}`" @click="selected=o"><template #append><v-btn v-if="o.status==='DRAFT'" size="small" @click.stop="action(o.id,'submit')">Submit</v-btn><v-btn v-if="o.status==='SUBMITTED'" size="small" @click.stop="action(o.id,'approve')">Approve</v-btn><v-btn v-if="o.status==='DRAFT'" size="small" color="error" @click.stop="action(o.id,'cancel')">Cancel</v-btn></template></v-list-item><v-list-item v-if="!orders.length" title="No purchase orders"/></v-list><v-dialog v-model="dialog" max-width="700"><v-card><v-card-title>Create Purchase Order</v-card-title><v-card-text><v-select v-model="supplier" :items="suppliers" item-title="displayName" item-value="id" label="Supplier"/><v-text-field v-model="notes" label="Notes"/><div v-for="(l,i) in lines" :key="i" class="d-flex ga-2"><v-select v-model="l.productId" :items="products" item-title="name" item-value="id" label="Product"/><v-text-field v-model.number="l.quantity" type="number" label="Quantity"/><v-text-field v-model.number="l.unitPrice" type="number" label="Unit price"/><v-btn icon="mdi-delete" @click="lines.splice(i,1)"/></div><v-btn variant="text" @click="add">Add line</v-btn><div class="text-right">Total: {{total}}</div></v-card-text><v-card-actions><v-spacer/><v-btn @click="dialog=false">Cancel</v-btn><v-btn color="primary" :loading="saving" @click="create">Create</v-btn></v-card-actions></v-card></v-dialog><v-dialog :model-value="!!selected" max-width="600" @update:model-value="selected=null"><v-card v-if="selected"><v-card-title>{{selected.order_number}}</v-card-title><v-card-text>Status: {{selected.status}}<div v-for="l in selected.lines" :key="l.productId">{{l.productId}} · {{l.quantity}} × {{l.unitPrice}}</div><div>Total: {{selected.total}}</div></v-card-text></v-card></v-dialog></section></template>
