package com.sami.app.sales.document;
import com.sami.app.common.exception.*; import com.sami.app.common.tenancy.TenantContext; import com.sami.app.contact.publicapi.ContactCustomerRoleLookup; import com.sami.app.organization.service.OrganizationScopeService; import com.sami.app.product.repository.ProductRepository; import com.sami.app.security.CurrentActor; import com.sami.app.sales.document.SalesDocumentDtos.*; import com.sami.app.sales.publicapi.QuotationConversionSource; import java.math.*; import java.time.*; import java.util.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor public class SalesDocumentService implements QuotationConversionSource { private final TenantContext tenants; private final OrganizationScopeService scope; private final ContactCustomerRoleLookup contacts; private final ProductRepository products; private final SalesDocumentRepository documents; private final SalesDocumentAuditRepository audits;
 @Transactional public Response create(Request r){Long t=tenants.requireTenantId(); scope.requireScope(r.companyId(),r.branchId()); Long contact=contacts.requireContactIdForCustomer(r.customerId()); SalesDocument d=SalesDocument.builder().tenantId(t).companyId(r.companyId()).branchId(r.branchId()).customerId(r.customerId()).contactId(contact).documentType(r.documentType()).documentNumber(number(r.documentType())).status(SalesDocumentStatus.DRAFT).currency(currency(r.currency())).notes(r.notes()).createdBy(CurrentActor.id()).createdByEmail(CurrentActor.email()).build(); apply(d,r); documents.saveAndFlush(d); audit(d,"CREATED",null,snapshot(d)); return Response.from(d); }
 @Transactional(readOnly=true) public List<Response> list(Long companyId,Long branchId,SalesDocumentType type){scope.requireScope(companyId,branchId); return documents.findByTenantIdAndCompanyIdAndBranchIdOrderByCreatedAtDesc(tenants.requireTenantId(),companyId,branchId).stream().filter(d->type==null||d.getDocumentType()==type).map(Response::from).toList();}
 @Transactional(readOnly=true) public Response get(Long id){return Response.from(find(id));}
 @Transactional public Response update(Long id,Request r){SalesDocument d=find(id); if(d.getStatus()!=SalesDocumentStatus.DRAFT)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Only drafts can be edited"); if(r.expectedVersion()!=null&&!r.expectedVersion().equals(d.getVersion()))throw new ApiException(ErrorCode.RESOURCE_CONFLICT,"Document was modified; reload and retry"); scope.requireScope(r.companyId(),r.branchId()); Map<String,Object> old=snapshot(d); d.setCompanyId(r.companyId());d.setBranchId(r.branchId());d.setCustomerId(r.customerId());d.setContactId(contacts.requireContactIdForCustomer(r.customerId()));d.setDocumentType(r.documentType());d.setCurrency(currency(r.currency()));d.setNotes(r.notes());apply(d,r);audit(d,"UPDATED",old,snapshot(d));return Response.from(d);}
 @Transactional public Response issue(Long id){SalesDocument d=find(id); if(d.getStatus()!=SalesDocumentStatus.DRAFT)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Only drafts can be issued");d.setStatus(SalesDocumentStatus.ISSUED);d.setIssuedAt(Instant.now());audit(d,"ISSUED",null,snapshot(d));return Response.from(d);}
 @Transactional public Response cancel(Long id){SalesDocument d=find(id); if(d.getStatus()==SalesDocumentStatus.CANCELLED||d.getStatus()==SalesDocumentStatus.EXPIRED)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Document is already terminal");d.setStatus(SalesDocumentStatus.CANCELLED);d.setCancelledAt(Instant.now());audit(d,"CANCELLED",null,snapshot(d));return Response.from(d);}
 @Transactional public Response expire(Long id){SalesDocument d=find(id); if(d.getStatus()!=SalesDocumentStatus.ISSUED)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Only issued documents can expire");d.setStatus(SalesDocumentStatus.EXPIRED);d.setExpiredAt(Instant.now());audit(d,"EXPIRED",null,snapshot(d));return Response.from(d);}
 @Transactional(readOnly=true) public List<AuditResponse> auditHistory(Long id){SalesDocument d=find(id);return audits.findByDocumentIdAndTenantIdOrderByOccurredAtDesc(id,d.getTenantId()).stream().map(AuditResponse::from).toList();}
 @Override @Transactional(readOnly=true) public QuotationSnapshot requireIssuedQuotation(Long id){SalesDocument d=find(id);if((d.getDocumentType()!=SalesDocumentType.QUOTATION&&d.getDocumentType()!=SalesDocumentType.PROFORMA)||d.getStatus()!=SalesDocumentStatus.ISSUED)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Only issued quotation/proforma documents are available for order conversion");return new QuotationSnapshot(d.getId(),d.getDocumentType(),d.getTenantId(),d.getCompanyId(),d.getBranchId(),d.getCustomerId(),d.getContactId(),d.getCurrency(),d.getLines().stream().map(l->new Line(l.getId(),l.getProductId(),l.getProductSku(),l.getProductName(),l.getQuantity(),l.getUnitPrice(),l.getDiscount(),l.getLineTotal())).toList());}
 private SalesDocument find(Long id){SalesDocument d=documents.findByIdAndTenantId(id,tenants.requireTenantId()).orElseThrow(()->ResourceNotFoundException.of("Sales document",id));scope.requireScope(d.getCompanyId(),d.getBranchId());return d;}
 private void apply(SalesDocument d,Request r){d.getLines().clear();BigDecimal subtotal=BigDecimal.ZERO,discount=BigDecimal.ZERO;for(LineRequest x:r.lines()){var p=products.findByIdAndTenantId(x.productId(),d.getTenantId()).orElseThrow(()->ResourceNotFoundException.of("Product",x.productId()));BigDecimal amount=money(x.unitPrice().multiply(x.quantity())),disc=money(x.discount()==null?BigDecimal.ZERO:x.discount());if(disc.compareTo(amount)>0)throw new ApiException(ErrorCode.VALIDATION_FAILED,"Line discount cannot exceed line amount");d.getLines().add(SalesDocumentLine.builder().document(d).tenantId(d.getTenantId()).productId(p.getId()).productSku(p.getSku()).productName(p.getName()).quantity(x.quantity()).unitPrice(money(x.unitPrice())).discount(disc).lineTotal(money(amount.subtract(disc))).build());subtotal=subtotal.add(amount);discount=discount.add(disc);}d.setSubtotal(money(subtotal));d.setDiscountTotal(money(discount));d.setFinalAmount(money(subtotal.subtract(discount)));}
 private void audit(SalesDocument d,String action,Map<String,Object> old,Map<String,Object> next){audits.save(SalesDocumentAudit.builder().document(d).tenantId(d.getTenantId()).action(action).actorId(CurrentActor.id()).actorEmail(CurrentActor.email()).oldValue(old).newValue(next).build());} private Map<String,Object> snapshot(SalesDocument d){return Map.of("status",d.getStatus().name(),"number",d.getDocumentNumber(),"finalAmount",d.getFinalAmount());} private String number(SalesDocumentType type){return (type==SalesDocumentType.QUOTATION?"QTN":"PRF")+"-"+Year.now(ZoneOffset.UTC).getValue()+"-%06d".formatted(documents.nextNumber());} private String currency(String v){return v==null||v.isBlank()?"IRR":v.toUpperCase(Locale.ROOT);} private BigDecimal money(BigDecimal v){return v.setScale(2,RoundingMode.HALF_UP);} }
