<script setup lang="ts">
import{onMounted,reactive,ref}from'vue';import{useI18n}from'vue-i18n';import{salesApi}from '@/api/sales';import{useApiError}from '@/composables/useApiError';import type{SalesFilter,SalesReport}from '@/types/sales';
const{t}=useI18n(),error=useApiError(),loading=ref(false),report=ref<SalesReport|null>(null),window=globalThis.window;const filters=reactive({from:'',to:'',branchId:null as number|null,sellerId:null as number|null,status:'',saleType:''});
const money=(v:number)=>new Intl.NumberFormat(undefined,{maximumFractionDigits:2}).format(v||0);function params():SalesFilter{return{from:filters.from?new Date(`${filters.from}T00:00:00`).toISOString():undefined,to:filters.to?new Date(`${filters.to}T23:59:59.999`).toISOString():undefined,branchId:filters.branchId||undefined,sellerId:filters.sellerId||undefined,status:filters.status||undefined,saleType:filters.saleType||undefined}}
async function load(){loading.value=true;error.clear();try{report.value=await salesApi.reports(params())}catch(e){error.set(e)}finally{loading.value=false}}
onMounted(load);
</script>
<template><section aria-labelledby="sales-reports-title"><div class="d-flex align-center flex-wrap ga-2 mb-4"><div><h2 id="sales-reports-title" class="text-h6">{{t('sales.reports')}}</h2><p class="text-body-2 text-medium-emphasis mb-0">{{t('sales.reportsSubtitle')}}</p></div><v-spacer/><v-btn variant="tonal" prepend-icon="mdi-file-excel-outline" @click="salesApi.exportCsv(params()).catch(error.set)">{{t('sales.export')}}</v-btn><v-btn variant="tonal" prepend-icon="mdi-printer-outline" @click="window.print()">{{t('sales.printReport')}}</v-btn></div>
 <v-alert v-if="error.message.value" type="error" closable class="mb-4" @click:close="error.clear()">{{error.message.value}}</v-alert>
 <v-card rounded="xl" class="pa-4 mb-4 app-data-surface"><v-row dense><v-col cols="6" md="2"><AppPersianDatePicker v-model="filters.from" :label="t('sales.from')" hide-details/></v-col><v-col cols="6" md="2"><AppPersianDatePicker v-model="filters.to" :label="t('sales.to')" hide-details/></v-col><v-col cols="6" md="2"><v-text-field v-model.number="filters.branchId" type="number" :label="t('sales.branch')" hide-details/></v-col><v-col cols="6" md="2"><v-text-field v-model.number="filters.sellerId" type="number" :label="t('sales.seller')" hide-details/></v-col><v-col cols="6" md="2"><v-select v-model="filters.status" :items="['','DRAFT','CONFIRMED','COMPLETED','CANCELLED','PARTIALLY_RETURNED','RETURNED']" :item-title="(v:string)=>v?t(`sales.values.${v}`,v):t('common.all')" :label="t('sales.status')" hide-details/></v-col><v-col cols="6" md="2" class="d-flex"><v-btn block color="primary" :loading="loading" @click="load">{{t('common.apply')}}</v-btn></v-col></v-row></v-card>
 <v-skeleton-loader v-if="loading&&!report" type="card@2"/>
 <template v-else-if="report"><v-row class="mb-2"><v-col v-for="metric in [{k:'revenue',v:money(report.revenue)},{k:'grossProfit',v:money(report.grossProfit)},{k:'averageTicket',v:money(report.averageTicket)},{k:'invoiceCount',v:report.invoiceCount},{k:'lostSaleCount',v:report.lostSaleCount},{k:'returnRate',v:`${report.returnRate}%`}]" :key="metric.k" cols="6" md="2"><v-card rounded="xl" class="pa-4 h-100"><div class="text-caption text-medium-emphasis">{{t(`sales.${metric.k}`)}}</div><div class="text-h6 font-weight-bold mt-2">{{metric.v}}</div></v-card></v-col></v-row>
 <v-row><v-col cols="12" md="6" v-for="group in [{key:'dailySales',rows:report.dailySales},{key:'topProducts',rows:report.topProducts},{key:'topSellers',rows:report.topSellers},{key:'paymentMethods',rows:report.paymentMethods}]" :key="group.key"><v-card rounded="xl" class="h-100 app-data-surface"><v-card-title class="text-subtitle-1">{{t(`sales.${group.key}`)}}</v-card-title><v-list v-if="group.rows.length" density="compact"><v-list-item v-for="row in group.rows" :key="row.label" :title="t(`sales.values.${row.label}`,row.label)" :subtitle="`${row.count} ${t('sales.records')}`"><template #append><strong>{{money(row.value)}}</strong></template></v-list-item></v-list><div v-else class="pa-8 text-center text-medium-emphasis">{{t('sales.noReportData')}}</div></v-card></v-col></v-row></template>
</section></template>
<style scoped>@media print{button,.v-card:first-of-type{display:none!important}}@media(max-width:599px){:deep(.v-btn){min-height:44px}}</style>
