<script setup lang="ts">
import{reactive,ref}from'vue';import{useI18n}from'vue-i18n';import{salesApi}from '@/api/sales';import{usePermission}from '@/composables/usePermission';import type{Sale,SaleAudit,SaleDiscount}from '@/types/sales';
const props=defineProps<{sale:Sale}>(),emit=defineEmits<{updated:[Sale];failed:[unknown]}>();const{t}=useI18n(),{can}=usePermission();const mode=ref<'payment'|'discount'|'return'|'audit'|'approval'|null>(null),busy=ref(false),audit=ref<SaleAudit[]>([]),discountHistory=ref<SaleDiscount[]>([]);const payment=reactive({method:'CASH',amount:0,referenceNo:''}),discount=reactive({type:'AMOUNT',amount:0,reason:''}),ret=reactive({reason:'',refundMethod:'CASH'});
async function submit(){busy.value=true;try{let value:Sale;if(mode.value==='payment')value=await salesApi.addPayment(props.sale.id,payment);else if(mode.value==='discount')value=await salesApi.requestDiscount(props.sale.id,discount);else value=await salesApi.returnSale(props.sale.id,{reason:ret.reason,refundMethod:ret.refundMethod,items:props.sale.items.filter(i=>i.returnedQuantity<i.quantity).map(i=>({saleItemId:i.id,quantity:i.quantity-i.returnedQuantity}))});emit('updated',value);mode.value=null}catch(e){emit('failed',e)}finally{busy.value=false}}
async function showAudit(){mode.value='audit';busy.value=true;try{audit.value=await salesApi.audit(props.sale.id)}catch(e){emit('failed',e)}finally{busy.value=false}}
async function showApprovals(){mode.value='approval';busy.value=true;try{discountHistory.value=await salesApi.discounts(props.sale.id)}catch(e){emit('failed',e)}finally{busy.value=false}}
async function decide(id:number,approved:boolean){busy.value=true;try{emit('updated',await salesApi.decideDiscount(props.sale.id,id,approved));discountHistory.value=await salesApi.discounts(props.sale.id)}catch(e){emit('failed',e)}finally{busy.value=false}}
</script>
<template><div class="sale-actions"><v-btn v-if="can('sales:payment')&&!['CANCELLED','RETURNED'].includes(sale.status)" color="primary" prepend-icon="mdi-credit-card-plus-outline" @click="mode='payment'">{{t('sales.payment')}}</v-btn><v-btn v-if="can('sales:edit')&&sale.status==='DRAFT'" variant="tonal" prepend-icon="mdi-sale-outline" @click="mode='discount'">{{t('sales.discount')}}</v-btn><v-btn v-if="can('sales:approve-discount')&&sale.status==='DRAFT'" variant="tonal" prepend-icon="mdi-check-decagram-outline" @click="showApprovals">{{t('sales.approvals')}}</v-btn><v-btn v-if="can('sales:return')&&['COMPLETED','PARTIALLY_RETURNED'].includes(sale.status)" color="warning" variant="tonal" prepend-icon="mdi-undo-variant" @click="mode='return'">{{t('sales.returnSale')}}</v-btn><v-btn v-if="can('sales:view-audit')" variant="tonal" prepend-icon="mdi-history" @click="showAudit">{{t('sales.audit')}}</v-btn></div>
<v-dialog :model-value="!!mode" max-width="560" @update:model-value="mode=null"><v-card rounded="xl"><v-card-title>{{mode?t(`sales.${mode}`):''}}</v-card-title><v-card-text>
 <template v-if="mode==='payment'"><v-select v-model="payment.method" :items="['CASH','CARD','TRANSFER','CHEQUE','WALLET','INSTALLMENT']" :item-title="(x:string)=>t(`sales.values.${x}`,x)" :label="t('sales.paymentMethod')"/><v-text-field v-model.number="payment.amount" type="number" min="0" :label="t('sales.amount')"/><v-text-field v-model="payment.referenceNo" :label="t('sales.reference')"/></template>
 <template v-else-if="mode==='discount'"><v-select v-model="discount.type" :items="['AMOUNT','PERCENT','VIP','CAMPAIGN','COUPON']" :label="t('sales.discountType')"/><v-text-field v-model.number="discount.amount" type="number" min="0" :label="t('sales.amount')"/><v-textarea v-model="discount.reason" :label="t('sales.reason')"/></template>
 <template v-else-if="mode==='return'"><v-alert type="warning" variant="tonal" class="mb-4">{{t('sales.returnAllRemaining')}}</v-alert><v-textarea v-model="ret.reason" :label="t('sales.reason')"/><v-select v-model="ret.refundMethod" :items="['CASH','CARD','TRANSFER','WALLET']" :label="t('sales.refundMethod')"/></template>
 <v-timeline v-else-if="mode==='audit'" side="end" density="compact"><v-timeline-item v-for="entry in audit" :key="entry.id" dot-color="primary"><strong>{{t(`sales.values.${entry.action}`,entry.action)}}</strong><div class="text-caption">{{entry.actorEmail}} · {{new Date(entry.occurredAt).toLocaleString()}}</div></v-timeline-item></v-timeline>
 <v-list v-else-if="mode==='approval'"><v-list-item v-for="entry in discountHistory" :key="entry.id" :title="`${entry.type} · ${entry.amount}`" :subtitle="entry.reason"><template #append><v-chip v-if="entry.status!=='PENDING'" size="small">{{entry.status}}</v-chip><div v-else class="d-flex ga-1"><v-btn color="success" icon="mdi-check" size="small" :loading="busy" @click="decide(entry.id,true)"/><v-btn color="error" icon="mdi-close" size="small" :loading="busy" @click="decide(entry.id,false)"/></div></template></v-list-item></v-list>
</v-card-text><v-card-actions><v-spacer/><v-btn variant="text" @click="mode=null">{{t('common.close')}}</v-btn><v-btn v-if="mode!=='audit'&&mode!=='approval'" color="primary" :loading="busy" @click="submit">{{t('common.save')}}</v-btn></v-card-actions></v-card></v-dialog></template>
<style scoped>.sale-actions{position:fixed;z-index:2500;inset-inline:16px;bottom:16px;display:flex;justify-content:center;gap:8px;flex-wrap:wrap;pointer-events:none}.sale-actions>*{pointer-events:auto}@media(min-width:960px){.sale-actions{inset-inline-start:auto;inset-inline-end:32px;justify-content:flex-end}}</style>
