<script setup lang="ts">
import {onMounted,ref,computed} from 'vue'; import {useI18n} from 'vue-i18n'; import {customersApi} from '@/api/customers'; import {treasuryApi} from '@/api/treasury'; import {salesInvoicesApi} from '@/api/salesInvoices'; import {salesReceiptsApi} from '@/api/salesReceipts'; import {useOrganizationContextStore} from '@/stores/organizationContext';
const {t}=useI18n();
const org=useOrganizationContextStore(),customers=ref<any[]>([]),accounts=ref<any[]>([]),invoices=ref<any[]>([]),customerId=ref<number>(),accountId=ref<number>(),amount=ref(0),allocation=ref(0),invoiceId=ref<number>(),result=ref<any>(),error=ref('');
async function load(){customers.value=(await customersApi.list({size:100})).content;accounts.value=await treasuryApi.accounts();invoices.value=await salesInvoicesApi.list(org.companyId!,org.branchId!)}
async function create(){try{const r=await salesReceiptsApi.create({companyId:org.companyId!,branchId:org.branchId!,customerId:customerId.value!,amount:amount.value,paymentMethod:'CASH'},crypto.randomUUID());await salesReceiptsApi.allocate(r.id,invoiceId.value!,allocation.value);result.value=await salesReceiptsApi.confirm(r.id,accountId.value!)}catch(e:any){error.value=e?.message??'Receipt failed'}}
onMounted(async()=>{if(!org.context)await org.refresh();await load()})
</script>
<template><v-card rounded="xl" class="receipt-panel"><v-card-title>{{t('sales.receiptTitle')}}</v-card-title><v-card-text><v-row dense><v-col cols="12" sm="6"><v-select v-model="customerId" :items="customers" item-title="displayName" item-value="id" :label="t('sales.customer')"/></v-col><v-col cols="12" sm="6"><v-text-field v-model.number="amount" type="number" inputmode="decimal" :label="t('sales.receiptAmount')"/></v-col><v-col cols="12" sm="6"><v-select v-model="accountId" :items="accounts" item-title="name" item-value="id" :label="t('sales.treasuryAccount')"/></v-col><v-col cols="12" sm="6"><v-select v-model="invoiceId" :items="invoices.filter(i=>i.customerId===customerId&&i.status==='ISSUED')" item-title="invoiceNumber" item-value="id" :label="t('sales.eligibleInvoice')"/></v-col><v-col cols="12" sm="6"><v-text-field v-model.number="allocation" type="number" inputmode="decimal" :label="t('sales.allocationAmount')"/></v-col></v-row><v-alert v-if="error" type="error" variant="tonal">{{error}}</v-alert><v-alert v-if="result" type="success" variant="tonal">{{result.status}} · {{t('sales.treasury')}}: {{result.treasury_transaction_id}} · {{t('sales.accounting')}}: {{result.accounting_posting_reference}}</v-alert></v-card-text><v-card-actions class="flex-wrap"><v-btn block color="primary" :disabled="!customerId||!accountId||!invoiceId||amount<=0||allocation<=0" @click="create">{{t('sales.confirmReceipt')}}</v-btn></v-card-actions></v-card></template>
