package com.sami.app.uom.service;
import com.sami.app.common.exception.*; import com.sami.app.common.tenancy.TenantContext; import com.sami.app.organization.service.FoundationAuditService; import com.sami.app.uom.domain.*; import com.sami.app.uom.dto.UomDtos.*; import com.sami.app.uom.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.*; import java.util.*;
@Service @RequiredArgsConstructor public class UomService { private final UnitOfMeasureRepository uoms; private final UomConversionRepository conversions; private final TenantContext tenants; private final FoundationAuditService audit;
 @Transactional(readOnly=true) public List<UomResponse> list(){return uoms.findAllByTenantIdOrderByCode(tenants.requireTenantId()).stream().map(this::uom).toList();}
 @Transactional public UomResponse create(UomRequest r){long t=tenants.requireTenantId();String c=r.code().trim().toUpperCase(Locale.ROOT);if(uoms.existsByTenantIdAndCode(t,c))throw new ApiException(ErrorCode.RESOURCE_CONFLICT,"UOM code already exists");UnitOfMeasure u=uoms.saveAndFlush(UnitOfMeasure.builder().tenantId(t).code(c).name(r.name()).status(status(r.status())).build());audit.record(t,null,null,"UOM",u.getId(),"CREATED",null,Map.of("code",c));return uom(u);}
 @Transactional public UomResponse update(Long id,UomRequest r){UnitOfMeasure u=uoms.findByTenantIdAndId(tenants.requireTenantId(),id).orElseThrow(()->ResourceNotFoundException.of("UOM",id));u.setName(r.name());u.setStatus(status(r.status()));audit.record(tenants.requireTenantId(),null,null,"UOM",id,"UPDATED",null,Map.of("status",u.getStatus()));return uom(u);}
 @Transactional public ConversionResponse createConversion(ConversionRequest r){long t=tenants.requireTenantId();if(r.fromUomId().equals(r.toUomId()))throw new ApiException(ErrorCode.VALIDATION_FAILED,"Conversion UOMs must differ");requireActive(r.fromUomId());requireActive(r.toUomId());if(conversions.findByTenantIdAndFromUomIdAndToUomId(t,r.fromUomId(),r.toUomId()).isPresent()||conversions.findByTenantIdAndFromUomIdAndToUomId(t,r.toUomId(),r.fromUomId()).isPresent())throw new ApiException(ErrorCode.RESOURCE_CONFLICT,"Conversion already exists");UomConversion c=conversions.saveAndFlush(UomConversion.builder().tenantId(t).fromUomId(r.fromUomId()).toUomId(r.toUomId()).factor(r.factor()).status(status(r.status())).build());audit.record(t,null,null,"UOM_CONVERSION",c.getId(),"CREATED",null,Map.of("fromUomId",r.fromUomId(),"toUomId",r.toUomId()));return conversion(c);}
 @Transactional public ConversionResponse updateConversion(Long id,ConversionRequest r){UomConversion c=conversions.findByTenantIdAndId(tenants.requireTenantId(),id).orElseThrow(()->ResourceNotFoundException.of("UOM conversion",id));if(r.fromUomId().equals(r.toUomId()))throw new ApiException(ErrorCode.VALIDATION_FAILED,"Conversion UOMs must differ");requireActive(r.fromUomId());requireActive(r.toUomId());c.setFactor(r.factor());c.setStatus(status(r.status()));audit.record(tenants.requireTenantId(),null,null,"UOM_CONVERSION",id,"UPDATED",null,Map.of("factor",r.factor()));return conversion(c);}
 @Transactional(readOnly=true) public List<ConversionResponse> conversions(){return conversions.findAllByTenantIdOrderById(tenants.requireTenantId()).stream().map(this::conversion).toList();}
 @Transactional(readOnly=true) public QuantityConversion convert(BigDecimal quantity,Long from,Long to){if(quantity==null||quantity.signum()<0)throw new ApiException(ErrorCode.VALIDATION_FAILED,"Quantity must be non-negative");if(from.equals(to))return new QuantityConversion(quantity,from,to,BigDecimal.ONE,quantity);long t=tenants.requireTenantId();requireActive(from);requireActive(to);Optional<UomConversion> direct=conversions.findByTenantIdAndFromUomIdAndToUomId(t,from,to);if(direct.isPresent()&&"ACTIVE".equals(direct.get().getStatus()))return result(quantity,from,to,direct.get().getFactor());Optional<UomConversion> reverse=conversions.findByTenantIdAndFromUomIdAndToUomId(t,to,from);if(reverse.isPresent()&&"ACTIVE".equals(reverse.get().getStatus())){BigDecimal factor=BigDecimal.ONE.divide(reverse.get().getFactor(),12,RoundingMode.HALF_UP);return new QuantityConversion(quantity,from,to,factor,quantity.divide(reverse.get().getFactor(),12,RoundingMode.HALF_UP).stripTrailingZeros());}throw new ApiException(ErrorCode.RESOURCE_NOT_FOUND,"Active conversion not found");}
 private QuantityConversion result(BigDecimal q,Long f,Long t,BigDecimal factor){return new QuantityConversion(q,f,t,factor,q.multiply(factor).stripTrailingZeros());} private void requireActive(Long id){UnitOfMeasure u=uoms.findByTenantIdAndId(tenants.requireTenantId(),id).orElseThrow(()->ResourceNotFoundException.of("UOM",id));if(!"ACTIVE".equals(u.getStatus()))throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"UOM is inactive");} private String status(String s){if(!Set.of("ACTIVE","INACTIVE").contains(s))throw new ApiException(ErrorCode.VALIDATION_FAILED,"Invalid status");return s;} private UomResponse uom(UnitOfMeasure u){return new UomResponse(u.getId(),u.getCode(),u.getName(),u.getStatus(),u.getCreatedAt(),u.getUpdatedAt(),u.getVersion());} private ConversionResponse conversion(UomConversion c){return new ConversionResponse(c.getId(),c.getFromUomId(),c.getToUomId(),c.getFactor(),c.getStatus(),c.getCreatedAt(),c.getUpdatedAt(),c.getVersion());}
}
