<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useDisplay } from 'vuetify'
import { useI18n } from 'vue-i18n'
import AppEmptyState from '@/components/AppEmptyState.vue'
import AppPageHeader from '@/components/AppPageHeader.vue'
import AppQuickCreateButton from '@/components/AppQuickCreateButton.vue'
import QuickCustomerCreateDialog from '@/components/QuickCustomerCreateDialog.vue'
import { appointmentsApi } from '@/api/appointments'
import { customersApi } from '@/api/customers'
import { useApiError } from '@/composables/useApiError'
import { useFormat } from '@/composables/useFormat'
import { useNotifications } from '@/composables/useNotifications'
import { usePermission } from '@/composables/usePermission'
import type { AppointmentCatalog, AppointmentResource, BookingPayload, BookingResult, TimeSlot } from '@/types/appointments'
import type { Customer, CustomerDetail } from '@/types/models'

const { t }=useI18n(); const { xs }=useDisplay(); const { can }=usePermission(); const { formatDateTime }=useFormat(); const notifications=useNotifications(); const { message:errorMessage,set:setError,clear:clearError }=useApiError()
const loading=ref(false); const saving=ref(false); const catalog=ref<AppointmentCatalog>({appointmentTypes:[],statuses:[],categories:[],resourceCategories:[],resourceStatuses:[]}); const resources=ref<AppointmentResource[]>([]); const customers=ref<Customer[]>([]); const slots=ref<TimeSlot[]>([]); const result=ref<BookingResult>(); const createOpen=ref(false); const quickCustomerOpen=ref(false)
const typeCode=ref(''); const resourceIds=ref<number[]>([]); const date=ref(new Date(Date.now()+86400000).toISOString().slice(0,10)); const fromTime=ref('08:00'); const toTime=ref('18:00'); const duration=ref<number>(); const title=ref(''); const description=ref(''); const customerId=ref<number>(); const joinWaitingList=ref(true); const selectedSlot=ref<TimeSlot>()
const typeItems=computed(()=>catalog.value.appointmentTypes.map(x=>({title:x.name,value:x.code,id:x.id,duration:x.defaultDurationMinutes}))); const resourceItems=computed(()=>resources.value.filter(x=>x.acceptsBookings).map(x=>({title:x.name,value:x.id})))
function iso(time:string):string{return new Date(`${date.value}T${time}:00`).toISOString()}
async function findSlots():Promise<void>{if(!typeCode.value)return;loading.value=true;clearError();try{const type=typeItems.value.find(x=>x.value===typeCode.value);if(!type) return;slots.value=await appointmentsApi.availability({appointmentTypeId:type.id,resourceIds:resourceIds.value,requiredSkills:[],desiredStart:iso(fromTime.value),desiredEnd:iso(toTime.value),durationMinutes:duration.value});selectedSlot.value=undefined}catch(e){setError(e)}finally{loading.value=false}}
function begin(slot:TimeSlot):void{selectedSlot.value=slot;title.value=catalog.value.appointmentTypes.find(x=>x.code===typeCode.value)?.name??'';createOpen.value=true}
function customerCreated(detail:CustomerDetail):void{if(!customers.value.some(x=>x.id===detail.customer.id))customers.value.push(detail.customer);customerId.value=detail.customer.id}
async function create():Promise<void>{if(!selectedSlot.value||!title.value)return;saving.value=true;try{const payload:BookingPayload={appointmentTypeCode:typeCode.value,title:title.value,description:description.value||undefined,customerId:customerId.value,resourceIds:[selectedSlot.value.resourceId],requiredSkills:[],startsAt:selectedSlot.value.start,durationMinutes:duration.value,sourceChannel:'WEB',joinWaitingList:joinWaitingList.value};result.value=await appointmentsApi.create(payload);createOpen.value=false;if(result.value.booked)notifications.success(t('appointments.booked'))}catch(e){setError(e)}finally{saving.value=false}}
onMounted(async()=>{loading.value=true;try{const[catalogData,resourceData,customerPage]=await Promise.all([appointmentsApi.catalog(),appointmentsApi.resources(),customersApi.list({size:100})]);catalog.value=catalogData;resources.value=resourceData;customers.value=customerPage.content;typeCode.value=catalog.value.appointmentTypes[0]?.code??'';duration.value=catalog.value.appointmentTypes[0]?.defaultDurationMinutes}catch(e){setError(e)}finally{loading.value=false}})
</script>
<template><div><AppPageHeader icon="mdi-calendar-clock-outline" :eyebrow="t('appointments.eyebrow')" :title="t('appointments.title')"/><v-alert v-if="errorMessage" type="error" variant="tonal" closable class="mb-4" @click:close="clearError">{{errorMessage}}</v-alert><v-alert type="info" variant="tonal" class="mb-4">{{t('appointments.contractNote')}}</v-alert>
<v-card rounded="xl"><v-card-title class="px-4 px-sm-6 pt-5">{{t('appointments.findAvailability')}}</v-card-title><v-card-text class="px-4 px-sm-6"><v-row><v-col cols="12" md="4"><v-select v-model="typeCode" :items="typeItems" :label="t('appointments.type')"/></v-col><v-col cols="12" md="4"><v-select v-model="resourceIds" :items="resourceItems" multiple chips clearable :label="t('appointments.resources')"/></v-col><v-col cols="12" md="4"><AppPersianDatePicker v-model="date" :label="t('appointments.date')"/></v-col><v-col cols="6" md="3"><v-text-field v-model="fromTime" type="time" :label="t('appointments.from')"/></v-col><v-col cols="6" md="3"><v-text-field v-model="toTime" type="time" :label="t('appointments.to')"/></v-col><v-col cols="12" md="3"><v-text-field v-model.number="duration" type="number" min="1" :label="t('appointments.duration')"/></v-col><v-col cols="12" md="3"><v-btn block color="primary" size="large" :loading="loading" :disabled="!typeCode" @click="findSlots">{{t('appointments.search')}}</v-btn></v-col></v-row></v-card-text><v-progress-linear v-if="loading" indeterminate/><div v-if="slots.length" class="slot-grid pa-4 pa-sm-6 pt-0"><v-card v-for="slot in slots" :key="`${slot.resourceId}-${slot.start}`" variant="tonal" rounded="lg"><v-card-text><div class="font-weight-bold">{{slot.resourceName}}</div><div class="text-body-2 mt-2">{{formatDateTime(slot.start)}} — {{formatDateTime(slot.end)}}</div><v-btn v-if="can('appointments:create')" block color="primary" variant="tonal" class="mt-4" @click="begin(slot)">{{t('appointments.book')}}</v-btn></v-card-text></v-card></div><AppEmptyState v-else-if="!loading" icon="mdi-calendar-search" :title="t('appointments.noSlots')" :description="t('appointments.noSlotsDescription')"/></v-card>
<v-dialog v-model="createOpen" :fullscreen="xs" max-width="620"><v-card :rounded="xs?0:'xl'"><v-card-title class="px-5 pt-5">{{t('appointments.create')}}</v-card-title><v-card-text class="px-5"><v-text-field v-model="title" :label="t('appointments.subject')"/><v-textarea v-model="description" :label="t('appointments.description')" rows="3"/><v-autocomplete v-model="customerId" clearable :items="customers" item-title="displayName" item-value="id" :label="t('appointments.customerId')"><template v-if="can('customers:create')" #append-inner><AppQuickCreateButton :label="t('common.createNew',{entity:t('sales.customer')})" @click="quickCustomerOpen=true"/></template></v-autocomplete><v-switch v-model="joinWaitingList" color="primary" :label="t('appointments.waitingList')"/></v-card-text><v-card-actions class="px-5 pb-5"><v-spacer/><v-btn variant="text" @click="createOpen=false">{{t('common.cancel')}}</v-btn><v-btn color="primary" :loading="saving" :disabled="!title" @click="create">{{t('appointments.confirm')}}</v-btn></v-card-actions></v-card></v-dialog>
<v-dialog :model-value="!!result&&!result.booked" max-width="520" @update:model-value="result=undefined"><v-card rounded="xl"><v-card-title class="px-5 pt-5">{{t('appointments.notBooked')}}</v-card-title><v-card-text class="px-5">{{result?.message||t('appointments.conflict')}}</v-card-text><v-card-actions class="px-5 pb-5"><v-spacer/><v-btn color="primary" @click="result=undefined">{{t('common.close')}}</v-btn></v-card-actions></v-card></v-dialog><QuickCustomerCreateDialog v-if="can('customers:create')" v-model="quickCustomerOpen" @created="customerCreated"/></div></template>
<style scoped>.slot-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(min(100%,260px),1fr));gap:14px}@media(max-width:599px){.slot-grid{grid-template-columns:1fr;padding:12px!important}}</style>
