<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useDisplay } from 'vuetify'
import { useI18n } from 'vue-i18n'
import AppEmptyState from '@/components/AppEmptyState.vue'
import AppPageHeader from '@/components/AppPageHeader.vue'
import { filesApi } from '@/api/files'
import { useApiError } from '@/composables/useApiError'
import { useFormat } from '@/composables/useFormat'
import { useNotifications } from '@/composables/useNotifications'
import { usePermission } from '@/composables/usePermission'
import type { FileCatalog, FileFolder, FileVersion, ManagedFile } from '@/types/files'

const { t } = useI18n(); const { xs } = useDisplay(); const { can } = usePermission(); const { formatDateTime, formatNumber } = useFormat()
const notifications = useNotifications(); const { message: errorMessage, set: setError, clear: clearError } = useApiError()
const loading = ref(false); const saving = ref(false); const files = ref<ManagedFile[]>([]); const folders = ref<FileFolder[]>([])
const catalog = ref<FileCatalog>({ categories: [] }); const q = ref(''); const category = ref<string>(); const folderId = ref<number>()
const page = ref(1); const total = ref(0); const uploadOpen = ref(false); const folderOpen = ref(false); const selected = ref<ManagedFile>(); const versions = ref<FileVersion[]>([]); const deleteTarget = ref<ManagedFile>()
const uploadFile = ref<File>(); const uploadName = ref(''); const uploadDescription = ref(''); const uploadCategory = ref(''); const folderName = ref('')
const categoryItems = computed(() => catalog.value.categories.map(item => ({ title: item.name, value: item.code })))
const folderItems = computed(() => [{ title: t('files.allFolders'), value: undefined }, ...folders.value.map(item => ({ title: item.path, value: item.id }))])

async function load(): Promise<void> { loading.value = true; clearError(); try { const result = await filesApi.search({ q: q.value || undefined, category: category.value, folderId: folderId.value, page: page.value - 1, size: 20, sort: 'createdAt,desc' }); files.value = result.content; total.value = result.totalElements } catch (e) { setError(e) } finally { loading.value = false } }
async function openDetails(file: ManagedFile): Promise<void> { selected.value = file; versions.value = []; try { versions.value = await filesApi.versions(file.fileUuid) } catch (e) { setError(e) } }
function chooseFile(value: File | File[] | null): void { uploadFile.value = Array.isArray(value) ? value[0] : value ?? undefined }
async function upload(): Promise<void> { if (!uploadFile.value || !uploadCategory.value) return; saving.value = true; try { const body = new FormData(); body.append('file', uploadFile.value); body.append('category', uploadCategory.value); if (uploadName.value) body.append('name', uploadName.value); if (uploadDescription.value) body.append('description', uploadDescription.value); if (folderId.value) body.append('folderId', String(folderId.value)); await filesApi.upload(body); uploadOpen.value = false; notifications.success(t('files.uploaded')); await load() } catch (e) { setError(e) } finally { saving.value = false } }
async function createFolder(): Promise<void> { if (!folderName.value) return; saving.value = true; try { await filesApi.createFolder({ name: folderName.value }); folderOpen.value = false; folderName.value = ''; folders.value = await filesApi.folders(); notifications.success(t('files.folderCreated')) } catch (e) { setError(e) } finally { saving.value = false } }
async function remove(): Promise<void> { if (!deleteTarget.value) return; try { await filesApi.remove(deleteTarget.value.fileUuid); deleteTarget.value = undefined; notifications.success(t('files.deleted')); await load() } catch (e) { setError(e) } }
onMounted(async () => { try { [catalog.value, folders.value] = await Promise.all([filesApi.catalog(), filesApi.folders()]); uploadCategory.value = catalog.value.categories[0]?.code ?? '' } catch (e) { setError(e) } await load() })
</script>

<template><div><AppPageHeader icon="mdi-folder-multiple-outline" :eyebrow="t('files.eyebrow')" :title="t('files.title')"><template #actions><v-btn v-if="can('files:create') || can('files:upload')" variant="tonal" prepend-icon="mdi-folder-plus-outline" @click="folderOpen=true">{{ t('files.newFolder') }}</v-btn><v-btn v-if="can('files:upload')" color="primary" prepend-icon="mdi-upload" @click="uploadOpen=true">{{ t('files.upload') }}</v-btn></template></AppPageHeader>
<v-alert v-if="errorMessage" type="error" variant="tonal" closable class="mb-4" @click:close="clearError">{{ errorMessage }}<template #append><v-btn variant="text" @click="load">{{ t('common.retry') }}</v-btn></template></v-alert>
<v-card rounded="xl"><v-card-text class="filters"><v-text-field v-model="q" clearable prepend-inner-icon="mdi-magnify" :label="t('common.search')" hide-details @keyup.enter="page=1;load()"/><v-select v-model="category" :items="categoryItems" clearable :label="t('files.category')" hide-details @update:model-value="page=1;load()"/><v-select v-model="folderId" :items="folderItems" :label="t('files.folder')" hide-details @update:model-value="page=1;load()"/><v-btn icon="mdi-refresh" variant="tonal" :loading="loading" :aria-label="t('common.refresh')" @click="load"/></v-card-text><v-progress-linear v-if="loading" indeterminate/>
<div v-if="files.length" class="file-grid pa-3 pa-sm-4"><v-card v-for="file in files" :key="file.fileUuid" variant="tonal" rounded="lg" @click="openDetails(file)"><v-card-text><div class="d-flex align-start ga-3"><v-avatar color="primary" variant="tonal"><v-icon icon="mdi-file-outline"/></v-avatar><div class="flex-grow-1 min-width-0"><div class="font-weight-bold text-truncate">{{ file.name }}</div><div class="text-caption text-truncate">{{ file.originalFilename }}</div></div><v-menu><template #activator="{props}"><v-btn v-bind="props" icon="mdi-dots-vertical" variant="text" @click.stop/></template><v-list density="compact"><v-list-item v-if="file.downloadable && can('files:download')" prepend-icon="mdi-download" :title="t('files.download')" @click="filesApi.download(file)"/><v-list-item v-if="can('files:delete')" base-color="error" prepend-icon="mdi-delete-outline" :title="t('common.delete')" @click="deleteTarget=file"/></v-list></v-menu></div><div class="d-flex justify-space-between mt-4 text-caption text-medium-emphasis"><span>{{ file.categoryName }}</span><span>{{ formatNumber(file.sizeBytes) }} B</span></div><div class="text-caption text-medium-emphasis mt-1">{{ formatDateTime(file.createdAt) }}</div></v-card-text></v-card></div>
<AppEmptyState v-else-if="!loading" icon="mdi-folder-open-outline" :title="t('files.empty')" :description="t('files.emptyDescription')" :action-label="can('files:upload') ? t('files.upload') : undefined" @action="uploadOpen=true"/><v-pagination v-if="total>20" v-model="page" :length="Math.ceil(total/20)" class="pb-4" @update:model-value="load"/></v-card>
<v-dialog v-model="uploadOpen" :fullscreen="xs" max-width="620"><v-card :rounded="xs?0:'xl'"><v-card-title class="px-5 pt-5">{{ t('files.upload') }}</v-card-title><v-card-text class="px-5"><v-file-input :label="t('files.chooseFile')" prepend-icon="mdi-paperclip" @update:model-value="chooseFile"/><v-select v-model="uploadCategory" :items="categoryItems" :label="t('files.category')"/><v-text-field v-model="uploadName" :label="t('files.displayName')"/><v-textarea v-model="uploadDescription" :label="t('files.description')" rows="3"/></v-card-text><v-card-actions class="px-5 pb-5"><v-spacer/><v-btn variant="text" @click="uploadOpen=false">{{ t('common.cancel') }}</v-btn><v-btn color="primary" :loading="saving" :disabled="!uploadFile||!uploadCategory" @click="upload">{{ t('files.upload') }}</v-btn></v-card-actions></v-card></v-dialog>
<v-dialog v-model="folderOpen" max-width="480"><v-card rounded="xl"><v-card-title class="px-5 pt-5">{{ t('files.newFolder') }}</v-card-title><v-card-text class="px-5"><v-text-field v-model="folderName" autofocus :label="t('files.folderName')"/></v-card-text><v-card-actions class="px-5 pb-5"><v-spacer/><v-btn variant="text" @click="folderOpen=false">{{ t('common.cancel') }}</v-btn><v-btn color="primary" :loading="saving" :disabled="!folderName" @click="createFolder">{{ t('common.save') }}</v-btn></v-card-actions></v-card></v-dialog>
<v-dialog :model-value="!!selected" :fullscreen="xs" max-width="680" @update:model-value="selected=undefined"><v-card :rounded="xs?0:'xl'"><v-card-title class="d-flex px-5 pt-5"><span class="text-truncate">{{ selected?.name }}</span><v-spacer/><v-btn icon="mdi-close" variant="text" @click="selected=undefined"/></v-card-title><v-card-text class="px-5"><v-list lines="two"><v-list-item :title="t('files.status')" :subtitle="selected?.statusName"/><v-list-item :title="t('files.folder')" :subtitle="selected?.folderPath||'—'"/><v-list-item :title="t('files.description')" :subtitle="selected?.description||'—'"/></v-list><h3 class="text-subtitle-1 mt-4 mb-2">{{ t('files.versions') }}</h3><v-list v-if="versions.length"><v-list-item v-for="version in versions" :key="version.id" :title="version.label" :subtitle="formatDateTime(version.createdAt)"><template #append><v-chip v-if="version.current" size="x-small" color="primary">{{ t('files.current') }}</v-chip></template></v-list-item></v-list><AppEmptyState v-else icon="mdi-history" :title="t('files.noVersions')"/></v-card-text></v-card></v-dialog>
<v-dialog :model-value="!!deleteTarget" max-width="440" @update:model-value="deleteTarget=undefined"><v-card rounded="xl"><v-card-title class="px-5 pt-5">{{ t('files.deleteTitle') }}</v-card-title><v-card-text class="px-5">{{ t('files.deleteMessage',{name:deleteTarget?.name}) }}</v-card-text><v-card-actions class="px-5 pb-5"><v-spacer/><v-btn variant="text" @click="deleteTarget=undefined">{{ t('common.cancel') }}</v-btn><v-btn color="error" @click="remove">{{ t('common.delete') }}</v-btn></v-card-actions></v-card></v-dialog></div></template>
<style scoped>.filters{display:grid;grid-template-columns:minmax(180px,2fr) repeat(2,minmax(150px,1fr)) auto;gap:12px;align-items:center}.file-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(min(100%,280px),1fr));gap:14px}.min-width-0{min-width:0}@media(max-width:959px){.filters{grid-template-columns:1fr 1fr}.filters>*:first-child{grid-column:1/-1}}@media(max-width:599px){.filters{grid-template-columns:1fr}.filters>*:first-child{grid-column:auto}.file-grid{grid-template-columns:1fr}}</style>
