<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { useDisplay } from 'vuetify'
import { marketSyncApi, type MarketRow } from '@/api/marketSync'
import { usePermission } from '@/composables/usePermission'
import { useServerLabel } from '@/composables/useServerLabel'
import AppMoneyField from '@/components/AppMoneyField.vue'
const { t }=useI18n(),{smAndUp}=useDisplay(),{can}=usePermission(),{enumLabel}=useServerLabel()
const tab=ref('overview'),busy=ref(false),error=ref(''),overview=ref<MarketRow>({}),sources=ref<MarketRow[]>([]),profiles=ref<MarketRow[]>([]),rules=ref<MarketRow[]>([]),runs=ref<MarketRow[]>([]),history=ref<MarketRow[]>([]),errors=ref<MarketRow[]>([]),sourceDialog=ref(false),profileDialog=ref(false),ruleDialog=ref(false),preview=ref<MarketRow>({})
const source=reactive<MarketRow>({id:null,code:'',name:'',enabled:false,providerKey:'ROND_CONTRACT_PENDING',endpointUrl:'',scheduleCron:'0 0 * * * *',pricingProfileId:null,authEnv:'',authHeader:'Authorization'})
const profile=reactive<MarketRow>({id:null,name:'',percentageAdjustment:0,fixedAdjustment:0,minimumProfit:null,roundingStep:1000,roundingMode:'NEAREST',minPublicationPrice:null,maxPublicationPrice:null,sourcePrice:0,acquisitionCost:null})
const rule=reactive<MarketRow>({sourceId:null,listType:'BLACKLIST',matchType:'PRODUCT_CODE',matchValue:'',enabled:true})
const healthColor=(v:string)=>({HEALTHY:'success',DEGRADED:'warning',FAILING:'error',DISABLED:'default'}[v]||'default')
const runHeaders=computed(()=>[{title:t('marketSync.source'),key:'source_id'},{title:t('marketSync.status'),key:'status'},{title:t('marketSync.fetched'),key:'fetched_count'},{title:t('marketSync.newProducts'),key:'new_count'},{title:t('marketSync.priceChanges'),key:'price_change_count'},{title:t('marketSync.startedAt'),key:'started_at'}])
async function load(){busy.value=true;error.value='';try{const [o,s,p,r]=await Promise.all([marketSyncApi.overview(),marketSyncApi.sources(),marketSyncApi.profiles(),marketSyncApi.rules()] as const);overview.value=o;sources.value=s;profiles.value=p;rules.value=r;if(can('market-sync:view-history'))[runs.value,history.value]=await Promise.all([marketSyncApi.runs(),marketSyncApi.history()]);if(can('market-sync:view-errors'))errors.value=await marketSyncApi.errors()}catch(e){error.value=e instanceof Error?e.message:t('marketSync.error')}finally{busy.value=false}}
function editSource(row?:MarketRow){Object.assign(source,{id:null,code:'',name:'',enabled:false,providerKey:'ROND_CONTRACT_PENDING',endpointUrl:'',scheduleCron:'0 0 * * * *',pricingProfileId:null,authEnv:'',authHeader:'Authorization'},row?{...row,providerKey:row.provider_key,endpointUrl:row.endpoint_url,scheduleCron:row.schedule_cron,pricingProfileId:row.pricing_profile_id,authEnv:row.auth_env??'',authHeader:row.auth_header??'Authorization'}:{});sourceDialog.value=true}
async function saveSource(){busy.value=true;try{await marketSyncApi.saveSource(source.id,{...source,sourceConfig:{authEnv:source.authEnv||undefined,authHeader:source.authHeader||undefined}});sourceDialog.value=false;await load()}catch(e){error.value=e instanceof Error?e.message:t('marketSync.error')}finally{busy.value=false}}
function editProfile(row?:MarketRow){Object.assign(profile,{id:null,name:'',percentageAdjustment:0,fixedAdjustment:0,minimumProfit:null,roundingStep:1000,roundingMode:'NEAREST',minPublicationPrice:null,maxPublicationPrice:null,sourcePrice:0,acquisitionCost:null},row?{...row,percentageAdjustment:row.percentage_adjustment,fixedAdjustment:row.fixed_adjustment,minimumProfit:row.minimum_profit,roundingStep:row.rounding_step,roundingMode:row.rounding_mode,minPublicationPrice:row.min_publication_price,maxPublicationPrice:row.max_publication_price}:{});profileDialog.value=true}
async function calculate(){preview.value=await marketSyncApi.preview(profile)} async function saveProfile(){await marketSyncApi.saveProfile(profile.id,profile);profileDialog.value=false;await load()}
async function saveRule(){await marketSyncApi.saveRule(rule);ruleDialog.value=false;await load()} async function sync(id:number){busy.value=true;try{await marketSyncApi.sync(id);await load()}catch(e){error.value=e instanceof Error?e.message:t('marketSync.error')}finally{busy.value=false}}
onMounted(load)
</script>
<template><div class="market-page pa-4 pa-md-6"><div class="d-flex flex-wrap align-center justify-space-between ga-3 mb-5"><div><h1 class="text-h4 font-weight-bold">{{t('marketSync.title')}}</h1><p class="text-medium-emphasis">{{t('marketSync.subtitle')}}</p></div><v-chip color="primary" variant="tonal" prepend-icon="mdi-shield-sync-outline">{{t('marketSync.failSafe')}}</v-chip></div><v-alert v-if="error" type="error" closable class="mb-4" @click:close="error=''">{{error}}</v-alert>
<v-tabs v-model="tab" show-arrows class="mb-4"><v-tab v-for="x in ['overview','sources','pricing','rules','runs','history','errors','health']" :key="x" :value="x">{{t(`marketSync.tabs.${x}`)}}</v-tab></v-tabs>
<v-window v-model="tab"><v-window-item value="overview"><v-row><v-col v-for="m in [{k:'sources',v:overview.sources},{k:'activeProducts',v:overview.active_products},{k:'priceChanges',v:overview.recent_price_changes},{k:'errors',v:overview.recent_errors}]" :key="m.k" cols="6" md="3"><v-card rounded="xl" class="pa-4"><div class="text-caption">{{t(`marketSync.${m.k}`)}}</div><div class="text-h4 mt-2">{{m.v??0}}</div></v-card></v-col></v-row><v-card rounded="xl" class="mt-4"><v-card-title>{{t('marketSync.sourceHealth')}}</v-card-title><v-list><v-list-item v-for="s in sources" :key="s.id" :title="s.name" :subtitle="s.last_successful_sync||t('marketSync.neverSynced')"><template #append><v-chip :color="healthColor(s.health_state)">{{t(`marketSync.health.${s.health_state}`)}}</v-chip></template></v-list-item></v-list></v-card></v-window-item>
<v-window-item value="sources"><div class="d-flex mb-3"><v-spacer/><v-btn v-if="can('market-sync:manage-sources')" color="primary" prepend-icon="mdi-plus" @click="editSource()">{{t('marketSync.addSource')}}</v-btn></div><v-card v-for="s in sources" :key="s.id" rounded="xl" class="mb-3"><v-card-text class="d-flex flex-wrap align-center ga-3"><div class="flex-grow-1"><strong>{{s.name}}</strong><div class="text-caption">{{s.code}} · {{enumLabel(s.provider_key)}} · {{s.schedule_cron}}</div></div><v-chip :color="healthColor(s.health_state)">{{t(`marketSync.health.${s.health_state}`)}}</v-chip><v-btn v-if="can('market-sync:execute')" :disabled="!s.enabled" :loading="busy" @click="sync(s.id)">{{t('marketSync.syncNow')}}</v-btn><v-btn v-if="can('market-sync:manage-sources')" icon="mdi-pencil" variant="text" @click="editSource(s)"/></v-card-text></v-card></v-window-item>
<v-window-item value="pricing"><div class="d-flex mb-3"><v-spacer/><v-btn v-if="can('market-sync:manage-pricing')" color="primary" @click="editProfile()">{{t('marketSync.addProfile')}}</v-btn></div><v-row><v-col v-for="p in profiles" :key="p.id" cols="12" md="6"><v-card rounded="xl"><v-card-title>{{p.name}}</v-card-title><v-card-text>{{p.percentage_adjustment}}% · {{p.fixed_adjustment}} · {{t('marketSync.rounding')}} {{p.rounding_step}}</v-card-text><v-card-actions><v-btn v-if="can('market-sync:manage-pricing')" @click="editProfile(p)">{{t('common.edit')}}</v-btn></v-card-actions></v-card></v-col></v-row></v-window-item>
<v-window-item value="rules"><v-btn v-if="can('market-sync:manage-publication')" color="primary" class="mb-3" @click="ruleDialog=true">{{t('marketSync.addRule')}}</v-btn><v-card rounded="xl"><v-list><v-list-item v-for="r in rules" :key="r.id" :title="`${enumLabel(r.list_type)}: ${r.match_value}`" :subtitle="enumLabel(r.match_type)"><template #append><v-btn v-if="can('market-sync:manage-publication')" icon="mdi-delete" color="error" variant="text" @click="marketSyncApi.deleteRule(r.id).then(load)"/></template></v-list-item></v-list><v-alert type="info" variant="tonal" class="ma-4">{{t('marketSync.rulePrecedence')}}</v-alert></v-card></v-window-item>
<v-window-item value="runs"><v-data-table :headers="runHeaders" :items="runs" :mobile="!smAndUp"><template #[`item.status`]="{item}"><v-chip size="small" variant="tonal">{{enumLabel(item.status)}}</v-chip></template></v-data-table></v-window-item><v-window-item value="history"><v-card rounded="xl"><v-list><v-list-item v-for="h in history" :key="h.id" :title="h.normalized_product_code" :subtitle="`${h.old_final_price??'—'} → ${h.new_final_price}`"/></v-list></v-card></v-window-item><v-window-item value="errors"><v-card rounded="xl"><v-list><v-list-item v-for="e in errors" :key="e.id" :title="e.code" :subtitle="e.message"><template #prepend><v-icon :color="e.severity==='ERROR'?'error':'warning'">mdi-alert-circle-outline</v-icon></template></v-list-item></v-list></v-card></v-window-item><v-window-item value="health"><v-card rounded="xl"><v-card-title>{{t('marketSync.healthContract')}}</v-card-title><v-card-text>{{t('marketSync.healthHint')}}</v-card-text></v-card></v-window-item></v-window>
<v-dialog v-model="sourceDialog" :fullscreen="!smAndUp" max-width="700"><v-card><v-card-title>{{t('marketSync.source')}}</v-card-title><v-card-text><v-row><v-col cols="12" sm="6"><v-text-field v-model="source.code" :label="t('marketSync.code')"/></v-col><v-col cols="12" sm="6"><v-text-field v-model="source.name" :label="t('common.name')"/></v-col><v-col cols="12"><v-select v-model="source.providerKey" :items="['ROND_CONTRACT_PENDING','STRUCTURED_JSON_V1']" :item-title="enumLabel" :label="t('marketSync.provider')"/></v-col><v-col cols="12"><v-text-field v-model="source.endpointUrl" :label="t('marketSync.endpoint')"/></v-col><v-col cols="12" sm="6"><v-text-field v-model="source.authEnv" :label="t('marketSync.authEnv')" :hint="t('marketSync.authEnvHint')" persistent-hint/></v-col><v-col cols="12" sm="6"><v-text-field v-model="source.authHeader" :label="t('marketSync.authHeader')"/></v-col><v-col cols="12" sm="6"><v-select v-model="source.pricingProfileId" :items="profiles" item-title="name" item-value="id" :label="t('marketSync.profile')"/></v-col><v-col cols="12" sm="6"><v-text-field v-model="source.scheduleCron" :label="t('marketSync.schedule')"/></v-col><v-col cols="12"><v-switch v-model="source.enabled" :label="t('marketSync.enabled')"/></v-col></v-row><v-alert type="warning" variant="tonal">{{t('marketSync.sourceContractWarning')}}</v-alert></v-card-text><v-card-actions><v-spacer/><v-btn @click="sourceDialog=false">{{t('common.cancel')}}</v-btn><v-btn color="primary" :loading="busy" @click="saveSource">{{t('common.save')}}</v-btn></v-card-actions></v-card></v-dialog>
<v-dialog v-model="profileDialog" :fullscreen="!smAndUp" max-width="850"><v-card><v-card-title>{{t('marketSync.profile')}}</v-card-title><v-card-text><v-row><v-col cols="12"><v-text-field v-model="profile.name" :label="t('common.name')"/></v-col><v-col cols="12" sm="6"><v-text-field v-model.number="profile.percentageAdjustment" type="number" :label="t('marketSync.percentageAdjustment')"/></v-col><v-col v-for="f in ['fixedAdjustment','minimumProfit','roundingStep','minPublicationPrice','maxPublicationPrice']" :key="f" cols="12" sm="6"><AppMoneyField v-model="profile[f]" :label="t(`marketSync.${f}`)"/></v-col><v-col cols="12" sm="6"><v-select v-model="profile.roundingMode" :items="['NEAREST','UP','DOWN']" :item-title="enumLabel" :label="t('marketSync.roundingMode')"/></v-col><v-col cols="12" sm="6"><AppMoneyField v-model="profile.sourcePrice" :label="t('marketSync.previewSourcePrice')"/></v-col><v-col cols="12" sm="6"><AppMoneyField v-model="profile.acquisitionCost" :label="t('marketSync.acquisitionCost')"/></v-col></v-row><v-btn variant="tonal" @click="calculate">{{t('marketSync.calculate')}}</v-btn><v-alert v-if="preview.status" class="mt-3" :type="preview.status==='CALCULATED'?'success':'warning'">{{t('marketSync.finalPrice')}}: {{preview.finalPrice}} · {{enumLabel(preview.status)}}<div>{{preview.publicationReasons?.map(enumLabel).join(', ')}}</div></v-alert></v-card-text><v-card-actions><v-spacer/><v-btn @click="profileDialog=false">{{t('common.cancel')}}</v-btn><v-btn color="primary" @click="saveProfile">{{t('common.save')}}</v-btn></v-card-actions></v-card></v-dialog>
<v-dialog v-model="ruleDialog" max-width="600"><v-card><v-card-title>{{t('marketSync.publicationRule')}}</v-card-title><v-card-text><v-select v-model="rule.listType" :items="['BLACKLIST','WHITELIST']" :item-title="enumLabel" :label="t('marketSync.listType')"/><v-select v-model="rule.matchType" :items="['PRODUCT_CODE','PREFIX']" :item-title="enumLabel" :label="t('marketSync.matchType')"/><v-text-field v-model="rule.matchValue" :label="t('marketSync.matchValue')"/></v-card-text><v-card-actions><v-spacer/><v-btn @click="ruleDialog=false">{{t('common.cancel')}}</v-btn><v-btn color="primary" @click="saveRule">{{t('common.save')}}</v-btn></v-card-actions></v-card></v-dialog></div></template>
<style scoped>.market-page{max-width:1600px;min-width:0;margin:auto;overflow-x:hidden}.market-page :deep(.v-table__wrapper){overflow-x:auto}</style>
