<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { purchasePaymentsApi, type PurchasePaymentRequest } from '@/api/purchasePayments'
import { treasuryApi, type TreasuryAccount } from '@/api/treasury'
import { useAuthStore } from '@/stores/auth'
import AppPersianDatePicker from '@/components/AppPersianDatePicker.vue'
const {t}=useI18n();const auth=useAuthStore();const loading=ref(false),error=ref(''),createOpen=ref(false),paymentOpen=ref(false),limitOpen=ref(false),selected=ref<PurchasePaymentRequest>(),rows=ref<PurchasePaymentRequest[]>([]),accounts=ref<TreasuryAccount[]>([])
const canAll=computed(()=>auth.can('purchase-payments:view-all')),canApprove=computed(()=>auth.can('purchase-payments:approve')),canPay=computed(()=>auth.can('purchase-payments:process'))
const form=reactive({amount:0,purpose:'',supplierName:'',documentReference:''}),payment=reactive({treasuryAccountId:0,method:'ACCOUNT_TRANSFER',amount:0,referenceNumber:'',note:'',completeWithPartialAmount:false})
const limit=reactive({treasuryAccountId:0,paymentDate:new Date().toISOString().slice(0,10),method:'ACCOUNT_TRANSFER',limitAmount:0})
async function load(){loading.value=true;error.value='';try{rows.value=await(canAll.value?purchasePaymentsApi.all():purchasePaymentsApi.mine());if(canPay.value)accounts.value=await treasuryApi.accounts()}catch(e){error.value=e instanceof Error?e.message:t('common.error')}finally{loading.value=false}}
async function create(){await purchasePaymentsApi.create(form);createOpen.value=false;Object.assign(form,{amount:0,purpose:'',supplierName:'',documentReference:''});await load()}
async function decide(row:PurchasePaymentRequest,approved:boolean){const rejectionReason=approved?undefined:window.prompt(t('purchasePayments.rejectionReason'))||undefined;if(!approved&&!rejectionReason)return;await purchasePaymentsApi.decide(row.id,{approved,rejectionReason});await load()}
function openPayment(row:PurchasePaymentRequest){selected.value=row;payment.amount=Number(row.requested_amount)-Number(row.paid_amount);paymentOpen.value=true}
async function recordPayment(){if(!selected.value)return;await purchasePaymentsApi.pay(selected.value.id,{...payment,paidAt:new Date().toISOString()});paymentOpen.value=false;await load()}
async function saveLimit(){await purchasePaymentsApi.setLimit(limit);limitOpen.value=false}
onMounted(load)
</script>
<template><div class="pa-3 pa-md-6"><div class="d-flex flex-wrap align-center ga-3 mb-5"><div><h1 class="text-h4">{{t('purchasePayments.title')}}</h1><p class="text-medium-emphasis">{{t('purchasePayments.subtitle')}}</p></div><v-spacer/><v-btn v-if="auth.can('purchase-payments:manage-limits')" variant="tonal" prepend-icon="mdi-speedometer" @click="limitOpen=true">{{t('purchasePayments.limit')}}</v-btn><v-btn v-if="auth.can('purchase-payments:create')" color="primary" prepend-icon="mdi-plus" @click="createOpen=true">{{t('purchasePayments.new')}}</v-btn></div>
<v-alert v-if="error" type="error" class="mb-4">{{error}}</v-alert><v-skeleton-loader v-if="loading" type="table"/><v-card v-else><v-card-text class="pa-0"><v-data-table :items="rows" :headers="[{title:t('purchasePayments.number'),key:'request_number'},{title:t('purchasePayments.supplier'),key:'supplier_name'},{title:t('purchasePayments.amount'),key:'requested_amount'},{title:t('purchasePayments.paid'),key:'paid_amount'},{title:t('common.status'),key:'status'},{title:'',key:'actions',sortable:false}]"><template #item.requested_amount="{item}">{{Number(item.requested_amount).toLocaleString()}} {{t('common.rial')}}</template><template #item.paid_amount="{item}">{{Number(item.paid_amount).toLocaleString()}}</template><template #item.status="{item}"><v-chip size="small">{{t(`purchasePayments.status.${item.status}`)}}</v-chip></template><template #item.actions="{item}"><div class="d-flex ga-1"><v-btn v-if="canApprove&&item.status==='WAITING_MANAGER'" size="small" color="success" icon="mdi-check" :aria-label="t('common.approve')" @click="decide(item,true)"/><v-btn v-if="canApprove&&item.status==='WAITING_MANAGER'" size="small" color="error" icon="mdi-close" :aria-label="t('common.reject')" @click="decide(item,false)"/><v-btn v-if="canPay&&['APPROVED','WAITING_PAYMENT','PARTIALLY_PAID','OVERDUE'].includes(item.status)" size="small" color="primary" icon="mdi-cash-check" :aria-label="t('purchasePayments.pay')" @click="openPayment(item)"/></div></template></v-data-table></v-card-text></v-card>
<v-dialog v-model="createOpen" max-width="620"><v-card><v-card-title>{{t('purchasePayments.new')}}</v-card-title><v-card-text><v-form class="d-grid ga-3" @submit.prevent="create"><v-text-field v-model.number="form.amount" type="number" inputmode="numeric" :label="t('purchasePayments.amount')"/><v-text-field v-model="form.supplierName" :label="t('purchasePayments.supplier')"/><v-textarea v-model="form.purpose" :label="t('purchasePayments.purpose')"/><v-text-field v-model="form.documentReference" :label="t('purchasePayments.document')"/></v-form></v-card-text><v-card-actions><v-spacer/><v-btn @click="createOpen=false">{{t('common.cancel')}}</v-btn><v-btn color="primary" @click="create">{{t('common.save')}}</v-btn></v-card-actions></v-card></v-dialog>
<v-dialog v-model="paymentOpen" max-width="620"><v-card><v-card-title>{{t('purchasePayments.pay')}}</v-card-title><v-card-text class="d-grid ga-3"><v-select v-model="payment.treasuryAccountId" :items="accounts" item-title="name" item-value="id" :label="t('purchasePayments.account')"/><v-select v-model="payment.method" :items="['ACCOUNT_TRANSFER','CARD_TRANSFER','IBAN','FROM_BRANCH']" :label="t('purchasePayments.method')"/><v-text-field v-model.number="payment.amount" type="number" inputmode="numeric" :label="t('purchasePayments.amount')"/><v-text-field v-model="payment.referenceNumber" :label="t('purchasePayments.reference')"/><v-checkbox v-model="payment.completeWithPartialAmount" :label="t('purchasePayments.completePartial')"/></v-card-text><v-card-actions><v-spacer/><v-btn @click="paymentOpen=false">{{t('common.cancel')}}</v-btn><v-btn color="primary" @click="recordPayment">{{t('purchasePayments.record')}}</v-btn></v-card-actions></v-card></v-dialog>
<v-dialog v-model="limitOpen" max-width="620"><v-card><v-card-title>{{t('purchasePayments.limit')}}</v-card-title><v-card-text class="d-grid ga-3"><v-select v-model="limit.treasuryAccountId" :items="accounts" item-title="name" item-value="id" :label="t('purchasePayments.account')"/><AppPersianDatePicker v-model="limit.paymentDate" :label="t('purchasePayments.date')"/><v-select v-model="limit.method" :items="['ACCOUNT_TRANSFER','CARD_TRANSFER','IBAN','FROM_BRANCH']" :label="t('purchasePayments.method')"/><v-text-field v-model.number="limit.limitAmount" type="number" inputmode="numeric" :label="t('purchasePayments.limitAmount')"/></v-card-text><v-card-actions><v-spacer/><v-btn @click="limitOpen=false">{{t('common.cancel')}}</v-btn><v-btn color="primary" @click="saveLimit">{{t('common.save')}}</v-btn></v-card-actions></v-card></v-dialog></div></template>
