<script setup lang="ts">
import{computed,onMounted,reactive,ref}from'vue';import{useDisplay}from'vuetify';import{useI18n}from'vue-i18n';import AppPageHeader from '@/components/AppPageHeader.vue';import SaleActionPanel from '@/components/SaleActionPanel.vue';import{salesApi}from '@/api/sales';import{customersApi}from '@/api/customers';import{productsApi}from '@/api/products';import{useApiError}from '@/composables/useApiError';import{usePermission}from '@/composables/usePermission';import type{Customer,Product}from '@/types/models';import type{Sale,SalePayload,SalesDashboard}from '@/types/sales';
const{t}=useI18n(),{mdAndUp}=useDisplay(),{can}=usePermission(),error=useApiError();const loading=ref(false),saving=ref(false),sales=ref<Sale[]>([]),total=ref(0),page=ref(1),dashboard=ref<SalesDashboard|null>(null),customers=ref<Customer[]>([]),products=ref<Product[]>([]),editor=ref(false),detail=ref(false),selected=ref<Sale|null>(null),notice=ref('');
type DraftLine={productId:number|null;quantity:number;unitPrice:number;costPrice:number;discount:number;tax:number;serialNumber:string;imei:string};
type DraftService={serviceType:string;description:string;price:number;cost:number;employeeId:number|null};
const editingId=ref<number|null>(null),form=reactive({companyId:1,branchId:1,customerId:null as number|null,saleType:'CASH',currency:'IRR',notes:'',items:[] as DraftLine[],services:[] as DraftService[],expectedVersion:undefined as number|undefined});
const headers=computed(()=>[{title:t('sales.invoice'),key:'invoiceNumber'},{title:t('sales.type'),key:'saleType'},{title:t('sales.status'),key:'status'},{title:t('sales.total'),key:'finalAmount',align:'end' as const},{title:t('sales.createdAt'),key:'createdAt'},{title:'',key:'actions',sortable:false}]);
const money=(v:number)=>new Intl.NumberFormat(undefined,{maximumFractionDigits:2}).format(v??0);const statusColor=(s:string)=>({DRAFT:'grey',CONFIRMED:'info',COMPLETED:'success',CANCELLED:'error',PARTIALLY_RETURNED:'warning',RETURNED:'secondary'}[s]||'grey');const label=(code:string)=>t(`sales.values.${code}`,code);const window=globalThis.window;
function newLine(){form.items.push({productId:null,quantity:1,unitPrice:0,costPrice:0,discount:0,tax:0,serialNumber:'',imei:''})}function chooseProduct(line:DraftLine){const p=products.value.find(x=>x.id===line.productId);if(p)line.unitPrice=Number(p.price)}
async function load(){loading.value=true;error.clear();try{const[r,d]=await Promise.all([salesApi.list({page:page.value-1,size:20,sort:'createdAt,desc'}),salesApi.dashboard()]);sales.value=r.content;total.value=r.totalElements;dashboard.value=d}catch(e){error.set(e)}finally{loading.value=false}}
async function loadLookups(){const[c,p]=await Promise.all([customersApi.list({size:100}),productsApi.list({size:100})]);customers.value=c.content;products.value=p.content}
function newService(){form.services.push({serviceType:'INSTALLATION',description:'',price:0,cost:0,employeeId:null})}
function openCreate(){editingId.value=null;Object.assign(form,{companyId:1,branchId:1,customerId:null,saleType:'CASH',currency:'IRR',notes:'',items:[],services:[],expectedVersion:undefined});newLine();editor.value=true;loadLookups().catch(error.set)}
async function openEdit(){if(!selected.value||selected.value.status!=='DRAFT')return;const s=selected.value;editingId.value=s.id;Object.assign(form,{companyId:s.companyId,branchId:s.branchId,customerId:s.customerId,saleType:s.saleType,currency:s.currency,notes:s.notes||'',expectedVersion:s.version,items:s.items.map(x=>({productId:x.productId,quantity:x.quantity,unitPrice:x.unitPrice,costPrice:x.costPrice,discount:x.discount,tax:x.tax,serialNumber:x.serialNumber||'',imei:x.imei||''})),services:s.services.map(x=>({serviceType:x.serviceType,description:x.description||'',price:x.price,cost:x.cost,employeeId:x.employeeId||null}))});detail.value=false;editor.value=true;await loadLookups()}
async function save(){if(!form.customerId||!form.items.length||form.items.some(x=>!x.productId||x.quantity<=0))return; saving.value=true;try{const payload:SalePayload={companyId:form.companyId,branchId:form.branchId,customerId:form.customerId,saleType:form.saleType,currency:form.currency,notes:form.notes,items:form.items.map(x=>({productId:x.productId!,quantity:x.quantity,unitPrice:x.unitPrice,costPrice:x.costPrice,discount:x.discount,tax:x.tax,serialNumber:x.serialNumber||undefined,imei:x.imei||undefined})),services:form.services.map(x=>({serviceType:x.serviceType,description:x.description||undefined,price:x.price,cost:x.cost,employeeId:x.employeeId||undefined})),expectedVersion:form.expectedVersion,idempotencyKey:editingId.value?undefined:crypto.randomUUID()};await(editingId.value?salesApi.update(editingId.value,payload):salesApi.create(payload));editor.value=false;notice.value=t('sales.saved');await load()}catch(e){error.set(e)}finally{saving.value=false}}
async function show(s:Sale){loading.value=true;try{selected.value=await salesApi.get(s.id);detail.value=true}catch(e){error.set(e)}finally{loading.value=false}}
async function act(action:'confirm'|'complete'|'cancel'){if(!selected.value)return;saving.value=true;try{selected.value=action==='cancel'?await salesApi.cancel(selected.value.id,t('sales.cancelReasonDefault')):await salesApi[action](selected.value.id);notice.value=t('sales.actionDone');await load()}catch(e){error.set(e)}finally{saving.value=false}}
const canAction=(a:string)=>selected.value&&can(`sales:${a}`);onMounted(load);
</script>

<template><div class="sales-page">
 <AppPageHeader icon="mdi-point-of-sale" :title="t('sales.title')" :subtitle="t('sales.subtitle')"><template #actions><v-btn v-if="can('sales:export')" variant="tonal" prepend-icon="mdi-download" @click="salesApi.exportCsv().catch(error.set)">{{t('sales.export')}}</v-btn><v-btn v-if="can('sales:create')" color="primary" prepend-icon="mdi-plus" @click="openCreate">{{t('sales.new')}}</v-btn></template></AppPageHeader>
 <v-alert v-if="error.message.value" type="error" closable class="mb-4" @click:close="error.clear()">{{error.message.value}}</v-alert>
 <v-row v-if="dashboard" class="mb-3"><v-col v-for="k in ['revenue','profit','drafts','completed']" :key="k" cols="6" md="3"><v-card class="metric pa-4"><div class="text-caption text-medium-emphasis">{{t(`sales.${k}`)}}</div><div class="text-h5 font-weight-bold mt-2">{{['revenue','profit'].includes(k)?money(dashboard[k as 'revenue']):dashboard[k as 'drafts']}}</div></v-card></v-col></v-row>
 <v-card class="app-data-surface" rounded="xl"><v-card-title class="d-flex align-center ga-2"><v-icon icon="mdi-receipt-text-outline"/><span>{{t('sales.list')}}</span><v-spacer/><v-btn icon="mdi-refresh" variant="text" :loading="loading" @click="load"/></v-card-title>
  <v-data-table-server v-if="mdAndUp" :headers="headers" :items="sales" :items-length="total" :loading="loading" v-model:page="page" @update:options="load"><template #item.status="{item}"><v-chip :color="statusColor(item.status)" size="small">{{label(item.status)}}</v-chip></template><template #item.saleType="{item}">{{label(item.saleType)}}</template><template #item.finalAmount="{item}">{{money(item.finalAmount)}} {{item.currency}}</template><template #item.createdAt="{item}">{{new Date(item.createdAt).toLocaleDateString()}}</template><template #item.actions="{item}"><v-btn icon="mdi-eye-outline" variant="text" :aria-label="t('sales.details')" @click="show(item)"/></template></v-data-table-server>
  <div v-else class="pa-3"><v-skeleton-loader v-if="loading" type="article@3"/><v-card v-for="s in sales" :key="s.id" variant="outlined" rounded="lg" class="sale-card mb-3" @click="show(s)"><v-card-text><div class="d-flex align-center"><strong>{{s.invoiceNumber}}</strong><v-spacer/><v-chip :color="statusColor(s.status)" size="small">{{label(s.status)}}</v-chip></div><div class="d-flex mt-4"><span class="text-medium-emphasis">{{label(s.saleType)}}</span><v-spacer/><strong>{{money(s.finalAmount)}} {{s.currency}}</strong></div></v-card-text></v-card><div v-if="!loading&&!sales.length" class="text-center pa-10 text-medium-emphasis">{{t('sales.empty')}}</div></div>
 </v-card>

 <v-dialog v-model="editor" :fullscreen="!mdAndUp" max-width="980" persistent><v-card rounded="xl"><v-toolbar color="transparent"><v-toolbar-title>{{editingId?t('sales.editDraft'):t('sales.new')}}</v-toolbar-title><v-btn icon="mdi-close" @click="editor=false"/></v-toolbar><v-card-text><v-row><v-col cols="12" md="4"><v-text-field v-model.number="form.companyId" type="number" :label="t('sales.company')"/></v-col><v-col cols="12" md="4"><v-text-field v-model.number="form.branchId" type="number" :label="t('sales.branch')"/></v-col><v-col cols="12" md="4"><v-autocomplete v-model="form.customerId" :items="customers" item-title="displayName" item-value="id" :label="t('sales.customer')"/></v-col><v-col cols="12" md="6"><v-select v-model="form.saleType" :items="['CASH','INSTALLMENT','ONLINE','PHONE','RESERVATION','PREORDER','SERVICE','WHOLESALE','PARTNER','CORPORATE']" :item-title="label" :label="t('sales.type')"/></v-col><v-col cols="12" md="6"><v-textarea v-model="form.notes" rows="1" :label="t('sales.notes')"/></v-col></v-row>
  <div class="d-flex align-center my-3"><h3>{{t('sales.items')}}</h3><v-spacer/><v-btn variant="tonal" prepend-icon="mdi-plus" @click="newLine">{{t('sales.addItem')}}</v-btn></div>
  <v-card v-for="(line,i) in form.items" :key="i" variant="outlined" class="pa-3 mb-3"><v-row dense><v-col cols="12" md="4"><v-autocomplete v-model="line.productId" :items="products" item-title="name" item-value="id" :label="t('sales.product')" @update:model-value="chooseProduct(line)"/></v-col><v-col cols="6" md="2"><v-text-field v-model.number="line.quantity" type="number" min="1" :label="t('sales.quantity')"/></v-col><v-col cols="6" md="2"><v-text-field v-model.number="line.unitPrice" type="number" :label="t('sales.unitPrice')"/></v-col><v-col cols="6" md="2"><v-text-field v-model="line.imei" :label="t('sales.imei')"/></v-col><v-col cols="6" md="2" class="d-flex"><v-btn color="error" variant="text" icon="mdi-delete-outline" :disabled="form.items.length===1" @click="form.items.splice(i,1)"/></v-col></v-row></v-card>
  <div class="d-flex align-center my-3"><h3>{{t('sales.services')}}</h3><v-spacer/><v-btn variant="tonal" prepend-icon="mdi-plus" @click="newService">{{t('sales.addService')}}</v-btn></div>
  <v-card v-for="(service,i) in form.services" :key="`service-${i}`" variant="outlined" class="pa-3 mb-3"><v-row dense><v-col cols="12" md="3"><v-text-field v-model="service.serviceType" :label="t('sales.serviceType')"/></v-col><v-col cols="12" md="4"><v-text-field v-model="service.description" :label="t('sales.description')"/></v-col><v-col cols="5" md="2"><v-text-field v-model.number="service.price" type="number" min="0" :label="t('sales.price')"/></v-col><v-col cols="5" md="2"><v-text-field v-model.number="service.cost" type="number" min="0" :label="t('sales.cost')"/></v-col><v-col cols="2" md="1"><v-btn color="error" variant="text" icon="mdi-delete-outline" @click="form.services.splice(i,1)"/></v-col></v-row></v-card>
 </v-card-text><v-card-actions class="pa-4"><v-spacer/><v-btn variant="text" @click="editor=false">{{t('common.cancel')}}</v-btn><v-btn color="primary" :loading="saving" :disabled="!form.customerId" @click="save">{{t('common.save')}}</v-btn></v-card-actions></v-card></v-dialog>

 <v-dialog v-model="detail" :fullscreen="!mdAndUp" max-width="920"><v-card v-if="selected" rounded="xl"><v-toolbar color="transparent"><v-toolbar-title>{{selected.invoiceNumber}}</v-toolbar-title><v-chip :color="statusColor(selected.status)">{{label(selected.status)}}</v-chip><v-btn icon="mdi-close" @click="detail=false"/></v-toolbar><v-card-text><v-row><v-col cols="6" md="3"><div class="text-caption">{{t('sales.total')}}</div><strong>{{money(selected.finalAmount)}}</strong></v-col><v-col cols="6" md="3"><div class="text-caption">{{t('sales.profit')}}</div><strong>{{money(selected.profit)}}</strong></v-col><v-col cols="6" md="3"><div class="text-caption">{{t('sales.discount')}}</div><strong>{{money(selected.discountTotal)}}</strong></v-col><v-col cols="6" md="3"><div class="text-caption">{{t('sales.tax')}}</div><strong>{{money(selected.taxTotal)}}</strong></v-col></v-row><v-divider class="my-4"/><v-list lines="two"><v-list-item v-for="item in selected.items" :key="item.id" :title="item.name" :subtitle="`${item.quantity} × ${money(item.unitPrice)}${item.imei?' · IMEI '+item.imei:''}`"><template #append><strong>{{money(item.lineTotal)}}</strong></template></v-list-item></v-list></v-card-text><v-card-actions class="pa-4 flex-wrap"><v-btn v-if="selected.status==='DRAFT'&&canAction('confirm')" color="info" @click="act('confirm')">{{t('sales.confirm')}}</v-btn><v-btn v-if="selected.status==='CONFIRMED'&&canAction('complete')" color="success" @click="act('complete')">{{t('sales.complete')}}</v-btn><v-btn v-if="['DRAFT','CONFIRMED'].includes(selected.status)&&canAction('cancel')" color="error" variant="tonal" @click="act('cancel')">{{t('sales.cancelSale')}}</v-btn><v-spacer/><v-btn prepend-icon="mdi-printer-outline" @click="window.print()">{{t('sales.print')}}</v-btn></v-card-actions></v-card></v-dialog>
 <v-btn v-if="detail&&selected?.status==='DRAFT'&&can('sales:edit')" class="edit-draft-action" color="secondary" prepend-icon="mdi-pencil-outline" @click="openEdit">{{t('sales.editDraft')}}</v-btn>
 <SaleActionPanel v-if="detail&&selected" :sale="selected" @updated="value=>{selected=value;notice=t('sales.actionDone');load()}" @failed="error.set"/>
 <v-snackbar :model-value="!!notice" color="success" @update:model-value="notice=''">{{notice}}</v-snackbar>
</div></template>
<style scoped>.metric{height:100%;border:1px solid rgba(var(--v-border-color),.12)}.sale-card{cursor:pointer;transition:transform .15s}.sale-card:active{transform:scale(.99)}.edit-draft-action{position:fixed;z-index:2501;inset-inline-start:16px;bottom:72px}@media(max-width:599px){.sales-page{padding-bottom:72px}:deep(.v-btn){min-height:44px}}</style>
