<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import AppPageHeader from '@/components/AppPageHeader.vue'
import AppEmptyState from '@/components/AppEmptyState.vue'
import AppErrorState from '@/components/AppErrorState.vue'
import { useApiError } from '@/composables/useApiError'
import { useFormat } from '@/composables/useFormat'
import { useNotifications } from '@/composables/useNotifications'
import { usePermission } from '@/composables/usePermission'
import { treasuryApi, type TreasuryAccount, type TreasuryAccountType, type TreasuryCheque, type TreasuryDashboard, type TreasuryTransaction, type TreasuryTransactionType } from '@/api/treasury'

const { t } = useI18n(); const { can } = usePermission(); const { formatNumber } = useFormat(); const notifications = useNotifications(); const error=useApiError()
const tab=ref('accounts'), loading=ref(false), dashboard=ref<TreasuryDashboard|null>(null), accounts=ref<TreasuryAccount[]>([]), transactionRows=ref<TreasuryTransaction[]>([]), chequeRows=ref<TreasuryCheque[]>([]), accountTypes=ref<TreasuryAccountType[]>([]), transactionTypes=ref<TreasuryTransactionType[]>([])
const accountDialog=ref(false), transactionDialog=ref(false), chequeDialog=ref(false), saving=ref(false)
const account=ref({accountTypeId:0,code:'',name:'',currencyCode:'IRR',openingBalance:0,allowNegativeBalance:false,active:true,bankName:''})
const transaction=ref({transactionTypeId:0,sourceAccountId:undefined as number|undefined,destinationAccountId:undefined as number|undefined,amount:0,currencyCode:'IRR',occurredAt:new Date().toISOString(),description:''})
const cheque=ref({direction:'RECEIVED' as 'RECEIVED'|'ISSUED',chequeNumber:'',bankName:'',amount:0,currencyCode:'IRR',statusId:0})
const tabs=computed(()=>[{value:'accounts',label:t('treasury.accounts'),icon:'mdi-bank-outline'},{value:'transactions',label:t('treasury.transactions'),icon:'mdi-cash-sync'},{value:'cheques',label:t('treasury.cheques'),icon:'mdi-checkbook'}])
const accountOptions=computed(()=>accounts.value.filter(v=>v.active).map(v=>({title:`${v.code} — ${v.name}`,value:v.id})))
async function load(){loading.value=true;error.clear();try{const [d,a,ts,cs,at,tt]=await Promise.all([treasuryApi.dashboard(),treasuryApi.accounts(),treasuryApi.transactions(),treasuryApi.cheques(),treasuryApi.accountTypes(),treasuryApi.transactionTypes()]);dashboard.value=d;accounts.value=a;transactionRows.value=ts.content;chequeRows.value=cs.content;accountTypes.value=at;transactionTypes.value=tt; if(!account.value.accountTypeId&&at[0])account.value.accountTypeId=at[0].id;if(!transaction.value.transactionTypeId&&tt[0])transaction.value.transactionTypeId=tt[0].id;const statuses=await treasuryApi.chequeStatuses();if(!cheque.value.statusId&&statuses[0])cheque.value.statusId=statuses[0].id}catch(e){error.set(e)}finally{loading.value=false}}
async function saveAccount(){saving.value=true;try{await treasuryApi.createAccount(account.value);accountDialog.value=false;notifications.success(t('treasury.saved'));await load()}catch(e){error.set(e)}finally{saving.value=false}}
async function saveTransaction(){saving.value=true;try{await treasuryApi.createTransaction(transaction.value);transactionDialog.value=false;notifications.success(t('treasury.saved'));await load()}catch(e){error.set(e)}finally{saving.value=false}}
async function saveCheque(){saving.value=true;try{await treasuryApi.createCheque(cheque.value);chequeDialog.value=false;notifications.success(t('treasury.saved'));await load()}catch(e){error.set(e)}finally{saving.value=false}}
async function action(row:TreasuryTransaction,name:'submit'|'approve'|'complete'|'cancel'){try{await treasuryApi[name](row.id);notifications.success(t('treasury.saved'));await load()}catch(e){error.set(e)}}
onMounted(load)
</script>
<template>
  <AppPageHeader icon="mdi-bank" :eyebrow="t('treasury.title')" :title="t('treasury.title')" :subtitle="t('treasury.subtitle')">
    <template #actions><v-btn v-if="can('treasury:manage')" color="primary" prepend-icon="mdi-bank-plus" @click="accountDialog=true">{{t('treasury.newAccount')}}</v-btn></template>
  </AppPageHeader>
  <AppErrorState v-if="error.message.value" class="mb-4" :title="error.message.value" :retry-label="t('common.retry')" @retry="load"/>
  <v-row v-if="dashboard" class="mb-3"><v-col cols="12" sm="4"><v-card rounded="xl"><v-card-text><div class="text-caption">{{t('treasury.balance')}}</div><div class="text-h5">{{formatNumber(dashboard.totalBalance)}} {{dashboard.currencyCode}}</div></v-card-text></v-card></v-col><v-col cols="6" sm="4"><v-card rounded="xl"><v-card-text>{{t('treasury.accounts')}}: {{dashboard.accounts}}</v-card-text></v-card></v-col><v-col cols="6" sm="4"><v-card rounded="xl"><v-card-text>{{t('treasury.cheques')}}: {{dashboard.cheques}}</v-card-text></v-card></v-col></v-row>
  <v-card rounded="xl"><v-tabs v-model="tab" color="primary"><v-tab v-for="item in tabs" :key="item.value" :value="item.value" :prepend-icon="item.icon">{{item.label}}</v-tab></v-tabs><v-window v-model="tab"><v-window-item value="accounts"><v-card-text><v-btn v-if="can('treasury:manage')" class="mb-3" variant="tonal" prepend-icon="mdi-plus" @click="accountDialog=true">{{t('treasury.newAccount')}}</v-btn><AppEmptyState v-if="!loading&&!accounts.length" :title="t('treasury.empty')"/><v-table v-else><thead><tr><th>{{t('common.name')}}</th><th>{{t('treasury.accountType')}}</th><th>{{t('treasury.balance')}}</th></tr></thead><tbody><tr v-for="item in accounts" :key="item.id"><td>{{item.code}} — {{item.name}}</td><td>{{item.accountTypeName}}</td><td>{{formatNumber(item.currentBalance)}} {{item.currencyCode}}</td></tr></tbody></v-table></v-card-text></v-window-item><v-window-item value="transactions"><v-card-text><v-btn v-if="can('treasury:create')" class="mb-3" color="primary" prepend-icon="mdi-plus" @click="transactionDialog=true">{{t('treasury.newTransaction')}}</v-btn><AppEmptyState v-if="!loading&&!transactionRows.length" :title="t('treasury.empty')"/><v-table v-else><thead><tr><th>{{t('treasury.number')}}</th><th>{{t('treasury.type')}}</th><th>{{t('treasury.amount')}}</th><th>{{t('treasury.status')}}</th><th/></tr></thead><tbody><tr v-for="item in transactionRows" :key="item.id"><td>{{item.number}}</td><td>{{item.typeName}}</td><td>{{formatNumber(item.amount)}} {{item.currencyCode}}</td><td><v-chip size="small">{{item.statusName}}</v-chip></td><td><v-btn v-if="item.statusCode==='draft'&&can('treasury:create')" size="small" variant="text" @click="action(item,'submit')">{{t('treasury.submit')}}</v-btn><v-btn v-if="item.statusCode==='pending'&&can('treasury:approve')" size="small" variant="text" @click="action(item,'approve')">{{t('treasury.approve')}}</v-btn><v-btn v-if="(item.statusCode==='draft'||item.statusCode==='approved')&&can('treasury:complete')" size="small" variant="text" @click="action(item,'complete')">{{t('treasury.complete')}}</v-btn></td></tr></tbody></v-table></v-card-text></v-window-item><v-window-item value="cheques"><v-card-text><v-btn v-if="can('treasury:manage-cheques')" class="mb-3" color="primary" prepend-icon="mdi-plus" @click="chequeDialog=true">{{t('treasury.newCheque')}}</v-btn><AppEmptyState v-if="!loading&&!chequeRows.length" :title="t('treasury.empty')"/><v-table v-else><thead><tr><th>{{t('treasury.number')}}</th><th>{{t('treasury.bank')}}</th><th>{{t('treasury.amount')}}</th><th>{{t('treasury.status')}}</th></tr></thead><tbody><tr v-for="item in chequeRows" :key="item.id"><td>{{item.chequeNumber}}</td><td>{{item.bankName}}</td><td>{{formatNumber(item.amount)}} {{item.currencyCode}}</td><td>{{item.statusName}}</td></tr></tbody></v-table></v-card-text></v-window-item></v-window></v-card>
  <v-dialog v-model="accountDialog" max-width="640"><v-card><v-card-title>{{t('treasury.newAccount')}}</v-card-title><v-card-text><v-row><v-col cols="12" sm="6"><v-select v-model="account.accountTypeId" :items="accountTypes" item-title="name" item-value="id" :label="t('treasury.accountType')"/></v-col><v-col cols="12" sm="6"><v-text-field v-model="account.code" label="Code"/></v-col><v-col cols="12"><v-text-field v-model="account.name" :label="t('common.name')"/></v-col><v-col cols="12" sm="6"><v-text-field v-model.number="account.openingBalance" type="number" inputmode="decimal" :label="t('treasury.openingBalance')"/></v-col><v-col cols="12" sm="6"><v-text-field v-model="account.bankName" :label="t('treasury.bank')"/></v-col></v-row></v-card-text><v-card-actions><v-spacer/><v-btn @click="accountDialog=false">{{t('common.cancel')}}</v-btn><v-btn color="primary" :loading="saving" @click="saveAccount">{{t('common.save')}}</v-btn></v-card-actions></v-card></v-dialog>
  <v-dialog v-model="transactionDialog" max-width="640"><v-card><v-card-title>{{t('treasury.newTransaction')}}</v-card-title><v-card-text><v-row><v-col cols="12"><v-select v-model="transaction.transactionTypeId" :items="transactionTypes" item-title="name" item-value="id" :label="t('treasury.type')"/></v-col><v-col cols="12" sm="6"><v-select v-model="transaction.sourceAccountId" :items="accountOptions" clearable :label="t('treasury.source')"/></v-col><v-col cols="12" sm="6"><v-select v-model="transaction.destinationAccountId" :items="accountOptions" clearable :label="t('treasury.destination')"/></v-col><v-col cols="12" sm="6"><v-text-field v-model.number="transaction.amount" type="number" inputmode="decimal" :label="t('treasury.amount')"/></v-col><v-col cols="12"><v-textarea v-model="transaction.description" :label="t('common.description')"/></v-col></v-row></v-card-text><v-card-actions><v-spacer/><v-btn @click="transactionDialog=false">{{t('common.cancel')}}</v-btn><v-btn color="primary" :loading="saving" @click="saveTransaction">{{t('common.save')}}</v-btn></v-card-actions></v-card></v-dialog>
  <v-dialog v-model="chequeDialog" max-width="640"><v-card><v-card-title>{{t('treasury.newCheque')}}</v-card-title><v-card-text><v-row><v-col cols="12" sm="6"><v-select v-model="cheque.direction" :items="[{title:t('treasury.received'),value:'RECEIVED'},{title:t('treasury.issued'),value:'ISSUED'}]" :label="t('treasury.direction')"/></v-col><v-col cols="12" sm="6"><v-text-field v-model="cheque.chequeNumber" :label="t('treasury.number')"/></v-col><v-col cols="12" sm="6"><v-text-field v-model="cheque.bankName" :label="t('treasury.bank')"/></v-col><v-col cols="12" sm="6"><v-text-field v-model.number="cheque.amount" type="number" inputmode="decimal" :label="t('treasury.amount')"/></v-col></v-row></v-card-text><v-card-actions><v-spacer/><v-btn @click="chequeDialog=false">{{t('common.cancel')}}</v-btn><v-btn color="primary" :loading="saving" @click="saveCheque">{{t('common.save')}}</v-btn></v-card-actions></v-card></v-dialog>
</template>
