package com.sami.app.sales.invoice;

import com.sami.app.accounting.publicapi.ReceivablePostingPort;
import com.sami.app.accounting.publicapi.ReceivablePostingPort.SalesInvoiceReceivableCommand;
import com.sami.app.common.exception.*;
import com.sami.app.common.tenancy.TenantContext;
import com.sami.app.contact.publicapi.ContactCustomerRoleLookup;
import com.sami.app.organization.service.OrganizationScopeService;
import com.sami.app.sales.delivery.*;
import com.sami.app.sales.order.*;
import com.sami.app.security.CurrentActor;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.*;
import java.time.*;
import java.util.*;
import static com.sami.app.sales.invoice.SalesInvoiceDtos.*;

@Service @RequiredArgsConstructor
public class SalesInvoiceService {
    private final TenantContext tenants; private final OrganizationScopeService scope; private final ContactCustomerRoleLookup contacts;
    private final SalesOrderRepository orders; private final DeliveryRepository deliveries; private final SalesInvoiceRepository invoices; private final SalesInvoiceAuditRepository audits;
    private final Optional<ReceivablePostingPort> receivablePosting;
    @Transactional public Response create(Request r){SalesOrder order=requireOrder(r.orderId());scope.requireScope(r.companyId(),r.branchId());if(order.getStatus()!=SalesOrderStatus.CONFIRMED)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Only confirmed orders can be invoiced");contacts.requireContactIdForCustomer(order.getCustomerId());SalesInvoice i=SalesInvoice.builder().tenantId(order.getTenantId()).order(order).companyId(order.getCompanyId()).branchId(order.getBranchId()).customerId(order.getCustomerId()).contactId(order.getContactId()).invoiceNumber(number()).status(InvoiceStatus.DRAFT).currency(currency(r.currency())).notes(r.notes()).createdBy(CurrentActor.id()).createdByEmail(CurrentActor.email()).build();addLines(i,order,r.lines());invoices.saveAndFlush(i);audit(i,"CREATED",null,Map.of("orderId",order.getId()));return Response.from(i);}
    @Transactional(readOnly=true) public List<Response> list(Long companyId,Long branchId){scope.requireScope(companyId,branchId);return invoices.findByTenantIdAndCompanyIdAndBranchIdOrderByCreatedAtDesc(tenants.requireTenantId(),companyId,branchId).stream().map(Response::from).toList();}
    @Transactional(readOnly=true) public Response get(Long id){return Response.from(find(id));}
    @Transactional public Response update(Long id,Request r){SalesInvoice i=find(id);if(i.getStatus()!=InvoiceStatus.DRAFT)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Only draft invoices can be edited");scope.requireScope(r.companyId(),r.branchId());SalesOrder order=requireOrder(i.getOrderId());i.getLines().clear();i.setNotes(r.notes());i.setCurrency(currency(r.currency()));addLines(i,order,r.lines());audit(i,"UPDATED",null,Map.of("orderId",order.getId()));return Response.from(i);}
    @Transactional(readOnly=true) public List<InvoiceableLine> invoiceable(Long orderId,Long companyId,Long branchId){SalesOrder order=requireOrder(orderId);scope.requireScope(companyId,branchId);if(order.getStatus()!=SalesOrderStatus.CONFIRMED)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Only confirmed orders can be invoiced");List<InvoiceableLine> result=new ArrayList<>();for(Delivery d:deliveries.findByOrderIdAndTenantIdAndStatus(orderId,tenants.requireTenantId(),DeliveryStatus.CONFIRMED)){for(DeliveryLine l:d.getLines()){BigDecimal delivered=l.getDeliveryQuantity(),previous=invoices.issuedQuantity(order.getTenantId(),l.getId()),available=delivered.subtract(previous).max(BigDecimal.ZERO);if(available.signum()>0)result.add(new InvoiceableLine(d.getId(),l.getId(),l.getOrderLineId(),l.getProductId(),l.getProductName(),l.getOrderedQuantity(),delivered,previous,available,order.getLines().stream().filter(x->Objects.equals(x.getId(),l.getOrderLineId())).findFirst().map(SalesOrderLine::getUnitPrice).orElse(BigDecimal.ZERO),order.getLines().stream().filter(x->Objects.equals(x.getId(),l.getOrderLineId())).findFirst().map(SalesOrderLine::getDiscount).orElse(BigDecimal.ZERO)));}}return result;}
    @Transactional public Response issue(Long id){SalesInvoice i=invoices.findByIdAndTenantIdForUpdate(id,tenants.requireTenantId()).orElseThrow(()->ResourceNotFoundException.of("Sales invoice",id));scope.requireScope(i.getCompanyId(),i.getBranchId());if(i.getStatus()==InvoiceStatus.ISSUED)return Response.from(i);if(i.getStatus()!=InvoiceStatus.DRAFT)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Only draft invoices can be issued");if(receivablePosting.isEmpty())throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Accounting receivable posting is not available");for(SalesInvoiceLine l:i.getLines()){BigDecimal issued=invoices.issuedQuantity(i.getTenantId(),l.getDeliveryLineId());DeliveryLine source=findDeliveryLine(l.getDeliveryLineId());if(issued.add(l.getQuantity()).compareTo(source.getDeliveryQuantity())>0)throw new ApiException(ErrorCode.RESOURCE_CONFLICT,"Invoice quantity exceeds invoiceable delivered quantity");}String key="SALES-INVOICE-"+i.getTenantId()+"-"+i.getId();Instant now=Instant.now();receivablePosting.get().createReceivable(new SalesInvoiceReceivableCommand(i.getTenantId(),i.getCompanyId(),i.getBranchId(),i.getContactId(),i.getId(),i.getFinalAmount(),i.getCurrency(),now,key));i.setReceivablePostingKey(key);i.setReceivablePostedAt(now);i.setStatus(InvoiceStatus.ISSUED);i.setIssuedAt(now);audit(i,"ISSUED",null,Map.of("postingKey",key,"amount",i.getFinalAmount()));return Response.from(i);}
    @Transactional public Response cancel(Long id){SalesInvoice i=find(id);if(i.getStatus()==InvoiceStatus.ISSUED)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Issued invoices require an approved reversal");if(i.getStatus()==InvoiceStatus.CANCELLED)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Invoice is already cancelled");i.setStatus(InvoiceStatus.CANCELLED);i.setCancelledAt(Instant.now());audit(i,"CANCELLED",null,Map.of());return Response.from(i);}
    @Transactional(readOnly=true) public List<AuditResponse> history(Long id){SalesInvoice i=find(id);return audits.findByInvoiceIdAndTenantIdOrderByOccurredAtDesc(id,i.getTenantId()).stream().map(AuditResponse::from).toList();}
    private SalesOrder requireOrder(Long id){return orders.findByIdAndTenantId(id,tenants.requireTenantId()).map(o->{scope.requireScope(o.getCompanyId(),o.getBranchId());return o;}).orElseThrow(()->ResourceNotFoundException.of("Sales order",id));}
    private SalesInvoice find(Long id){return invoices.findByIdAndTenantId(id,tenants.requireTenantId()).map(i->{scope.requireScope(i.getCompanyId(),i.getBranchId());return i;}).orElseThrow(()->ResourceNotFoundException.of("Sales invoice",id));}
    private DeliveryLine findDeliveryLine(Long id){Delivery d=deliveries.findByDeliveryLineIdAndTenantId(id,tenants.requireTenantId()).orElseThrow(()->ResourceNotFoundException.of("Delivery line",id));return d.getLines().stream().filter(l->Objects.equals(l.getId(),id)).findFirst().orElseThrow(()->ResourceNotFoundException.of("Delivery line",id));}
    private void addLines(SalesInvoice i,SalesOrder order,List<LineRequest> requests){for(LineRequest x:requests){DeliveryLine source=null;for(Delivery d:deliveries.findByOrderIdAndTenantIdAndStatus(order.getId(),order.getTenantId(),DeliveryStatus.CONFIRMED))for(DeliveryLine l:d.getLines())if(Objects.equals(l.getId(),x.deliveryLineId()))source=l;if(source==null)throw ResourceNotFoundException.of("Delivery line",x.deliveryLineId());BigDecimal issued=invoices.issuedQuantity(order.getTenantId(),source.getId()),available=source.getDeliveryQuantity().subtract(issued).max(BigDecimal.ZERO);if(x.quantity().compareTo(available)>0)throw new ApiException(ErrorCode.RESOURCE_CONFLICT,"Invoice quantity exceeds invoiceable delivered quantity");SalesOrderLine ol=null;for(SalesOrderLine candidate:order.getLines())if(Objects.equals(candidate.getId(),source.getOrderLineId())){ol=candidate;break;}if(ol==null)throw ResourceNotFoundException.of("Order line",source.getOrderLineId());BigDecimal amount=money(ol.getUnitPrice().multiply(x.quantity())),discount=money(ol.getDiscount().multiply(x.quantity()).divide(ol.getQuantity(),2,RoundingMode.HALF_UP));i.getLines().add(SalesInvoiceLine.builder().invoice(i).tenantId(order.getTenantId()).orderLineId(ol.getId()).deliveryLineId(source.getId()).productId(ol.getProductId()).productSku(ol.getProductSku()).productName(ol.getProductName()).quantity(x.quantity()).unitPrice(ol.getUnitPrice()).discount(discount).lineTotal(money(amount.subtract(discount))).build());}totals(i);}
    private void totals(SalesInvoice i){BigDecimal subtotal=i.getLines().stream().map(l->l.getUnitPrice().multiply(l.getQuantity())).reduce(BigDecimal.ZERO,BigDecimal::add),discount=i.getLines().stream().map(SalesInvoiceLine::getDiscount).reduce(BigDecimal.ZERO,BigDecimal::add);i.setSubtotal(money(subtotal));i.setDiscountTotal(money(discount));i.setFinalAmount(money(subtotal.subtract(discount)));if(!i.getLines().isEmpty())i.setDeliveryId(i.getLines().getFirst().getDeliveryLineId());}
    private void audit(SalesInvoice i,String action,Map<String,Object> old,Map<String,Object> next){audits.save(SalesInvoiceAudit.builder().invoice(i).tenantId(i.getTenantId()).action(action).actorId(CurrentActor.id()).actorEmail(CurrentActor.email()).oldValue(old).newValue(next).build());}
    private String number(){return "INV-%d-%06d".formatted(Year.now(ZoneOffset.UTC).getValue(),invoices.nextNumber());}private String currency(String x){return x==null||x.isBlank()?"IRR":x.toUpperCase(Locale.ROOT);}private BigDecimal money(BigDecimal x){return x.setScale(2,RoundingMode.HALF_UP);}
}
