package com.sami.app.attendance.service;

import com.sami.app.attendance.domain.*;
import com.sami.app.attendance.dto.AttendanceDtos.*;
import com.sami.app.attendance.repository.*;
import com.sami.app.common.api.PageResponse;
import com.sami.app.common.exception.*;
import com.sami.app.common.tenancy.TenantContext;
import com.sami.app.security.CurrentActor;
import lombok.RequiredArgsConstructor;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.*;

@Service @RequiredArgsConstructor
public class AttendanceService {
 private final EmployeeRepository employees; private final AttendanceRecordRepository records; private final TenantContext tenant; private final JdbcTemplate jdbc;
 @Transactional(readOnly=true) public PageResponse<EmployeeResponse> employees(String q,String status,int page,int size){return PageResponse.from(employees.search(tenant.requireTenantId(),blank(q),blank(status),PageRequest.of(page,Math.min(Math.max(size,1),100),Sort.by("lastName","firstName"))),EmployeeResponse::from);}
 @Transactional public EmployeeResponse create(EmployeeRequest r){Long t=tenant.requireTenantId();if(employees.existsByTenantIdAndEmployeeCodeIgnoreCase(t,r.employeeCode()))throw new ApiException(ErrorCode.RESOURCE_CONFLICT,"Employee code already exists");var e=Employee.builder().tenantId(t).employeeCode(r.employeeCode().trim()).firstName(r.firstName().trim()).lastName(r.lastName().trim()).userId(r.userId()).companyId(r.companyId()).branchId(r.branchId()).jobTitle(blank(r.jobTitle())).mobile(blank(r.mobile())).hireDate(r.hireDate()).status(r.status()==null?"ACTIVE":r.status()).build();try{e=employees.save(e);}catch(DataIntegrityViolationException ex){throw new ApiException(ErrorCode.RESOURCE_CONFLICT,"Employee identity or organization assignment is invalid");}audit(t,"EMPLOYEE",e.getId(),"CREATED");return EmployeeResponse.from(e);}
 @Transactional public EmployeeResponse update(Long id,EmployeeRequest r){Long t=tenant.requireTenantId();var e=employee(id,t);if(!e.getEmployeeCode().equalsIgnoreCase(r.employeeCode())&&employees.existsByTenantIdAndEmployeeCodeIgnoreCase(t,r.employeeCode()))throw new ApiException(ErrorCode.RESOURCE_CONFLICT,"Employee code already exists");e.setEmployeeCode(r.employeeCode().trim());e.setFirstName(r.firstName().trim());e.setLastName(r.lastName().trim());e.setUserId(r.userId());e.setCompanyId(r.companyId());e.setBranchId(r.branchId());e.setJobTitle(blank(r.jobTitle()));e.setMobile(blank(r.mobile()));e.setHireDate(r.hireDate());e.setStatus(r.status()==null?"ACTIVE":r.status());try{e=employees.save(e);}catch(DataIntegrityViolationException ex){throw new ApiException(ErrorCode.RESOURCE_CONFLICT,"Employee identity or organization assignment is invalid");}audit(t,"EMPLOYEE",id,"UPDATED");return EmployeeResponse.from(e);}
 @Transactional public RecordResponse clockIn(ClockRequest r){Long t=tenant.requireTenantId();var e=employee(r.employeeId(),t);if(!"ACTIVE".equals(e.getStatus()))throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Inactive employee cannot clock in");if(records.findByTenantIdAndEmployeeIdAndClockOutIsNull(t,e.getId()).isPresent())throw new ApiException(ErrorCode.RESOURCE_CONFLICT,"Employee already has an open attendance record");Instant at=r.occurredAt()==null?Instant.now():r.occurredAt();var rec=AttendanceRecord.builder().tenantId(t).employee(e).workDate(LocalDate.ofInstant(at,zone(e))).clockIn(at).status("PRESENT").source("MANUAL").notes(blank(r.notes())).createdBy(CurrentActor.id()).updatedBy(CurrentActor.id()).build();try{rec=records.save(rec);}catch(DataIntegrityViolationException ex){throw new ApiException(ErrorCode.RESOURCE_CONFLICT,"Employee already has an open attendance record");}audit(t,"ATTENDANCE",rec.getId(),"CLOCK_IN");return RecordResponse.from(rec);}
 @Transactional public RecordResponse clockOut(ClockRequest r){Long t=tenant.requireTenantId();employee(r.employeeId(),t);var rec=records.findByTenantIdAndEmployeeIdAndClockOutIsNull(t,r.employeeId()).orElseThrow(()->new ApiException(ErrorCode.RESOURCE_CONFLICT,"No open attendance record"));Instant at=r.occurredAt()==null?Instant.now():r.occurredAt();if(at.isBefore(rec.getClockIn()))throw new ApiException(ErrorCode.VALIDATION_FAILED,"Clock-out cannot be before clock-in");rec.setClockOut(at);rec.setUpdatedBy(CurrentActor.id());if(r.notes()!=null)rec.setNotes(blank(r.notes()));audit(t,"ATTENDANCE",rec.getId(),"CLOCK_OUT");return RecordResponse.from(records.save(rec));}
 @Transactional public RecordResponse correct(Long id,CorrectionRequest r){Long t=tenant.requireTenantId();var rec=records.findByIdAndTenantId(id,t).orElseThrow(()->new ApiException(ErrorCode.RESOURCE_NOT_FOUND));if(!rec.getVersion().equals(r.expectedVersion()))throw new ApiException(ErrorCode.RESOURCE_CONFLICT,"Attendance record changed; refresh and retry");if(r.clockOut()!=null&&r.clockOut().isBefore(r.clockIn()))throw new ApiException(ErrorCode.VALIDATION_FAILED,"Clock-out cannot be before clock-in");rec.setClockIn(r.clockIn());rec.setClockOut(r.clockOut());rec.setWorkDate(LocalDate.ofInstant(r.clockIn(),zone(rec.getEmployee())));rec.setStatus(r.status()==null?"PRESENT":r.status());rec.setNotes(blank(r.notes()));rec.setSource("MANUAL");rec.setUpdatedBy(CurrentActor.id());audit(t,"ATTENDANCE",id,"CORRECTED");return RecordResponse.from(records.save(rec));}
 @Transactional(readOnly=true) public PageResponse<RecordResponse> records(Long employeeId,LocalDate from,LocalDate to,int page,int size){return PageResponse.from(records.search(tenant.requireTenantId(),employeeId,from,to,PageRequest.of(page,Math.min(Math.max(size,1),100),Sort.by(Sort.Direction.DESC,"clockIn"))),RecordResponse::from);}
 @Transactional(readOnly=true) public ContextResponse context(){Long t=tenant.requireTenantId();var companies=jdbc.query("select id,name from companies where tenant_id=? and is_active order by display_order,name",(rs,n)->new OptionResponse(rs.getLong(1),rs.getString(2),null),t);var branches=jdbc.query("select id,name,company_id from branches where tenant_id=? and is_active order by display_order,name",(rs,n)->new OptionResponse(rs.getLong(1),rs.getString(2),rs.getLong(3)),t);var users=jdbc.query("select id,full_name from users where tenant_id=? and deleted_at is null order by full_name",(rs,n)->new OptionResponse(rs.getLong(1),rs.getString(2),null),t);return new ContextResponse(companies,branches,users);}
 private Employee employee(Long id,Long t){return employees.findByIdAndTenantId(id,t).orElseThrow(()->new ApiException(ErrorCode.RESOURCE_NOT_FOUND,"Employee not found"));}
 private ZoneId zone(Employee e){String z=jdbc.queryForObject("select coalesce(b.timezone,c.timezone,'Asia/Tehran') from branches b join companies c on c.id=b.company_id where b.id=? and b.tenant_id=?",String.class,e.getBranchId(),e.getTenantId());return ZoneId.of(z);}
 private void audit(Long t,String type,Long id,String action){jdbc.update("insert into attendance_audit_logs(tenant_id,entity_type,entity_id,action,actor_id,actor_email) values(?,?,?,?,?,?)",t,type,id,action,CurrentActor.id(),CurrentActor.email());}
 private static String blank(String s){return s==null||s.isBlank()?null:s.trim();}
}
