package com.sami.app.sales;
import static org.assertj.core.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
import com.sami.app.common.tenancy.TenantContext; import com.sami.app.contact.publicapi.ContactCustomerRoleLookup; import com.sami.app.organization.service.OrganizationScopeService; import com.sami.app.product.domain.Product; import com.sami.app.product.repository.ProductRepository; import com.sami.app.sales.document.*; import com.sami.app.sales.document.SalesDocumentDtos.*; import java.math.BigDecimal; import java.util.*; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import org.springframework.test.util.ReflectionTestUtils;
@ExtendWith(MockitoExtension.class) class SalesDocumentServiceTest { @Mock TenantContext tenants; @Mock OrganizationScopeService scope; @Mock ContactCustomerRoleLookup contacts; @Mock ProductRepository products; @Mock SalesDocumentRepository documents; @Mock SalesDocumentAuditRepository audits; @InjectMocks SalesDocumentService service;
 @Test void createsNonPostingPriceSnapshotInGrantedScope(){when(tenants.requireTenantId()).thenReturn(41L);when(contacts.requireContactIdForCustomer(9L)).thenReturn(70L);Product p=Product.builder().tenantId(41L).name("Phone").sku("P1").price(new BigDecimal("999")).active(true).build();ReflectionTestUtils.setField(p,"id",5L);when(products.findByIdAndTenantId(5L,41L)).thenReturn(Optional.of(p));when(documents.nextNumber()).thenReturn(1L);when(documents.saveAndFlush(any())).thenAnswer(i->{SalesDocument d=i.getArgument(0);ReflectionTestUtils.setField(d,"id",91L);return d;});Response r=service.create(new Request(7L,8L,9L,SalesDocumentType.QUOTATION,"IRR",null,List.of(new LineRequest(5L,new BigDecimal("2"),new BigDecimal("100"),new BigDecimal("20"))),null));assertThat(r.finalAmount()).isEqualByComparingTo("180.00");assertThat(r.lines().getFirst().unitPrice()).isEqualByComparingTo("100.00");verify(scope).requireScope(7L,8L);verify(audits).save(any());}
 @Test void issuedDocumentCannotBeEdited(){SalesDocument d=doc(SalesDocumentStatus.ISSUED);when(tenants.requireTenantId()).thenReturn(41L);when(documents.findByIdAndTenantId(91L,41L)).thenReturn(Optional.of(d));assertThatThrownBy(()->service.update(91L,new Request(7L,8L,9L,SalesDocumentType.QUOTATION,"IRR",null,List.of(new LineRequest(5L,BigDecimal.ONE,BigDecimal.ONE,BigDecimal.ZERO)),0L))).isInstanceOf(RuntimeException.class);verify(scope).requireScope(7L,8L);}
 @Test void alteredScopeIsRejectedForRead(){SalesDocument d=doc(SalesDocumentStatus.DRAFT);when(tenants.requireTenantId()).thenReturn(41L);when(documents.findByIdAndTenantId(91L,41L)).thenReturn(Optional.of(d));doThrow(new com.sami.app.common.exception.ApiException(com.sami.app.common.exception.ErrorCode.ACCESS_DENIED,"denied")).when(scope).requireScope(7L,8L);assertThatThrownBy(()->service.get(91L)).isInstanceOf(RuntimeException.class);}
 @Test void issuedQuotationExposesOnlyItsPersistedSnapshotToFutureOrder(){SalesDocument d=doc(SalesDocumentStatus.ISSUED);SalesDocumentLine line=SalesDocumentLine.builder().document(d).tenantId(41L).productId(5L).productSku("P1").productName("Phone").quantity(BigDecimal.ONE).unitPrice(new BigDecimal("100.00")).discount(BigDecimal.TEN).lineTotal(new BigDecimal("90.00")).build();ReflectionTestUtils.setField(line,"id",12L);d.getLines().add(line);when(tenants.requireTenantId()).thenReturn(41L);when(documents.findByIdAndTenantId(91L,41L)).thenReturn(Optional.of(d));var snapshot=service.requireIssuedQuotation(91L);assertThat(snapshot.customerId()).isEqualTo(9L);assertThat(snapshot.lines()).singleElement().satisfies(l->assertThat(l.unitPrice()).isEqualByComparingTo("100.00"));}
 @Test void onlyIssuedDocumentsCanExpire(){SalesDocument d=doc(SalesDocumentStatus.ISSUED);when(tenants.requireTenantId()).thenReturn(41L);when(documents.findByIdAndTenantId(91L,41L)).thenReturn(Optional.of(d));service.expire(91L);assertThat(d.getStatus()).isEqualTo(SalesDocumentStatus.EXPIRED);verify(audits).save(any());}
 private SalesDocument doc(SalesDocumentStatus s){SalesDocument d=SalesDocument.builder().tenantId(41L).companyId(7L).branchId(8L).customerId(9L).contactId(70L).documentType(SalesDocumentType.QUOTATION).documentNumber("QTN-2026-000001").status(s).build();ReflectionTestUtils.setField(d,"id",91L);return d;}}
