package com.sami.app.purchasepayment.service;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.sami.app.common.exception.*;
import com.sami.app.common.tenancy.TenantContext;
import com.sami.app.purchasepayment.dto.PurchasePaymentDtos.*;
import com.sami.app.security.CurrentActor;
import com.sami.app.notification.service.StaffNotificationService;
import com.sami.app.treasury.service.TreasuryService;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;

@Service @RequiredArgsConstructor
public class PurchasePaymentService {
 private final JdbcTemplate jdbc; private final TenantContext tenants; private final TreasuryService treasury; private final ObjectMapper json; private final StaffNotificationService notifications;
 @Transactional public Map<String,Object> create(CreateRequest r){long tenant=tenant(),actor=actor();boolean approval=jdbc.query("select manager_approval_required from purchase_payment_settings where tenant_id=?",rs->rs.next()?rs.getBoolean(1):true,tenant);String status=approval?"WAITING_MANAGER":"APPROVED";String number="PPR-"+Year.now().getValue()+"-"+UUID.randomUUID().toString().substring(0,8).toUpperCase(Locale.ROOT);Long id=jdbc.queryForObject("insert into purchase_payment_requests(tenant_id,request_number,requester_id,supplier_name,purpose,requested_amount,document_reference,attachment_file_id,status) values(?,?,?,?,?,?,?,?,?) returning id",Long.class,tenant,number,actor,r.supplierName(),r.purpose(),r.amount(),r.documentReference(),r.attachmentFileId(),status);audit(id,"CREATED",Map.of("status",status,"amount",r.amount()));return get(id,false);}
 @Transactional(readOnly=true) public List<Map<String,Object>> mine(){return rows("select * from purchase_payment_requests where tenant_id=? and requester_id=? order by created_at desc",tenant(),actor());}
 @Transactional(readOnly=true) public List<Map<String,Object>> all(){return rows("select * from purchase_payment_requests where tenant_id=? order by created_at desc",tenant());}
 @Transactional(readOnly=true) public Map<String,Object> get(Long id,boolean ownOnly){Map<String,Object> request=one("select * from purchase_payment_requests where tenant_id=? and id=?"+(ownOnly?" and requester_id=?":""),ownOnly?new Object[]{tenant(),id,actor()}:new Object[]{tenant(),id});request.put("receipts",rows("select * from purchase_payment_receipts where tenant_id=? and request_id=? order by paid_at",tenant(),id));return request;}
 @Transactional public Map<String,Object> view(Long id,boolean ownOnly){Map<String,Object> result=get(id,ownOnly);jdbc.update("update purchase_payment_requests set "+(ownOnly?"requester_viewed_at":"accountant_viewed_at")+"=coalesce("+(ownOnly?"requester_viewed_at":"accountant_viewed_at")+",now()) where tenant_id=? and id=?",tenant(),id);return result;}
 @Transactional public Map<String,Object> decide(Long id,DecisionRequest r){Map<String,Object>x=lock(id);require("WAITING_MANAGER".equals(x.get("status")),"Request is not waiting for manager");if(!r.approved()&&(r.rejectionReason()==null||r.rejectionReason().isBlank()))throw new ApiException(ErrorCode.VALIDATION_FAILED,"Rejection reason is required");String status=r.approved()?"WAITING_PAYMENT":"REJECTED";jdbc.update("update purchase_payment_requests set status=?,manager_id=?,manager_decided_at=now(),rejection_reason=?,assigned_accountant_id=?,assigned_at=case when ? then now() else null end,payment_deadline_at=case when ? then now()+interval '20 minutes' else null end,updated_at=now(),version=version+1 where tenant_id=? and id=?",status,actor(),r.rejectionReason(),r.accountantId(),r.approved(),r.approved(),tenant(),id);audit(id,r.approved()?"APPROVED":"REJECTED",Map.of("status",status));return get(id,false);}
 @Transactional public Map<String,Object> pay(Long id,PaymentRequest r){Map<String,Object>x=lock(id);String state=String.valueOf(x.get("status"));require(Set.of("APPROVED","WAITING_PAYMENT","PARTIALLY_PAID","OVERDUE").contains(state),"Request is not payable");BigDecimal requested=(BigDecimal)x.get("requested_amount"),paid=(BigDecimal)x.get("paid_amount"),remaining=requested.subtract(paid);if(r.amount().compareTo(remaining)>0)throw new ApiException(ErrorCode.VALIDATION_FAILED,"Payment exceeds remaining amount");LocalDate paymentDate=LocalDate.ofInstant(r.paidAt(),ZoneId.of("Asia/Tehran"));lockLimit(r.treasuryAccountId(),paymentDate,r.method());BigDecimal available=available(r.treasuryAccountId(),paymentDate,r.method());if(r.amount().compareTo(available)>0)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Daily payment capacity is insufficient");Long tx=treasury.recordOutflow(r.treasuryAccountId(),r.amount(),r.paidAt(),"purchase-payment",String.valueOf(x.get("request_number")),r.note());jdbc.update("insert into purchase_payment_receipts(tenant_id,request_id,treasury_account_id,treasury_transaction_id,method,amount,paid_at,reference_number,receipt_file_id,note,created_by) values(?,?,?,?,?,?,?,?,?,?,?)",tenant(),id,r.treasuryAccountId(),tx,r.method(),r.amount(),java.sql.Timestamp.from(r.paidAt()),r.referenceNumber(),r.receiptFileId(),r.note(),actor());BigDecimal total=paid.add(r.amount());String next=total.compareTo(requested)==0||r.completeWithPartialAmount()?"PAID":"PARTIALLY_PAID";jdbc.update("update purchase_payment_requests set paid_amount=?,status=?,completed_at=case when ?='PAID' then now() else null end,updated_at=now(),version=version+1 where tenant_id=? and id=?",total,next,next,tenant(),id);audit(id,"PAYMENT_RECORDED",Map.of("amount",r.amount(),"method",r.method(),"status",next));return get(id,false);}
 @Transactional public Map<String,Object> cancel(Long id){Map<String,Object>x=lock(id);require(Set.of("DRAFT","WAITING_MANAGER").contains(String.valueOf(x.get("status"))),"Request can no longer be cancelled");require(((Number)x.get("requester_id")).longValue()==actor(),"Only requester can cancel");jdbc.update("update purchase_payment_requests set status='CANCELLED',cancelled_at=now(),updated_at=now(),version=version+1 where tenant_id=? and id=?",tenant(),id);audit(id,"CANCELLED",Map.of());return get(id,true);}
 @Transactional public Map<String,Object> delay(Long id,DelayRequest r){lock(id);jdbc.update("update purchase_payment_requests set status='OVERDUE',delay_reason=?,updated_at=now(),version=version+1 where tenant_id=? and id=?",r.reason(),tenant(),id);audit(id,"DELAY_RECORDED",Map.of("reason",r.reason()));return get(id,false);}
 @Transactional public Map<String,Object> setLimit(LimitRequest r){jdbc.update("insert into purchase_payment_daily_limits(tenant_id,treasury_account_id,payment_date,method,limit_amount,created_by,updated_by) values(?,?,?,?,?,?,?) on conflict(tenant_id,treasury_account_id,payment_date,method) do update set limit_amount=excluded.limit_amount,updated_by=excluded.updated_by,updated_at=now(),version=purchase_payment_daily_limits.version+1",tenant(),r.treasuryAccountId(),r.paymentDate(),r.method(),r.limitAmount(),actor(),actor());return Map.of("availableAmount",available(r.treasuryAccountId(),r.paymentDate(),r.method()));}
 @Transactional(readOnly=true) public Map<String,Object> capacity(Long account,LocalDate date,String method){return Map.of("availableAmount",available(account,date,method),"date",date,"method",method);}
 @Transactional public int processReminders(Instant scheduledFor){Instant now=scheduledFor==null?Instant.now():scheduledFor;List<Map<String,Object>> due=rows("select * from purchase_payment_requests where tenant_id=? and status in ('WAITING_MANAGER','APPROVED','WAITING_PAYMENT','PARTIALLY_PAID','OVERDUE')",tenant());int created=0;for(Map<String,Object> r:due){Long id=((Number)r.get("id")).longValue();Long requester=((Number)r.get("requester_id")).longValue();String status=String.valueOf(r.get("status"));Instant deadline=toInstant(r.get("payment_deadline_at"));if(deadline!=null&&now.isAfter(deadline)&&!"OVERDUE".equals(status)){jdbc.update("update purchase_payment_requests set status='OVERDUE',updated_at=now(),version=version+1 where tenant_id=? and id=?",tenant(),id);status="OVERDUE";}long cadence=r.get("requester_viewed_at")==null?60:300;long window=now.getEpochSecond()/cadence;notifications.createSystem(requester,"PURCHASE_PAYMENT","notifications.purchasePayment.title","notifications.purchasePayment."+("OVERDUE".equals(status)?"overdue":"reminder"),"/purchase-payments","purchase-payment:"+id+":"+window+":"+requester);created++;Object accountant=r.get("assigned_accountant_id");if("OVERDUE".equals(status)&&accountant instanceof Number n){notifications.createSystem(n.longValue(),"PURCHASE_PAYMENT","notifications.purchasePayment.title","notifications.purchasePayment.overdue","/purchase-payments","purchase-payment-overdue:"+id+":"+window+":"+n.longValue());created++;}}return created;}
 private BigDecimal available(Long account,LocalDate date,String method){List<BigDecimal>v=jdbc.query("select greatest(l.limit_amount-coalesce(sum(r.amount),0),0) from purchase_payment_daily_limits l left join purchase_payment_receipts r on r.tenant_id=l.tenant_id and r.treasury_account_id=l.treasury_account_id and r.method=l.method and r.paid_at>=l.payment_date and r.paid_at<l.payment_date+1 where l.tenant_id=? and l.treasury_account_id=? and l.payment_date=? and l.method=? group by l.limit_amount",(rs,n)->rs.getBigDecimal(1),tenant(),account,date,method);return v.isEmpty()?BigDecimal.ZERO:v.getFirst();}
 private Instant toInstant(Object value){if(value instanceof java.sql.Timestamp t)return t.toInstant();if(value instanceof java.time.OffsetDateTime o)return o.toInstant();return null;}
 private void lockLimit(Long account,LocalDate date,String method){List<Long> ids=jdbc.query("select id from purchase_payment_daily_limits where tenant_id=? and treasury_account_id=? and payment_date=? and method=? for update",(rs,n)->rs.getLong(1),tenant(),account,date,method);if(ids.isEmpty())throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,"Daily payment capacity is not configured");}
 private Map<String,Object> lock(Long id){return one("select * from purchase_payment_requests where tenant_id=? and id=? for update",tenant(),id);} private List<Map<String,Object>> rows(String sql,Object...args){return jdbc.queryForList(sql,args).stream().map(HashMap::new).map(x->(Map<String,Object>)x).toList();} private Map<String,Object> one(String sql,Object...args){List<Map<String,Object>>x=rows(sql,args);if(x.isEmpty())throw new ApiException(ErrorCode.RESOURCE_NOT_FOUND);return x.getFirst();}
 private void audit(Long id,String action,Map<String,Object>d){try{jdbc.update("insert into purchase_payment_audit_log(tenant_id,request_id,action,actor_id,details) values(?,?,?,?,cast(? as jsonb))",tenant(),id,action,CurrentActor.id(),json.writeValueAsString(d));}catch(Exception e){throw new IllegalStateException(e);}} private long tenant(){return tenants.requireTenantId();} private long actor(){return CurrentActor.id()==null?failActor():CurrentActor.id();} private long failActor(){throw new ApiException(ErrorCode.ACCESS_DENIED,"Authenticated user is required");} private void require(boolean ok,String m){if(!ok)throw new ApiException(ErrorCode.OPERATION_NOT_ALLOWED,m);}
}
