package com.sami.app.treasury.dto;

import com.sami.app.treasury.domain.*;
import jakarta.validation.constraints.*;
import java.math.BigDecimal;
import java.time.*;
import java.util.List;

/** Transport contract for the tenant-scoped Treasury module. Tenant/user ownership is never client input. */
public final class TreasuryDtos {
 private TreasuryDtos() { }
 public record Lookup(Long id,String code,String name,boolean active,int displayOrder) { }
 public record AccountTypeResponse(Long id,String code,String name,String description,boolean requiresBankDetails,boolean allowsNegativeBalance,boolean active,boolean system,int displayOrder) {
  public static AccountTypeResponse from(TreasuryAccountType v){return new AccountTypeResponse(v.getId(),v.getCode(),v.getName(),v.getDescription(),v.isRequiresBankDetails(),v.isAllowsNegativeBalance(),v.isActive(),v.isSystem(),v.getDisplayOrder());}
 }
 public record TransactionTypeResponse(Long id,String code,String name,String direction,String description,boolean active,boolean system,int displayOrder) {
  public static TransactionTypeResponse from(TreasuryTransactionType v){return new TransactionTypeResponse(v.getId(),v.getCode(),v.getName(),v.getDirection().name(),v.getDescription(),v.isActive(),v.isSystem(),v.getDisplayOrder());}
 }
 public record TransactionStatusResponse(Long id,String code,String name,boolean allowsEditing,boolean draft,boolean pending,boolean approved,boolean completed,boolean rejected,boolean cancelled,boolean terminal,int displayOrder) {
  public static TransactionStatusResponse from(TreasuryTransactionStatus v){return new TransactionStatusResponse(v.getId(),v.getCode(),v.getName(),v.isAllowsEditing(),v.isDraftState(),v.isPendingState(),v.isApprovedState(),v.isCompletedState(),v.isRejectedState(),v.isCancelledState(),v.isTerminal(),v.getDisplayOrder());}
 }
 public record ChequeStatusResponse(Long id,String code,String name,boolean terminal,boolean active,int displayOrder) { public static ChequeStatusResponse from(TreasuryChequeStatus v){return new ChequeStatusResponse(v.getId(),v.getCode(),v.getName(),v.isTerminal(),v.isActive(),v.getDisplayOrder());} }
 public record CategoryResponse(Long id,String kind,String code,String name,String description,boolean active,int displayOrder) { public static CategoryResponse from(TreasuryCategory v){return new CategoryResponse(v.getId(),v.getKind().name(),v.getCode(),v.getName(),v.getDescription(),v.isActive(),v.getDisplayOrder());} }
 public record AccountRequest(@NotNull Long accountTypeId,@NotBlank @Size(max=64) String code,@NotBlank @Size(max=160) String name,@Pattern(regexp="[A-Z]{3}") String currencyCode,@NotNull BigDecimal openingBalance,boolean allowNegativeBalance,Long responsibleUserId,@Size(max=160) String bankName,@Size(max=160) String bankBranch,@Size(max=64) String iban,@Size(max=80) String accountNumber,@Size(max=32) String cardNumber,@Size(max=160) String accountHolder,@Size(max=1000) String description,boolean active) { }
 public record AccountResponse(Long id,Long accountTypeId,String accountTypeCode,String accountTypeName,String code,String name,String currencyCode,BigDecimal openingBalance,BigDecimal currentBalance,boolean allowNegativeBalance,Long responsibleUserId,String bankName,String bankBranch,String iban,String accountNumber,String cardNumber,String accountHolder,String description,boolean active,Long version) { public static AccountResponse from(TreasuryAccount v){return new AccountResponse(v.getId(),v.getAccountType().getId(),v.getAccountType().getCode(),v.getAccountType().getName(),v.getCode(),v.getName(),v.getCurrencyCode(),v.getOpeningBalance(),v.getCurrentBalance(),v.isAllowNegativeBalance(),v.getResponsibleUserId(),v.getBankName(),v.getBankBranch(),v.getIban(),v.getAccountNumber(),v.getCardNumber(),v.getAccountHolder(),v.getDescription(),v.isActive(),v.getVersion());} }
 public record TransactionRequest(@NotNull Long transactionTypeId,Long categoryId,Long sourceAccountId,Long destinationAccountId,@NotNull @DecimalMin(value="0.01") BigDecimal amount,@Pattern(regexp="[A-Z]{3}") String currencyCode,@NotNull Instant occurredAt,@Size(max=64) String referenceModule,@Size(max=160) String referenceNumber,@Size(max=2000) String description) { }
 public record TransactionResponse(Long id,String number,Long typeId,String typeCode,String typeName,String direction,Long statusId,String statusCode,String statusName,Long categoryId,String categoryName,Long sourceAccountId,String sourceAccountName,Long destinationAccountId,String destinationAccountName,BigDecimal amount,String currencyCode,Instant occurredAt,String referenceModule,String referenceNumber,String description,Long createdBy,Long approvedBy,Instant approvedAt,Instant completedAt,Instant cancelledAt,Long reversalOfId,Long version) { public static TransactionResponse from(TreasuryTransaction v){return new TransactionResponse(v.getId(),v.getTransactionNumber(),v.getTransactionType().getId(),v.getTransactionType().getCode(),v.getTransactionType().getName(),v.getTransactionType().getDirection().name(),v.getStatus().getId(),v.getStatus().getCode(),v.getStatus().getName(),v.getCategory()==null?null:v.getCategory().getId(),v.getCategory()==null?null:v.getCategory().getName(),v.getSourceAccount()==null?null:v.getSourceAccount().getId(),v.getSourceAccount()==null?null:v.getSourceAccount().getName(),v.getDestinationAccount()==null?null:v.getDestinationAccount().getId(),v.getDestinationAccount()==null?null:v.getDestinationAccount().getName(),v.getAmount(),v.getCurrencyCode(),v.getOccurredAt(),v.getReferenceModule(),v.getReferenceNumber(),v.getDescription(),v.getCreatedBy(),v.getApprovedBy(),v.getApprovedAt(),v.getCompletedAt(),v.getCancelledAt(),v.getReversalOf()==null?null:v.getReversalOf().getId(),v.getVersion());} }
 public record MovementResponse(Long id,Long transactionId,String transactionNumber,BigDecimal amount,BigDecimal balanceAfter,Instant occurredAt) { public static MovementResponse from(TreasuryMovement v){return new MovementResponse(v.getId(),v.getTransaction().getId(),v.getTransaction().getTransactionNumber(),v.getAmount(),v.getBalanceAfter(),v.getOccurredAt());} }
 public record ChequeRequest(@NotNull TreasuryCheque.Direction direction,@NotBlank @Size(max=100) String chequeNumber,@NotBlank @Size(max=160) String bankName,@Size(max=160) String bankBranch,@NotNull @DecimalMin(value="0.01") BigDecimal amount,@Pattern(regexp="[A-Z]{3}") String currencyCode,@Size(max=160) String ownerName,@Size(max=160) String recipientName,LocalDate issueDate,LocalDate dueDate,@NotNull Long statusId,Long treasuryAccountId,Long transactionId,Long imageFileId,@Size(max=2000) String description) { }
 public record ChequeResponse(Long id,String direction,String chequeNumber,String bankName,String bankBranch,BigDecimal amount,String currencyCode,String ownerName,String recipientName,LocalDate issueDate,LocalDate dueDate,Long statusId,String statusCode,String statusName,Long treasuryAccountId,Long transactionId,Long imageFileId,String description,Instant statusChangedAt,Long version) { public static ChequeResponse from(TreasuryCheque v){return new ChequeResponse(v.getId(),v.getDirection().name(),v.getChequeNumber(),v.getBankName(),v.getBankBranch(),v.getAmount(),v.getCurrencyCode(),v.getOwnerName(),v.getRecipientName(),v.getIssueDate(),v.getDueDate(),v.getStatus().getId(),v.getStatus().getCode(),v.getStatus().getName(),v.getTreasuryAccount()==null?null:v.getTreasuryAccount().getId(),v.getTransaction()==null?null:v.getTransaction().getId(),v.getImageFileId(),v.getDescription(),v.getStatusChangedAt(),v.getVersion());} }
 public record ChequeStatusUpdate(@NotNull Long statusId) { }
 public record DailyClosingRequest(@NotNull Long accountId,@NotNull LocalDate closingDate,@NotNull BigDecimal declaredBalance,@Size(max=1000) String note) { }
 public record DailyClosingResponse(Long id,Long accountId,LocalDate closingDate,BigDecimal expectedBalance,BigDecimal declaredBalance,BigDecimal differenceAmount,Instant closedAt) { public static DailyClosingResponse from(TreasuryDailyClosing v){return new DailyClosingResponse(v.getId(),v.getAccount().getId(),v.getClosingDate(),v.getExpectedBalance(),v.getDeclaredBalance(),v.getDifferenceAmount(),v.getClosedAt());} }
 public record DashboardResponse(long accounts,long transactions,long cheques,BigDecimal totalBalance,String currencyCode) { }
}
