import { test, expect } from '@playwright/test'

test('creates a branch through the rendered Vuetify selector and proves persistence', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'The mutation runs once on desktop; responsive verification reuses persisted state')
  const marker = `${Date.now().toString(36)}-${testInfo.repeatEachIndex}`.toUpperCase()
  const branchCode = `BR-${marker}`
  const branchName = `Browser Branch ${marker}`
  const consoleErrors: string[] = []
  const failedRequests: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') consoleErrors.push(message.text()) })
  page.on('requestfailed', (request) => {
    const reason = request.failure()?.errorText ?? ''
    if (!/ERR_ABORTED|Load request cancelled/i.test(reason)) failedRequests.push(`${request.method()} ${request.url()} ${reason}`)
  })

  const organizationLoaded = page.waitForResponse((response) => /\/api\/v1\/organization\/companies$/.test(response.url()) && response.ok())
  const branchTypesLoaded = page.waitForResponse((response) => /\/api\/v1\/organization\/branch-types$/.test(response.url()) && response.ok())
  await page.goto('/organization', { waitUntil: 'domcontentloaded' })
  await Promise.all([organizationLoaded, branchTypesLoaded])
  await expect(page).toHaveURL(/\/organization$/)
  await expect(page.getByRole('heading', { name: /Organisation|سازمان/i })).toBeVisible()
  await expect(page.getByText('BROWSER-COMP', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: /Add branch|افزودن شعبه/i }).click()
  const dialog = page.getByRole('dialog', { name: /Add branch|افزودن شعبه/i })
  await expect(dialog).toBeVisible()
  const save = dialog.getByRole('button', { name: /Save|ذخیره/i })
  await expect(save).toBeDisabled()

  const company = dialog.getByRole('combobox', { name: /Company|شرکت/i })
  await company.focus()
  await company.press('ArrowDown')
  await expect(company).toHaveAttribute('aria-expanded', 'true')
  const companyOption = page.getByRole('option', { name: /BROWSER-COMP|شرکت تست مرورگر/i })
  await expect(companyOption).toBeVisible()
  await companyOption.click()
  await expect(company).toHaveValue(/BROWSER-COMP|شرکت تست مرورگر/i)

  await dialog.getByRole('textbox', { name: /Branch code|کد شعبه/i }).fill(branchCode)
  await dialog.getByRole('textbox', { name: /Branch name|نام شعبه/i }).fill(branchName)
  const branchType = dialog.getByRole('combobox', { name: /Branch type|نوع شعبه/i })
  await branchType.focus()
  await branchType.press('ArrowDown')
  await expect(branchType).toHaveAttribute('aria-expanded', 'true')
  const retailOption = page.getByRole('option', { name: 'Retail Store', exact: true })
  await expect(retailOption).toBeVisible()
  await retailOption.click()
  await expect(branchType).toHaveValue('Retail Store')
  await expect(save).toBeEnabled()

  const created = page.waitForResponse((response) => /\/api\/v1\/organization\/companies\/\d+\/branches$/.test(response.url()) && response.request().method() === 'POST')
  await save.click()
  expect((await created).ok()).toBeTruthy()
  await expect(page.getByText(/Branch created successfully|شعبه با موفقیت ایجاد شد/i)).toBeVisible()
  const row = page.getByRole('row').filter({ hasText: branchCode })
  await expect(row).toContainText(branchName)
  await expect(row).toContainText(/BROWSER-COMP|شرکت تست مرورگر/i)
  await expect(row).toContainText('Retail Store')
  await expect(row).toContainText(/Active|فعال/i)

  await page.reload({ waitUntil: 'domcontentloaded' })
  await expect(page.getByRole('row').filter({ hasText: branchCode })).toBeVisible()
  await page.goto('/')
  await page.goto('/organization', { waitUntil: 'domcontentloaded' })
  await expect(page.getByRole('row').filter({ hasText: branchCode })).toBeVisible()

  const userId = process.env.SAMI_E2E_USER_ID
  expect(userId, 'SAMI_E2E_USER_ID is required for the visible branch-grant prerequisite').toBeTruthy()
  const userIdField = page.getByRole('spinbutton', { name: /User ID|شناسه کاربر/i })
  await userIdField.fill(userId!)
  await userIdField.press('Tab')
  const grantCompany = page.getByRole('combobox', { name: /Company|شرکت/i }).last()
  await grantCompany.focus()
  await grantCompany.press('ArrowDown')
  await page.getByRole('option', { name: /BROWSER-COMP|شرکت تست مرورگر/i }).click()
  const grantBranch = page.getByRole('combobox', { name: /Branch|شعبه/i }).last()
  await grantBranch.focus()
  await grantBranch.press('ArrowDown')
  await page.getByRole('option', { name: branchName, exact: true }).click()
  const grantButton = page.getByRole('button', { name: /Grant branch access|اعطای دسترسی شعبه/i })
  if (await grantButton.isDisabled()) {
    const grantRole = page.getByRole('combobox', { name: /Role|نقش/i })
    await grantRole.focus()
    await grantRole.press('ArrowDown')
    const roleOption = page.getByRole('option').first()
    await expect(roleOption).toBeVisible()
    await roleOption.click()
    const assignmentResponse = page.waitForResponse((response) => /\/api\/v1\/organization\/grants$/.test(response.url()) && response.request().method() === 'POST')
    await page.getByRole('button', { name: /Assign company access|اعطای دسترسی شرکت/i }).click()
    expect((await assignmentResponse).ok()).toBeTruthy()
  }
  await expect(grantButton).toBeEnabled()
  const grantResponse = page.waitForResponse((response) => /\/api\/v1\/organization\/grants\/\d+\/branches$/.test(response.url()) && response.request().method() === 'POST')
  await grantButton.click()
  expect((await grantResponse).ok()).toBeTruthy()

  await page.reload({ waitUntil: 'domcontentloaded' })
  const contextButton = page.getByRole('button', { name: /Branch|شعبه|BROWSER-COMP|شرکت تست مرورگر/i }).first()
  await contextButton.click()
  const companyContextResponse = page.waitForResponse((response) => /\/api\/v1\/organization\/context$/.test(response.url()) && response.request().method() === 'PUT')
  await page.getByText(/شرکت تست مرورگر|BROWSER-COMP/, { exact: true }).last().click()
  expect((await companyContextResponse).ok()).toBeTruthy()
  await contextButton.click()
  const contextBranch = page.getByRole('menuitem', { name: branchName, exact: true })
  await expect(contextBranch).toBeVisible()
  const contextResponse = page.waitForResponse((response) => /\/api\/v1\/organization\/context$/.test(response.url()) && response.request().method() === 'PUT')
  await contextBranch.click()
  expect((await contextResponse).ok()).toBeTruthy()
  await expect(contextButton).toContainText(branchName)
  expect(consoleErrors, consoleErrors.join('\n')).toEqual([])
  expect(failedRequests, failedRequests.join('\n')).toEqual([])
})
