-- License, Subscription, Tenant & Feature Management — the licensing control
-- plane for SAMI ERP. Business modules never implement licensing logic: they ask
-- this module whether a feature is available (`@features.enabled('...')`) and
-- register usage meters. Everything is configuration: statuses, license types,
-- limit types, expiry behaviours, features, plans and their limits are rows.
-- Works unchanged for on-premise and cloud/SaaS (multi-tenant) deployments.

-- One configurable status catalogue scoped per aggregate (LICENSE|TENANT|PLAN),
-- so new statuses never require a schema change.
CREATE TABLE licensing_statuses (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    scope             VARCHAR(16)  NOT NULL,
    code              VARCHAR(64)  NOT NULL,
    name              VARCHAR(100) NOT NULL,
    is_default        BOOLEAN      NOT NULL DEFAULT FALSE,
    grants_access     BOOLEAN      NOT NULL DEFAULT FALSE,  -- licensed functionality allowed
    is_expired_state  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_grace_state    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_blocked_state  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system         BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order     INTEGER      NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_licensing_statuses PRIMARY KEY (id),
    CONSTRAINT uq_licensing_statuses_scope_code UNIQUE (scope, code),
    CONSTRAINT ck_licensing_statuses_scope CHECK (scope IN ('LICENSE', 'TENANT', 'PLAN'))
);
CREATE UNIQUE INDEX uq_licensing_statuses_default ON licensing_statuses (scope) WHERE is_default;

INSERT INTO licensing_statuses (scope, code, name, is_default, grants_access, is_expired_state, is_grace_state, is_blocked_state, is_system, display_order) VALUES
    ('LICENSE', 'draft',        'Draft',        TRUE,  FALSE, FALSE, FALSE, FALSE, TRUE, 10),
    ('LICENSE', 'active',       'Active',       FALSE, TRUE,  FALSE, FALSE, FALSE, TRUE, 20),
    ('LICENSE', 'grace-period', 'Grace Period', FALSE, TRUE,  FALSE, TRUE,  FALSE, TRUE, 30),
    ('LICENSE', 'expired',      'Expired',      FALSE, FALSE, TRUE,  FALSE, FALSE, TRUE, 40),
    ('LICENSE', 'suspended',    'Suspended',    FALSE, FALSE, FALSE, FALSE, TRUE,  TRUE, 50),
    ('LICENSE', 'cancelled',    'Cancelled',    FALSE, FALSE, FALSE, FALSE, TRUE,  TRUE, 60),
    ('LICENSE', 'blocked',      'Blocked',      FALSE, FALSE, FALSE, FALSE, TRUE,  TRUE, 70),
    ('TENANT',  'draft',        'Draft',        TRUE,  FALSE, FALSE, FALSE, FALSE, TRUE, 10),
    ('TENANT',  'active',       'Active',       FALSE, TRUE,  FALSE, FALSE, FALSE, TRUE, 20),
    ('TENANT',  'suspended',    'Suspended',    FALSE, FALSE, FALSE, FALSE, TRUE,  TRUE, 30),
    ('PLAN',    'draft',        'Draft',        TRUE,  FALSE, FALSE, FALSE, FALSE, TRUE, 10),
    ('PLAN',    'active',       'Active',       FALSE, TRUE,  FALSE, FALSE, FALSE, TRUE, 20),
    ('PLAN',    'retired',      'Retired',      FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 30);

-- Configurable license types (on-premise / cloud / trial / perpetual …).
CREATE TABLE license_types (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    description   VARCHAR(255),
    requires_online_validation BOOLEAN NOT NULL DEFAULT FALSE,
    is_default    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_license_types PRIMARY KEY (id),
    CONSTRAINT uq_license_types_code UNIQUE (code)
);
CREATE UNIQUE INDEX uq_license_types_default ON license_types (is_default) WHERE is_default;

INSERT INTO license_types (code, name, description, requires_online_validation, is_default, is_system, display_order) VALUES
    ('on-premise', 'On-Premise', 'Installed at the customer site; validated offline', FALSE, TRUE,  TRUE, 10),
    ('cloud',      'Cloud SaaS', 'Hosted multi-tenant subscription',                  TRUE,  FALSE, TRUE, 20),
    ('trial',      'Trial',      'Time-limited evaluation licence',                   FALSE, FALSE, TRUE, 30),
    ('perpetual',  'Perpetual',  'Never expires; features fixed at purchase',         FALSE, FALSE, TRUE, 40);

-- Behaviour applied once a licence lapses. The code resolves to an
-- ExpiryBehaviorHandler bean, so new behaviours are plugins, not schema changes.
-- Business data is never mutated by any of these — they only gate access.
CREATE TABLE expiry_behaviors (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    description   VARCHAR(255),
    is_default    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_expiry_behaviors PRIMARY KEY (id),
    CONSTRAINT uq_expiry_behaviors_code UNIQUE (code)
);
CREATE UNIQUE INDEX uq_expiry_behaviors_default ON expiry_behaviors (is_default) WHERE is_default;

INSERT INTO expiry_behaviors (code, name, description, is_default, is_system, display_order) VALUES
    ('grace',     'Grace Period', 'Full access for a configured grace window after expiry', TRUE,  TRUE, 10),
    ('read-only', 'Read Only',    'Reads allowed, writes rejected',                          FALSE, TRUE, 20),
    ('limited',   'Limited Access', 'Only features flagged as core remain available',        FALSE, TRUE, 30),
    ('blocked',   'Fully Blocked', 'All licensed functionality rejected',                    FALSE, TRUE, 40);

-- Configurable catalogue of measurable limits. A UsageMeterProvider bean supplies
-- the current value for each code, so the core never counts business data itself.
CREATE TABLE usage_limit_types (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    unit          VARCHAR(32)  NOT NULL DEFAULT 'count',
    description   VARCHAR(255),
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_usage_limit_types PRIMARY KEY (id),
    CONSTRAINT uq_usage_limit_types_code UNIQUE (code)
);

INSERT INTO usage_limit_types (code, name, unit, description, is_system, display_order) VALUES
    ('max-users',      'Maximum Users',        'count', 'Active user accounts',        TRUE, 10),
    ('max-companies',  'Company Count',        'count', 'Companies in the tenant',     TRUE, 20),
    ('max-branches',   'Branch Count',         'count', 'Branches in the tenant',      TRUE, 30),
    ('storage-mb',     'Storage Limit',        'MB',    'Stored file volume',          TRUE, 40),
    ('api-calls',      'API Calls',            'count', 'API calls per period',        TRUE, 50),
    ('transactions',   'Transaction Volume',   'count', 'Business transactions',       TRUE, 60),
    ('documents',      'Document Count',       'count', 'Generated/stored documents',  TRUE, 70),
    ('retention-days', 'Data Retention Period','days',  'Historical data retention',   TRUE, 80);

-- Tenants (the SaaS isolation root). On-premise installs run a single tenant.
CREATE TABLE tenants (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(160) NOT NULL,
    description   VARCHAR(2000),
    status_id     BIGINT       NOT NULL,
    contact_email VARCHAR(255),
    config        JSONB        NOT NULL DEFAULT '{}'::jsonb,
    activated_at  TIMESTAMPTZ,
    suspended_at  TIMESTAMPTZ,
    created_by    BIGINT,
    created_by_email VARCHAR(255),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_tenants PRIMARY KEY (id),
    CONSTRAINT uq_tenants_code UNIQUE (code),
    CONSTRAINT fk_tenants_status FOREIGN KEY (status_id) REFERENCES licensing_statuses (id)
);

-- Feature catalogue: the unit business modules gate on.
CREATE TABLE features (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code             VARCHAR(128) NOT NULL,
    name             VARCHAR(160) NOT NULL,
    description      VARCHAR(1000),
    module_code      VARCHAR(64),
    license_required BOOLEAN      NOT NULL DEFAULT TRUE,
    is_core          BOOLEAN      NOT NULL DEFAULT FALSE,  -- survives 'limited' expiry mode
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    is_system        BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order    INTEGER      NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_features PRIMARY KEY (id),
    CONSTRAINT uq_features_code UNIQUE (code)
);
CREATE INDEX idx_features_module ON features (module_code);

-- Feature dependency graph (validated to reject cycles / missing prerequisites).
CREATE TABLE feature_dependencies (
    feature_id    BIGINT NOT NULL,
    depends_on_id BIGINT NOT NULL,
    CONSTRAINT pk_feature_dependencies PRIMARY KEY (feature_id, depends_on_id),
    CONSTRAINT fk_feature_dep_feature FOREIGN KEY (feature_id) REFERENCES features (id) ON DELETE CASCADE,
    CONSTRAINT fk_feature_dep_target  FOREIGN KEY (depends_on_id) REFERENCES features (id) ON DELETE CASCADE,
    CONSTRAINT ck_feature_dep_self CHECK (feature_id <> depends_on_id)
);

INSERT INTO features (code, name, description, module_code, license_required, is_core, is_system, display_order) VALUES
    ('core.access',            'Core Access',             'Baseline ERP access',                 NULL,         FALSE, TRUE,  TRUE, 10),
    ('products.catalogue',     'Product Catalogue',       'Product master data',                 'products',   TRUE,  TRUE,  TRUE, 20),
    ('crm.customers',          'Customer Management',     'CRM customer 360',                    'customers',  TRUE,  TRUE,  TRUE, 30),
    ('crm.segments',           'Customer Segments',       'Saved segments and marketing lists',  'customers',  TRUE,  FALSE, TRUE, 40),
    ('suppliers.management',   'Supplier Management',     'Supplier registry and evaluation',    'suppliers',  TRUE,  TRUE,  TRUE, 50),
    ('purchasing.workflow',    'Purchasing Workflow',     'Purchase approval and receiving',     'purchasing', TRUE,  TRUE,  TRUE, 60),
    ('dashboards.executive',   'Executive Dashboards',    'Dashboards, KPIs and cockpit',        'dashboards', TRUE,  FALSE, TRUE, 70),
    ('automation.engine',      'Process Automation',      'Business process automation rules',   'automation', TRUE,  FALSE, TRUE, 80),
    ('inventory.advanced',     'Advanced Inventory',      'Advanced inventory operations',       'inventory',  TRUE,  FALSE, TRUE, 90);

INSERT INTO feature_dependencies (feature_id, depends_on_id)
SELECT f.id, d.id FROM features f, features d
WHERE (f.code, d.code) IN (
    ('crm.segments',        'crm.customers'),
    ('purchasing.workflow', 'suppliers.management'),
    ('automation.engine',   'core.access'),
    ('inventory.advanced',  'products.catalogue')
);

-- Subscription plans (configurable bundles of features + limits).
CREATE TABLE subscription_plans (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code            VARCHAR(64)  NOT NULL,
    name            VARCHAR(160) NOT NULL,
    description     VARCHAR(2000),
    status_id       BIGINT       NOT NULL,
    duration_days   INTEGER      NOT NULL DEFAULT 365,
    renewal_policy  VARCHAR(32)  NOT NULL DEFAULT 'MANUAL',  -- MANUAL | AUTO | NONE
    price_config    JSONB        NOT NULL DEFAULT '{}'::jsonb,
    is_default      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system       BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order   INTEGER      NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_subscription_plans PRIMARY KEY (id),
    CONSTRAINT uq_subscription_plans_code UNIQUE (code),
    CONSTRAINT fk_subscription_plans_status FOREIGN KEY (status_id) REFERENCES licensing_statuses (id)
);
CREATE UNIQUE INDEX uq_subscription_plans_default ON subscription_plans (is_default) WHERE is_default;

CREATE TABLE plan_features (
    plan_id    BIGINT NOT NULL,
    feature_id BIGINT NOT NULL,
    CONSTRAINT pk_plan_features PRIMARY KEY (plan_id, feature_id),
    CONSTRAINT fk_plan_features_plan    FOREIGN KEY (plan_id) REFERENCES subscription_plans (id) ON DELETE CASCADE,
    CONSTRAINT fk_plan_features_feature FOREIGN KEY (feature_id) REFERENCES features (id) ON DELETE CASCADE
);

CREATE TABLE plan_limits (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    plan_id       BIGINT NOT NULL,
    limit_type_id BIGINT NOT NULL,
    limit_value   BIGINT NOT NULL,          -- -1 = unlimited
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    version       BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT pk_plan_limits PRIMARY KEY (id),
    CONSTRAINT uq_plan_limits UNIQUE (plan_id, limit_type_id),
    CONSTRAINT fk_plan_limits_plan  FOREIGN KEY (plan_id) REFERENCES subscription_plans (id) ON DELETE CASCADE,
    CONSTRAINT fk_plan_limits_type  FOREIGN KEY (limit_type_id) REFERENCES usage_limit_types (id)
);

INSERT INTO subscription_plans (code, name, description, status_id, duration_days, renewal_policy, is_default, is_system, display_order)
SELECT p.code, p.name, p.description, s.id, p.days, p.policy, p.is_default, TRUE, p.ord
FROM (VALUES
    ('basic',        'Basic',        'Core ERP for a single shop',          365, 'MANUAL', TRUE,  10),
    ('professional', 'Professional', 'Multi-branch retail with dashboards', 365, 'AUTO',   FALSE, 20),
    ('enterprise',   'Enterprise',   'Full platform incl. automation',      365, 'AUTO',   FALSE, 30),
    ('custom',       'Custom',       'Negotiated feature/limit set',        365, 'MANUAL', FALSE, 40)
) AS p(code, name, description, days, policy, is_default, ord)
JOIN licensing_statuses s ON s.scope = 'PLAN' AND s.code = 'active';

-- Plan → feature bundles.
INSERT INTO plan_features (plan_id, feature_id)
SELECT p.id, f.id FROM subscription_plans p, features f
WHERE (p.code = 'basic'        AND f.code IN ('core.access','products.catalogue','crm.customers','suppliers.management'))
   OR (p.code = 'professional' AND f.code IN ('core.access','products.catalogue','crm.customers','crm.segments','suppliers.management','purchasing.workflow','dashboards.executive'))
   OR (p.code = 'enterprise'   AND f.code IN ('core.access','products.catalogue','crm.customers','crm.segments','suppliers.management','purchasing.workflow','dashboards.executive','automation.engine','inventory.advanced'))
   OR (p.code = 'custom'       AND f.code = 'core.access');

-- Plan → limits (-1 = unlimited).
INSERT INTO plan_limits (plan_id, limit_type_id, limit_value)
SELECT p.id, t.id, v.limit_value
FROM (VALUES
    ('basic',        'max-users',      5),
    ('basic',        'max-companies',  1),
    ('basic',        'max-branches',   1),
    ('basic',        'storage-mb',     1024),
    ('professional', 'max-users',      25),
    ('professional', 'max-companies',  3),
    ('professional', 'max-branches',   10),
    ('professional', 'storage-mb',     10240),
    ('enterprise',   'max-users',      -1),
    ('enterprise',   'max-companies',  -1),
    ('enterprise',   'max-branches',   -1),
    ('enterprise',   'storage-mb',     -1)
) AS v(plan_code, limit_code, limit_value)
JOIN subscription_plans p ON p.code = v.plan_code
JOIN usage_limit_types  t ON t.code = v.limit_code;

-- The licence itself.
CREATE TABLE licenses (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    license_key            VARCHAR(255) NOT NULL,
    code                   VARCHAR(64)  NOT NULL,
    license_type_id        BIGINT       NOT NULL,
    tenant_id              BIGINT       NOT NULL,
    company_id             BIGINT,                    -- null = shared by all companies in the tenant
    status_id              BIGINT       NOT NULL,
    plan_id                BIGINT       NOT NULL,
    expiry_behavior_id     BIGINT,
    activation_date        TIMESTAMPTZ,
    expiration_date        TIMESTAMPTZ,
    grace_days             INTEGER      NOT NULL DEFAULT 0,
    activated_at           TIMESTAMPTZ,
    activation_fingerprint VARCHAR(255),              -- blocks duplicate/foreign activation
    limit_overrides        JSONB        NOT NULL DEFAULT '{}'::jsonb,
    notes                  VARCHAR(2000),
    created_by             BIGINT,
    created_by_email       VARCHAR(255),
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version                BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_licenses PRIMARY KEY (id),
    CONSTRAINT uq_licenses_key  UNIQUE (license_key),
    CONSTRAINT uq_licenses_code UNIQUE (code),
    CONSTRAINT fk_licenses_type     FOREIGN KEY (license_type_id) REFERENCES license_types (id),
    CONSTRAINT fk_licenses_tenant   FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_licenses_status   FOREIGN KEY (status_id) REFERENCES licensing_statuses (id),
    CONSTRAINT fk_licenses_plan     FOREIGN KEY (plan_id) REFERENCES subscription_plans (id),
    CONSTRAINT fk_licenses_behavior FOREIGN KEY (expiry_behavior_id) REFERENCES expiry_behaviors (id)
);
CREATE INDEX idx_licenses_tenant  ON licenses (tenant_id);
CREATE INDEX idx_licenses_status  ON licenses (status_id);
CREATE INDEX idx_licenses_expiry  ON licenses (expiration_date);

-- Per-licence feature overrides: enable/disable without touching the plan and
-- without a deployment or restart.
CREATE TABLE license_features (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    license_id BIGINT  NOT NULL,
    feature_id BIGINT  NOT NULL,
    enabled    BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version    BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT pk_license_features PRIMARY KEY (id),
    CONSTRAINT uq_license_features UNIQUE (license_id, feature_id),
    CONSTRAINT fk_license_features_license FOREIGN KEY (license_id) REFERENCES licenses (id) ON DELETE CASCADE,
    CONSTRAINT fk_license_features_feature FOREIGN KEY (feature_id) REFERENCES features (id) ON DELETE CASCADE
);

-- Measured usage per tenant/limit/period (period_key '' = lifetime counter).
CREATE TABLE usage_counters (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tenant_id     BIGINT      NOT NULL,
    limit_type_id BIGINT      NOT NULL,
    period_key    VARCHAR(32) NOT NULL DEFAULT '',
    current_value BIGINT      NOT NULL DEFAULT 0,
    recorded_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    version       BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT pk_usage_counters PRIMARY KEY (id),
    CONSTRAINT uq_usage_counters UNIQUE (tenant_id, limit_type_id, period_key),
    CONSTRAINT fk_usage_counters_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT fk_usage_counters_type   FOREIGN KEY (limit_type_id) REFERENCES usage_limit_types (id)
);

-- Append-only audit trail (old/new snapshots).
CREATE TABLE license_audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    entity_type VARCHAR(32)  NOT NULL,   -- LICENSE | TENANT | PLAN | FEATURE | USAGE
    entity_id   BIGINT,
    action      VARCHAR(64)  NOT NULL,
    old_values  JSONB,
    new_values  JSONB,
    actor_id    BIGINT,
    actor_email VARCHAR(255),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_license_audit_log PRIMARY KEY (id)
);
CREATE INDEX idx_license_audit_entity ON license_audit_log (entity_type, entity_id);

-- Module + granular permissions.
INSERT INTO modules (code, name, description, icon, path, display_order, enabled, is_system)
VALUES ('licensing', 'Licensing', 'Licences, tenants, subscription plans and feature flags',
        'mdi-certificate-outline', '/licensing', 120, TRUE, TRUE);

INSERT INTO permissions (module_id, action, code, name, is_system)
SELECT m.id, a.action, m.code || ':' || a.action, m.name || ' — ' || a.label, TRUE
FROM modules m
CROSS JOIN (VALUES
    ('view',             'View licences'),
    ('create',           'Create licences'),
    ('edit',             'Edit licences'),
    ('delete',           'Delete licences'),
    ('activate',         'Activate licences'),
    ('renew',            'Renew subscriptions'),
    ('manage-tenants',   'Manage tenants'),
    ('manage-plans',     'Manage subscription plans'),
    ('manage-features',  'Manage feature flags'),
    ('view-usage',       'View usage'),
    ('export',           'Export licence reports')
) AS a(action, label)
WHERE m.code = 'licensing';
