-- Data Quality & Validation Management — enterprise data governance for the whole
-- ERP. Business modules never implement validation logic: they submit an entity
-- payload and this module evaluates the configured rules. A rule is data
-- (validation_type + JSON config + condition tree); the validators, duplicate
-- matchers and candidate providers behind them are plugin beans, so new rule
-- kinds and dimensions never require a core change.

-- Configurable rule lifecycle statuses.
CREATE TABLE quality_statuses (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code              VARCHAR(64)  NOT NULL,
    name              VARCHAR(100) NOT NULL,
    is_default        BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active_state   BOOLEAN      NOT NULL DEFAULT FALSE,   -- rule participates in validation
    is_archived_state BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system         BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order     INTEGER      NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_quality_statuses PRIMARY KEY (id),
    CONSTRAINT uq_quality_statuses_code UNIQUE (code)
);
CREATE UNIQUE INDEX uq_quality_statuses_default  ON quality_statuses (is_default)        WHERE is_default;
CREATE UNIQUE INDEX uq_quality_statuses_archived ON quality_statuses (is_archived_state) WHERE is_archived_state;

INSERT INTO quality_statuses (code, name, is_default, is_active_state, is_archived_state, is_system, display_order) VALUES
    ('draft',    'Draft',    TRUE,  FALSE, FALSE, TRUE, 10),
    ('testing',  'Testing',  FALSE, FALSE, FALSE, TRUE, 20),
    ('active',   'Active',   FALSE, TRUE,  FALSE, TRUE, 30),
    ('disabled', 'Disabled', FALSE, FALSE, FALSE, TRUE, 40),
    ('archived', 'Archived', FALSE, FALSE, TRUE,  TRUE, 50);

-- Configurable severities. `blocks_save` lets a caller reject a payload outright.
CREATE TABLE quality_severities (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    weight        NUMERIC(6,2) NOT NULL DEFAULT 1,   -- score penalty multiplier
    blocks_save   BOOLEAN      NOT NULL DEFAULT FALSE,
    is_default    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_quality_severities PRIMARY KEY (id),
    CONSTRAINT uq_quality_severities_code UNIQUE (code)
);
CREATE UNIQUE INDEX uq_quality_severities_default ON quality_severities (is_default) WHERE is_default;

INSERT INTO quality_severities (code, name, weight, blocks_save, is_default, is_system, display_order) VALUES
    ('info',     'Info',     0.25, FALSE, FALSE, TRUE, 10),
    ('warning',  'Warning',  1.00, FALSE, TRUE,  TRUE, 20),
    ('error',    'Error',    3.00, TRUE,  FALSE, TRUE, 30),
    ('critical', 'Critical', 6.00, TRUE,  FALSE, TRUE, 40);

-- Configurable quality dimensions with scoring weights.
CREATE TABLE quality_dimensions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    description   VARCHAR(255),
    weight        NUMERIC(6,2) NOT NULL DEFAULT 1,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_quality_dimensions PRIMARY KEY (id),
    CONSTRAINT uq_quality_dimensions_code UNIQUE (code)
);

INSERT INTO quality_dimensions (code, name, description, weight, is_system, display_order) VALUES
    ('completeness', 'Completeness', 'Required data is present',              1.5, TRUE, 10),
    ('accuracy',     'Accuracy',     'Values reflect reality',                1.5, TRUE, 20),
    ('consistency',  'Consistency',  'Values agree across records',           1.0, TRUE, 30),
    ('validity',     'Validity',     'Values conform to format/domain rules', 1.5, TRUE, 40),
    ('uniqueness',   'Uniqueness',   'No unintended duplicates',              2.0, TRUE, 50),
    ('timeliness',   'Timeliness',   'Data is current',                       1.0, TRUE, 60),
    ('integrity',    'Integrity',    'References resolve correctly',          1.5, TRUE, 70),
    ('availability', 'Availability', 'Data is reachable when needed',         0.5, TRUE, 80);

-- Configurable score bands (Excellent … Critical).
CREATE TABLE quality_score_bands (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    min_score     NUMERIC(6,2) NOT NULL,
    color         VARCHAR(32),
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_quality_score_bands PRIMARY KEY (id),
    CONSTRAINT uq_quality_score_bands_code UNIQUE (code)
);

INSERT INTO quality_score_bands (code, name, min_score, color, is_system, display_order) VALUES
    ('excellent',  'Excellent',  95, '#2E7D5B', TRUE, 10),
    ('good',       'Good',       85, '#4CAF50', TRUE, 20),
    ('acceptable', 'Acceptable', 70, '#B27A1B', TRUE, 30),
    ('poor',       'Poor',       50, '#E07A3F', TRUE, 40),
    ('critical',   'Critical',    0, '#C0453C', TRUE, 50);

-- The rule: configuration only. `validation_type` resolves to a ValidationRule
-- bean; `config` carries its parameters; `condition_config` makes the rule
-- conditional; `weight` feeds the score.
CREATE TABLE quality_rules (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code             VARCHAR(64)  NOT NULL,
    name             VARCHAR(160) NOT NULL,
    description      VARCHAR(2000),
    module_code      VARCHAR(64)  NOT NULL,
    entity_code      VARCHAR(64)  NOT NULL,
    category         VARCHAR(64),
    priority         INTEGER      NOT NULL DEFAULT 100,
    status_id        BIGINT       NOT NULL,
    severity_id      BIGINT       NOT NULL,
    dimension_id     BIGINT,
    validation_type  VARCHAR(128) NOT NULL,
    target_field     VARCHAR(128),
    config           JSONB        NOT NULL DEFAULT '{}'::jsonb,
    condition_config JSONB        NOT NULL DEFAULT '{}'::jsonb,
    weight           NUMERIC(6,2) NOT NULL DEFAULT 1,
    company_id       BIGINT,
    tenant_id        BIGINT,
    created_by       BIGINT,
    created_by_email VARCHAR(255),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_quality_rules PRIMARY KEY (id),
    CONSTRAINT uq_quality_rules_code UNIQUE (code),
    CONSTRAINT fk_quality_rules_status    FOREIGN KEY (status_id) REFERENCES quality_statuses (id),
    CONSTRAINT fk_quality_rules_severity  FOREIGN KEY (severity_id) REFERENCES quality_severities (id),
    CONSTRAINT fk_quality_rules_dimension FOREIGN KEY (dimension_id) REFERENCES quality_dimensions (id)
);
CREATE INDEX idx_quality_rules_target ON quality_rules (module_code, entity_code);
CREATE INDEX idx_quality_rules_status ON quality_rules (status_id);

-- One validation run over one entity instance (or a batch item).
CREATE TABLE validation_runs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    run_number     VARCHAR(40)  NOT NULL,
    module_code    VARCHAR(64)  NOT NULL,
    entity_code    VARCHAR(64)  NOT NULL,
    entity_id      BIGINT,
    status         VARCHAR(32)  NOT NULL,    -- PASSED | FAILED
    rule_count     INTEGER      NOT NULL DEFAULT 0,
    passed_count   INTEGER      NOT NULL DEFAULT 0,
    failed_count   INTEGER      NOT NULL DEFAULT 0,
    score          NUMERIC(6,2),
    band_code      VARCHAR(64),
    blocking       BOOLEAN      NOT NULL DEFAULT FALSE,
    payload        JSONB,
    started_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    ended_at       TIMESTAMPTZ,
    duration_ms    BIGINT,
    executed_by    BIGINT,
    executed_by_email VARCHAR(255),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_validation_runs PRIMARY KEY (id),
    CONSTRAINT uq_validation_runs_number UNIQUE (run_number)
);
CREATE INDEX idx_validation_runs_target ON validation_runs (module_code, entity_code, entity_id);
CREATE INDEX idx_validation_runs_started ON validation_runs (started_at DESC);

CREATE SEQUENCE validation_run_seq START 1;

-- A detected problem. Append-only until explicitly resolved/ignored.
CREATE TABLE quality_issues (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    run_id          BIGINT,
    rule_id         BIGINT,
    module_code     VARCHAR(64)  NOT NULL,
    entity_code     VARCHAR(64)  NOT NULL,
    entity_id       BIGINT,
    field_name      VARCHAR(128),
    severity_code   VARCHAR(64)  NOT NULL,
    dimension_code  VARCHAR(64),
    message         VARCHAR(1000) NOT NULL,
    detail          JSONB,
    status          VARCHAR(32)  NOT NULL DEFAULT 'OPEN',  -- OPEN | RESOLVED | IGNORED
    resolution_note VARCHAR(1000),
    resolved_at     TIMESTAMPTZ,
    resolved_by     BIGINT,
    resolved_by_email VARCHAR(255),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_quality_issues PRIMARY KEY (id),
    CONSTRAINT fk_quality_issues_run  FOREIGN KEY (run_id) REFERENCES validation_runs (id) ON DELETE SET NULL,
    CONSTRAINT fk_quality_issues_rule FOREIGN KEY (rule_id) REFERENCES quality_rules (id) ON DELETE SET NULL
);
CREATE INDEX idx_quality_issues_target ON quality_issues (module_code, entity_code, entity_id);
CREATE INDEX idx_quality_issues_status ON quality_issues (status, severity_code);

-- A correction applied to fix an issue (manual or automatic).
CREATE TABLE quality_corrections (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    issue_id       BIGINT       NOT NULL,
    field_name     VARCHAR(128),
    old_value      VARCHAR(2000),
    new_value      VARCHAR(2000),
    automatic      BOOLEAN      NOT NULL DEFAULT FALSE,
    note           VARCHAR(1000),
    applied_by     BIGINT,
    applied_by_email VARCHAR(255),
    applied_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_quality_corrections PRIMARY KEY (id),
    CONSTRAINT fk_quality_corrections_issue FOREIGN KEY (issue_id) REFERENCES quality_issues (id) ON DELETE CASCADE
);

-- Historical scores per module/entity/dimension for trend analysis.
CREATE TABLE quality_scores (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    module_code    VARCHAR(64)  NOT NULL,
    entity_code    VARCHAR(64)  NOT NULL,
    dimension_code VARCHAR(64),
    score          NUMERIC(6,2) NOT NULL,
    band_code      VARCHAR(64),
    sample_size    INTEGER      NOT NULL DEFAULT 0,
    detail         JSONB,
    computed_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_quality_scores PRIMARY KEY (id)
);
CREATE INDEX idx_quality_scores_target ON quality_scores (module_code, entity_code, computed_at DESC);

-- Append-only audit trail.
CREATE TABLE quality_audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    entity_type VARCHAR(32)  NOT NULL,   -- RULE | ISSUE | CORRECTION | RUN
    entity_id   BIGINT,
    action      VARCHAR(64)  NOT NULL,
    old_values  JSONB,
    new_values  JSONB,
    actor_id    BIGINT,
    actor_email VARCHAR(255),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_quality_audit_log PRIMARY KEY (id)
);
CREATE INDEX idx_quality_audit_entity ON quality_audit_log (entity_type, entity_id);

-- Seeded rules — configuration, not code. These cover the mobile-retail
-- specifics (IMEI, Iranian national ID and mobile numbers) and basic hygiene.
INSERT INTO quality_rules (code, name, description, module_code, entity_code, category,
                           priority, status_id, severity_id, dimension_id, validation_type,
                           target_field, config, weight)
SELECT r.code, r.name, r.description, r.module_code, r.entity_code, r.category, r.priority,
       st.id, sv.id, dim.id, r.validation_type, r.target_field, r.config::jsonb, r.weight
FROM (VALUES
    ('cust-name-required', 'Customer display name required', 'Every customer must have a display name',
     'crm', 'customer', 'completeness', 10, 'error', 'completeness', 'required', 'displayName', '{}', 2.0),
    ('cust-national-id',   'Customer national ID valid', 'Iranian national ID checksum must be valid',
     'crm', 'customer', 'validity', 20, 'error', 'validity', 'national-id', 'nationalCode', '{}', 2.0),
    ('cust-mobile',        'Customer mobile valid', 'Iranian mobile number format',
     'crm', 'customer', 'validity', 30, 'warning', 'validity', 'phone', 'mobile', '{}', 1.0),
    ('cust-email',         'Customer email valid', 'Email address format',
     'crm', 'customer', 'validity', 40, 'warning', 'validity', 'email', 'email', '{}', 1.0),
    ('cust-duplicate',     'Duplicate customer detection', 'Fuzzy duplicate detection on display name',
     'crm', 'customer', 'uniqueness', 50, 'warning', 'uniqueness', 'duplicate', 'displayName',
     '{"strategy":"fuzzy","threshold":0.9}', 3.0),
    ('prod-sku-required',  'Product SKU required', 'Every product must have a SKU',
     'products', 'product', 'completeness', 10, 'error', 'completeness', 'required', 'sku', '{}', 2.0),
    ('prod-price-range',   'Product price non-negative', 'Price must be zero or greater',
     'products', 'product', 'validity', 20, 'error', 'validity', 'range', 'price', '{"min":0}', 2.0),
    ('prod-imei',          'Product IMEI valid', 'IMEI must pass the Luhn check',
     'products', 'product', 'validity', 30, 'critical', 'validity', 'imei', 'imei', '{}', 3.0),
    ('prod-imei-unique',   'IMEI must be unique', 'The same IMEI may never be registered twice',
     'products', 'product', 'uniqueness', 40, 'critical', 'uniqueness', 'duplicate', 'imei',
     '{"strategy":"exact"}', 4.0),
    ('sup-name-required',  'Supplier company name required', 'Suppliers must have a company name',
     'suppliers', 'supplier', 'completeness', 10, 'error', 'completeness', 'required', 'companyName', '{}', 2.0)
) AS r(code, name, description, module_code, entity_code, category, priority,
       severity_code, dimension_code, validation_type, target_field, config, weight)
JOIN quality_statuses   st  ON st.code  = 'active'
JOIN quality_severities sv  ON sv.code  = r.severity_code
JOIN quality_dimensions dim ON dim.code = r.dimension_code;

-- Module + granular permissions.
INSERT INTO modules (code, name, description, icon, path, display_order, enabled, is_system)
VALUES ('data-quality', 'Data Quality', 'Data quality rules, validation, issues and scoring',
        'mdi-shield-check-outline', '/data-quality', 130, TRUE, TRUE);

INSERT INTO permissions (module_id, action, code, name, is_system)
SELECT m.id, a.action, m.code || ':' || a.action, m.name || ' — ' || a.label, TRUE
FROM modules m
CROSS JOIN (VALUES
    ('view',                'View quality rules'),
    ('create',              'Create quality rules'),
    ('edit',                'Edit quality rules'),
    ('delete',              'Delete quality rules'),
    ('execute',             'Execute validation'),
    ('resolve',             'Resolve issues'),
    ('manage-corrections',  'Manage automatic corrections'),
    ('export',              'Export quality reports')
) AS a(action, label)
WHERE m.code = 'data-quality';
