-- Licensing lifecycle extensions: feature states, billing cycle & payment
-- status, activation modes (online / offline / emergency), auto-renewal,
-- licence transfer and integration limits. Additive to V12 — all new behaviour
-- is again expressed as configurable rows plus plugin keys.

-- Feature lifecycle states. `grants_access` decides whether the gate may pass;
-- the other flags drive trial windows, beta opt-in, catalogue visibility and
-- deprecation warnings. New states are rows.
CREATE TABLE feature_states (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code           VARCHAR(64)  NOT NULL,
    name           VARCHAR(100) NOT NULL,
    description    VARCHAR(255),
    grants_access  BOOLEAN      NOT NULL DEFAULT FALSE,
    requires_optin BOOLEAN      NOT NULL DEFAULT FALSE,  -- beta: tenant must opt in
    is_trial       BOOLEAN      NOT NULL DEFAULT FALSE,  -- time-boxed by trial_days
    is_premium     BOOLEAN      NOT NULL DEFAULT FALSE,  -- must be in the plan bundle
    is_deprecated  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_hidden      BOOLEAN      NOT NULL DEFAULT FALSE,  -- omitted from catalogues
    is_default     BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system      BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order  INTEGER      NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_feature_states PRIMARY KEY (id),
    CONSTRAINT uq_feature_states_code UNIQUE (code)
);
CREATE UNIQUE INDEX uq_feature_states_default ON feature_states (is_default) WHERE is_default;

INSERT INTO feature_states (code, name, description, grants_access, requires_optin, is_trial, is_premium, is_deprecated, is_hidden, is_default, is_system, display_order) VALUES
    ('enabled',    'Enabled',    'Generally available',                       TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  TRUE, 10),
    ('disabled',   'Disabled',   'Switched off for everyone',                 FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 20),
    ('trial',      'Trial',      'Available for a limited trial window',      TRUE,  FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, TRUE, 30),
    ('beta',       'Beta',       'Available to tenants that opt in',          TRUE,  TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 40),
    ('premium',    'Premium',    'Requires the feature in the plan bundle',   TRUE,  FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, TRUE, 50),
    ('deprecated', 'Deprecated', 'Still works; scheduled for removal',        TRUE,  FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, TRUE, 60),
    ('hidden',     'Hidden',     'Internal only; never advertised or granted', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, TRUE, 70);

ALTER TABLE features ADD COLUMN state_id   BIGINT;
ALTER TABLE features ADD COLUMN trial_days INTEGER NOT NULL DEFAULT 0;
UPDATE features SET state_id = (SELECT id FROM feature_states WHERE code = 'enabled');
ALTER TABLE features ALTER COLUMN state_id SET NOT NULL;
ALTER TABLE features ADD CONSTRAINT fk_features_state FOREIGN KEY (state_id) REFERENCES feature_states (id);
-- Advanced inventory ships as a 30-day trial to demonstrate the trial window.
UPDATE features SET state_id = (SELECT id FROM feature_states WHERE code = 'trial'), trial_days = 30
WHERE code = 'inventory.advanced';

-- Configurable billing cycles.
CREATE TABLE billing_cycles (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    months        INTEGER      NOT NULL DEFAULT 12,
    is_default    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_billing_cycles PRIMARY KEY (id),
    CONSTRAINT uq_billing_cycles_code UNIQUE (code)
);
CREATE UNIQUE INDEX uq_billing_cycles_default ON billing_cycles (is_default) WHERE is_default;

INSERT INTO billing_cycles (code, name, months, is_default, is_system, display_order) VALUES
    ('monthly',   'Monthly',      1,  FALSE, TRUE, 10),
    ('quarterly', 'Quarterly',    3,  FALSE, TRUE, 20),
    ('biannual',  'Semi-annual',  6,  FALSE, TRUE, 30),
    ('yearly',    'Yearly',       12, TRUE,  TRUE, 40),
    ('one-time',  'One-time',     0,  FALSE, TRUE, 50);

ALTER TABLE subscription_plans ADD COLUMN billing_cycle_id BIGINT;
UPDATE subscription_plans SET billing_cycle_id = (SELECT id FROM billing_cycles WHERE code = 'yearly');
ALTER TABLE subscription_plans
    ADD CONSTRAINT fk_subscription_plans_cycle FOREIGN KEY (billing_cycle_id) REFERENCES billing_cycles (id);

-- Configurable payment status. `blocks_access` lets unpaid subscriptions gate
-- functionality without deleting or corrupting any business data.
CREATE TABLE payment_statuses (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    blocks_access BOOLEAN      NOT NULL DEFAULT FALSE,
    is_default    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_payment_statuses PRIMARY KEY (id),
    CONSTRAINT uq_payment_statuses_code UNIQUE (code)
);
CREATE UNIQUE INDEX uq_payment_statuses_default ON payment_statuses (is_default) WHERE is_default;

INSERT INTO payment_statuses (code, name, blocks_access, is_default, is_system, display_order) VALUES
    ('trial',    'Trial',    FALSE, FALSE, TRUE, 10),
    ('pending',  'Pending',  FALSE, TRUE,  TRUE, 20),
    ('paid',     'Paid',     FALSE, FALSE, TRUE, 30),
    ('overdue',  'Overdue',  TRUE,  FALSE, TRUE, 40),
    ('refunded', 'Refunded', TRUE,  FALSE, TRUE, 50);

-- Licence lifecycle additions.
ALTER TABLE licenses ADD COLUMN payment_status_id BIGINT;
ALTER TABLE licenses ADD COLUMN auto_renew        BOOLEAN     NOT NULL DEFAULT FALSE;
ALTER TABLE licenses ADD COLUMN activation_mode   VARCHAR(32) NOT NULL DEFAULT 'MANUAL';
ALTER TABLE licenses ADD COLUMN emergency_until   TIMESTAMPTZ;
ALTER TABLE licenses ADD COLUMN transferred_at    TIMESTAMPTZ;
ALTER TABLE licenses ADD COLUMN transfer_count    INTEGER     NOT NULL DEFAULT 0;
UPDATE licenses SET payment_status_id = (SELECT id FROM payment_statuses WHERE code = 'pending');
ALTER TABLE licenses
    ADD CONSTRAINT fk_licenses_payment_status FOREIGN KEY (payment_status_id) REFERENCES payment_statuses (id);
ALTER TABLE licenses
    ADD CONSTRAINT ck_licenses_activation_mode
    CHECK (activation_mode IN ('MANUAL', 'ONLINE', 'OFFLINE', 'EMERGENCY'));

-- Append-only licence transfer history (tenant/installation moves).
CREATE TABLE license_transfers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    license_id      BIGINT      NOT NULL,
    from_tenant_id  BIGINT,
    to_tenant_id    BIGINT      NOT NULL,
    from_fingerprint VARCHAR(255),
    reason          VARCHAR(1000),
    transferred_by  BIGINT,
    transferred_by_email VARCHAR(255),
    transferred_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    version         BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT pk_license_transfers PRIMARY KEY (id),
    CONSTRAINT fk_license_transfers_license FOREIGN KEY (license_id) REFERENCES licenses (id) ON DELETE CASCADE,
    CONSTRAINT fk_license_transfers_to      FOREIGN KEY (to_tenant_id) REFERENCES tenants (id)
);
CREATE INDEX idx_license_transfers_license ON license_transfers (license_id, transferred_at DESC);

-- Integration limit type (external connections per tenant).
INSERT INTO usage_limit_types (code, name, unit, description, is_system, display_order)
VALUES ('integrations', 'Integration Limit', 'count', 'Active external integrations', TRUE, 90);

-- Additional permissions for the extended lifecycle.
INSERT INTO permissions (module_id, action, code, name, is_system)
SELECT m.id, a.action, m.code || ':' || a.action, m.name || ' — ' || a.label, TRUE
FROM modules m
CROSS JOIN (VALUES
    ('transfer',        'Transfer licences'),
    ('emergency',       'Emergency activation'),
    ('manage-billing',  'Manage billing and payment status')
) AS a(action, label)
WHERE m.code = 'licensing';
