-- =====================================================================
-- V18 — Enterprise File Storage & Media Management (module 10)
--
-- Centralised binary storage for the whole ERP. Business modules hold a
-- file reference and nothing else: no paths, no buckets, no provider
-- knowledge. See docs/documents-and-files.md.
--
-- Everything that looks like behaviour is data:
--   * storage_providers.handler_key  → StorageProvider bean
--   * file_processors.handler_key    → FileProcessor bean
--   * file_categories                → size/mime/processing rules per category
--   * file_statuses                  → lifecycle by FLAG, never by name
-- A new provider, processor, category or status is a row, not a release.
--
-- Tenancy (docs/tenancy.md): config tables are Tier S (nullable tenant_id,
-- NULL = platform default), data tables are Tier T (NOT NULL). Tier T
-- columns carry the V17 scaffold default until @TenantId enforcement ships.
-- =====================================================================


-- ---------------------------------------------------------------------
-- Configurable file lifecycle statuses.
--
-- Flags drive behaviour: a file may only be downloaded from a status with
-- allows_download, so quarantining a file makes it unservable without any
-- code path checking for the string 'quarantined'.
-- ---------------------------------------------------------------------
CREATE TABLE file_statuses (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                  VARCHAR(64)  NOT NULL,
    name                  VARCHAR(100) NOT NULL,
    is_default            BOOLEAN      NOT NULL DEFAULT FALSE,
    is_available_state    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_processing_state   BOOLEAN      NOT NULL DEFAULT FALSE,
    is_locked_state       BOOLEAN      NOT NULL DEFAULT FALSE,
    is_archived_state     BOOLEAN      NOT NULL DEFAULT FALSE,
    is_deleted_state      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_quarantined_state  BOOLEAN      NOT NULL DEFAULT FALSE,
    allows_download       BOOLEAN      NOT NULL DEFAULT FALSE,
    allows_new_version    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system             BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order         INTEGER      NOT NULL DEFAULT 0,
    tenant_id             BIGINT,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version               BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_file_statuses PRIMARY KEY (id),
    CONSTRAINT fk_file_statuses_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_file_statuses_code_global ON file_statuses (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_file_statuses_code_tenant ON file_statuses (tenant_id, code) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_file_statuses_default_global ON file_statuses ((TRUE)) WHERE is_default AND tenant_id IS NULL;
CREATE UNIQUE INDEX uq_file_statuses_default_tenant ON file_statuses (tenant_id) WHERE is_default AND tenant_id IS NOT NULL;
CREATE INDEX idx_file_statuses_tenant ON file_statuses (tenant_id);

INSERT INTO file_statuses (code, name, is_default, is_available_state, is_processing_state,
                           is_locked_state, is_archived_state, is_deleted_state, is_quarantined_state,
                           allows_download, allows_new_version, is_system, display_order) VALUES
    ('uploading',   'Uploading',   TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 10),
    ('processing',  'Processing',  FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 20),
    ('available',   'Available',   FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  TRUE,  TRUE, 30),
    ('locked',      'Locked',      FALSE, TRUE,  FALSE, TRUE,  FALSE, FALSE, FALSE, TRUE,  FALSE, TRUE, 40),
    ('quarantined', 'Quarantined', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, TRUE, 50),
    ('archived',    'Archived',    FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, TRUE,  FALSE, TRUE, 60),
    ('deleted',     'Deleted',     FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, TRUE, 70);


-- ---------------------------------------------------------------------
-- Retention policies. retain_days NULL = permanent.
-- action_on_expiry maps to a RetentionHandler bean.
-- ---------------------------------------------------------------------
CREATE TABLE retention_policies (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code               VARCHAR(64)  NOT NULL,
    name               VARCHAR(100) NOT NULL,
    retain_days        INTEGER,
    action_on_expiry   VARCHAR(64)  NOT NULL DEFAULT 'archive',
    allows_legal_hold  BOOLEAN      NOT NULL DEFAULT TRUE,
    is_default         BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system          BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order      INTEGER      NOT NULL DEFAULT 0,
    tenant_id          BIGINT,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version            BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_retention_policies PRIMARY KEY (id),
    CONSTRAINT ck_retention_action CHECK (action_on_expiry IN ('delete', 'archive', 'anonymise', 'notify')),
    CONSTRAINT fk_retention_policies_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_retention_policies_code_global ON retention_policies (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_retention_policies_code_tenant ON retention_policies (tenant_id, code) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_retention_policies_default_global ON retention_policies ((TRUE)) WHERE is_default AND tenant_id IS NULL;
CREATE UNIQUE INDEX uq_retention_policies_default_tenant ON retention_policies (tenant_id) WHERE is_default AND tenant_id IS NOT NULL;

INSERT INTO retention_policies (code, name, retain_days, action_on_expiry, allows_legal_hold, is_default, is_system, display_order) VALUES
    ('permanent',  'Permanent',      NULL, 'notify',   TRUE,  TRUE,  TRUE, 10),
    ('temporary',  'Temporary (7d)',    7, 'delete',   FALSE, FALSE, TRUE, 20),
    ('days-30',    '30 Days',          30, 'delete',   TRUE,  FALSE, TRUE, 30),
    ('days-90',    '90 Days',          90, 'archive',  TRUE,  FALSE, TRUE, 40),
    ('year-1',     '1 Year',          365, 'archive',  TRUE,  FALSE, TRUE, 50),
    ('years-7',    '7 Years (legal)', 2555, 'archive', TRUE,  FALSE, TRUE, 60);


-- ---------------------------------------------------------------------
-- Storage providers. handler_key resolves a StorageProvider bean; config
-- is provider-specific (bucket, endpoint, credentials-ref, base path).
--
-- Credentials are NEVER stored here in plaintext — config holds a
-- reference resolved at runtime from environment/secret storage.
-- ---------------------------------------------------------------------
CREATE TABLE storage_providers (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                 VARCHAR(64)  NOT NULL,
    name                 VARCHAR(100) NOT NULL,
    handler_key          VARCHAR(64)  NOT NULL,
    config               JSONB        NOT NULL DEFAULT '{}'::jsonb,
    is_default           BOOLEAN      NOT NULL DEFAULT FALSE,
    enabled              BOOLEAN      NOT NULL DEFAULT TRUE,
    supports_streaming   BOOLEAN      NOT NULL DEFAULT TRUE,
    supports_signed_url  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_archive_tier      BOOLEAN      NOT NULL DEFAULT FALSE,
    max_file_bytes       BIGINT,
    priority             INTEGER      NOT NULL DEFAULT 0,
    is_system            BOOLEAN      NOT NULL DEFAULT FALSE,
    tenant_id            BIGINT,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version              BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_storage_providers PRIMARY KEY (id),
    CONSTRAINT fk_storage_providers_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_storage_providers_code_global ON storage_providers (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_storage_providers_code_tenant ON storage_providers (tenant_id, code) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_storage_providers_default_global ON storage_providers ((TRUE)) WHERE is_default AND tenant_id IS NULL;
CREATE UNIQUE INDEX uq_storage_providers_default_tenant ON storage_providers (tenant_id) WHERE is_default AND tenant_id IS NOT NULL;

-- Only 'local' has an implementation today. The rest are seeded DISABLED so the
-- catalogue is complete and enabling one is a config change once its bean exists.
INSERT INTO storage_providers (code, name, handler_key, config, is_default, enabled,
                               supports_streaming, supports_signed_url, is_archive_tier, priority, is_system) VALUES
    ('local',   'Local Storage',   'local',   '{}'::jsonb, TRUE,  TRUE,  TRUE, FALSE, FALSE, 10, TRUE),
    ('network', 'Network Storage', 'network', '{}'::jsonb, FALSE, FALSE, TRUE, FALSE, FALSE, 20, TRUE),
    ('object',  'Object Storage',  'object',  '{}'::jsonb, FALSE, FALSE, TRUE, TRUE,  FALSE, 30, TRUE),
    ('cloud',   'Cloud Storage',   'cloud',   '{}'::jsonb, FALSE, FALSE, TRUE, TRUE,  FALSE, 40, TRUE),
    ('hybrid',  'Hybrid Storage',  'hybrid',  '{}'::jsonb, FALSE, FALSE, TRUE, TRUE,  FALSE, 50, TRUE),
    ('cold',    'Cold Storage',    'cold',    '{}'::jsonb, FALSE, FALSE, FALSE, FALSE, TRUE, 60, TRUE),
    ('archive', 'Archive Storage', 'archive', '{}'::jsonb, FALSE, FALSE, FALSE, FALSE, TRUE, 70, TRUE);


-- ---------------------------------------------------------------------
-- File categories: the validation and processing contract per kind of file.
-- Adding "Certificate" or "Digital Signature" is an INSERT.
-- ---------------------------------------------------------------------
CREATE TABLE file_categories (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                  VARCHAR(64)  NOT NULL,
    name                  VARCHAR(100) NOT NULL,
    description           VARCHAR(500),
    max_bytes             BIGINT,
    allowed_mime_types    JSONB        NOT NULL DEFAULT '[]'::jsonb,   -- [] = any
    allowed_extensions    JSONB        NOT NULL DEFAULT '[]'::jsonb,
    scan_required         BOOLEAN      NOT NULL DEFAULT FALSE,
    versioning_enabled    BOOLEAN      NOT NULL DEFAULT TRUE,
    dedupe_enabled        BOOLEAN      NOT NULL DEFAULT TRUE,
    processors            JSONB        NOT NULL DEFAULT '[]'::jsonb,   -- ordered processor codes
    retention_policy_id   BIGINT,
    default_provider_id   BIGINT,
    is_system             BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order         INTEGER      NOT NULL DEFAULT 0,
    tenant_id             BIGINT,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version               BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_file_categories PRIMARY KEY (id),
    CONSTRAINT fk_file_categories_retention FOREIGN KEY (retention_policy_id) REFERENCES retention_policies (id),
    CONSTRAINT fk_file_categories_provider  FOREIGN KEY (default_provider_id) REFERENCES storage_providers (id),
    CONSTRAINT fk_file_categories_tenant    FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_file_categories_code_global ON file_categories (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_file_categories_code_tenant ON file_categories (tenant_id, code) WHERE tenant_id IS NOT NULL;

INSERT INTO file_categories (code, name, description, max_bytes, allowed_mime_types, allowed_extensions,
                             scan_required, versioning_enabled, dedupe_enabled, processors,
                             retention_policy_id, is_system, display_order)
SELECT c.code, c.name, c.description, c.max_bytes, c.mimes::jsonb, c.exts::jsonb,
       c.scan, c.versioning, c.dedupe, c.processors::jsonb, rp.id, TRUE, c.ord
FROM (VALUES
    ('image',      'Image',      'Photographs and raster images',      20971520,
     '["image/jpeg","image/png","image/webp","image/gif"]', '["jpg","jpeg","png","webp","gif"]',
     FALSE, TRUE, TRUE, '["metadata","thumbnail"]', 'permanent', 10),
    ('pdf',        'PDF',        'Portable documents',                 52428800,
     '["application/pdf"]', '["pdf"]',
     TRUE,  TRUE, TRUE, '["metadata"]', 'years-7', 20),
    ('video',      'Video',      'Video assets',                      524288000,
     '["video/mp4","video/quicktime","video/x-msvideo"]', '["mp4","mov","avi"]',
     FALSE, TRUE, TRUE, '["metadata"]', 'year-1', 30),
    ('audio',      'Audio',      'Audio recordings',                   52428800,
     '["audio/mpeg","audio/wav","audio/ogg"]', '["mp3","wav","ogg"]',
     FALSE, TRUE, TRUE, '["metadata"]', 'year-1', 40),
    ('document',   'Document',   'Word-processing documents',          52428800,
     '["application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document"]',
     '["doc","docx","odt","rtf"]',
     TRUE,  TRUE, TRUE, '["metadata"]', 'years-7', 50),
    ('spreadsheet','Spreadsheet','Spreadsheets',                       52428800,
     '["application/vnd.ms-excel","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]',
     '["xls","xlsx","ods","csv"]',
     TRUE,  TRUE, TRUE, '["metadata"]', 'years-7', 60),
    ('presentation','Presentation','Slide decks',                      104857600,
     '["application/vnd.ms-powerpoint","application/vnd.openxmlformats-officedocument.presentationml.presentation"]',
     '["ppt","pptx","odp"]',
     TRUE,  TRUE, TRUE, '["metadata"]', 'year-1', 70),
    ('archive',    'Archive',    'Compressed archives',               524288000,
     '["application/zip","application/x-tar","application/gzip"]', '["zip","tar","gz"]',
     TRUE,  TRUE, TRUE, '["metadata"]', 'days-90', 80),
    ('text',       'Text',       'Plain text',                          5242880,
     '["text/plain","text/csv","application/json","application/xml"]', '["txt","csv","json","xml","log"]',
     FALSE, TRUE, TRUE, '["metadata"]', 'days-90', 90),
    ('certificate','Certificate','Warranty and compliance certificates', 20971520,
     '["application/pdf","image/jpeg","image/png"]', '["pdf","jpg","jpeg","png"]',
     TRUE,  TRUE, FALSE, '["metadata","watermark"]', 'years-7', 100),
    ('signature',  'Digital Signature', 'Signed agreements and signature images', 10485760,
     '["application/pdf","image/png"]', '["pdf","png","p7s"]',
     TRUE,  TRUE, FALSE, '["metadata"]', 'years-7', 110),
    ('source',     'Source File', 'Design and source assets',          524288000,
     '[]', '[]', TRUE, TRUE, TRUE, '["metadata"]', 'year-1', 120),
    ('temporary',  'Temporary',  'Short-lived working files',          104857600,
     '[]', '[]', FALSE, FALSE, FALSE, '[]', 'temporary', 130)
) AS c(code, name, description, max_bytes, mimes, exts, scan, versioning, dedupe, processors, retention_code, ord)
JOIN retention_policies rp ON rp.code = c.retention_code AND rp.tenant_id IS NULL;


-- ---------------------------------------------------------------------
-- Processing pipeline. Each row maps to a FileProcessor bean; run_order
-- sequences them. is_async defers to the scheduler once one exists —
-- until then async processors run inline after commit.
-- ---------------------------------------------------------------------
CREATE TABLE file_processors (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code           VARCHAR(64)  NOT NULL,
    name           VARCHAR(100) NOT NULL,
    handler_key    VARCHAR(64)  NOT NULL,
    config         JSONB        NOT NULL DEFAULT '{}'::jsonb,
    enabled        BOOLEAN      NOT NULL DEFAULT TRUE,
    is_async       BOOLEAN      NOT NULL DEFAULT FALSE,
    fails_upload   BOOLEAN      NOT NULL DEFAULT FALSE,   -- error aborts the upload vs logs
    run_order      INTEGER      NOT NULL DEFAULT 0,
    is_system      BOOLEAN      NOT NULL DEFAULT FALSE,
    tenant_id      BIGINT,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_file_processors PRIMARY KEY (id),
    CONSTRAINT fk_file_processors_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_file_processors_code_global ON file_processors (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_file_processors_code_tenant ON file_processors (tenant_id, code) WHERE tenant_id IS NOT NULL;

-- 'metadata' and 'thumbnail' have real JDK-only implementations. The rest are
-- seeded DISABLED: their SPI contract exists, the bean does not, and enabling
-- one without an implementation is refused at validation time rather than
-- silently skipped.
INSERT INTO file_processors (code, name, handler_key, config, enabled, is_async, fails_upload, run_order, is_system) VALUES
    ('metadata',   'Metadata Extraction',  'metadata',   '{}'::jsonb,                          TRUE,  FALSE, FALSE, 10, TRUE),
    ('virus-scan', 'Virus Scan',           'virus-scan', '{}'::jsonb,                          FALSE, FALSE, TRUE,  20, TRUE),
    ('thumbnail',  'Thumbnail Generation', 'thumbnail',  '{"width":320,"height":320}'::jsonb,  TRUE,  TRUE,  FALSE, 30, TRUE),
    ('preview',    'Preview Generation',   'preview',    '{"width":1280}'::jsonb,              FALSE, TRUE,  FALSE, 40, TRUE),
    ('optimize',   'Image Optimization',   'optimize',   '{"quality":0.85}'::jsonb,            FALSE, TRUE,  FALSE, 50, TRUE),
    ('compress',   'Compression',          'compress',   '{}'::jsonb,                          FALSE, TRUE,  FALSE, 60, TRUE),
    ('watermark',  'Watermark',            'watermark',  '{"text":"SAMI"}'::jsonb,             FALSE, TRUE,  FALSE, 70, TRUE),
    ('ocr',        'OCR Processing',       'ocr',        '{"language":"eng+fas"}'::jsonb,      FALSE, TRUE,  FALSE, 80, TRUE),
    ('convert',    'Format Conversion',    'convert',    '{}'::jsonb,                          FALSE, TRUE,  FALSE, 90, TRUE);


-- ---------------------------------------------------------------------
-- Tags.
-- ---------------------------------------------------------------------
CREATE TABLE file_tags (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    color         VARCHAR(24),
    is_confidential BOOLEAN    NOT NULL DEFAULT FALSE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    tenant_id     BIGINT,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_file_tags PRIMARY KEY (id),
    CONSTRAINT fk_file_tags_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_file_tags_code_global ON file_tags (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_file_tags_code_tenant ON file_tags (tenant_id, code) WHERE tenant_id IS NOT NULL;

INSERT INTO file_tags (code, name, color, is_confidential, is_system, display_order) VALUES
    ('customer',     'Customer',     '#26375F', FALSE, TRUE, 10),
    ('supplier',     'Supplier',     '#4A6FA5', FALSE, TRUE, 20),
    ('invoice',      'Invoice',      '#B0894F', FALSE, TRUE, 30),
    ('repair',       'Repair',       '#8B5E3C', FALSE, TRUE, 40),
    ('warranty',     'Warranty',     '#2E7D5B', FALSE, TRUE, 50),
    ('contract',     'Contract',     '#6A4C93', TRUE,  TRUE, 60),
    ('marketing',    'Marketing',    '#C1666B', FALSE, TRUE, 70),
    ('archive',      'Archive',      '#7A7A7A', FALSE, TRUE, 80),
    ('confidential', 'Confidential', '#B00020', TRUE,  TRUE, 90),
    ('temporary',    'Temporary',    '#9E9E9E', FALSE, TRUE, 100);


-- ---------------------------------------------------------------------
-- Storage quotas, by configurable scope.
-- ---------------------------------------------------------------------
CREATE TABLE storage_quotas (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    scope_kind   VARCHAR(32)  NOT NULL,
    scope_ref    VARCHAR(128),
    provider_id  BIGINT,
    max_bytes    BIGINT,
    max_files    BIGINT,
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    tenant_id    BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version      BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_storage_quotas PRIMARY KEY (id),
    CONSTRAINT ck_storage_quota_scope CHECK (scope_kind IN ('TENANT', 'COMPANY', 'BRANCH', 'MODULE', 'PROVIDER')),
    CONSTRAINT uq_storage_quotas UNIQUE (tenant_id, scope_kind, scope_ref, provider_id),
    CONSTRAINT fk_storage_quotas_provider FOREIGN KEY (provider_id) REFERENCES storage_providers (id),
    CONSTRAINT fk_storage_quotas_tenant   FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);


-- ---------------------------------------------------------------------
-- Folders. Physical (materialised path), virtual, or smart (saved query).
-- ---------------------------------------------------------------------
CREATE TABLE file_folders (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    parent_id     BIGINT,
    name          VARCHAR(160) NOT NULL,
    path          VARCHAR(2000) NOT NULL,
    description   VARCHAR(500),
    is_virtual    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_smart      BOOLEAN      NOT NULL DEFAULT FALSE,
    smart_query   JSONB,
    module_code   VARCHAR(64),
    company_id    BIGINT,
    branch_id     BIGINT,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    tenant_id     BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_file_folders PRIMARY KEY (id),
    CONSTRAINT ck_file_folders_smart CHECK (NOT is_smart OR smart_query IS NOT NULL),
    CONSTRAINT uq_file_folders_path UNIQUE (tenant_id, path),
    CONSTRAINT fk_file_folders_parent FOREIGN KEY (parent_id) REFERENCES file_folders (id) ON DELETE RESTRICT,
    CONSTRAINT fk_file_folders_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_file_folders_parent ON file_folders (parent_id);
CREATE INDEX idx_file_folders_tenant ON file_folders (tenant_id);


-- ---------------------------------------------------------------------
-- Files. The business-facing object; business modules keep only file_uuid.
--
-- storage_key/provider live on the VERSION, not here, so moving a file
-- between providers is a new version row and never rewrites history.
-- ---------------------------------------------------------------------
CREATE SEQUENCE file_code_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE files (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    file_uuid            UUID         NOT NULL,
    file_code            VARCHAR(32)  NOT NULL,
    name                 VARCHAR(255) NOT NULL,
    original_filename    VARCHAR(255) NOT NULL,
    description          VARCHAR(1000),
    category_id          BIGINT       NOT NULL,
    status_id            BIGINT       NOT NULL,
    folder_id            BIGINT,
    module_code          VARCHAR(64),
    entity_code          VARCHAR(64),
    entity_id            BIGINT,
    company_id           BIGINT,
    branch_id            BIGINT,
    owner_id             BIGINT,
    owner_email          VARCHAR(255),
    current_version_id   BIGINT,
    size_bytes           BIGINT       NOT NULL DEFAULT 0,
    extension            VARCHAR(32),
    mime_type            VARCHAR(160),
    checksum_sha256      VARCHAR(64),
    metadata             JSONB        NOT NULL DEFAULT '{}'::jsonb,
    retention_policy_id  BIGINT,
    retention_expires_at TIMESTAMPTZ,
    legal_hold_until     TIMESTAMPTZ,
    uploaded_ip          VARCHAR(64),
    deleted_at           TIMESTAMPTZ,
    deleted_by           BIGINT,
    restored_at          TIMESTAMPTZ,
    tenant_id            BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version              BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_files PRIMARY KEY (id),
    CONSTRAINT uq_files_uuid UNIQUE (file_uuid),
    CONSTRAINT uq_files_code UNIQUE (tenant_id, file_code),
    CONSTRAINT fk_files_category  FOREIGN KEY (category_id) REFERENCES file_categories (id),
    CONSTRAINT fk_files_status    FOREIGN KEY (status_id)   REFERENCES file_statuses (id),
    CONSTRAINT fk_files_folder    FOREIGN KEY (folder_id)   REFERENCES file_folders (id) ON DELETE SET NULL,
    CONSTRAINT fk_files_retention FOREIGN KEY (retention_policy_id) REFERENCES retention_policies (id),
    CONSTRAINT fk_files_tenant    FOREIGN KEY (tenant_id)   REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_files_tenant     ON files (tenant_id);
CREATE INDEX idx_files_entity     ON files (tenant_id, module_code, entity_code, entity_id);
CREATE INDEX idx_files_category   ON files (tenant_id, category_id);
CREATE INDEX idx_files_status     ON files (tenant_id, status_id);
CREATE INDEX idx_files_folder     ON files (folder_id);
CREATE INDEX idx_files_owner      ON files (tenant_id, owner_id);
CREATE INDEX idx_files_retention  ON files (retention_expires_at) WHERE retention_expires_at IS NOT NULL;
CREATE INDEX idx_files_name       ON files (tenant_id, lower(name));
-- Content-addressed dedupe: one live file per (tenant, category, checksum).
CREATE UNIQUE INDEX uq_files_checksum ON files (tenant_id, category_id, checksum_sha256)
    WHERE checksum_sha256 IS NOT NULL AND deleted_at IS NULL;


-- ---------------------------------------------------------------------
-- Versions. Major/minor/revision, each with its own stored object, so
-- rollback is a pointer move and never a destructive copy.
-- ---------------------------------------------------------------------
CREATE TABLE file_versions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    file_id          BIGINT       NOT NULL,
    version_major    INTEGER      NOT NULL DEFAULT 1,
    version_minor    INTEGER      NOT NULL DEFAULT 0,
    revision         INTEGER      NOT NULL DEFAULT 0,
    label            VARCHAR(64)  NOT NULL,
    provider_id      BIGINT       NOT NULL,
    storage_key      VARCHAR(1024) NOT NULL,
    size_bytes       BIGINT       NOT NULL,
    checksum_sha256  VARCHAR(64)  NOT NULL,
    mime_type        VARCHAR(160),
    metadata         JSONB        NOT NULL DEFAULT '{}'::jsonb,
    comment          VARCHAR(1000),
    is_current       BOOLEAN      NOT NULL DEFAULT FALSE,
    created_by       BIGINT,
    created_by_email VARCHAR(255),
    tenant_id        BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_file_versions PRIMARY KEY (id),
    CONSTRAINT uq_file_versions_label UNIQUE (file_id, label),
    CONSTRAINT uq_file_versions_number UNIQUE (file_id, version_major, version_minor, revision),
    CONSTRAINT fk_file_versions_file     FOREIGN KEY (file_id) REFERENCES files (id) ON DELETE CASCADE,
    CONSTRAINT fk_file_versions_provider FOREIGN KEY (provider_id) REFERENCES storage_providers (id),
    CONSTRAINT fk_file_versions_tenant   FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_file_versions_file ON file_versions (file_id);
CREATE UNIQUE INDEX uq_file_versions_current ON file_versions (file_id) WHERE is_current;

ALTER TABLE files ADD CONSTRAINT fk_files_current_version
    FOREIGN KEY (current_version_id) REFERENCES file_versions (id) ON DELETE SET NULL;


-- ---------------------------------------------------------------------
-- Derivatives: thumbnails, previews, OCR text, watermarked renditions.
-- Keyed by version so a rollback exposes that version's derivatives.
-- ---------------------------------------------------------------------
CREATE TABLE file_derivatives (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    file_id       BIGINT       NOT NULL,
    version_id    BIGINT       NOT NULL,
    kind          VARCHAR(64)  NOT NULL,
    provider_id   BIGINT,
    storage_key   VARCHAR(1024),
    mime_type     VARCHAR(160),
    size_bytes    BIGINT,
    width         INTEGER,
    height        INTEGER,
    page_count    INTEGER,
    duration_ms   BIGINT,
    text_content  TEXT,
    generator_key VARCHAR(64)  NOT NULL,
    status        VARCHAR(32)  NOT NULL DEFAULT 'ready',
    error_message VARCHAR(2000),
    generated_at  TIMESTAMPTZ,
    tenant_id     BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_file_derivatives PRIMARY KEY (id),
    CONSTRAINT ck_file_derivatives_status CHECK (status IN ('pending', 'ready', 'failed', 'skipped')),
    CONSTRAINT uq_file_derivatives UNIQUE (version_id, kind),
    CONSTRAINT fk_file_derivatives_file    FOREIGN KEY (file_id) REFERENCES files (id) ON DELETE CASCADE,
    CONSTRAINT fk_file_derivatives_version FOREIGN KEY (version_id) REFERENCES file_versions (id) ON DELETE CASCADE,
    CONSTRAINT fk_file_derivatives_tenant  FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_file_derivatives_file ON file_derivatives (file_id);


-- ---------------------------------------------------------------------
-- Scan results.
-- ---------------------------------------------------------------------
CREATE TABLE file_scan_results (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    file_id      BIGINT       NOT NULL,
    version_id   BIGINT       NOT NULL,
    scanner_key  VARCHAR(64)  NOT NULL,
    verdict      VARCHAR(32)  NOT NULL,
    threat       VARCHAR(255),
    details      JSONB        NOT NULL DEFAULT '{}'::jsonb,
    scanned_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    tenant_id    BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version      BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_file_scan_results PRIMARY KEY (id),
    CONSTRAINT ck_file_scan_verdict CHECK (verdict IN ('clean', 'infected', 'suspicious', 'error', 'skipped')),
    CONSTRAINT fk_file_scan_file    FOREIGN KEY (file_id) REFERENCES files (id) ON DELETE CASCADE,
    CONSTRAINT fk_file_scan_version FOREIGN KEY (version_id) REFERENCES file_versions (id) ON DELETE CASCADE,
    CONSTRAINT fk_file_scan_tenant  FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_file_scan_file ON file_scan_results (file_id);


-- ---------------------------------------------------------------------
-- Tag links.
-- ---------------------------------------------------------------------
CREATE TABLE file_tag_links (
    file_id    BIGINT NOT NULL,
    tag_id     BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_file_tag_links PRIMARY KEY (file_id, tag_id),
    CONSTRAINT fk_file_tag_links_file FOREIGN KEY (file_id) REFERENCES files (id) ON DELETE CASCADE,
    CONSTRAINT fk_file_tag_links_tag  FOREIGN KEY (tag_id)  REFERENCES file_tags (id) ON DELETE CASCADE
);
CREATE INDEX idx_file_tag_links_tag ON file_tag_links (tag_id);


-- ---------------------------------------------------------------------
-- References: who points at this file. Makes deletion safe and orphan
-- detection a query. A file with live references cannot be purged.
-- ---------------------------------------------------------------------
CREATE TABLE file_references (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    file_id      BIGINT       NOT NULL,
    module_code  VARCHAR(64)  NOT NULL,
    entity_code  VARCHAR(64)  NOT NULL,
    record_id    BIGINT       NOT NULL,
    role         VARCHAR(64),
    tenant_id    BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version      BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_file_references PRIMARY KEY (id),
    CONSTRAINT uq_file_references UNIQUE (file_id, module_code, entity_code, record_id, role),
    CONSTRAINT fk_file_references_file   FOREIGN KEY (file_id) REFERENCES files (id) ON DELETE CASCADE,
    CONSTRAINT fk_file_references_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_file_references_target ON file_references (tenant_id, module_code, entity_code, record_id);


-- ---------------------------------------------------------------------
-- Upload sessions — interrupted upload and partial-recovery support.
-- A session that never completes is reclaimable by the retention sweep.
-- ---------------------------------------------------------------------
CREATE TABLE file_upload_sessions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    session_uuid      UUID         NOT NULL,
    file_id           BIGINT,
    category_id       BIGINT       NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    declared_size     BIGINT,
    declared_checksum VARCHAR(64),
    received_bytes    BIGINT       NOT NULL DEFAULT 0,
    chunk_count       INTEGER      NOT NULL DEFAULT 0,
    status            VARCHAR(32)  NOT NULL DEFAULT 'open',
    provider_id       BIGINT,
    staging_key       VARCHAR(1024),
    expires_at        TIMESTAMPTZ  NOT NULL,
    failure_reason    VARCHAR(1000),
    owner_id          BIGINT,
    tenant_id         BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_file_upload_sessions PRIMARY KEY (id),
    CONSTRAINT uq_file_upload_sessions UNIQUE (session_uuid),
    CONSTRAINT ck_file_upload_status CHECK (status IN ('open', 'completed', 'aborted', 'expired', 'failed')),
    CONSTRAINT fk_file_upload_category FOREIGN KEY (category_id) REFERENCES file_categories (id),
    CONSTRAINT fk_file_upload_file     FOREIGN KEY (file_id) REFERENCES files (id) ON DELETE SET NULL,
    CONSTRAINT fk_file_upload_tenant   FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_file_upload_sessions_open ON file_upload_sessions (status, expires_at);


-- ---------------------------------------------------------------------
-- Audit. Mirrors the per-module pattern; migrates to the shared audit
-- engine (docs/platform-architecture.md D-B) when that lands.
-- ---------------------------------------------------------------------
CREATE TABLE file_audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    entity_type  VARCHAR(64)  NOT NULL,
    entity_id    BIGINT,
    action       VARCHAR(64)  NOT NULL,
    old_values   JSONB,
    new_values   JSONB,
    actor_id     BIGINT,
    actor_email  VARCHAR(255),
    actor_ip     VARCHAR(64),
    tenant_id    BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version      BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_file_audit_log PRIMARY KEY (id),
    CONSTRAINT fk_file_audit_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_file_audit_entity ON file_audit_log (tenant_id, entity_type, entity_id);
CREATE INDEX idx_file_audit_created ON file_audit_log (tenant_id, created_at DESC);


-- ---------------------------------------------------------------------
-- Root folder + module and permissions.
-- ---------------------------------------------------------------------
INSERT INTO file_folders (parent_id, name, path, description, is_system)
VALUES (NULL, 'Root', '/', 'Implicit root folder', TRUE);

INSERT INTO modules (code, name, description, icon, path, display_order, enabled, is_system)
VALUES ('files', 'Files & Media', 'Central file storage, media, versions and retention',
        'mdi-folder-multiple-outline', '/files', 140, TRUE, TRUE);

INSERT INTO permissions (module_id, action, code, name, is_system)
SELECT m.id, a.action, m.code || ':' || a.action, m.name || ' — ' || a.label, TRUE
FROM modules m
CROSS JOIN (VALUES
    ('view',              'View files'),
    ('upload',            'Upload files'),
    ('download',          'Download files'),
    ('edit',              'Edit file metadata'),
    ('delete',            'Delete files'),
    ('restore',           'Restore files'),
    ('manage-storage',    'Manage storage providers'),
    ('manage-retention',  'Manage retention policies'),
    ('manage-policies',   'Manage file categories and processors'),
    ('export',            'Export files and metadata')
) AS a(action, label)
WHERE m.code = 'files';
