-- =====================================================================
-- V19 — Shared Scheduler  (common platform service, docs/platform-architecture.md D-D)
--
-- The ERP had no clock. Four already-built features were inert for want of
-- one: automation's retry queue, licensing's expiry sweep and auto-renewal,
-- and the file module's retention sweep. Each was on its way to growing its
-- own @Scheduled method — the duplicated infrastructure the architecture
-- rules forbid.
--
-- This is deliberately NOT raw @Scheduled. Jobs are rows, so they can be
-- listed, paused, retimed, audited and replayed; execution history is
-- persisted; and every run is wrapped in a tenant context, which a static
-- annotation cannot be.
--
-- Behaviour is data: scheduled_jobs.handler_key resolves a JobHandler bean.
-- A new scheduled job is an INSERT plus a bean, never a change to the runner.
-- =====================================================================


-- ---------------------------------------------------------------------
-- Configurable job lifecycle states. Flag-driven: the poller selects work
-- by `allows_run`, so pausing a job is a status change, not a code path.
-- ---------------------------------------------------------------------
CREATE TABLE job_statuses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code            VARCHAR(64)  NOT NULL,
    name            VARCHAR(100) NOT NULL,
    is_default      BOOLEAN      NOT NULL DEFAULT FALSE,
    allows_run      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_paused_state BOOLEAN      NOT NULL DEFAULT FALSE,
    is_failed_state BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system       BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order   INTEGER      NOT NULL DEFAULT 0,
    tenant_id       BIGINT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_job_statuses PRIMARY KEY (id),
    CONSTRAINT fk_job_statuses_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_job_statuses_code_global ON job_statuses (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_job_statuses_code_tenant ON job_statuses (tenant_id, code) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_job_statuses_default_global ON job_statuses ((TRUE)) WHERE is_default AND tenant_id IS NULL;
CREATE UNIQUE INDEX uq_job_statuses_default_tenant ON job_statuses (tenant_id) WHERE is_default AND tenant_id IS NOT NULL;

INSERT INTO job_statuses (code, name, is_default, allows_run, is_paused_state, is_failed_state, is_system, display_order) VALUES
    ('draft',     'Draft',     TRUE,  FALSE, FALSE, FALSE, TRUE, 10),
    ('active',    'Active',    FALSE, TRUE,  FALSE, FALSE, TRUE, 20),
    ('paused',    'Paused',    FALSE, FALSE, TRUE,  FALSE, TRUE, 30),
    ('failed',    'Failed',    FALSE, FALSE, FALSE, TRUE,  TRUE, 40),
    ('completed', 'Completed', FALSE, FALSE, FALSE, FALSE, TRUE, 50);


-- ---------------------------------------------------------------------
-- The jobs themselves.
--
-- `catch_up = FALSE` means a job whose window was missed (process down)
-- runs once at the next opportunity rather than replaying every missed
-- occurrence — the correct default for sweeps, which are idempotent.
--
-- `max_failures` auto-pauses a job that keeps failing, so a broken handler
-- cannot hammer the database indefinitely.
-- ---------------------------------------------------------------------
CREATE TABLE scheduled_jobs (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                 VARCHAR(64)   NOT NULL,
    name                 VARCHAR(160)  NOT NULL,
    description          VARCHAR(1000),
    handler_key          VARCHAR(64)   NOT NULL,
    schedule_kind        VARCHAR(32)   NOT NULL DEFAULT 'CRON',
    cron_expression      VARCHAR(160),
    interval_seconds     INTEGER,
    config               JSONB         NOT NULL DEFAULT '{}'::jsonb,
    status_id            BIGINT        NOT NULL,
    timezone             VARCHAR(64)   NOT NULL DEFAULT 'UTC',
    next_run_at          TIMESTAMPTZ,
    last_run_at          TIMESTAMPTZ,
    last_status          VARCHAR(32),
    last_duration_ms     BIGINT,
    consecutive_failures INTEGER       NOT NULL DEFAULT 0,
    max_failures         INTEGER       NOT NULL DEFAULT 5,
    timeout_seconds      INTEGER       NOT NULL DEFAULT 300,
    catch_up             BOOLEAN       NOT NULL DEFAULT FALSE,
    run_on_startup       BOOLEAN       NOT NULL DEFAULT FALSE,
    is_system            BOOLEAN       NOT NULL DEFAULT FALSE,
    tenant_id            BIGINT        NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at           TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version              BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT pk_scheduled_jobs PRIMARY KEY (id),
    CONSTRAINT uq_scheduled_jobs_code UNIQUE (tenant_id, code),
    CONSTRAINT ck_scheduled_jobs_kind CHECK (schedule_kind IN ('CRON', 'FIXED_DELAY', 'FIXED_RATE', 'ONCE')),
    -- A schedule must actually be specifiable: cron needs an expression,
    -- interval kinds need an interval. Enforced here so a job can never be
    -- saved in a state the runner cannot interpret.
    CONSTRAINT ck_scheduled_jobs_schedule CHECK (
        (schedule_kind = 'CRON'  AND cron_expression IS NOT NULL)
     OR (schedule_kind IN ('FIXED_DELAY', 'FIXED_RATE') AND interval_seconds IS NOT NULL AND interval_seconds > 0)
     OR (schedule_kind = 'ONCE' AND next_run_at IS NOT NULL)),
    CONSTRAINT fk_scheduled_jobs_status FOREIGN KEY (status_id) REFERENCES job_statuses (id),
    CONSTRAINT fk_scheduled_jobs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
-- Drives the poller: "which jobs are due?"
CREATE INDEX idx_scheduled_jobs_due ON scheduled_jobs (next_run_at) WHERE next_run_at IS NOT NULL;
CREATE INDEX idx_scheduled_jobs_tenant ON scheduled_jobs (tenant_id);


-- ---------------------------------------------------------------------
-- Execution history. Every run is recorded, so a sweep that silently did
-- nothing is distinguishable from one that never ran.
-- ---------------------------------------------------------------------
CREATE SEQUENCE job_execution_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE job_executions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    job_id           BIGINT       NOT NULL,
    execution_number VARCHAR(32)  NOT NULL,
    trigger_kind     VARCHAR(32)  NOT NULL DEFAULT 'SCHEDULED',
    status           VARCHAR(32)  NOT NULL DEFAULT 'RUNNING',
    started_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    finished_at      TIMESTAMPTZ,
    duration_ms      BIGINT,
    outcome          VARCHAR(2000),
    error_message    VARCHAR(4000),
    items_processed  INTEGER,
    actor_id         BIGINT,
    actor_email      VARCHAR(255),
    tenant_id        BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_job_executions PRIMARY KEY (id),
    CONSTRAINT uq_job_executions_number UNIQUE (tenant_id, execution_number),
    CONSTRAINT ck_job_executions_status CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED', 'TIMED_OUT', 'SKIPPED')),
    CONSTRAINT ck_job_executions_trigger CHECK (trigger_kind IN ('SCHEDULED', 'MANUAL', 'STARTUP')),
    CONSTRAINT fk_job_executions_job    FOREIGN KEY (job_id) REFERENCES scheduled_jobs (id) ON DELETE CASCADE,
    CONSTRAINT fk_job_executions_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_job_executions_job ON job_executions (job_id, started_at DESC);


-- ---------------------------------------------------------------------
-- Seed the jobs that activate already-built but dormant features.
--
-- All seeded in 'draft' (allows_run = FALSE) DELIBERATELY: applying this
-- migration must not silently start sweeping data on an existing install.
-- An operator enables each one explicitly.
-- ---------------------------------------------------------------------
INSERT INTO scheduled_jobs (code, name, description, handler_key, schedule_kind,
                            cron_expression, config, status_id, timeout_seconds, is_system)
SELECT j.code, j.name, j.description, j.handler_key, 'CRON', j.cron, '{}'::jsonb, st.id, j.timeout, TRUE
FROM (VALUES
    ('files-retention',    'File Retention Sweep',
     'Applies expired retention policies and reclaims stale upload sessions',
     'files-retention',    '0 30 2 * * *', 600),
    ('licensing-expiry',   'Licence Expiry Sweep',
     'Moves lapsed licences to the expired state',
     'licensing-expiry',   '0 0 3 * * *',  300),
    ('licensing-renewals', 'Licence Auto-Renewal',
     'Processes licences flagged for automatic renewal',
     'licensing-renewals', '0 15 3 * * *', 300),
    ('automation-retry',   'Automation Retry Drain',
     'Re-runs automation actions parked in the failure queue',
     'automation-retry',   '0 */5 * * * *', 120)
) AS j(code, name, description, handler_key, cron, timeout)
JOIN job_statuses st ON st.code = 'draft' AND st.tenant_id IS NULL;


-- ---------------------------------------------------------------------
-- Module + permissions.
-- ---------------------------------------------------------------------
INSERT INTO modules (code, name, description, icon, path, display_order, enabled, is_system)
VALUES ('scheduler', 'Scheduler', 'Scheduled jobs, execution history and manual runs',
        'mdi-clock-outline', '/scheduler', 150, TRUE, TRUE);

INSERT INTO permissions (module_id, action, code, name, is_system)
SELECT m.id, a.action, m.code || ':' || a.action, m.name || ' — ' || a.label, TRUE
FROM modules m
CROSS JOIN (VALUES
    ('view',    'View scheduled jobs'),
    ('create',  'Create scheduled jobs'),
    ('edit',    'Edit scheduled jobs'),
    ('delete',  'Delete scheduled jobs'),
    ('execute', 'Run jobs manually'),
    ('export',  'Export execution history')
) AS a(action, label)
WHERE m.code = 'scheduler';
