-- =====================================================================
-- V20 — Knowledge Base & SOP Management (module 13)
--
-- Centralised organisational knowledge: articles, standard operating
-- procedures, policies, work instructions, troubleshooting guides, FAQs.
--
-- This is NOT a document management system and NOT a file store. Article
-- CONTENT lives here; article ATTACHMENTS are references into the files
-- module (V18) by file UUID — no bytes are ever stored in this module.
--
-- Behaviour is data: statuses, categories, relation types, risk levels,
-- approval stages and step types are all configuration rows with
-- behavioural flags. A new category ("Trade-In Evaluation Guide") or a new
-- approval stage is an INSERT, never a release.
--
-- FULL-TEXT SEARCH NOTE. PostgreSQL ships no Persian (Farsi) text search
-- configuration — the closest, 'arabic', shares the script but stems a
-- different language and would produce wrong matches. Persian therefore
-- uses 'simple' (correct tokenisation, no stemming) and English uses
-- 'english'. The choice is driven by kb_articles.language, so replacing
-- 'simple' with a real Persian dictionary later is a configuration change
-- rather than a migration.
-- =====================================================================


-- ---------------------------------------------------------------------
-- Article lifecycle. Flag-driven: `is_visible` is what makes an article
-- readable by ordinary users, so deprecating one hides it without any
-- service testing for the string 'deprecated'.
-- ---------------------------------------------------------------------
CREATE TABLE kb_statuses (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                VARCHAR(64)  NOT NULL,
    name                VARCHAR(100) NOT NULL,
    is_default          BOOLEAN      NOT NULL DEFAULT FALSE,
    is_draft_state      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_review_state     BOOLEAN      NOT NULL DEFAULT FALSE,
    is_approved_state   BOOLEAN      NOT NULL DEFAULT FALSE,
    is_published_state  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_deprecated_state BOOLEAN      NOT NULL DEFAULT FALSE,
    is_archived_state   BOOLEAN      NOT NULL DEFAULT FALSE,
    allows_edit         BOOLEAN      NOT NULL DEFAULT FALSE,
    is_visible          BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system           BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order       INTEGER      NOT NULL DEFAULT 0,
    tenant_id           BIGINT,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version             BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_kb_statuses PRIMARY KEY (id),
    CONSTRAINT fk_kb_statuses_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_kb_statuses_code_global ON kb_statuses (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_kb_statuses_code_tenant ON kb_statuses (tenant_id, code) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_kb_statuses_default_global ON kb_statuses ((TRUE)) WHERE is_default AND tenant_id IS NULL;
CREATE UNIQUE INDEX uq_kb_statuses_default_tenant ON kb_statuses (tenant_id) WHERE is_default AND tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_kb_statuses_published_global ON kb_statuses ((TRUE)) WHERE is_published_state AND tenant_id IS NULL;

INSERT INTO kb_statuses (code, name, is_default, is_draft_state, is_review_state, is_approved_state,
                         is_published_state, is_deprecated_state, is_archived_state,
                         allows_edit, is_visible, is_system, display_order) VALUES
    ('draft',      'Draft',      TRUE,  TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, TRUE, 10),
    ('review',     'In Review',  FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 20),
    ('approved',   'Approved',   FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 30),
    ('published',  'Published',  FALSE, FALSE, FALSE, TRUE,  TRUE,  FALSE, FALSE, FALSE, TRUE,  TRUE, 40),
    ('deprecated', 'Deprecated', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, TRUE,  TRUE, 50),
    ('archived',   'Archived',   FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, TRUE, 60);


-- ---------------------------------------------------------------------
-- Categories. `review_months` drives the "expired SOP" report: a category
-- can require its articles be re-reviewed on a cadence.
-- ---------------------------------------------------------------------
CREATE TABLE kb_categories (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code              VARCHAR(64)  NOT NULL,
    name              VARCHAR(120) NOT NULL,
    description       VARCHAR(500),
    icon              VARCHAR(64),
    parent_id         BIGINT,
    requires_approval BOOLEAN      NOT NULL DEFAULT FALSE,
    is_procedure      BOOLEAN      NOT NULL DEFAULT FALSE,   -- category holds SOPs
    review_months     INTEGER,
    is_system         BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order     INTEGER      NOT NULL DEFAULT 0,
    tenant_id         BIGINT,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_kb_categories PRIMARY KEY (id),
    CONSTRAINT fk_kb_categories_parent FOREIGN KEY (parent_id) REFERENCES kb_categories (id) ON DELETE RESTRICT,
    CONSTRAINT fk_kb_categories_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_kb_categories_code_global ON kb_categories (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_kb_categories_code_tenant ON kb_categories (tenant_id, code) WHERE tenant_id IS NOT NULL;

INSERT INTO kb_categories (code, name, description, icon, requires_approval, is_procedure, review_months, is_system, display_order) VALUES
    ('sop',            'SOP',                 'Standard operating procedures',      'mdi-clipboard-list-outline', TRUE,  TRUE,  12, TRUE, 10),
    ('policy',         'Policy',              'Organisational policies',            'mdi-gavel',                  TRUE,  FALSE, 24, TRUE, 20),
    ('work-instruction','Work Instruction',   'Task-level instructions',            'mdi-tools',                  TRUE,  TRUE,  12, TRUE, 30),
    ('troubleshooting','Troubleshooting',     'Diagnostic and fault guides',        'mdi-wrench-outline',         FALSE, FALSE, 12, TRUE, 40),
    ('faq',            'FAQ',                 'Frequently asked questions',         'mdi-help-circle-outline',    FALSE, FALSE, NULL, TRUE, 50),
    ('technical',      'Technical Guide',     'Technical reference material',       'mdi-book-cog-outline',       FALSE, FALSE, 12, TRUE, 60),
    ('sales',          'Sales Guide',         'Sales process guidance',             'mdi-cash-register',          FALSE, FALSE, 12, TRUE, 70),
    ('repair',         'Repair Guide',        'Device repair procedures',           'mdi-cellphone-cog',          TRUE,  TRUE,  12, TRUE, 80),
    ('accounting',     'Accounting Procedure','Financial and accounting procedures','mdi-calculator',             TRUE,  TRUE,  12, TRUE, 90),
    ('hr',             'HR Procedure',        'People and employment procedures',   'mdi-account-group-outline',  TRUE,  TRUE,  24, TRUE, 100),
    ('compliance',     'Compliance',          'Regulatory and compliance material', 'mdi-shield-check-outline',   TRUE,  FALSE, 12, TRUE, 110),
    ('security',       'Security',            'Security policies and procedures',   'mdi-lock-outline',           TRUE,  FALSE, 12, TRUE, 120),
    ('training',       'Training',            'Onboarding and training material',   'mdi-school-outline',         FALSE, FALSE, 24, TRUE, 130);


-- ---------------------------------------------------------------------
-- Risk levels for SOPs. `requires_approval` lets a high-risk procedure
-- demand sign-off even in a category that otherwise does not.
-- ---------------------------------------------------------------------
CREATE TABLE kb_risk_levels (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code              VARCHAR(64)  NOT NULL,
    name              VARCHAR(100) NOT NULL,
    weight            NUMERIC(6,2) NOT NULL DEFAULT 1,
    requires_approval BOOLEAN      NOT NULL DEFAULT FALSE,
    is_default        BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system         BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order     INTEGER      NOT NULL DEFAULT 0,
    tenant_id         BIGINT,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_kb_risk_levels PRIMARY KEY (id),
    CONSTRAINT fk_kb_risk_levels_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_kb_risk_levels_code_global ON kb_risk_levels (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_kb_risk_levels_code_tenant ON kb_risk_levels (tenant_id, code) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_kb_risk_levels_default_global ON kb_risk_levels ((TRUE)) WHERE is_default AND tenant_id IS NULL;

INSERT INTO kb_risk_levels (code, name, weight, requires_approval, is_default, is_system, display_order) VALUES
    ('low',      'Low',      1, FALSE, TRUE,  TRUE, 10),
    ('medium',   'Medium',   2, FALSE, FALSE, TRUE, 20),
    ('high',     'High',     3, TRUE,  FALSE, TRUE, 30),
    ('critical', 'Critical', 5, TRUE,  FALSE, TRUE, 40);


-- ---------------------------------------------------------------------
-- Approval stages. An ordered, configurable chain; `is_final` marks the
-- stage whose approval permits publication.
-- ---------------------------------------------------------------------
CREATE TABLE kb_approval_stages (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code           VARCHAR(64)  NOT NULL,
    name           VARCHAR(120) NOT NULL,
    stage_order    INTEGER      NOT NULL,
    required_permission VARCHAR(120),
    is_final       BOOLEAN      NOT NULL DEFAULT FALSE,
    is_optional    BOOLEAN      NOT NULL DEFAULT FALSE,
    requires_signature BOOLEAN  NOT NULL DEFAULT FALSE,
    is_system      BOOLEAN      NOT NULL DEFAULT FALSE,
    tenant_id      BIGINT,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_kb_approval_stages PRIMARY KEY (id),
    CONSTRAINT fk_kb_approval_stages_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_kb_approval_stages_code_global ON kb_approval_stages (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_kb_approval_stages_code_tenant ON kb_approval_stages (tenant_id, code) WHERE tenant_id IS NOT NULL;

INSERT INTO kb_approval_stages (code, name, stage_order, required_permission, is_final, is_optional, requires_signature, is_system) VALUES
    ('author',     'Author Submission',  10, 'knowledge:create',  FALSE, FALSE, FALSE, TRUE),
    ('reviewer',   'Technical Review',   20, 'knowledge:approve', FALSE, FALSE, FALSE, TRUE),
    ('manager',    'Department Manager', 30, 'knowledge:approve', FALSE, TRUE,  FALSE, TRUE),
    ('compliance', 'Compliance Review',  40, 'knowledge:approve', FALSE, TRUE,  TRUE,  TRUE),
    ('final',      'Final Approval',     50, 'knowledge:publish', TRUE,  FALSE, TRUE,  TRUE);


-- ---------------------------------------------------------------------
-- Relationship types. `inverse_code` lets a relation be navigated both
-- ways without storing it twice; symmetric relations are their own inverse.
-- ---------------------------------------------------------------------
CREATE TABLE kb_relation_types (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(120) NOT NULL,
    inverse_code  VARCHAR(64),
    is_symmetric  BOOLEAN      NOT NULL DEFAULT FALSE,
    target_kind   VARCHAR(32)  NOT NULL DEFAULT 'ARTICLE',
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    tenant_id     BIGINT,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_kb_relation_types PRIMARY KEY (id),
    CONSTRAINT ck_kb_relation_target CHECK (target_kind IN ('ARTICLE', 'ENTITY', 'ANY')),
    CONSTRAINT fk_kb_relation_types_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_kb_relation_types_code_global ON kb_relation_types (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_kb_relation_types_code_tenant ON kb_relation_types (tenant_id, code) WHERE tenant_id IS NOT NULL;

INSERT INTO kb_relation_types (code, name, inverse_code, is_symmetric, target_kind, is_system, display_order) VALUES
    ('related',      'Related Article',   'related',    TRUE,  'ARTICLE', TRUE, 10),
    ('supersedes',   'Supersedes',        'superseded', FALSE, 'ARTICLE', TRUE, 20),
    ('superseded',   'Superseded By',     'supersedes', FALSE, 'ARTICLE', TRUE, 30),
    ('prerequisite', 'Prerequisite',      'required-by', FALSE, 'ARTICLE', TRUE, 40),
    ('required-by',  'Required By',       'prerequisite', FALSE, 'ARTICLE', TRUE, 50),
    ('references',   'References',        NULL,         FALSE, 'ANY',     TRUE, 60),
    ('applies-to',   'Applies To',        NULL,         FALSE, 'ENTITY',  TRUE, 70);


-- ---------------------------------------------------------------------
-- Procedure step kinds.
-- ---------------------------------------------------------------------
CREATE TABLE kb_step_types (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code           VARCHAR(64)  NOT NULL,
    name           VARCHAR(100) NOT NULL,
    is_default     BOOLEAN      NOT NULL DEFAULT FALSE,
    is_decision    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_parallel    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_conditional BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system      BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order  INTEGER      NOT NULL DEFAULT 0,
    tenant_id      BIGINT,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_kb_step_types PRIMARY KEY (id),
    CONSTRAINT fk_kb_step_types_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_kb_step_types_code_global ON kb_step_types (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_kb_step_types_code_tenant ON kb_step_types (tenant_id, code) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_kb_step_types_default_global ON kb_step_types ((TRUE)) WHERE is_default AND tenant_id IS NULL;

INSERT INTO kb_step_types (code, name, is_default, is_decision, is_parallel, is_conditional, is_system, display_order) VALUES
    ('sequential',  'Sequential',  TRUE,  FALSE, FALSE, FALSE, TRUE, 10),
    ('parallel',    'Parallel',    FALSE, FALSE, TRUE,  FALSE, TRUE, 20),
    ('decision',    'Decision',    FALSE, TRUE,  FALSE, FALSE, TRUE, 30),
    ('conditional', 'Conditional', FALSE, FALSE, FALSE, TRUE,  TRUE, 40),
    ('checklist',   'Checklist',   FALSE, FALSE, FALSE, FALSE, TRUE, 50);


-- =====================================================================
-- Articles
-- =====================================================================

CREATE SEQUENCE kb_article_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE kb_sop_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE kb_articles (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    article_code       VARCHAR(32)  NOT NULL,
    title              VARCHAR(255) NOT NULL,
    summary            VARCHAR(2000),
    category_id        BIGINT       NOT NULL,
    status_id          BIGINT       NOT NULL,
    module_code        VARCHAR(64),
    process_code       VARCHAR(64),
    company_id         BIGINT,
    branch_id          BIGINT,
    language           VARCHAR(16)  NOT NULL DEFAULT 'en',
    owner_id           BIGINT,
    owner_email        VARCHAR(255),
    reviewer_id        BIGINT,
    current_version_id BIGINT,
    published_version_id BIGINT,
    keywords           VARCHAR(1000),
    view_count         BIGINT       NOT NULL DEFAULT 0,
    last_viewed_at     TIMESTAMPTZ,
    published_at       TIMESTAMPTZ,
    effective_date     DATE,
    review_date        DATE,
    archived_at        TIMESTAMPTZ,
    created_by         BIGINT,
    created_by_email   VARCHAR(255),
    -- Maintained by trigger; language decides the text-search configuration.
    search_vector      TSVECTOR,
    tenant_id          BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version            BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_kb_articles PRIMARY KEY (id),
    CONSTRAINT uq_kb_articles_code UNIQUE (tenant_id, article_code),
    CONSTRAINT fk_kb_articles_category FOREIGN KEY (category_id) REFERENCES kb_categories (id),
    CONSTRAINT fk_kb_articles_status   FOREIGN KEY (status_id)   REFERENCES kb_statuses (id),
    CONSTRAINT fk_kb_articles_tenant   FOREIGN KEY (tenant_id)   REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_kb_articles_tenant   ON kb_articles (tenant_id);
CREATE INDEX idx_kb_articles_category ON kb_articles (tenant_id, category_id);
CREATE INDEX idx_kb_articles_status   ON kb_articles (tenant_id, status_id);
CREATE INDEX idx_kb_articles_module   ON kb_articles (tenant_id, module_code, process_code);
CREATE INDEX idx_kb_articles_owner    ON kb_articles (tenant_id, owner_id);
CREATE INDEX idx_kb_articles_review   ON kb_articles (review_date) WHERE review_date IS NOT NULL;
CREATE INDEX idx_kb_articles_search   ON kb_articles USING GIN (search_vector);


-- ---------------------------------------------------------------------
-- Versions. Published versions are immutable: content is edited on a draft
-- version and publication swaps the pointer, so a procedure someone
-- followed last year can still be produced exactly as it stood.
-- ---------------------------------------------------------------------
CREATE TABLE kb_article_versions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    article_id       BIGINT       NOT NULL,
    version_major    INTEGER      NOT NULL DEFAULT 1,
    version_minor    INTEGER      NOT NULL DEFAULT 0,
    label            VARCHAR(32)  NOT NULL,
    content          TEXT,
    content_format   VARCHAR(32)  NOT NULL DEFAULT 'markdown',
    change_note      VARCHAR(2000),
    is_current       BOOLEAN      NOT NULL DEFAULT FALSE,
    is_published     BOOLEAN      NOT NULL DEFAULT FALSE,
    published_at     TIMESTAMPTZ,
    published_by     BIGINT,
    archived_at      TIMESTAMPTZ,
    created_by       BIGINT,
    created_by_email VARCHAR(255),
    tenant_id        BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_kb_article_versions PRIMARY KEY (id),
    CONSTRAINT uq_kb_article_versions UNIQUE (article_id, version_major, version_minor),
    CONSTRAINT uq_kb_article_versions_label UNIQUE (article_id, label),
    CONSTRAINT ck_kb_content_format CHECK (content_format IN ('markdown', 'html', 'text')),
    CONSTRAINT fk_kb_versions_article FOREIGN KEY (article_id) REFERENCES kb_articles (id) ON DELETE CASCADE,
    CONSTRAINT fk_kb_versions_tenant  FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_kb_versions_article ON kb_article_versions (article_id);
-- Exactly one draft-in-progress and one published version per article.
CREATE UNIQUE INDEX uq_kb_versions_current   ON kb_article_versions (article_id) WHERE is_current;
CREATE UNIQUE INDEX uq_kb_versions_published ON kb_article_versions (article_id) WHERE is_published;

ALTER TABLE kb_articles ADD CONSTRAINT fk_kb_articles_current_version
    FOREIGN KEY (current_version_id) REFERENCES kb_article_versions (id) ON DELETE SET NULL;
ALTER TABLE kb_articles ADD CONSTRAINT fk_kb_articles_published_version
    FOREIGN KEY (published_version_id) REFERENCES kb_article_versions (id) ON DELETE SET NULL;


-- =====================================================================
-- Standard operating procedures
--
-- An SOP is the structured face of an article VERSION, not of the article,
-- so its steps are versioned with the content and a published SOP cannot
-- change underneath the people following it.
-- =====================================================================
CREATE TABLE kb_sops (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    article_version_id BIGINT       NOT NULL,
    sop_number         VARCHAR(32)  NOT NULL,
    purpose            VARCHAR(2000),
    scope              VARCHAR(2000),
    required_inputs    JSONB        NOT NULL DEFAULT '[]'::jsonb,
    required_outputs   JSONB        NOT NULL DEFAULT '[]'::jsonb,
    estimated_minutes  INTEGER,
    risk_level_id      BIGINT,
    effective_date     DATE,
    review_date        DATE,
    tenant_id          BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version            BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_kb_sops PRIMARY KEY (id),
    CONSTRAINT uq_kb_sops_version UNIQUE (article_version_id),
    CONSTRAINT uq_kb_sops_number UNIQUE (tenant_id, sop_number, article_version_id),
    CONSTRAINT fk_kb_sops_version FOREIGN KEY (article_version_id) REFERENCES kb_article_versions (id) ON DELETE CASCADE,
    CONSTRAINT fk_kb_sops_risk    FOREIGN KEY (risk_level_id) REFERENCES kb_risk_levels (id),
    CONSTRAINT fk_kb_sops_tenant  FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);

-- Roles responsible for a procedure. Referenced by role id where the role
-- exists, or by a free-text label for roles the ERP does not yet model.
CREATE TABLE kb_sop_roles (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sop_id         BIGINT       NOT NULL,
    role_id        BIGINT,
    role_label     VARCHAR(160),
    responsibility VARCHAR(1000),
    is_accountable BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order  INTEGER      NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_kb_sop_roles PRIMARY KEY (id),
    CONSTRAINT ck_kb_sop_roles_identified CHECK (role_id IS NOT NULL OR role_label IS NOT NULL),
    CONSTRAINT fk_kb_sop_roles_sop  FOREIGN KEY (sop_id) REFERENCES kb_sops (id) ON DELETE CASCADE,
    CONSTRAINT fk_kb_sop_roles_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE SET NULL
);

CREATE TABLE kb_sop_steps (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sop_id            BIGINT       NOT NULL,
    parent_step_id    BIGINT,
    step_number       INTEGER      NOT NULL,
    step_type_id      BIGINT       NOT NULL,
    title             VARCHAR(255) NOT NULL,
    instruction       TEXT,
    expected_result   VARCHAR(2000),
    is_mandatory      BOOLEAN      NOT NULL DEFAULT TRUE,
    -- Steps sharing a parallel_group may be performed in any order.
    parallel_group    VARCHAR(64),
    condition_config  JSONB,
    -- Decision steps branch: {"yes": 4, "no": 7} referencing step numbers.
    branch_config     JSONB,
    estimated_minutes INTEGER,
    warning           VARCHAR(1000),
    display_order     INTEGER      NOT NULL DEFAULT 0,
    tenant_id         BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_kb_sop_steps PRIMARY KEY (id),
    CONSTRAINT uq_kb_sop_steps UNIQUE (sop_id, step_number),
    CONSTRAINT fk_kb_sop_steps_sop    FOREIGN KEY (sop_id) REFERENCES kb_sops (id) ON DELETE CASCADE,
    CONSTRAINT fk_kb_sop_steps_parent FOREIGN KEY (parent_step_id) REFERENCES kb_sop_steps (id) ON DELETE CASCADE,
    CONSTRAINT fk_kb_sop_steps_type   FOREIGN KEY (step_type_id) REFERENCES kb_step_types (id),
    CONSTRAINT fk_kb_sop_steps_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_kb_sop_steps_sop ON kb_sop_steps (sop_id, step_number);

CREATE TABLE kb_step_checklist_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    step_id       BIGINT       NOT NULL,
    text          VARCHAR(1000) NOT NULL,
    is_mandatory  BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_kb_step_checklist_items PRIMARY KEY (id),
    CONSTRAINT fk_kb_checklist_step FOREIGN KEY (step_id) REFERENCES kb_sop_steps (id) ON DELETE CASCADE
);


-- =====================================================================
-- Relationships, attachments, approvals, usage
-- =====================================================================

-- Article → article, or article → any business record. One table for both,
-- because "related to this repair" and "related to this article" are the
-- same navigational need from the reader's point of view.
CREATE TABLE kb_relations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    article_id       BIGINT       NOT NULL,
    relation_type_id BIGINT       NOT NULL,
    target_article_id BIGINT,
    target_module    VARCHAR(64),
    target_entity    VARCHAR(64),
    target_record_id BIGINT,
    note             VARCHAR(500),
    display_order    INTEGER      NOT NULL DEFAULT 0,
    tenant_id        BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_kb_relations PRIMARY KEY (id),
    -- A relation must point at exactly one kind of thing.
    CONSTRAINT ck_kb_relations_target CHECK (
        (target_article_id IS NOT NULL AND target_module IS NULL)
     OR (target_article_id IS NULL AND target_module IS NOT NULL AND target_record_id IS NOT NULL)),
    CONSTRAINT ck_kb_relations_not_self CHECK (target_article_id IS NULL OR target_article_id <> article_id),
    CONSTRAINT fk_kb_relations_article FOREIGN KEY (article_id) REFERENCES kb_articles (id) ON DELETE CASCADE,
    CONSTRAINT fk_kb_relations_target  FOREIGN KEY (target_article_id) REFERENCES kb_articles (id) ON DELETE CASCADE,
    CONSTRAINT fk_kb_relations_type    FOREIGN KEY (relation_type_id) REFERENCES kb_relation_types (id),
    CONSTRAINT fk_kb_relations_tenant  FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_kb_relations_article ON kb_relations (article_id);
CREATE INDEX idx_kb_relations_entity  ON kb_relations (tenant_id, target_module, target_entity, target_record_id);

-- Attachments are REFERENCES into the files module (V18). No bytes here.
CREATE TABLE kb_attachments (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    article_version_id BIGINT       NOT NULL,
    step_id            BIGINT,
    file_uuid          UUID,
    external_url       VARCHAR(2000),
    kind               VARCHAR(32)  NOT NULL DEFAULT 'document',
    caption            VARCHAR(500),
    display_order      INTEGER      NOT NULL DEFAULT 0,
    tenant_id          BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version            BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_kb_attachments PRIMARY KEY (id),
    -- Either a managed file or an external link, never both and never neither.
    CONSTRAINT ck_kb_attachments_source CHECK (
        (file_uuid IS NOT NULL AND external_url IS NULL)
     OR (file_uuid IS NULL AND external_url IS NOT NULL)),
    CONSTRAINT ck_kb_attachments_kind CHECK (kind IN ('image', 'video', 'document', 'spreadsheet', 'link', 'template')),
    CONSTRAINT fk_kb_attachments_version FOREIGN KEY (article_version_id) REFERENCES kb_article_versions (id) ON DELETE CASCADE,
    CONSTRAINT fk_kb_attachments_step    FOREIGN KEY (step_id) REFERENCES kb_sop_steps (id) ON DELETE CASCADE,
    CONSTRAINT fk_kb_attachments_tenant  FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_kb_attachments_version ON kb_attachments (article_version_id);

CREATE TABLE kb_approvals (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    article_version_id BIGINT       NOT NULL,
    stage_id           BIGINT       NOT NULL,
    decision           VARCHAR(32)  NOT NULL DEFAULT 'pending',
    approver_id        BIGINT,
    approver_email     VARCHAR(255),
    decided_at         TIMESTAMPTZ,
    comment            VARCHAR(2000),
    signature_ref      VARCHAR(255),
    tenant_id          BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version            BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_kb_approvals PRIMARY KEY (id),
    CONSTRAINT uq_kb_approvals UNIQUE (article_version_id, stage_id),
    CONSTRAINT ck_kb_approvals_decision CHECK (decision IN ('pending', 'approved', 'rejected', 'skipped')),
    CONSTRAINT fk_kb_approvals_version FOREIGN KEY (article_version_id) REFERENCES kb_article_versions (id) ON DELETE CASCADE,
    CONSTRAINT fk_kb_approvals_stage   FOREIGN KEY (stage_id) REFERENCES kb_approval_stages (id),
    CONSTRAINT fk_kb_approvals_tenant  FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_kb_approvals_version ON kb_approvals (article_version_id);

-- Usage tracking. Records the business context a reader came from, which is
-- what makes the "knowledge coverage" and "unused articles" reports useful.
CREATE TABLE kb_article_views (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    article_id      BIGINT       NOT NULL,
    version_id      BIGINT,
    viewer_id       BIGINT,
    viewer_email    VARCHAR(255),
    context_module  VARCHAR(64),
    context_entity  VARCHAR(64),
    context_record_id BIGINT,
    viewed_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    tenant_id       BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_kb_article_views PRIMARY KEY (id),
    CONSTRAINT fk_kb_views_article FOREIGN KEY (article_id) REFERENCES kb_articles (id) ON DELETE CASCADE,
    CONSTRAINT fk_kb_views_tenant  FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_kb_views_article ON kb_article_views (article_id, viewed_at DESC);
CREATE INDEX idx_kb_views_context ON kb_article_views (tenant_id, context_module, context_entity);

CREATE TABLE kb_audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    entity_type VARCHAR(64)  NOT NULL,
    entity_id   BIGINT,
    action      VARCHAR(64)  NOT NULL,
    old_values  JSONB,
    new_values  JSONB,
    actor_id    BIGINT,
    actor_email VARCHAR(255),
    actor_ip    VARCHAR(64),
    tenant_id   BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_kb_audit_log PRIMARY KEY (id),
    CONSTRAINT fk_kb_audit_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_kb_audit_entity ON kb_audit_log (tenant_id, entity_type, entity_id);


-- =====================================================================
-- Full-text search
--
-- The configuration is chosen from the article's language. PostgreSQL has
-- no Persian dictionary, so Persian uses 'simple': correct tokenisation,
-- no stemming. Swapping in a real dictionary later means changing this
-- function, not the schema.
-- =====================================================================
CREATE FUNCTION kb_search_config(lang VARCHAR) RETURNS REGCONFIG
    LANGUAGE sql IMMUTABLE
    AS $$ SELECT CASE WHEN lang = 'en' THEN 'english'::regconfig ELSE 'simple'::regconfig END $$;

CREATE FUNCTION kb_refresh_search_vector() RETURNS TRIGGER
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.search_vector :=
        setweight(to_tsvector(kb_search_config(NEW.language), coalesce(NEW.title, '')),    'A') ||
        setweight(to_tsvector(kb_search_config(NEW.language), coalesce(NEW.keywords, '')), 'B') ||
        setweight(to_tsvector(kb_search_config(NEW.language), coalesce(NEW.summary, '')),  'C') ||
        setweight(to_tsvector(kb_search_config(NEW.language), coalesce(NEW.article_code, '')), 'D');
    RETURN NEW;
END $$;

CREATE TRIGGER trg_kb_articles_search
    BEFORE INSERT OR UPDATE OF title, summary, keywords, article_code, language
    ON kb_articles
    FOR EACH ROW EXECUTE FUNCTION kb_refresh_search_vector();


-- ---------------------------------------------------------------------
-- Module + permissions.
-- ---------------------------------------------------------------------
INSERT INTO modules (code, name, description, icon, path, display_order, enabled, is_system)
VALUES ('knowledge', 'Knowledge Base', 'Articles, standard operating procedures and policies',
        'mdi-book-open-page-variant-outline', '/knowledge', 160, TRUE, TRUE);

INSERT INTO permissions (module_id, action, code, name, is_system)
SELECT m.id, a.action, m.code || ':' || a.action, m.name || ' — ' || a.label, TRUE
FROM modules m
CROSS JOIN (VALUES
    ('view',         'View knowledge base'),
    ('create',       'Create articles'),
    ('edit',         'Edit articles'),
    ('delete',       'Delete articles'),
    ('approve',      'Approve articles'),
    ('publish',      'Publish articles'),
    ('manage-sops',  'Manage standard operating procedures'),
    ('export',       'Export knowledge')
) AS a(action, label)
WHERE m.code = 'knowledge';
