-- =====================================================================
-- V22 — Organisation hierarchy: companies and branches
--
-- Executes decision D-C in docs/platform-architecture.md ("org hierarchy
-- required — reverses the V16 deferral"). Seven migrations since V10 have
-- declared `company_id` / `branch_id` columns with nothing to point at;
-- this migration creates the targets and wires the existing columns up.
--
-- Scope discipline. This is deliberately small. It is NOT an HR module:
-- there are no employees, no org charts, no cost centres, no reporting
-- lines. It answers exactly one question — "which legal entity and which
-- physical location does this row belong to?" — because that is what the
-- scheduler (V24) needs to scope a resource, and what every module since
-- V10 has been unable to express.
--
-- Behaviour is data. Branch capability lives in `branch_types` as
-- behavioural flags (`allows_appointments`, `allows_repair`, …), never as
-- a service testing for the string 'warehouse'. A new kind of location is
-- an INSERT.
--
-- Multi-tenancy. Both tables are Tier T (tenant-owned, NOT NULL
-- tenant_id) per docs/tenancy.md. `branch_types` is Tier S: a NULL tenant
-- means a platform-wide default that every tenant inherits.
-- =====================================================================


-- ---------------------------------------------------------------------
-- Legal entities. Self-referencing so a group structure (holding company
-- with subsidiaries) is representable without a second table; a flat
-- single-company install simply leaves parent_company_id NULL.
-- ---------------------------------------------------------------------
CREATE TABLE companies (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                    VARCHAR(64)  NOT NULL,
    name                    VARCHAR(255) NOT NULL,
    legal_name              VARCHAR(255),
    parent_company_id       BIGINT,

    tax_number              VARCHAR(64),
    registration_number     VARCHAR(64),

    -- Defaults inherited by branches that do not override them.
    currency_code           VARCHAR(8)   NOT NULL DEFAULT 'IRR',
    timezone                VARCHAR(64)  NOT NULL DEFAULT 'Asia/Tehran',
    locale                  VARCHAR(16)  NOT NULL DEFAULT 'fa',

    -- Drives fiscal-period arithmetic. 1 = January; the Persian fiscal
    -- year starting in Farvardin maps to 3 (Gregorian March).
    fiscal_year_start_month SMALLINT     NOT NULL DEFAULT 1,

    email                   VARCHAR(255),
    phone                   VARCHAR(64),
    website                 VARCHAR(255),

    address_line1           VARCHAR(255),
    address_line2           VARCHAR(255),
    city                    VARCHAR(128),
    state                   VARCHAR(128),
    postal_code             VARCHAR(32),
    country_code            VARCHAR(8),

    -- Reference into the files module (V18) by UUID. No bytes here.
    logo_file_uuid          UUID,

    is_default              BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active               BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order           INTEGER      NOT NULL DEFAULT 0,

    tenant_id               BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version                 BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_companies PRIMARY KEY (id),
    CONSTRAINT fk_companies_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT fk_companies_parent FOREIGN KEY (parent_company_id) REFERENCES companies (id) ON DELETE SET NULL,
    CONSTRAINT ck_companies_fiscal_month CHECK (fiscal_year_start_month BETWEEN 1 AND 12),
    CONSTRAINT ck_companies_not_own_parent CHECK (parent_company_id IS NULL OR parent_company_id <> id)
);

CREATE UNIQUE INDEX uq_companies_code ON companies (tenant_id, code);
CREATE UNIQUE INDEX uq_companies_default ON companies (tenant_id) WHERE is_default;
CREATE INDEX ix_companies_parent ON companies (parent_company_id) WHERE parent_company_id IS NOT NULL;
CREATE INDEX ix_companies_active ON companies (tenant_id, is_active);


-- ---------------------------------------------------------------------
-- What a location is allowed to do. The scheduler reads
-- `allows_appointments` to decide whether a branch can host bookings at
-- all — a warehouse cannot, a service centre can — without knowing any
-- branch-type names.
-- ---------------------------------------------------------------------
CREATE TABLE branch_types (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                 VARCHAR(64)  NOT NULL,
    name                 VARCHAR(100) NOT NULL,
    description          VARCHAR(500),

    allows_sales         BOOLEAN      NOT NULL DEFAULT FALSE,
    allows_inventory     BOOLEAN      NOT NULL DEFAULT FALSE,
    allows_repair        BOOLEAN      NOT NULL DEFAULT FALSE,
    allows_appointments  BOOLEAN      NOT NULL DEFAULT FALSE,
    allows_walk_in       BOOLEAN      NOT NULL DEFAULT FALSE,
    is_customer_facing   BOOLEAN      NOT NULL DEFAULT FALSE,

    is_default           BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system            BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order        INTEGER      NOT NULL DEFAULT 0,

    tenant_id            BIGINT,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version              BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_branch_types PRIMARY KEY (id),
    CONSTRAINT fk_branch_types_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uq_branch_types_code_global ON branch_types (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_branch_types_code_tenant ON branch_types (tenant_id, code) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_branch_types_default_global ON branch_types ((TRUE)) WHERE is_default AND tenant_id IS NULL;
CREATE UNIQUE INDEX uq_branch_types_default_tenant ON branch_types (tenant_id) WHERE is_default AND tenant_id IS NOT NULL;


-- ---------------------------------------------------------------------
-- Physical locations. `timezone` is nullable and falls back to the
-- company's: a chain operating in one timezone configures it once, while
-- a cross-border group can still override per site. The scheduler resolves
-- this fallback in one place (BranchService.zoneOf) so no caller has to.
-- ---------------------------------------------------------------------
CREATE TABLE branches (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    company_id          BIGINT       NOT NULL,
    branch_type_id      BIGINT       NOT NULL,

    code                VARCHAR(64)  NOT NULL,
    name                VARCHAR(255) NOT NULL,
    description         VARCHAR(500),

    email               VARCHAR(255),
    phone               VARCHAR(64),

    address_line1       VARCHAR(255),
    address_line2       VARCHAR(255),
    city                VARCHAR(128),
    state               VARCHAR(128),
    postal_code         VARCHAR(32),
    country_code        VARCHAR(8),
    latitude            NUMERIC(10, 7),
    longitude           NUMERIC(10, 7),

    -- NULL means "inherit from the owning company".
    timezone            VARCHAR(64),

    manager_user_id     BIGINT,

    is_default          BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active           BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order       INTEGER      NOT NULL DEFAULT 0,

    opened_on           DATE,
    closed_on           DATE,

    tenant_id           BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version             BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_branches PRIMARY KEY (id),
    CONSTRAINT fk_branches_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
    CONSTRAINT fk_branches_type FOREIGN KEY (branch_type_id) REFERENCES branch_types (id),
    CONSTRAINT fk_branches_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT fk_branches_manager FOREIGN KEY (manager_user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT ck_branches_closed_after_open CHECK (closed_on IS NULL OR opened_on IS NULL OR closed_on >= opened_on)
);

CREATE UNIQUE INDEX uq_branches_code ON branches (company_id, code);
CREATE UNIQUE INDEX uq_branches_default ON branches (company_id) WHERE is_default;
CREATE INDEX ix_branches_company ON branches (company_id, is_active);
CREATE INDEX ix_branches_tenant ON branches (tenant_id);
CREATE INDEX ix_branches_type ON branches (branch_type_id);


-- =====================================================================
-- Seed
-- =====================================================================

INSERT INTO branch_types (code, name, description, allows_sales, allows_inventory, allows_repair,
                          allows_appointments, allows_walk_in, is_customer_facing,
                          is_default, is_system, display_order)
VALUES
    ('RETAIL_STORE',   'Retail Store',   'Customer-facing sales floor',              TRUE,  TRUE,  FALSE, TRUE,  TRUE,  TRUE,  TRUE,  TRUE, 10),
    ('SERVICE_CENTER', 'Service Centre', 'Device repair and warranty inspection',    FALSE, TRUE,  TRUE,  TRUE,  TRUE,  TRUE,  FALSE, TRUE, 20),
    ('FLAGSHIP',       'Flagship Store', 'Sales, repair and consultation combined',  TRUE,  TRUE,  TRUE,  TRUE,  TRUE,  TRUE,  FALSE, TRUE, 30),
    ('WAREHOUSE',      'Warehouse',      'Stock holding, no customer access',        FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 40),
    ('KIOSK',          'Kiosk',          'Compact sales point',                      TRUE,  FALSE, FALSE, FALSE, TRUE,  TRUE,  FALSE, TRUE, 50),
    ('HEAD_OFFICE',    'Head Office',    'Administrative site, internal meetings',   FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, TRUE, 60);

-- One company and one branch so every existing row has somewhere to belong.
-- Names are deliberately generic; an installation renames them on day one.
INSERT INTO companies (code, name, legal_name, is_default, is_active, display_order)
VALUES ('DEFAULT', 'Default Company', 'Default Company', TRUE, TRUE, 10);

INSERT INTO branches (company_id, branch_type_id, code, name, is_default, is_active, display_order)
SELECT c.id, bt.id, 'MAIN', 'Main Branch', TRUE, TRUE, 10
FROM companies c
CROSS JOIN branch_types bt
WHERE c.code = 'DEFAULT' AND bt.code = 'FLAGSHIP';


-- =====================================================================
-- Retrofit the orphan columns
--
-- Every `company_id` / `branch_id` declared since V10 has been a bare
-- BIGINT with no referent. They are all nullable and, on any existing
-- installation, all NULL — nothing has ever written them, because there
-- was nothing to write. Adding the constraint now is therefore additive:
-- it changes no data and rejects no existing row, but from here on a
-- typo'd id fails at the database instead of silently pointing nowhere.
--
-- Left nullable on purpose. NULL keeps its established meaning of
-- "applies across the organisation" — the same convention tenant_id uses
-- for platform-wide rows. Forcing a company onto every row would break
-- global dashboard widgets and global metadata definitions.
-- =====================================================================

DO $$
DECLARE
    r RECORD;
    orphans BIGINT;
BEGIN
    FOR r IN
        SELECT c.table_name, c.column_name,
               CASE c.column_name WHEN 'company_id' THEN 'companies' ELSE 'branches' END AS target
        FROM information_schema.columns c
        JOIN information_schema.tables t
          ON t.table_schema = c.table_schema AND t.table_name = c.table_name
        WHERE c.table_schema = current_schema()
          AND c.column_name IN ('company_id', 'branch_id')
          AND t.table_type = 'BASE TABLE'
          AND c.table_name NOT IN ('companies', 'branches')
    LOOP
        -- Never add a constraint that would fail: if an installation has
        -- somehow written ids, leave the column alone and say so rather
        -- than aborting the whole migration.
        EXECUTE format(
            'SELECT count(*) FROM %I x WHERE x.%I IS NOT NULL '
            'AND NOT EXISTS (SELECT 1 FROM %I y WHERE y.id = x.%I)',
            r.table_name, r.column_name, r.target, r.column_name)
        INTO orphans;

        IF orphans > 0 THEN
            RAISE WARNING 'V22: %.% has % unresolvable value(s); FK not added',
                r.table_name, r.column_name, orphans;
            CONTINUE;
        END IF;

        EXECUTE format(
            'ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY (%I) REFERENCES %I (id) ON DELETE SET NULL',
            r.table_name, 'fk_' || r.table_name || '_' || r.column_name, r.column_name, r.target);
    END LOOP;
END $$;


-- =====================================================================
-- Module registration and permissions
-- =====================================================================

INSERT INTO modules (code, name, description, icon, path, display_order, enabled, is_system)
VALUES ('organization', 'Organisation', 'Companies, branches and locations',
        'mdi-office-building-outline', '/organization', 20, TRUE, TRUE);

INSERT INTO permissions (module_id, action, code, name, is_system)
SELECT m.id, a.action, m.code || ':' || a.action, m.name || ' — ' || a.label, TRUE
FROM modules m
CROSS JOIN (VALUES
    ('view',            'View companies and branches'),
    ('create',          'Create companies and branches'),
    ('edit',            'Edit companies and branches'),
    ('delete',          'Delete companies and branches'),
    ('manage-types',    'Manage branch types')
) AS a(action, label)
WHERE m.code = 'organization';


-- =====================================================================
-- Post-migration assertions. A migration that half-applied is worse than
-- one that failed, so prove the invariants before committing.
-- =====================================================================

DO $$
DECLARE
    company_count BIGINT;
    branch_count  BIGINT;
    type_count    BIGINT;
BEGIN
    SELECT count(*) INTO company_count FROM companies WHERE is_default;
    SELECT count(*) INTO branch_count  FROM branches  WHERE is_default;
    SELECT count(*) INTO type_count    FROM branch_types WHERE is_default;

    IF company_count <> 1 THEN
        RAISE EXCEPTION 'V22: expected exactly 1 default company, found %', company_count;
    END IF;
    IF branch_count <> 1 THEN
        RAISE EXCEPTION 'V22: expected exactly 1 default branch, found %', branch_count;
    END IF;
    IF type_count <> 1 THEN
        RAISE EXCEPTION 'V22: expected exactly 1 default branch type, found %', type_count;
    END IF;
END $$;
