-- =====================================================================
-- V26 — Enterprise Communication Hub & Omnichannel Messaging
--
-- The DELIVERY half of messaging: HOW a message reaches a person over a
-- channel, through which provider, with what retry/expiry behaviour, and
-- with a permanent, entity-linked record of what happened.
--
-- It is NOT a notification centre. Deciding WHAT to send and to WHOM is
-- the caller's job (the future notification module, the scheduler's
-- reminders, workflow, campaigns). This module accepts a send request
-- and owns everything after it: routing, templating, dispatch, retry,
-- fallback, tracking, history.
--
-- WHAT THIS ABSORBS (and deliberately does not duplicate):
--   * common/mail/MailSender — the password-reset port stays, but a real
--     provider now backs it through this module's SMTP handler.
--   * V24 reminder_channels — the scheduler keeps its ReminderChannelHandler
--     SPI; this module registers the handlers those inactive rows have
--     been waiting for. Activating a reminder channel is now a data flip.
--   * sup_channels (V9) is a CRM record of a supplier's PREFERRED contact
--     routes — preference data, not delivery machinery. Untouched.
--
-- Behaviour is data throughout: channel types, providers, statuses,
-- delivery policies, routing rules and templates are all configuration
-- rows resolved through SPI registries. A provider row whose handler_key
-- has no bean is inert configuration — the WhatsApp row can exist today
-- and start delivering the day its handler bean ships, with no migration.
--
-- THE OUTBOUND GUARANTEE. A message is a row FIRST, then a delivery
-- attempt (transactional-outbox shape). Dispatch failure can never lose a
-- message: the row stays queued with attempts/next_attempt_at and the
-- sweep (a V19 scheduled job, seeded draft) retries it under the
-- channel's delivery policy until it succeeds, exhausts retries, or
-- expires. Duplicate sends are stopped at the database by a unique
-- idempotency key, not by caller discipline.
-- =====================================================================


-- ---------------------------------------------------------------------
-- Channel taxonomy. Behavioural flags drive validation and capability
-- checks; no service ever tests for the string 'SMS'.
-- ---------------------------------------------------------------------
CREATE TABLE comm_channel_types (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                   VARCHAR(64)  NOT NULL,
    name                   VARCHAR(100) NOT NULL,
    description            VARCHAR(500),
    icon                   VARCHAR(64),

    -- What a recipient address must be, and what the channel can carry.
    requires_phone         BOOLEAN      NOT NULL DEFAULT FALSE,
    requires_email         BOOLEAN      NOT NULL DEFAULT FALSE,
    requires_device_token  BOOLEAN      NOT NULL DEFAULT FALSE,
    supports_subject       BOOLEAN      NOT NULL DEFAULT FALSE,
    supports_attachments   BOOLEAN      NOT NULL DEFAULT FALSE,
    supports_conversations BOOLEAN      NOT NULL DEFAULT FALSE,
    supports_read_receipt  BOOLEAN      NOT NULL DEFAULT FALSE,
    -- 0 = unlimited. SMS is the reason this exists.
    max_body_length        INTEGER      NOT NULL DEFAULT 0,
    max_attachment_bytes   BIGINT       NOT NULL DEFAULT 0,

    is_default             BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system              BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active              BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order          INTEGER      NOT NULL DEFAULT 0,

    tenant_id              BIGINT,
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version                BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_comm_channel_types PRIMARY KEY (id),
    CONSTRAINT fk_comm_channel_types_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT ck_comm_channel_types_limits CHECK (max_body_length >= 0 AND max_attachment_bytes >= 0)
);
CREATE UNIQUE INDEX uq_comm_channel_types_code_global ON comm_channel_types (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_comm_channel_types_code_tenant ON comm_channel_types (tenant_id, code) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_comm_channel_types_default ON comm_channel_types ((TRUE)) WHERE is_default AND tenant_id IS NULL;


-- ---------------------------------------------------------------------
-- Providers: WHO physically delivers. `handler_key` resolves to a
-- CommProviderHandler bean; `config` holds provider-specific settings
-- (endpoints, sender ids — NEVER secrets; credentials stay in
-- environment variables referenced BY NAME from config).
-- ---------------------------------------------------------------------
CREATE TABLE comm_providers (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code           VARCHAR(64)  NOT NULL,
    name           VARCHAR(100) NOT NULL,
    description    VARCHAR(500),
    handler_key    VARCHAR(64)  NOT NULL,
    config         JSONB,

    is_default     BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order  INTEGER      NOT NULL DEFAULT 0,

    tenant_id      BIGINT,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version        BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_comm_providers PRIMARY KEY (id),
    CONSTRAINT fk_comm_providers_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_comm_providers_code_global ON comm_providers (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_comm_providers_code_tenant ON comm_providers (tenant_id, code) WHERE tenant_id IS NOT NULL;


CREATE TABLE comm_channel_statuses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code            VARCHAR(64)  NOT NULL,
    name            VARCHAR(100) NOT NULL,
    color           VARCHAR(16),
    -- The operative flag: may messages be dispatched through the channel?
    allows_sending  BOOLEAN      NOT NULL DEFAULT FALSE,
    -- Testing mode: dispatch runs but only to allow-listed test recipients.
    is_test_mode    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_default      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system       BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order   INTEGER      NOT NULL DEFAULT 0,
    tenant_id       BIGINT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_comm_channel_statuses PRIMARY KEY (id),
    CONSTRAINT fk_comm_channel_statuses_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_comm_channel_statuses_code_global ON comm_channel_statuses (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_comm_channel_statuses_code_tenant ON comm_channel_statuses (tenant_id, code) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_comm_channel_statuses_default ON comm_channel_statuses ((TRUE)) WHERE is_default AND tenant_id IS NULL;


-- ---------------------------------------------------------------------
-- Delivery behaviour, as data. Backoff is base_interval * multiplier^n
-- so "3 tries, a minute apart" and "6 tries, exponential" are both rows.
-- ---------------------------------------------------------------------
CREATE TABLE comm_delivery_policies (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                        VARCHAR(64)  NOT NULL,
    name                        VARCHAR(100) NOT NULL,
    description                 VARCHAR(500),

    max_attempts                INTEGER      NOT NULL DEFAULT 3,
    retry_base_seconds          INTEGER      NOT NULL DEFAULT 60,
    retry_backoff_multiplier    NUMERIC(4,2) NOT NULL DEFAULT 2.0,
    retry_max_seconds           INTEGER      NOT NULL DEFAULT 3600,
    -- Per-attempt provider timeout.
    timeout_seconds             INTEGER      NOT NULL DEFAULT 30,
    -- Queued messages older than this are expired, never sent late. 0 = never.
    expiration_minutes          INTEGER      NOT NULL DEFAULT 0,

    requires_delivery_receipt   BOOLEAN      NOT NULL DEFAULT FALSE,
    requires_read_receipt       BOOLEAN      NOT NULL DEFAULT FALSE,

    is_default                  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system                   BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order               INTEGER      NOT NULL DEFAULT 0,

    tenant_id                   BIGINT,
    created_at                  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version                     BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_comm_delivery_policies PRIMARY KEY (id),
    CONSTRAINT fk_comm_delivery_policies_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT ck_comm_delivery_policies_sane CHECK (
        max_attempts >= 1 AND retry_base_seconds >= 1
        AND retry_backoff_multiplier >= 1.0 AND retry_max_seconds >= retry_base_seconds
        AND timeout_seconds >= 1 AND expiration_minutes >= 0)
);
CREATE UNIQUE INDEX uq_comm_delivery_policies_code_global ON comm_delivery_policies (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_comm_delivery_policies_code_tenant ON comm_delivery_policies (tenant_id, code) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_comm_delivery_policies_default ON comm_delivery_policies ((TRUE)) WHERE is_default AND tenant_id IS NULL;


-- ---------------------------------------------------------------------
-- A channel: a type served by a provider under a policy, scoped to an
-- organisation. "SMS via Gateway-A for Branch 1" and "SMS via Gateway-B
-- for Branch 2" are two rows with different priorities — which is what
-- makes provider fallback a data question.
-- ---------------------------------------------------------------------
CREATE TABLE comm_channels (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                VARCHAR(64)  NOT NULL,
    name                VARCHAR(100) NOT NULL,
    description         VARCHAR(500),

    channel_type_id     BIGINT       NOT NULL,
    provider_id         BIGINT       NOT NULL,
    status_id           BIGINT       NOT NULL,
    delivery_policy_id  BIGINT,

    company_id          BIGINT,
    branch_id           BIGINT,

    -- Higher wins among channels of the same type when routing.
    priority            INTEGER      NOT NULL DEFAULT 0,

    -- Sender identity presented to recipients (from-address, sender id).
    sender_address      VARCHAR(255),

    tenant_id           BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version             BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_comm_channels PRIMARY KEY (id),
    CONSTRAINT fk_comm_channels_type FOREIGN KEY (channel_type_id) REFERENCES comm_channel_types (id),
    CONSTRAINT fk_comm_channels_provider FOREIGN KEY (provider_id) REFERENCES comm_providers (id),
    CONSTRAINT fk_comm_channels_status FOREIGN KEY (status_id) REFERENCES comm_channel_statuses (id),
    CONSTRAINT fk_comm_channels_policy FOREIGN KEY (delivery_policy_id) REFERENCES comm_delivery_policies (id),
    CONSTRAINT fk_comm_channels_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE SET NULL,
    CONSTRAINT fk_comm_channels_branch FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE SET NULL,
    CONSTRAINT fk_comm_channels_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_comm_channels_code ON comm_channels (tenant_id, code);
CREATE INDEX ix_comm_channels_type ON comm_channels (channel_type_id, priority DESC);
CREATE INDEX ix_comm_channels_branch ON comm_channels (branch_id) WHERE branch_id IS NOT NULL;


-- ---------------------------------------------------------------------
-- Routing rules: which channel type to prefer, and where to fall back,
-- optionally scoped to a calling module. Evaluated in priority order;
-- first match wins. `respect_business_hours` defers non-urgent sends to
-- the next working window via the V23 calendar — the "no marketing SMS
-- at 3 a.m." rule as a column instead of a code branch.
-- ---------------------------------------------------------------------
CREATE TABLE comm_routing_rules (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                    VARCHAR(64)  NOT NULL,
    name                    VARCHAR(100) NOT NULL,
    description             VARCHAR(500),

    -- NULL = applies to every module.
    module_code             VARCHAR(64),
    -- Only messages at or above this priority match. 0 = all.
    min_message_priority    INTEGER      NOT NULL DEFAULT 0,

    preferred_channel_id    BIGINT       NOT NULL,
    fallback_channel_id     BIGINT,

    respect_business_hours  BOOLEAN      NOT NULL DEFAULT FALSE,
    -- Urgent overrides: a message at/above this priority ignores business
    -- hours even when the rule respects them. 0 = never override.
    emergency_priority      INTEGER      NOT NULL DEFAULT 0,

    is_active               BOOLEAN      NOT NULL DEFAULT TRUE,
    priority                INTEGER      NOT NULL DEFAULT 0,

    tenant_id               BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version                 BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_comm_routing_rules PRIMARY KEY (id),
    CONSTRAINT fk_comm_routing_pref FOREIGN KEY (preferred_channel_id) REFERENCES comm_channels (id) ON DELETE CASCADE,
    CONSTRAINT fk_comm_routing_fallback FOREIGN KEY (fallback_channel_id) REFERENCES comm_channels (id) ON DELETE SET NULL,
    CONSTRAINT fk_comm_routing_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_comm_routing_rules_code ON comm_routing_rules (tenant_id, code);
CREATE INDEX ix_comm_routing_rules_eval ON comm_routing_rules (priority DESC) WHERE is_active;


-- ---------------------------------------------------------------------
-- Templates. `{{variable}}` placeholders; `variables` declares the
-- allowed names. Rendering is FAIL-CLOSED both ways: an undeclared
-- placeholder in the template and a missing value at send time are both
-- errors — a customer must never receive "Dear {{name}}".
-- ---------------------------------------------------------------------
CREATE TABLE comm_templates (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code              VARCHAR(64)  NOT NULL,
    name              VARCHAR(100) NOT NULL,
    description       VARCHAR(500),

    -- NULL = usable on any channel type.
    channel_type_id   BIGINT,
    module_code       VARCHAR(64),

    language          VARCHAR(16)  NOT NULL DEFAULT 'fa',
    subject_template  VARCHAR(500),
    body_template     TEXT         NOT NULL,
    -- Declared placeholder names, e.g. ["customerName","amount","dueDate"].
    variables         JSONB,

    -- Editing creates a new revision and deactivates the old one, so a
    -- message row's template_id always shows the exact text that was sent.
    revision          INTEGER      NOT NULL DEFAULT 1,
    is_active         BOOLEAN      NOT NULL DEFAULT TRUE,
    is_system         BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order     INTEGER      NOT NULL DEFAULT 0,

    tenant_id         BIGINT,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version           BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_comm_templates PRIMARY KEY (id),
    CONSTRAINT fk_comm_templates_type FOREIGN KEY (channel_type_id) REFERENCES comm_channel_types (id) ON DELETE SET NULL,
    CONSTRAINT fk_comm_templates_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
-- Uniqueness is per ACTIVE revision: history keeps the code, only one live.
CREATE UNIQUE INDEX uq_comm_templates_code_global ON comm_templates (code, language) WHERE is_active AND tenant_id IS NULL;
CREATE UNIQUE INDEX uq_comm_templates_code_tenant ON comm_templates (tenant_id, code, language) WHERE is_active AND tenant_id IS NOT NULL;


CREATE TABLE comm_message_statuses (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code               VARCHAR(64)  NOT NULL,
    name               VARCHAR(100) NOT NULL,
    color              VARCHAR(16),

    is_queued_state    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_sending_state   BOOLEAN      NOT NULL DEFAULT FALSE,
    is_sent_state      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_delivered_state BOOLEAN      NOT NULL DEFAULT FALSE,
    is_read_state      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_failed_state    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_expired_state   BOOLEAN      NOT NULL DEFAULT FALSE,
    is_cancelled_state BOOLEAN      NOT NULL DEFAULT FALSE,

    -- May the sweep retry a message in this status?
    allows_retry       BOOLEAN      NOT NULL DEFAULT FALSE,
    is_terminal        BOOLEAN      NOT NULL DEFAULT FALSE,
    counts_as_success  BOOLEAN      NOT NULL DEFAULT FALSE,

    is_default         BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system          BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order      INTEGER      NOT NULL DEFAULT 0,
    tenant_id          BIGINT,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version            BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_comm_message_statuses PRIMARY KEY (id),
    CONSTRAINT fk_comm_message_statuses_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_comm_message_statuses_code_global ON comm_message_statuses (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_comm_message_statuses_code_tenant ON comm_message_statuses (tenant_id, code) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_comm_message_statuses_default ON comm_message_statuses ((TRUE)) WHERE is_default AND tenant_id IS NULL;


CREATE TABLE comm_conversation_statuses (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code           VARCHAR(64)  NOT NULL,
    name           VARCHAR(100) NOT NULL,
    color          VARCHAR(16),
    is_open_state  BOOLEAN      NOT NULL DEFAULT FALSE,
    allows_reply   BOOLEAN      NOT NULL DEFAULT FALSE,
    is_terminal    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_default     BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system      BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order  INTEGER      NOT NULL DEFAULT 0,
    tenant_id      BIGINT,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_comm_conversation_statuses PRIMARY KEY (id),
    CONSTRAINT fk_comm_conversation_statuses_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_comm_conv_statuses_code_global ON comm_conversation_statuses (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_comm_conv_statuses_code_tenant ON comm_conversation_statuses (tenant_id, code) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_comm_conv_statuses_default ON comm_conversation_statuses ((TRUE)) WHERE is_default AND tenant_id IS NULL;


-- ---------------------------------------------------------------------
-- Conversations: a thread of messages with a business context. The
-- entity link (module/type/id) is a soft reference resolved through the
-- caller's world — never an FK into business tables, same rule as V24.
-- ---------------------------------------------------------------------
CREATE TABLE comm_conversations (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    conversation_number  VARCHAR(32)  NOT NULL,
    subject              VARCHAR(255),

    channel_id           BIGINT       NOT NULL,
    status_id            BIGINT       NOT NULL,
    owner_user_id        BIGINT,

    customer_id          BIGINT,
    supplier_id          BIGINT,

    module_code          VARCHAR(64),
    related_entity_type  VARCHAR(64),
    related_entity_id    BIGINT,

    started_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_activity_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    closed_at            TIMESTAMPTZ,

    tenant_id            BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version              BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_comm_conversations PRIMARY KEY (id),
    CONSTRAINT fk_comm_conversations_channel FOREIGN KEY (channel_id) REFERENCES comm_channels (id),
    CONSTRAINT fk_comm_conversations_status FOREIGN KEY (status_id) REFERENCES comm_conversation_statuses (id),
    CONSTRAINT fk_comm_conversations_owner FOREIGN KEY (owner_user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_comm_conversations_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE SET NULL,
    CONSTRAINT fk_comm_conversations_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id) ON DELETE SET NULL,
    CONSTRAINT fk_comm_conversations_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_comm_conversations_number ON comm_conversations (tenant_id, conversation_number);
CREATE INDEX ix_comm_conversations_activity ON comm_conversations (last_activity_at DESC);
CREATE INDEX ix_comm_conversations_customer ON comm_conversations (customer_id) WHERE customer_id IS NOT NULL;
CREATE INDEX ix_comm_conversations_supplier ON comm_conversations (supplier_id) WHERE supplier_id IS NOT NULL;
CREATE INDEX ix_comm_conversations_related ON comm_conversations (module_code, related_entity_type, related_entity_id)
    WHERE related_entity_id IS NOT NULL;


CREATE TABLE comm_conversation_participants (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    conversation_id  BIGINT       NOT NULL,
    -- USER | CUSTOMER | SUPPLIER | EXTERNAL
    participant_kind VARCHAR(32)  NOT NULL,
    participant_id   BIGINT,
    display_name     VARCHAR(255),
    address          VARCHAR(255),
    joined_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_comm_conversation_participants PRIMARY KEY (id),
    CONSTRAINT fk_comm_participants_conversation FOREIGN KEY (conversation_id)
        REFERENCES comm_conversations (id) ON DELETE CASCADE
);
CREATE INDEX ix_comm_participants_conversation ON comm_conversation_participants (conversation_id);


-- ---------------------------------------------------------------------
-- Messages: the permanent record. Row first, delivery second.
-- ---------------------------------------------------------------------
CREATE TABLE comm_messages (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message_number       VARCHAR(32)  NOT NULL,
    conversation_id      BIGINT,
    channel_id           BIGINT       NOT NULL,
    status_id            BIGINT       NOT NULL,
    template_id          BIGINT,

    -- OUTBOUND today; INBOUND reserved for the omnichannel-inbox future.
    direction            VARCHAR(16)  NOT NULL DEFAULT 'OUTBOUND',

    sender_user_id       BIGINT,
    recipient_address    VARCHAR(255) NOT NULL,
    customer_id          BIGINT,
    supplier_id          BIGINT,

    module_code          VARCHAR(64),
    related_entity_type  VARCHAR(64),
    related_entity_id    BIGINT,

    subject              VARCHAR(500),
    body                 TEXT         NOT NULL,
    language             VARCHAR(16)  NOT NULL DEFAULT 'fa',
    priority             INTEGER      NOT NULL DEFAULT 0,

    -- Caller-supplied dedup key; the partial unique index below is what
    -- actually prevents double delivery, not caller discipline.
    idempotency_key      VARCHAR(128),

    attempts             INTEGER      NOT NULL DEFAULT 0,
    next_attempt_at      TIMESTAMPTZ,
    last_error           VARCHAR(1000),
    provider_message_ref VARCHAR(255),

    queued_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    sent_at              TIMESTAMPTZ,
    delivered_at         TIMESTAMPTZ,
    read_at              TIMESTAMPTZ,
    failed_at            TIMESTAMPTZ,
    expires_at           TIMESTAMPTZ,

    tenant_id            BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version              BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_comm_messages PRIMARY KEY (id),
    CONSTRAINT fk_comm_messages_conversation FOREIGN KEY (conversation_id) REFERENCES comm_conversations (id) ON DELETE SET NULL,
    CONSTRAINT fk_comm_messages_channel FOREIGN KEY (channel_id) REFERENCES comm_channels (id),
    CONSTRAINT fk_comm_messages_status FOREIGN KEY (status_id) REFERENCES comm_message_statuses (id),
    CONSTRAINT fk_comm_messages_template FOREIGN KEY (template_id) REFERENCES comm_templates (id) ON DELETE SET NULL,
    CONSTRAINT fk_comm_messages_sender FOREIGN KEY (sender_user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_comm_messages_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE SET NULL,
    CONSTRAINT fk_comm_messages_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id) ON DELETE SET NULL,
    CONSTRAINT fk_comm_messages_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT ck_comm_messages_direction CHECK (direction IN ('OUTBOUND', 'INBOUND'))
);
CREATE UNIQUE INDEX uq_comm_messages_number ON comm_messages (tenant_id, message_number);
-- THE dedup guard: one live message per caller-supplied key.
CREATE UNIQUE INDEX uq_comm_messages_idempotency ON comm_messages (tenant_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;
-- The sweep's working set: retryable work that is due.
CREATE INDEX ix_comm_messages_due ON comm_messages (next_attempt_at) WHERE next_attempt_at IS NOT NULL;
CREATE INDEX ix_comm_messages_conversation ON comm_messages (conversation_id) WHERE conversation_id IS NOT NULL;
CREATE INDEX ix_comm_messages_recipient ON comm_messages (recipient_address);
CREATE INDEX ix_comm_messages_customer ON comm_messages (customer_id, created_at DESC) WHERE customer_id IS NOT NULL;
CREATE INDEX ix_comm_messages_related ON comm_messages (module_code, related_entity_type, related_entity_id)
    WHERE related_entity_id IS NOT NULL;
CREATE INDEX ix_comm_messages_status ON comm_messages (status_id, created_at DESC);


-- Attachment references into the files module (V18). No bytes here.
CREATE TABLE comm_message_attachments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message_id    BIGINT       NOT NULL,
    file_uuid     UUID         NOT NULL,
    file_name     VARCHAR(255) NOT NULL,
    content_type  VARCHAR(128),
    size_bytes    BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_comm_message_attachments PRIMARY KEY (id),
    CONSTRAINT fk_comm_attachments_message FOREIGN KEY (message_id) REFERENCES comm_messages (id) ON DELETE CASCADE
);
CREATE INDEX ix_comm_attachments_message ON comm_message_attachments (message_id);


-- Audit trail, same JSONB shape as kb_audit_log / schedule_audit_log.
CREATE TABLE comm_audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    entity_type  VARCHAR(64)  NOT NULL,
    entity_id    BIGINT       NOT NULL,
    action       VARCHAR(64)  NOT NULL,
    old_values   JSONB,
    new_values   JSONB,
    actor_id     BIGINT,
    actor_email  VARCHAR(255),
    actor_ip     VARCHAR(64),
    tenant_id    BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version      BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_comm_audit_log PRIMARY KEY (id),
    CONSTRAINT fk_comm_audit_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE INDEX ix_comm_audit_entity ON comm_audit_log (entity_type, entity_id, created_at DESC);


-- =====================================================================
-- Seed
-- =====================================================================

INSERT INTO comm_channel_types (code, name, description, icon, requires_phone, requires_email,
        requires_device_token, supports_subject, supports_attachments, supports_conversations,
        supports_read_receipt, max_body_length, max_attachment_bytes, is_default, is_system, display_order)
VALUES
    ('EMAIL',      'Email',            'SMTP / provider email',          'mdi-email-outline',        FALSE, TRUE,  FALSE, TRUE,  TRUE,  TRUE,  FALSE, 0,    26214400, TRUE,  TRUE, 10),
    ('SMS',        'SMS',              'Short text messages',            'mdi-message-text-outline', TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 1000, 0,        FALSE, TRUE, 20),
    ('WHATSAPP',   'WhatsApp',         'WhatsApp Business messages',     'mdi-whatsapp',             TRUE,  FALSE, FALSE, FALSE, TRUE,  TRUE,  TRUE,  4096, 16777216, FALSE, TRUE, 30),
    ('TELEGRAM',   'Telegram',         'Telegram bot messages',          'mdi-send-circle-outline',  FALSE, FALSE, FALSE, FALSE, TRUE,  TRUE,  FALSE, 4096, 52428800, FALSE, TRUE, 40),
    ('VOICE',      'Voice Call',       'Automated voice calls',          'mdi-phone-outline',        TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 0,    0,        FALSE, TRUE, 50),
    ('PUSH',       'Push Notification','Mobile push notifications',      'mdi-cellphone-message',    FALSE, FALSE, TRUE,  TRUE,  FALSE, FALSE, FALSE, 512,  0,        FALSE, TRUE, 60),
    ('WEB',        'Web Notification', 'Browser notifications',          'mdi-web',                  FALSE, FALSE, TRUE,  TRUE,  FALSE, FALSE, FALSE, 512,  0,        FALSE, TRUE, 70),
    ('IN_APP',     'In-App Message',   'Messages inside SAMI screens',   'mdi-application-outline',  FALSE, FALSE, FALSE, TRUE,  TRUE,  TRUE,  TRUE,  0,    10485760, FALSE, TRUE, 80),
    ('LIVE_CHAT',  'Live Chat',        'Portal live chat',               'mdi-chat-outline',         FALSE, FALSE, FALSE, FALSE, TRUE,  TRUE,  TRUE,  0,    10485760, FALSE, TRUE, 90);

-- Handlers that exist today: 'smtp' (wraps Spring mail / MailSender path)
-- and 'log' (development sink). Every other row is inert configuration
-- awaiting its bean — the same contract as V24's reminder channels.
INSERT INTO comm_providers (code, name, description, handler_key, config, is_default, is_system, display_order)
VALUES
    ('LOG',        'Development Log',       'Writes messages to the application log; for development and testing', 'log',      NULL, TRUE,  TRUE, 10),
    ('SMTP',       'SMTP Server',           'Standard SMTP relay',                                                 'smtp',     '{"hostEnv":"COMM_SMTP_HOST","portEnv":"COMM_SMTP_PORT","userEnv":"COMM_SMTP_USER","passwordEnv":"COMM_SMTP_PASSWORD"}', FALSE, TRUE, 20),
    ('M365',       'Microsoft 365',         'Microsoft Graph mail',                                                'm365',     NULL, FALSE, TRUE, 30),
    ('GWS',        'Google Workspace',      'Gmail API',                                                           'gws',      NULL, FALSE, TRUE, 40),
    ('SMS_GATEWAY','SMS Gateway',           'Generic HTTP SMS gateway',                                            'sms_http', '{"endpointEnv":"COMM_SMS_ENDPOINT","apiKeyEnv":"COMM_SMS_API_KEY"}', FALSE, TRUE, 50),
    ('WHATSAPP',   'WhatsApp Business API', 'Meta WhatsApp Business Cloud API',                                    'whatsapp', NULL, FALSE, TRUE, 60),
    ('TELEGRAM',   'Telegram Bot API',      'Telegram bot sendMessage',                                            'telegram', NULL, FALSE, TRUE, 70),
    ('FIREBASE',   'Firebase FCM',          'Firebase Cloud Messaging push',                                       'fcm',      NULL, FALSE, TRUE, 80),
    ('APNS',       'Apple Push',            'Apple Push Notification Service',                                     'apns',     NULL, FALSE, TRUE, 90);

INSERT INTO comm_channel_statuses (code, name, color, allows_sending, is_test_mode, is_default, is_system, display_order)
VALUES
    ('DRAFT',       'Draft',       '#9E9E9E', FALSE, FALSE, TRUE,  TRUE, 10),
    ('TESTING',     'Testing',     '#FB8C00', TRUE,  TRUE,  FALSE, TRUE, 20),
    ('ACTIVE',      'Active',      '#2E7D32', TRUE,  FALSE, FALSE, TRUE, 30),
    ('DISABLED',    'Disabled',    '#E53935', FALSE, FALSE, FALSE, TRUE, 40),
    ('MAINTENANCE', 'Maintenance', '#8E24AA', FALSE, FALSE, FALSE, TRUE, 50),
    ('ARCHIVED',    'Archived',    '#607D8B', FALSE, FALSE, FALSE, TRUE, 60);

INSERT INTO comm_delivery_policies (code, name, description, max_attempts, retry_base_seconds,
        retry_backoff_multiplier, retry_max_seconds, timeout_seconds, expiration_minutes,
        requires_delivery_receipt, requires_read_receipt, is_default, is_system, display_order)
VALUES
    ('STANDARD', 'Standard',              'Three attempts, exponential backoff',            3, 60,  2.0, 3600,  30, 0,     FALSE, FALSE, TRUE,  TRUE, 10),
    ('URGENT',   'Urgent',                'Six rapid attempts; expires after two hours',    6, 15,  1.5, 300,   15, 120,   TRUE,  FALSE, FALSE, TRUE, 20),
    ('OTP',      'One-Time Password',     'Two immediate attempts; useless after 5 minutes',2, 10,  1.0, 10,    10, 5,     TRUE,  FALSE, FALSE, TRUE, 30),
    ('BULK',     'Bulk / Marketing',      'Patient retries over a day; no receipts',        5, 300, 2.0, 21600, 60, 1440,  FALSE, FALSE, FALSE, TRUE, 40);

INSERT INTO comm_message_statuses (code, name, color, is_queued_state, is_sending_state, is_sent_state,
        is_delivered_state, is_read_state, is_failed_state, is_expired_state, is_cancelled_state,
        allows_retry, is_terminal, counts_as_success, is_default, is_system, display_order)
VALUES
    ('QUEUED',    'Queued',    '#9E9E9E', TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, TRUE,  TRUE, 10),
    ('SENDING',   'Sending',   '#FB8C00', FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 20),
    ('SENT',      'Sent',      '#00897B', FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, TRUE, 30),
    ('DELIVERED', 'Delivered', '#2E7D32', FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, TRUE, 40),
    ('READ',      'Read',      '#1B5E20', FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, TRUE,  TRUE,  FALSE, TRUE, 50),
    ('FAILED',    'Failed',    '#E53935', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, TRUE, 60),
    ('EXPIRED',   'Expired',   '#8E24AA', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, TRUE,  FALSE, FALSE, TRUE, 70),
    ('CANCELLED', 'Cancelled', '#607D8B', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, TRUE,  FALSE, FALSE, TRUE, 80),
    ('DEAD',      'Retries Exhausted', '#B71C1C', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, 90);

INSERT INTO comm_conversation_statuses (code, name, color, is_open_state, allows_reply, is_terminal,
        is_default, is_system, display_order)
VALUES
    ('OPEN',     'Open',     '#2E7D32', TRUE,  TRUE,  FALSE, TRUE,  TRUE, 10),
    ('PENDING',  'Pending',  '#FB8C00', TRUE,  TRUE,  FALSE, FALSE, TRUE, 20),
    ('RESOLVED', 'Resolved', '#00897B', FALSE, TRUE,  FALSE, FALSE, TRUE, 30),
    ('CLOSED',   'Closed',   '#607D8B', FALSE, FALSE, TRUE,  FALSE, TRUE, 40);

-- A development-safe default channel: email through the log sink. Real
-- providers are configured by the administrator, not by a migration.
INSERT INTO comm_channels (code, name, description, channel_type_id, provider_id, status_id,
        delivery_policy_id, priority, sender_address)
SELECT 'DEFAULT_EMAIL', 'Default Email', 'Email via the development log sink until a real provider is configured',
       ct.id, p.id, cs.id, dp.id, 10, 'no-reply@sami.local'
FROM comm_channel_types ct, comm_providers p, comm_channel_statuses cs, comm_delivery_policies dp
WHERE ct.code = 'EMAIL' AND p.code = 'LOG' AND cs.code = 'ACTIVE' AND dp.code = 'STANDARD';

INSERT INTO comm_routing_rules (code, name, description, module_code, min_message_priority,
        preferred_channel_id, fallback_channel_id, respect_business_hours, emergency_priority, is_active, priority)
SELECT 'DEFAULT', 'Default Route', 'Everything through the default email channel until routing is configured',
       NULL, 0, c.id, NULL, FALSE, 0, TRUE, 0
FROM comm_channels c WHERE c.code = 'DEFAULT_EMAIL';

-- Retail templates. Persian first (the shop floor language), English pair
-- where the audience may be either. Variables are declared, and rendering
-- fails closed on any mismatch.
INSERT INTO comm_templates (code, name, channel_type_id, module_code, language, subject_template, body_template, variables, is_system, display_order)
VALUES
    ('INSTALLMENT_REMINDER', 'Installment Reminder', NULL, 'installments', 'fa',
     NULL,
     'مشتری گرامی {{customerName}}، قسط شماره {{installmentNo}} به مبلغ {{amount}} ریال در تاریخ {{dueDate}} سررسید می‌شود. سامی موبایل',
     '["customerName","installmentNo","amount","dueDate"]', TRUE, 10),
    ('REPAIR_READY', 'Repair Ready', NULL, 'repair', 'fa',
     NULL,
     'مشتری گرامی {{customerName}}، دستگاه {{deviceModel}} شما آماده تحویل است. شماره پذیرش: {{ticketNo}}. سامی موبایل',
     '["customerName","deviceModel","ticketNo"]', TRUE, 20),
    ('WARRANTY_UPDATE', 'Warranty Update', NULL, 'warranty', 'fa',
     NULL,
     'مشتری گرامی {{customerName}}، وضعیت درخواست گارانتی {{claimNo}} به «{{status}}» تغییر کرد. سامی موبایل',
     '["customerName","claimNo","status"]', TRUE, 30),
    ('INVOICE_DELIVERY', 'Invoice Delivery', NULL, 'sales', 'fa',
     'فاکتور خرید {{invoiceNo}}',
     'مشتری گرامی {{customerName}}، فاکتور شماره {{invoiceNo}} به مبلغ {{total}} ریال صادر شد. از خرید شما سپاسگزاریم.',
     '["customerName","invoiceNo","total"]', TRUE, 40),
    ('DELIVERY_NOTICE', 'Delivery Notice', NULL, 'sales', 'fa',
     NULL,
     'مشتری گرامی {{customerName}}، سفارش {{orderNo}} در تاریخ {{deliveryDate}} تحویل می‌شود.',
     '["customerName","orderNo","deliveryDate"]', TRUE, 50),
    ('BIRTHDAY', 'Birthday Greeting', NULL, 'crm', 'fa',
     NULL,
     '{{customerName}} عزیز، زادروزتان خجسته باد! به مناسبت تولدتان، {{offer}} برای شما فعال شد. سامی موبایل',
     '["customerName","offer"]', TRUE, 60),
    ('PROMOTION', 'Promotion', NULL, 'crm', 'fa',
     NULL,
     '{{customerName}} عزیز، {{promoText}} — تا {{validUntil}} فرصت دارید. سامی موبایل',
     '["customerName","promoText","validUntil"]', TRUE, 70),
    ('OTP', 'One-Time Password', NULL, 'portal', 'fa',
     NULL,
     'کد تایید شما: {{code}} — اعتبار: {{ttlMinutes}} دقیقه. سامی موبایل',
     '["code","ttlMinutes"]', TRUE, 80),
    ('OTP', 'One-Time Password', NULL, 'portal', 'en',
     NULL,
     'Your verification code is {{code}}. Valid for {{ttlMinutes}} minutes. Sami Mobile',
     '["code","ttlMinutes"]', TRUE, 81),
    ('PASSWORD_RESET', 'Password Reset', NULL, 'auth', 'en',
     'Reset your SAMI password',
     'Hello, a password reset was requested for your account. Use this link within {{ttlMinutes}} minutes: {{resetLink}} — if you did not request it, ignore this message.',
     '["resetLink","ttlMinutes"]', TRUE, 90);

-- Sequences for human-readable numbers.
CREATE SEQUENCE comm_message_number_seq START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE comm_conversation_number_seq START WITH 1000 INCREMENT BY 1;

-- The outbound sweep, on the shared scheduler (V19). Seeded DRAFT like
-- every other job: applying this migration starts nothing.
INSERT INTO scheduled_jobs (code, name, description, handler_key, schedule_kind,
        interval_seconds, config, status_id, timeout_seconds, is_system)
SELECT 'comm-outbound-sweep', 'Communication Outbound Sweep',
       'Retries queued/failed messages under their delivery policies and expires stale ones',
       'comm-outbound-sweep', 'FIXED_DELAY', 60, '{}'::jsonb, js.id, 300, TRUE
FROM job_statuses js WHERE js.code = 'draft';


-- =====================================================================
-- Module registration, permissions, lifecycle
-- =====================================================================

INSERT INTO modules (code, name, description, icon, path, display_order, enabled, is_system,
        backend_status_id, frontend_status_id, progress_percentage, development_notes)
SELECT 'communication', 'Communication', 'Omnichannel messaging: channels, providers, templates and delivery',
       'mdi-message-badge-outline', '/communication', 190, TRUE, TRUE,
       bs.id, fs.id, 60,
       'Delivery layer complete (smtp/log handlers live; other providers are seeded configuration awaiting their handler beans). Notification Center — the WHAT layer — is a separate future module.'
FROM module_statuses bs, module_statuses fs
WHERE bs.code = 'BACKEND_READY' AND fs.code = 'IN_DEVELOPMENT'
  AND bs.tenant_id IS NULL AND fs.tenant_id IS NULL;

INSERT INTO permissions (module_id, action, code, name, is_system)
SELECT m.id, a.action, m.code || ':' || a.action, m.name || ' — ' || a.label, TRUE
FROM modules m
CROSS JOIN (VALUES
    ('view',             'View conversations and messages'),
    ('send',             'Send messages'),
    ('manage-channels',  'Manage channels'),
    ('manage-providers', 'Manage providers'),
    ('manage-templates', 'Manage templates'),
    ('manage-routing',   'Manage routing rules'),
    ('view-logs',        'View delivery logs'),
    ('export',           'Export communication history')
) AS a(action, label)
WHERE m.code = 'communication';


-- =====================================================================
-- Post-migration assertions
-- =====================================================================

DO $$
DECLARE
    n BIGINT;
BEGIN
    SELECT count(*) INTO n FROM comm_message_statuses WHERE is_default;
    IF n <> 1 THEN RAISE EXCEPTION 'V26: expected 1 default message status, found %', n; END IF;

    SELECT count(*) INTO n FROM comm_channel_types WHERE is_default;
    IF n <> 1 THEN RAISE EXCEPTION 'V26: expected 1 default channel type, found %', n; END IF;

    SELECT count(*) INTO n FROM comm_channels c JOIN comm_channel_statuses s ON s.id = c.status_id
    WHERE s.allows_sending;
    IF n < 1 THEN RAISE EXCEPTION 'V26: no sendable channel was seeded'; END IF;

    -- A terminal status must never be retryable, or the sweep would
    -- resurrect cancelled and expired messages forever.
    IF EXISTS (SELECT 1 FROM comm_message_statuses WHERE is_terminal AND allows_retry) THEN
        RAISE EXCEPTION 'V26: a terminal message status is flagged retryable';
    END IF;

    SELECT count(*) INTO n FROM modules WHERE code = 'communication';
    IF n <> 1 THEN RAISE EXCEPTION 'V26: module row missing'; END IF;

    SELECT count(*) INTO n FROM scheduled_jobs WHERE handler_key = 'comm-outbound-sweep';
    IF n <> 1 THEN RAISE EXCEPTION 'V26: outbound sweep job missing'; END IF;
END $$;
