-- Per-user application preferences and the staff in-app notification centre.
-- The existing portal notifications belong to customer portal accounts and
-- cannot safely represent authenticated staff notifications.

CREATE TABLE user_experience_preferences (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id                  BIGINT       NOT NULL,
    user_id                    BIGINT       NOT NULL,
    mobile_navigation_codes    JSONB        NOT NULL DEFAULT '[]'::jsonb,
    demo_notifications_enabled BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at                 TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                 TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version                    BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_user_experience_preferences_owner UNIQUE (tenant_id, user_id),
    CONSTRAINT fk_user_experience_preferences_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_experience_preferences_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_user_experience_preferences_mobile_codes CHECK (
        jsonb_typeof(mobile_navigation_codes) = 'array'
        AND jsonb_array_length(mobile_navigation_codes) <= 4
    )
);

CREATE INDEX idx_user_experience_preferences_tenant_user
    ON user_experience_preferences (tenant_id, user_id);

CREATE TABLE staff_notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT        NOT NULL,
    user_id         BIGINT        NOT NULL,
    type            VARCHAR(64)   NOT NULL,
    title_key       VARCHAR(160)  NOT NULL,
    message_key     VARCHAR(160)  NOT NULL,
    route           VARCHAR(500)  NOT NULL DEFAULT '/',
    idempotency_key VARCHAR(220)  NOT NULL,
    read_at         TIMESTAMPTZ,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version         BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT uq_staff_notifications_delivery UNIQUE (tenant_id, user_id, idempotency_key),
    CONSTRAINT fk_staff_notifications_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT fk_staff_notifications_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_staff_notifications_inbox
    ON staff_notifications (tenant_id, user_id, created_at DESC);
CREATE INDEX idx_staff_notifications_unread
    ON staff_notifications (tenant_id, user_id, created_at DESC) WHERE read_at IS NULL;

-- Existing tenants receive one visible scheduler definition. The handler is a
-- no-op unless DEMO_HOURLY_NOTIFICATION_ENABLED=true, and each user must also
-- opt in. Future tenants can add the same system job through the Scheduler API.
INSERT INTO scheduled_jobs (
    code, name, description, handler_key, schedule_kind, cron_expression,
    config, status_id, timezone, timeout_seconds, catch_up, run_on_startup,
    is_system, tenant_id
)
SELECT 'demo-hourly-notification',
       'Hourly Demo Notification',
       'Creates opt-in staff demo notifications when the deployment feature flag is enabled',
       'notification.demo-hourly',
       'CRON',
       '0 0 * * * *',
       '{}'::jsonb,
       status.id,
       'UTC',
       120,
       FALSE,
       FALSE,
       TRUE,
       tenant.id
FROM tenants tenant
CROSS JOIN LATERAL (
    SELECT id FROM job_statuses WHERE code = 'active' ORDER BY tenant_id NULLS FIRST LIMIT 1
) status
ON CONFLICT (tenant_id, code) DO NOTHING;
