-- RBAC schema: roles, modules, permissions, the role/permission join table and
-- the server-side token stores. Also moves users from the old role enum column
-- to a role_id foreign key.

-- Roles: behavior flags (is_super_admin, is_default) live in data, never in code.
CREATE TABLE roles (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name           VARCHAR(100) NOT NULL,
    description    VARCHAR(255),
    is_system      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_super_admin BOOLEAN      NOT NULL DEFAULT FALSE,
    is_default     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT uq_roles_name UNIQUE (name)
);

-- At most one role may be the default assigned to newly registered users.
CREATE UNIQUE INDEX uq_roles_default ON roles (is_default) WHERE is_default;

-- Modules: functional areas of the application; the permission-code prefix.
CREATE TABLE modules (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    description   VARCHAR(255),
    icon          VARCHAR(64),
    path          VARCHAR(255),
    display_order INTEGER      NOT NULL DEFAULT 0,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_modules PRIMARY KEY (id),
    CONSTRAINT uq_modules_code UNIQUE (code)
);

-- Permissions: one action within a module. code = '<module.code>:<action>' is
-- denormalized so authorities load without joining modules.
CREATE TABLE permissions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    module_id   BIGINT       NOT NULL,
    action      VARCHAR(64)  NOT NULL,
    code        VARCHAR(150) NOT NULL,
    name        VARCHAR(150) NOT NULL,
    description VARCHAR(255),
    is_system   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_permissions PRIMARY KEY (id),
    CONSTRAINT uq_permissions_code UNIQUE (code),
    CONSTRAINT uq_permissions_module_action UNIQUE (module_id, action),
    CONSTRAINT fk_permissions_module FOREIGN KEY (module_id)
        REFERENCES modules (id) ON DELETE CASCADE
);

-- Role/permission grants. Pure join table; cascades keep it consistent when
-- either side is deleted.
CREATE TABLE role_permissions (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id)
        REFERENCES roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id)
        REFERENCES permissions (id) ON DELETE CASCADE
);

CREATE INDEX idx_role_permissions_permission_id ON role_permissions (permission_id);

-- Server-side refresh-token store (SHA-256 hashes, never the raw token).
-- Enables real logout, rotation and revoke-all-on-password-change.
CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT      NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version    BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT uq_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);

-- Single-use password-reset tokens (hashed, short-lived).
CREATE TABLE password_reset_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT      NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version    BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT pk_password_reset_tokens PRIMARY KEY (id),
    CONSTRAINT uq_password_reset_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens (user_id);

-- The two system roles must exist before existing users can be migrated.
-- Modules, permissions and grants are seeded in V4.
INSERT INTO roles (name, description, is_system, is_super_admin, is_default) VALUES
    ('Super Administrator', 'Unrestricted access to every module and action', TRUE, TRUE, FALSE),
    ('User', 'Standard account with baseline access', TRUE, FALSE, TRUE);

-- Move users to the role_id foreign key: old ADMIN accounts become Super
-- Administrators, everything else falls back to the default User role.
ALTER TABLE users ADD COLUMN role_id BIGINT;

UPDATE users SET role_id = (SELECT id FROM roles WHERE is_super_admin) WHERE role = 'ADMIN';
UPDATE users SET role_id = (SELECT id FROM roles WHERE is_default) WHERE role_id IS NULL;

ALTER TABLE users ALTER COLUMN role_id SET NOT NULL;
ALTER TABLE users ADD CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (id);
CREATE INDEX idx_users_role_id ON users (role_id);

DROP INDEX idx_users_role;
ALTER TABLE users DROP COLUMN role;
