CREATE TABLE legacy_import_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    source_system VARCHAR(32) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    sha256 CHAR(64) NOT NULL,
    parser_version VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL,
    uploaded_by BIGINT,
    uploaded_by_email VARCHAR(255),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    dataset_count INTEGER NOT NULL DEFAULT 0,
    record_count BIGINT NOT NULL DEFAULT 0,
    warning_count INTEGER NOT NULL DEFAULT 0,
    error_count INTEGER NOT NULL DEFAULT 0,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_legacy_batch_source CHECK (source_system IN ('ASAN')),
    CONSTRAINT ck_legacy_batch_status CHECK (status IN ('UPLOADED','ANALYZING','READY','IMPORTING','COMPLETED','COMPLETED_WITH_WARNINGS','FAILED','CANCELLED')),
    CONSTRAINT uq_legacy_batch_hash UNIQUE (tenant_id, source_system, sha256)
);
CREATE INDEX idx_legacy_batches_tenant_created ON legacy_import_batches(tenant_id, created_at DESC);

CREATE TABLE legacy_import_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    import_batch_id BIGINT NOT NULL REFERENCES legacy_import_batches(id) ON DELETE CASCADE,
    source_path VARCHAR(500) NOT NULL,
    safe_name VARCHAR(255) NOT NULL,
    extension VARCHAR(32), size_bytes BIGINT NOT NULL, sha256 CHAR(64),
    format VARCHAR(64) NOT NULL, support_status VARCHAR(24) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_legacy_file_path UNIQUE(import_batch_id, source_path),
    CONSTRAINT ck_legacy_file_support CHECK (support_status IN ('SUPPORTED','PARTIAL','UNSUPPORTED'))
);
CREATE INDEX idx_legacy_files_batch ON legacy_import_files(tenant_id, import_batch_id);

CREATE TABLE legacy_datasets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    import_batch_id BIGINT NOT NULL REFERENCES legacy_import_batches(id) ON DELETE CASCADE,
    import_file_id BIGINT REFERENCES legacy_import_files(id) ON DELETE CASCADE,
    dataset_key VARCHAR(300) NOT NULL, source_table VARCHAR(255), semantic_type VARCHAR(40) NOT NULL DEFAULT 'UNKNOWN',
    support_status VARCHAR(24) NOT NULL, source_encoding VARCHAR(40), source_record_count BIGINT NOT NULL DEFAULT 0,
    imported_record_count BIGINT NOT NULL DEFAULT 0, field_dictionary JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_legacy_dataset UNIQUE(import_batch_id, dataset_key),
    CONSTRAINT ck_legacy_dataset_support CHECK (support_status IN ('SUPPORTED','PARTIAL','UNSUPPORTED'))
);
CREATE INDEX idx_legacy_datasets_batch ON legacy_datasets(tenant_id, import_batch_id);

CREATE TABLE legacy_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    import_batch_id BIGINT NOT NULL REFERENCES legacy_import_batches(id) ON DELETE CASCADE,
    dataset_id BIGINT NOT NULL REFERENCES legacy_datasets(id) ON DELETE CASCADE,
    source_record_id VARCHAR(255), legacy_code VARCHAR(255), normalized_key VARCHAR(500),
    raw_record JSONB NOT NULL, normalized_record JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_legacy_records_dataset ON legacy_records(tenant_id, import_batch_id, dataset_id, id);
CREATE INDEX idx_legacy_records_code ON legacy_records(tenant_id, legacy_code) WHERE legacy_code IS NOT NULL;
CREATE INDEX idx_legacy_records_normalized ON legacy_records(tenant_id, normalized_key) WHERE normalized_key IS NOT NULL;

CREATE TABLE legacy_import_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    import_batch_id BIGINT NOT NULL REFERENCES legacy_import_batches(id) ON DELETE CASCADE,
    import_file_id BIGINT REFERENCES legacy_import_files(id) ON DELETE CASCADE,
    dataset_id BIGINT REFERENCES legacy_datasets(id) ON DELETE CASCADE,
    severity VARCHAR(12) NOT NULL, code VARCHAR(80) NOT NULL, message VARCHAR(1000) NOT NULL,
    source_record_id VARCHAR(255), context JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_legacy_message_severity CHECK (severity IN ('INFO','WARNING','ERROR'))
);
CREATE INDEX idx_legacy_messages_batch ON legacy_import_messages(tenant_id, import_batch_id, severity, id);

CREATE TABLE legacy_comparison_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    import_batch_id BIGINT NOT NULL REFERENCES legacy_import_batches(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL, requested_by BIGINT, comparison_version VARCHAR(40) NOT NULL,
    counts JSONB NOT NULL DEFAULT '{}'::jsonb, duration_ms BIGINT, completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_legacy_comparison_status CHECK (status IN ('RUNNING','COMPLETED','FAILED'))
);
CREATE INDEX idx_legacy_comparisons_batch ON legacy_comparison_runs(tenant_id, import_batch_id, created_at DESC);

CREATE TABLE legacy_comparison_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    comparison_run_id BIGINT NOT NULL REFERENCES legacy_comparison_runs(id) ON DELETE CASCADE,
    legacy_record_id BIGINT NOT NULL REFERENCES legacy_records(id) ON DELETE CASCADE,
    classification VARCHAR(32) NOT NULL, note VARCHAR(2000), reviewed_by BIGINT, reviewed_by_email VARCHAR(255), reviewed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_legacy_review UNIQUE(comparison_run_id, legacy_record_id),
    CONSTRAINT ck_legacy_review_classification CHECK (classification IN ('CONFIRMED_MATCH','EXPECTED_DIFFERENCE','NEEDS_INVESTIGATION','SAMI_ISSUE','LEGACY_DATA_ISSUE'))
);

CREATE TABLE legacy_import_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    import_batch_id BIGINT NOT NULL REFERENCES legacy_import_batches(id) ON DELETE CASCADE,
    action VARCHAR(80) NOT NULL, actor_id BIGINT, actor_email VARCHAR(255), detail JSONB,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_legacy_audit_batch ON legacy_import_audit_logs(tenant_id, import_batch_id, occurred_at DESC);

INSERT INTO modules (code, name, description, icon, path, display_order, enabled, is_system,
                     backend_status_id, frontend_status_id, progress_percentage, is_production_ready)
VALUES ('legacy-import', 'Data Migration & Comparison', 'Tenant-safe legacy staging and comparison center',
        'mdi-database-import-outline', '/legacy-imports', 135, TRUE, TRUE,
        (SELECT id FROM module_statuses WHERE code='ACTIVE' AND tenant_id IS NULL),
        (SELECT id FROM module_statuses WHERE code='ACTIVE' AND tenant_id IS NULL), 100, TRUE);

INSERT INTO permissions (module_id, action, code, name, is_system)
SELECT m.id, a.action, m.code || ':' || a.action, m.name || ' — ' || a.label, TRUE
FROM modules m CROSS JOIN (VALUES
 ('view','View legacy financial data'), ('create','Upload legacy archives'), ('analyze','Analyze legacy archives'),
 ('execute','Import into legacy staging'), ('compare','Run comparisons'), ('review','Review discrepancies'),
 ('delete','Delete legacy batches')) a(action,label)
WHERE m.code='legacy-import';

-- Sensitive legacy access is admin-only by default.
INSERT INTO role_permissions(role_id, permission_id)
SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code LIKE 'legacy-import:%'
WHERE r.is_super_admin OR lower(r.name) IN ('admin','administrator')
ON CONFLICT DO NOTHING;
