ALTER TABLE products ADD COLUMN hamta_eligible BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE hamta_settings (
    tenant_id BIGINT PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE,
    enforcement_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE hamta_activations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    serial_unit_id BIGINT NOT NULL REFERENCES inventory_serial_units(id) ON DELETE RESTRICT,
    activation_code VARCHAR(128) NOT NULL,
    delivered BOOLEAN NOT NULL DEFAULT FALSE,
    delivery_datetime TIMESTAMPTZ,
    delivered_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    delivered_sale_id BIGINT REFERENCES sales(id) ON DELETE RESTRICT,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_by_email VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_hamta_serial_unit UNIQUE (serial_unit_id),
    CONSTRAINT ck_hamta_delivery_state CHECK (
        (NOT delivered AND delivery_datetime IS NULL AND delivered_by_user_id IS NULL AND delivered_sale_id IS NULL)
        OR (delivered AND delivery_datetime IS NOT NULL AND delivered_sale_id IS NOT NULL)
    )
);
CREATE INDEX ix_hamta_tenant_delivery ON hamta_activations(tenant_id, delivered, created_at DESC);

CREATE TABLE hamta_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    activation_id BIGINT REFERENCES hamta_activations(id) ON DELETE SET NULL,
    serial_unit_id BIGINT REFERENCES inventory_serial_units(id) ON DELETE SET NULL,
    sale_id BIGINT REFERENCES sales(id) ON DELETE SET NULL,
    action VARCHAR(64) NOT NULL,
    actor_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    actor_email VARCHAR(255),
    detail JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_hamta_audit_tenant ON hamta_audit_logs(tenant_id, occurred_at DESC);

INSERT INTO modules (code, name, description, icon, path, display_order, enabled, is_system,
                     backend_status_id, frontend_status_id, progress_percentage, is_production_ready)
VALUES ('hamta', 'HAMTA Activation Codes', 'Activation-code custody, delivery and reporting for eligible used phones',
        'mdi-cellphone-key', '/hamta', 136, TRUE, TRUE,
        (SELECT id FROM module_statuses WHERE code='ACTIVE' AND tenant_id IS NULL),
        (SELECT id FROM module_statuses WHERE code='ACTIVE' AND tenant_id IS NULL), 100, TRUE);

INSERT INTO permissions (module_id, action, code, name, is_system)
SELECT m.id, a.action, m.code || ':' || a.action, m.name || ' — ' || a.label, TRUE
FROM modules m CROSS JOIN (VALUES
 ('view','View delivery state'), ('view-code','View activation codes'),
 ('edit','Register or correct undelivered codes'), ('deliver','Deliver activation codes'),
 ('report','View operational reports'), ('settings-update','Update HAMTA settings')) a(action,label)
WHERE m.code='hamta';

INSERT INTO role_permissions(role_id, permission_id)
SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code LIKE 'hamta:%'
WHERE r.is_super_admin OR lower(r.name) IN ('admin','administrator')
ON CONFLICT DO NOTHING;
