CREATE TABLE market_pricing_profiles (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
 name VARCHAR(120) NOT NULL,
 percentage_adjustment NUMERIC(9,4) NOT NULL DEFAULT 0,
 fixed_adjustment NUMERIC(18,2) NOT NULL DEFAULT 0,
 minimum_profit NUMERIC(18,2),
 rounding_step NUMERIC(18,2) NOT NULL DEFAULT 1 CHECK(rounding_step > 0),
 rounding_mode VARCHAR(16) NOT NULL DEFAULT 'NEAREST' CHECK(rounding_mode IN ('NEAREST','UP','DOWN')),
 min_publication_price NUMERIC(18,2), max_publication_price NUMERIC(18,2),
 profile_version BIGINT NOT NULL DEFAULT 1,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT uq_market_pricing_name UNIQUE(tenant_id,name),
 CONSTRAINT ck_market_publication_range CHECK(min_publication_price IS NULL OR max_publication_price IS NULL OR min_publication_price <= max_publication_price)
);

CREATE TABLE market_sources (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
 code VARCHAR(64) NOT NULL, name VARCHAR(160) NOT NULL, enabled BOOLEAN NOT NULL DEFAULT FALSE,
 provider_key VARCHAR(80) NOT NULL, endpoint_url VARCHAR(1000), schedule_cron VARCHAR(100) NOT NULL DEFAULT '0 0 * * * *',
 pricing_profile_id BIGINT REFERENCES market_pricing_profiles(id) ON DELETE RESTRICT,
 source_config JSONB NOT NULL DEFAULT '{}'::jsonb,
 health_state VARCHAR(16) NOT NULL DEFAULT 'DISABLED' CHECK(health_state IN ('HEALTHY','DEGRADED','FAILING','DISABLED')),
 last_attempted_sync TIMESTAMPTZ, last_successful_sync TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT uq_market_source_code UNIQUE(tenant_id,code)
);

CREATE TABLE market_sync_runs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
 source_id BIGINT NOT NULL REFERENCES market_sources(id) ON DELETE CASCADE,
 trigger_type VARCHAR(16) NOT NULL CHECK(trigger_type IN ('MANUAL','SCHEDULED')),
 status VARCHAR(24) NOT NULL CHECK(status IN ('RUNNING','COMPLETED','COMPLETED_WITH_WARNINGS','FAILED')),
 started_at TIMESTAMPTZ NOT NULL DEFAULT now(), finished_at TIMESTAMPTZ,
 fetched_count INTEGER NOT NULL DEFAULT 0, new_count INTEGER NOT NULL DEFAULT 0, updated_count INTEGER NOT NULL DEFAULT 0,
 price_change_count INTEGER NOT NULL DEFAULT 0, published_count INTEGER NOT NULL DEFAULT 0, unpublished_count INTEGER NOT NULL DEFAULT 0,
 warning_count INTEGER NOT NULL DEFAULT 0, error_count INTEGER NOT NULL DEFAULT 0, duration_ms BIGINT,
 requested_by BIGINT REFERENCES users(id) ON DELETE SET NULL, requested_by_email VARCHAR(255)
);
CREATE INDEX ix_market_runs_source ON market_sync_runs(tenant_id,source_id,started_at DESC);

CREATE TABLE market_products (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
 product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
 source_id BIGINT NOT NULL REFERENCES market_sources(id) ON DELETE RESTRICT,
 normalized_product_code VARCHAR(32) NOT NULL, raw_source_identifier VARCHAR(128),
 source_price NUMERIC(18,2), final_price NUMERIC(18,2), acquisition_cost NUMERIC(18,2),
 pricing_profile_id BIGINT REFERENCES market_pricing_profiles(id) ON DELETE RESTRICT, pricing_profile_version BIGINT,
 pricing_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' CHECK(pricing_status IN ('PENDING','CALCULATED','COST_UNVERIFIED','INVALID_PRICE')),
 availability_state VARCHAR(32) NOT NULL DEFAULT 'SOURCE_AVAILABLE' CHECK(availability_state IN ('SOURCE_AVAILABLE','SOURCE_MISSING','SOLD_LOCKED','CONFLICT')),
 publication_state VARCHAR(24) NOT NULL DEFAULT 'UNPUBLISHED' CHECK(publication_state IN ('ELIGIBLE','PUBLISHED','UNPUBLISHED','FAILED')),
 publication_reason VARCHAR(64) NOT NULL DEFAULT 'NOT_EVALUATED', remote_present BOOLEAN NOT NULL DEFAULT TRUE,
 unresolved_conflict BOOLEAN NOT NULL DEFAULT FALSE, last_seen_at TIMESTAMPTZ, last_calculated_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT uq_market_product_code UNIQUE(tenant_id,normalized_product_code),
 CONSTRAINT uq_market_product_product UNIQUE(tenant_id,product_id)
);
CREATE INDEX ix_market_products_source ON market_products(tenant_id,source_id,availability_state);

CREATE TABLE market_publication_rules (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
 source_id BIGINT REFERENCES market_sources(id) ON DELETE CASCADE,
 list_type VARCHAR(16) NOT NULL CHECK(list_type IN ('BLACKLIST','WHITELIST')),
 match_type VARCHAR(16) NOT NULL DEFAULT 'PRODUCT_CODE' CHECK(match_type IN ('PRODUCT_CODE','PREFIX')),
 match_value VARCHAR(64) NOT NULL, enabled BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX uq_market_rule_source ON market_publication_rules(tenant_id,source_id,list_type,match_type,match_value) WHERE source_id IS NOT NULL;
CREATE UNIQUE INDEX uq_market_rule_global ON market_publication_rules(tenant_id,list_type,match_type,match_value) WHERE source_id IS NULL;

CREATE TABLE market_price_history (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
 market_product_id BIGINT NOT NULL REFERENCES market_products(id) ON DELETE CASCADE,
 source_id BIGINT NOT NULL REFERENCES market_sources(id) ON DELETE RESTRICT,
 sync_run_id BIGINT REFERENCES market_sync_runs(id) ON DELETE SET NULL,
 old_source_price NUMERIC(18,2), new_source_price NUMERIC(18,2), old_final_price NUMERIC(18,2), new_final_price NUMERIC(18,2),
 changed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_market_price_history ON market_price_history(tenant_id,market_product_id,changed_at DESC);

CREATE TABLE market_sync_messages (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
 sync_run_id BIGINT NOT NULL REFERENCES market_sync_runs(id) ON DELETE CASCADE,
 source_id BIGINT NOT NULL REFERENCES market_sources(id) ON DELETE CASCADE,
 severity VARCHAR(12) NOT NULL CHECK(severity IN ('INFO','WARNING','ERROR')),
 code VARCHAR(80) NOT NULL, message VARCHAR(1000) NOT NULL, raw_identifier VARCHAR(128), created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_market_messages_run ON market_sync_messages(tenant_id,sync_run_id,severity,id);

CREATE TABLE market_publications (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
 market_product_id BIGINT NOT NULL REFERENCES market_products(id) ON DELETE CASCADE,
 channel_code VARCHAR(64) NOT NULL DEFAULT 'WEBSITE', external_publication_id VARCHAR(255),
 desired_published BOOLEAN NOT NULL DEFAULT FALSE, last_published_price NUMERIC(18,2), last_attempt_at TIMESTAMPTZ,
 last_success_at TIMESTAMPTZ, last_error VARCHAR(1000),
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT uq_market_publication UNIQUE(tenant_id,market_product_id,channel_code)
);

CREATE TABLE market_audit_logs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
 source_id BIGINT REFERENCES market_sources(id) ON DELETE SET NULL, action VARCHAR(80) NOT NULL,
 actor_id BIGINT REFERENCES users(id) ON DELETE SET NULL, actor_email VARCHAR(255), detail JSONB NOT NULL DEFAULT '{}'::jsonb,
 occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO market_sources(tenant_id,code,name,enabled,provider_key,endpoint_url,health_state)
SELECT id,'MOSHTAREKIN123_ROND','moshtarekin123.rond.ir',FALSE,'ROND_CONTRACT_PENDING','https://moshtarekin123.rond.ir/','DISABLED' FROM tenants
ON CONFLICT(tenant_id,code) DO NOTHING;
INSERT INTO market_sources(tenant_id,code,name,enabled,provider_key,endpoint_url,health_state)
SELECT id,'SAMISTORE_ROND','samistore.rond.ir',FALSE,'ROND_CONTRACT_PENDING','https://samistore.rond.ir/','DISABLED' FROM tenants
ON CONFLICT(tenant_id,code) DO NOTHING;

INSERT INTO modules(code,name,description,icon,path,display_order,enabled,is_system,backend_status_id,frontend_status_id,progress_percentage,is_production_ready)
VALUES('market-sync','Market Sync','SIM-card market synchronization, pricing and publication','mdi-sync-circle','/market-sync',137,TRUE,TRUE,
 (SELECT id FROM module_statuses WHERE code='ACTIVE' AND tenant_id IS NULL),(SELECT id FROM module_statuses WHERE code='ACTIVE' AND tenant_id IS NULL),90,FALSE);
INSERT INTO permissions(module_id,action,code,name,is_system)
SELECT m.id,a.action,m.code||':'||a.action,m.name||' — '||a.label,TRUE FROM modules m CROSS JOIN (VALUES
 ('view','View overview'),('manage-sources','Manage sources'),('manage-pricing','Manage pricing'),('manage-publication','Manage publication rules'),
 ('execute','Run synchronization'),('view-history','View history'),('view-errors','View errors')) a(action,label) WHERE m.code='market-sync';
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code LIKE 'market-sync:%'
WHERE r.is_super_admin OR lower(r.name) IN ('admin','administrator') ON CONFLICT DO NOTHING;
