-- Canonical employee identity and tenant-safe attendance tracking.
CREATE UNIQUE INDEX IF NOT EXISTS uq_companies_id_tenant ON companies(id, tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_branches_id_tenant ON branches(id, tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_branches_id_tenant_company ON branches(id, tenant_id, company_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_id_tenant ON users(id, tenant_id);

CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    employee_code VARCHAR(32) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    user_id BIGINT,
    company_id BIGINT NOT NULL,
    branch_id BIGINT NOT NULL,
    job_title VARCHAR(120),
    mobile VARCHAR(32),
    hire_date DATE,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','INACTIVE')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_employees_code UNIQUE(tenant_id, employee_code),
    CONSTRAINT fk_employees_user_tenant FOREIGN KEY(user_id, tenant_id) REFERENCES users(id, tenant_id) ON DELETE SET NULL (user_id),
    CONSTRAINT fk_employees_company_tenant FOREIGN KEY(company_id, tenant_id) REFERENCES companies(id, tenant_id) ON DELETE RESTRICT,
    CONSTRAINT fk_employees_branch_company_tenant FOREIGN KEY(branch_id, tenant_id, company_id)
        REFERENCES branches(id, tenant_id, company_id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX uq_employees_id_tenant ON employees(id, tenant_id);
CREATE UNIQUE INDEX uq_employees_user ON employees(tenant_id, user_id) WHERE user_id IS NOT NULL;
CREATE INDEX ix_employees_branch_status ON employees(tenant_id, branch_id, status, last_name);

CREATE TABLE attendance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    employee_id BIGINT NOT NULL,
    work_date DATE NOT NULL,
    clock_in TIMESTAMPTZ NOT NULL,
    clock_out TIMESTAMPTZ,
    status VARCHAR(20) NOT NULL DEFAULT 'PRESENT' CHECK(status IN ('PRESENT','LATE','ABSENT','LEAVE','MISSION')),
    source VARCHAR(16) NOT NULL DEFAULT 'MANUAL' CHECK(source IN ('SELF','MANUAL','DEVICE','IMPORT')),
    notes VARCHAR(500),
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_attendance_order CHECK(clock_out IS NULL OR clock_out >= clock_in),
    CONSTRAINT fk_attendance_employee_tenant FOREIGN KEY(employee_id, tenant_id)
        REFERENCES employees(id, tenant_id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX uq_attendance_open_record ON attendance_records(tenant_id, employee_id) WHERE clock_out IS NULL;
CREATE INDEX ix_attendance_daily ON attendance_records(tenant_id, work_date DESC, employee_id);

CREATE TABLE attendance_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    entity_type VARCHAR(24) NOT NULL,
    entity_id BIGINT NOT NULL,
    action VARCHAR(40) NOT NULL,
    actor_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    actor_email VARCHAR(255),
    detail JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_attendance_audit ON attendance_audit_logs(tenant_id, entity_type, entity_id, occurred_at DESC);

INSERT INTO modules(code,name,description,icon,path,display_order,enabled,is_system,backend_status_id,frontend_status_id,progress_percentage,is_production_ready)
VALUES('attendance','Employees & Attendance','Employee directory and attendance tracking','mdi-account-clock','/attendance',138,TRUE,TRUE,
 (SELECT id FROM module_statuses WHERE code='ACTIVE' AND tenant_id IS NULL),(SELECT id FROM module_statuses WHERE code='ACTIVE' AND tenant_id IS NULL),85,FALSE);
INSERT INTO permissions(module_id,action,code,name,is_system)
SELECT m.id,a.action,m.code||':'||a.action,m.name||' — '||a.label,TRUE FROM modules m CROSS JOIN (VALUES
 ('view','View employees and attendance'),('manage-employees','Manage employees'),('clock','Record attendance'),
 ('correct','Correct attendance'),('report','View reports')) a(action,label) WHERE m.code='attendance';
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code LIKE 'attendance:%'
WHERE r.is_super_admin OR lower(r.name) IN ('admin','administrator') ON CONFLICT DO NOTHING;
