CREATE TABLE sim_investment_import_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    source_code VARCHAR(80) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    observed_on DATE NOT NULL,
    full_snapshot BOOLEAN NOT NULL DEFAULT TRUE,
    status VARCHAR(24) NOT NULL CHECK (status IN ('PROCESSING','COMPLETED','COMPLETED_WITH_WARNINGS','FAILED')),
    source_row_count INTEGER NOT NULL DEFAULT 0,
    imported_count INTEGER NOT NULL DEFAULT 0,
    duplicate_count INTEGER NOT NULL DEFAULT 0,
    warning_count INTEGER NOT NULL DEFAULT 0,
    error_count INTEGER NOT NULL DEFAULT 0,
    requested_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    requested_by_email VARCHAR(255),
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT uq_sim_investment_import_hash UNIQUE (tenant_id, sha256)
);
CREATE INDEX ix_sim_investment_imports ON sim_investment_import_batches(tenant_id, observed_on DESC, id DESC);

CREATE TABLE sim_investment_listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    source_code VARCHAR(80) NOT NULL,
    normalized_phone VARCHAR(11) NOT NULL CHECK (normalized_phone ~ '^0912[0-9]{7}$'),
    price_toman NUMERIC(18,2) NOT NULL CHECK (price_toman >= 0),
    condition_code VARCHAR(32) NOT NULL,
    seller_external_id VARCHAR(120) NOT NULL,
    first_seen_on DATE NOT NULL,
    last_seen_on DATE NOT NULL,
    removed_on DATE,
    last_import_batch_id BIGINT NOT NULL REFERENCES sim_investment_import_batches(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_sim_investment_listing UNIQUE (tenant_id, source_code, normalized_phone),
    CONSTRAINT ck_sim_investment_seen_dates CHECK (first_seen_on <= last_seen_on),
    CONSTRAINT ck_sim_investment_removed_date CHECK (removed_on IS NULL OR removed_on >= last_seen_on)
);
CREATE INDEX ix_sim_investment_active_listings ON sim_investment_listings(tenant_id, source_code, normalized_phone) WHERE removed_on IS NULL;

CREATE TABLE sim_investment_listing_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    import_batch_id BIGINT NOT NULL REFERENCES sim_investment_import_batches(id) ON DELETE CASCADE,
    normalized_phone VARCHAR(11) NOT NULL CHECK (normalized_phone ~ '^0912[0-9]{7}$'),
    price_toman NUMERIC(18,2) NOT NULL CHECK (price_toman >= 0),
    condition_code VARCHAR(32) NOT NULL,
    seller_external_id VARCHAR(120) NOT NULL,
    source_row_number INTEGER NOT NULL CHECK (source_row_number >= 2),
    observed_on DATE NOT NULL,
    CONSTRAINT uq_sim_investment_history_phone UNIQUE (import_batch_id, normalized_phone)
);
CREATE INDEX ix_sim_investment_history_phone ON sim_investment_listing_history(tenant_id, normalized_phone, observed_on DESC);

CREATE TABLE sim_investment_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    normalized_phone VARCHAR(11) NOT NULL CHECK (normalized_phone ~ '^0912[0-9]{7}$'),
    prefix VARCHAR(4) NOT NULL,
    number_class VARCHAR(16) NOT NULL CHECK (number_class IN ('ORDINARY','SEMI_ROUND','ROUND','SPECIAL','VIP')),
    rondi_score INTEGER NOT NULL CHECK (rondi_score BETWEEN 0 AND 100),
    rondi_patterns JSONB NOT NULL DEFAULT '[]'::jsonb,
    block_group VARCHAR(40),
    market_mean NUMERIC(18,2),
    market_median NUMERIC(18,2),
    market_floor NUMERIC(18,2),
    market_ceiling NUMERIC(18,2),
    best_buy_price NUMERIC(18,2),
    normal_buy_price NUMERIC(18,2),
    normal_sell_price NUMERIC(18,2),
    best_sell_price NUMERIC(18,2),
    sample_count INTEGER NOT NULL DEFAULT 0 CHECK (sample_count >= 0),
    confidence VARCHAR(16) NOT NULL CHECK (confidence IN ('LOW','MEDIUM','HIGH')),
    liquidity VARCHAR(16) NOT NULL CHECK (liquidity IN ('LOW','MEDIUM','HIGH')),
    outlier BOOLEAN NOT NULL DEFAULT FALSE,
    trend_percent NUMERIC(9,2),
    actual_buy_price NUMERIC(18,2),
    actual_sell_price NUMERIC(18,2),
    potential_profit NUMERIC(18,2),
    investment_score INTEGER NOT NULL DEFAULT 0 CHECK (investment_score BETWEEN 0 AND 100),
    last_observed_on DATE NOT NULL,
    calculated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_sim_investment_analysis UNIQUE (tenant_id, normalized_phone)
);
CREATE INDEX ix_sim_investment_opportunities ON sim_investment_analyses(tenant_id, investment_score DESC, confidence, liquidity);
CREATE INDEX ix_sim_investment_class ON sim_investment_analyses(tenant_id, number_class, rondi_score DESC);

CREATE TABLE sim_investment_import_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    import_batch_id BIGINT NOT NULL REFERENCES sim_investment_import_batches(id) ON DELETE CASCADE,
    severity VARCHAR(12) NOT NULL CHECK (severity IN ('WARNING','ERROR')),
    code VARCHAR(80) NOT NULL,
    source_row_number INTEGER,
    message VARCHAR(500) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_sim_investment_messages ON sim_investment_import_messages(tenant_id, import_batch_id, severity, id);

CREATE TABLE sim_investment_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    import_batch_id BIGINT REFERENCES sim_investment_import_batches(id) ON DELETE SET NULL,
    action VARCHAR(80) NOT NULL,
    actor_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    actor_email VARCHAR(255),
    detail JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO modules(code,name,description,icon,path,display_order,enabled,is_system,backend_status_id,frontend_status_id,progress_percentage,is_production_ready)
VALUES('sim-investment','0912 Investment','0912 SIM market analysis, valuation and investment opportunities','mdi-chart-line-variant','/sim-investment',138,TRUE,TRUE,
 (SELECT id FROM module_statuses WHERE code='ACTIVE' AND tenant_id IS NULL),
 (SELECT id FROM module_statuses WHERE code='ACTIVE' AND tenant_id IS NULL),100,TRUE);

INSERT INTO permissions(module_id,action,code,name,is_system)
SELECT m.id,a.action,m.code||':'||a.action,m.name||' — '||a.label,TRUE FROM modules m CROSS JOIN (VALUES
 ('view','View dashboard and analyses'),('import','Import market snapshots'),('recalculate','Recalculate investment analysis'),
 ('view-history','View import and price history')) a(action,label) WHERE m.code='sim-investment';

INSERT INTO role_permissions(role_id,permission_id)
SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code LIKE 'sim-investment:%'
WHERE r.is_super_admin OR lower(r.name) IN ('admin','administrator') ON CONFLICT DO NOTHING;
