-- Makes the existing company schema in V22 reachable through the organization module.
CREATE TABLE organization_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    action VARCHAR(40) NOT NULL,
    actor_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    actor_email VARCHAR(255),
    detail JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_organization_audit_company ON organization_audit_logs(tenant_id, company_id, occurred_at DESC);

UPDATE modules
SET enabled = TRUE,
    is_available = TRUE,
    is_production_ready = TRUE,
    backend_status_id = (SELECT id FROM module_statuses WHERE code = 'ACTIVE' AND tenant_id IS NULL),
    frontend_status_id = (SELECT id FROM module_statuses WHERE code = 'ACTIVE' AND tenant_id IS NULL),
    overall_status_id = NULL,
    progress_percentage = 100,
    development_notes = 'Tenant-scoped company management is available; branch management remains separate.'
WHERE code = 'organization';

INSERT INTO role_permissions(role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN ('organization:view', 'organization:create', 'organization:edit')
WHERE r.is_super_admin OR lower(r.name) IN ('admin', 'administrator')
ON CONFLICT DO NOTHING;
