-- Phase 0 Foundation: additive organization scope, Contact mapping, and audit foundation.
-- Existing data remains the compatibility source until consuming modules complete dual-read cutover.

ALTER TABLE companies ADD CONSTRAINT uq_companies_id_tenant UNIQUE (id, tenant_id);
ALTER TABLE users ADD CONSTRAINT uq_users_id_tenant UNIQUE (id, tenant_id);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM branches b
        JOIN companies c ON c.id = b.company_id
        WHERE b.tenant_id <> c.tenant_id
    ) THEN
        RAISE EXCEPTION 'V51 refuses to add Company/Branch tenant integrity: existing mismatch detected';
    END IF;
END $$;

ALTER TABLE branches
    ADD CONSTRAINT fk_branches_company_tenant
    FOREIGN KEY (company_id, tenant_id) REFERENCES companies (id, tenant_id);

CREATE TABLE user_company_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL REFERENCES roles(id),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_ucr_user_tenant FOREIGN KEY (user_id, tenant_id) REFERENCES users(id, tenant_id),
    CONSTRAINT fk_ucr_company_tenant FOREIGN KEY (company_id, tenant_id) REFERENCES companies(id, tenant_id),
    CONSTRAINT uq_ucr_scope UNIQUE (tenant_id, user_id, company_id)
);
CREATE INDEX ix_ucr_user_tenant ON user_company_roles(tenant_id, user_id, is_active);

CREATE TABLE user_branch_grants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    assignment_id BIGINT NOT NULL REFERENCES user_company_roles(id) ON DELETE CASCADE,
    branch_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_ubg_branch_tenant FOREIGN KEY (branch_id, tenant_id) REFERENCES branches(id, tenant_id),
    CONSTRAINT uq_ubg_assignment_branch UNIQUE (assignment_id, branch_id)
);
CREATE INDEX ix_ubg_scope ON user_branch_grants(tenant_id, branch_id, is_active);

CREATE TABLE user_organization_contexts (
    tenant_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    company_id BIGINT,
    branch_id BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (tenant_id, user_id),
    CONSTRAINT fk_uoc_user_tenant FOREIGN KEY (user_id, tenant_id) REFERENCES users(id, tenant_id),
    CONSTRAINT fk_uoc_company_tenant FOREIGN KEY (company_id, tenant_id) REFERENCES companies(id, tenant_id),
    CONSTRAINT fk_uoc_branch_tenant FOREIGN KEY (branch_id, tenant_id) REFERENCES branches(id, tenant_id)
);

CREATE TABLE foundation_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    company_id BIGINT,
    branch_id BIGINT,
    actor_id BIGINT,
    actor_email VARCHAR(255),
    subject_type VARCHAR(80) NOT NULL,
    subject_id BIGINT,
    action VARCHAR(80) NOT NULL,
    reason VARCHAR(1000),
    context JSONB NOT NULL DEFAULT '{}'::jsonb,
    before_values JSONB,
    after_values JSONB,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_foundation_audit_scope ON foundation_audit_logs(tenant_id, company_id, branch_id, occurred_at DESC);
CREATE INDEX ix_foundation_audit_subject ON foundation_audit_logs(tenant_id, subject_type, subject_id, occurred_at DESC);

-- Product Owner approved bootstrap: the active user status is authoritative;
-- the sole active default Company/Branch is the only selected initial scope.
-- Returned rows are audited, so the policy remains an accountable migration,
-- not an implicit authorization path.
WITH created_assignments AS (
    INSERT INTO user_company_roles (tenant_id, user_id, company_id, role_id)
    SELECT u.tenant_id, u.id, c.id, u.role_id
    FROM users u
    JOIN user_statuses us ON us.id = u.status_id AND lower(us.code) = 'active'
    JOIN companies c ON c.tenant_id = u.tenant_id AND c.is_default AND c.is_active
    ON CONFLICT (tenant_id, user_id, company_id) DO NOTHING
    RETURNING id, tenant_id, user_id, company_id, role_id
)
INSERT INTO foundation_audit_logs (tenant_id, company_id, subject_type, subject_id, action, reason, context, after_values)
SELECT tenant_id, company_id, 'USER_COMPANY_ROLE', id, 'BOOTSTRAP_ASSIGNED',
       'PHASE_0_INITIAL_BOOTSTRAP',
       jsonb_build_object('userId', user_id, 'policy', 'active-user/default-active-company'),
       jsonb_build_object('roleId', role_id, 'active', true)
FROM created_assignments;

WITH created_grants AS (
    INSERT INTO user_branch_grants (tenant_id, assignment_id, branch_id)
    SELECT a.tenant_id, a.id, b.id
    FROM user_company_roles a
    JOIN branches b ON b.tenant_id = a.tenant_id AND b.company_id = a.company_id
                 AND b.is_default AND b.is_active
    ON CONFLICT (assignment_id, branch_id) DO NOTHING
    RETURNING id, tenant_id, assignment_id, branch_id
)
INSERT INTO foundation_audit_logs (tenant_id, branch_id, subject_type, subject_id, action, reason, context, after_values)
SELECT g.tenant_id, g.branch_id, 'USER_BRANCH_GRANT', g.id, 'BOOTSTRAP_GRANTED',
       'PHASE_0_INITIAL_BOOTSTRAP',
       jsonb_build_object('assignmentId', g.assignment_id, 'policy', 'active-user/default-active-branch'),
       jsonb_build_object('active', true)
FROM created_grants g;

-- An installation lacking a deterministic default is deliberately not granted
-- access. Preserve an explicit review signal for the administrator instead.
INSERT INTO foundation_audit_logs (tenant_id, subject_type, action, reason, context)
SELECT DISTINCT u.tenant_id, 'BOOTSTRAP', 'REVIEW_REQUIRED',
       'No active default Company was available for Phase 0 bootstrap',
       jsonb_build_object('policy', 'active-user/default-active-company')
FROM users u
JOIN user_statuses us ON us.id = u.status_id AND lower(us.code) = 'active'
WHERE NOT EXISTS (SELECT 1 FROM companies c WHERE c.tenant_id = u.tenant_id AND c.is_default AND c.is_active);

INSERT INTO foundation_audit_logs (tenant_id, company_id, subject_type, action, reason, context)
SELECT c.tenant_id, c.id, 'BOOTSTRAP', 'REVIEW_REQUIRED',
       'No active default Branch was available for Phase 0 bootstrap',
       jsonb_build_object('policy', 'active-user/default-active-branch')
FROM companies c
WHERE c.is_default AND c.is_active
  AND NOT EXISTS (SELECT 1 FROM branches b WHERE b.tenant_id = c.tenant_id AND b.company_id = c.id AND b.is_default AND b.is_active);

CREATE TABLE contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    identity_type VARCHAR(16) NOT NULL,
    display_name VARCHAR(160) NOT NULL,
    first_name VARCHAR(80),
    last_name VARCHAR(80),
    company_name VARCHAR(160),
    national_code VARCHAR(32),
    legal_identifier VARCHAR(64),
    tax_number VARCHAR(64),
    email VARCHAR(255),
    phone VARCHAR(64),
    legacy_source_type VARCHAR(16),
    legacy_source_id BIGINT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    merged_into_id BIGINT REFERENCES contacts(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_contacts_identity_type CHECK (identity_type IN ('NATURAL','LEGAL')),
    CONSTRAINT ck_contacts_not_self_merged CHECK (merged_into_id IS NULL OR merged_into_id <> id)
);
CREATE UNIQUE INDEX uq_contacts_national_code ON contacts(tenant_id, national_code) WHERE national_code IS NOT NULL;
CREATE UNIQUE INDEX uq_contacts_legal_identifier ON contacts(tenant_id, legal_identifier) WHERE legal_identifier IS NOT NULL;
CREATE UNIQUE INDEX uq_contacts_legacy_source ON contacts(tenant_id, legacy_source_type, legacy_source_id)
    WHERE legacy_source_type IS NOT NULL AND legacy_source_id IS NOT NULL;
CREATE INDEX ix_contacts_tax_number ON contacts(tenant_id, tax_number) WHERE tax_number IS NOT NULL;

CREATE TABLE contact_customer_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    contact_id BIGINT NOT NULL REFERENCES contacts(id),
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_contact_customer_role_contact UNIQUE(contact_id),
    CONSTRAINT uq_contact_customer_role_customer UNIQUE(customer_id)
);
CREATE INDEX ix_contact_customer_roles_tenant ON contact_customer_roles(tenant_id, contact_id);

CREATE TABLE contact_supplier_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    contact_id BIGINT NOT NULL REFERENCES contacts(id),
    supplier_id BIGINT NOT NULL REFERENCES suppliers(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_contact_supplier_role_contact_supplier UNIQUE(contact_id, supplier_id),
    CONSTRAINT uq_contact_supplier_role_supplier UNIQUE(supplier_id)
);
CREATE INDEX ix_contact_supplier_roles_tenant ON contact_supplier_roles(tenant_id, contact_id);

CREATE TABLE legacy_contact_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    legacy_type VARCHAR(16) NOT NULL,
    legacy_id BIGINT NOT NULL,
    contact_id BIGINT NOT NULL REFERENCES contacts(id),
    match_method VARCHAR(32) NOT NULL,
    review_required BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_legacy_contact_mapping_type CHECK (legacy_type IN ('CUSTOMER','SUPPLIER')),
    CONSTRAINT uq_legacy_contact_mapping UNIQUE(tenant_id, legacy_type, legacy_id)
);
CREATE INDEX ix_legacy_contact_mapping_contact ON legacy_contact_mappings(tenant_id, contact_id);

CREATE TABLE contact_merge_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    left_contact_id BIGINT NOT NULL REFERENCES contacts(id),
    right_contact_id BIGINT NOT NULL REFERENCES contacts(id),
    reason VARCHAR(500) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_contact_merge_candidate_distinct CHECK(left_contact_id <> right_contact_id),
    CONSTRAINT uq_contact_merge_candidate_pair UNIQUE(tenant_id, left_contact_id, right_contact_id)
);

-- Deterministic Customer source rows first. A legacy source is retained even
-- when it shares an approved canonical identifier with another source row.
INSERT INTO contacts (tenant_id, identity_type, display_name, first_name, last_name, company_name, national_code, tax_number)
SELECT c.tenant_id,
       CASE WHEN c.national_code IS NOT NULL THEN 'NATURAL' ELSE 'LEGAL' END,
       c.display_name, c.first_name, c.last_name, c.company_name, c.national_code, c.tax_number
FROM customers c
WHERE c.merged_into_id IS NULL AND c.national_code IS NOT NULL
ON CONFLICT (tenant_id, national_code) WHERE national_code IS NOT NULL DO NOTHING;

INSERT INTO contacts (tenant_id, identity_type, display_name, first_name, last_name, company_name, tax_number, legacy_source_type, legacy_source_id)
SELECT c.tenant_id, 'LEGAL', c.display_name, c.first_name, c.last_name, c.company_name, c.tax_number, 'CUSTOMER', c.id
FROM customers c
WHERE c.merged_into_id IS NULL AND c.national_code IS NULL
ON CONFLICT (tenant_id, legacy_source_type, legacy_source_id) WHERE legacy_source_type IS NOT NULL AND legacy_source_id IS NOT NULL DO NOTHING;

INSERT INTO legacy_contact_mappings (tenant_id, legacy_type, legacy_id, contact_id, match_method)
SELECT c.tenant_id, 'CUSTOMER', c.id, x.id,
       CASE WHEN c.national_code IS NOT NULL THEN 'NATIONAL_CODE' ELSE 'CUSTOMER_SOURCE' END
FROM customers c
JOIN contacts x ON x.tenant_id=c.tenant_id
 AND ((c.national_code IS NOT NULL AND x.national_code=c.national_code)
      OR (c.national_code IS NULL AND x.legacy_source_type='CUSTOMER' AND x.legacy_source_id=c.id))
WHERE c.merged_into_id IS NULL;

INSERT INTO contact_customer_roles (tenant_id, contact_id, customer_id)
SELECT DISTINCT ON (tenant_id, contact_id) tenant_id, contact_id, legacy_id
FROM legacy_contact_mappings
WHERE legacy_type='CUSTOMER'
ORDER BY tenant_id, contact_id, legacy_id;

-- Supplier joins a Customer Contact only on exact approved national/legal identifiers; otherwise it receives its own Contact.
INSERT INTO contacts (tenant_id, identity_type, display_name, company_name, legal_identifier, tax_number)
SELECT s.tenant_id, 'LEGAL', s.display_name, s.company_name, s.national_id, s.tax_number
FROM suppliers s
WHERE s.national_id IS NOT NULL
ON CONFLICT (tenant_id, legal_identifier) WHERE legal_identifier IS NOT NULL DO NOTHING;

INSERT INTO contacts (tenant_id, identity_type, display_name, company_name, tax_number, legacy_source_type, legacy_source_id)
SELECT s.tenant_id, 'LEGAL', s.display_name, s.company_name, s.tax_number, 'SUPPLIER', s.id
FROM suppliers s
WHERE s.national_id IS NULL
ON CONFLICT (tenant_id, legacy_source_type, legacy_source_id) WHERE legacy_source_type IS NOT NULL AND legacy_source_id IS NOT NULL DO NOTHING;

INSERT INTO legacy_contact_mappings (tenant_id, legacy_type, legacy_id, contact_id, match_method)
SELECT s.tenant_id, 'SUPPLIER', s.id, c.id,
 CASE WHEN s.national_id IS NOT NULL AND (c.legal_identifier=s.national_id OR c.national_code=s.national_id) THEN 'EXACT_IDENTIFIER' ELSE 'EXACT_TAX_NUMBER' END
FROM suppliers s
JOIN LATERAL (
 SELECT c.id, c.legal_identifier, c.national_code, c.tax_number FROM contacts c
 WHERE c.tenant_id=s.tenant_id
 AND ((s.national_id IS NOT NULL AND (c.legal_identifier=s.national_id OR c.national_code=s.national_id))
   OR (s.tax_number IS NOT NULL AND c.tax_number=s.tax_number)
   OR (c.legacy_source_type='SUPPLIER' AND c.legacy_source_id=s.id))
 ORDER BY CASE
   WHEN s.national_id IS NOT NULL AND (c.legal_identifier=s.national_id OR c.national_code=s.national_id) THEN 0
   WHEN s.tax_number IS NOT NULL AND c.tax_number=s.tax_number THEN 1
   ELSE 2
 END, c.id
 LIMIT 1
) c ON TRUE;

INSERT INTO contact_supplier_roles (tenant_id, contact_id, supplier_id)
SELECT tenant_id, contact_id, legacy_id FROM legacy_contact_mappings WHERE legacy_type='SUPPLIER';

DO $$
DECLARE missing_customer BIGINT; missing_supplier BIGINT;
BEGIN
 SELECT count(*) INTO missing_customer FROM customers c WHERE c.merged_into_id IS NULL AND NOT EXISTS (SELECT 1 FROM legacy_contact_mappings m WHERE m.tenant_id=c.tenant_id AND m.legacy_type='CUSTOMER' AND m.legacy_id=c.id);
 SELECT count(*) INTO missing_supplier FROM suppliers s WHERE NOT EXISTS (SELECT 1 FROM legacy_contact_mappings m WHERE m.tenant_id=s.tenant_id AND m.legacy_type='SUPPLIER' AND m.legacy_id=s.id);
 IF missing_customer <> 0 OR missing_supplier <> 0 THEN
   RAISE EXCEPTION 'V51 Contact reconciliation failed: missing customer %, supplier % mappings', missing_customer, missing_supplier;
 END IF;
END $$;
