-- Phase 1 / Slice 1: preserve the existing Sales aggregate while future
-- commercial documents are introduced. This migration intentionally creates
-- no target documents and performs no historical data backfill.
--
-- The composite key is additive and allows the mapping FK below to prove that
-- a provenance row has the same tenant/company/branch as its legacy Sale.
ALTER TABLE sales
    ADD CONSTRAINT uq_sales_tenant_scope_id UNIQUE (tenant_id, id, company_id, branch_id);

CREATE TABLE legacy_sale_document_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    legacy_sale_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
    branch_id BIGINT NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,
    document_type VARCHAR(32) NOT NULL,
    document_id BIGINT NOT NULL CHECK (document_id > 0),
    mapping_reason VARCHAR(48) NOT NULL DEFAULT 'LEGACY_COMPATIBILITY',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_legacy_sale_document_mapping_type
        CHECK (document_type IN ('QUOTATION', 'SALES_ORDER', 'FULFILLMENT', 'SALES_INVOICE')),
    CONSTRAINT fk_legacy_sale_document_mapping_legacy_scope
        FOREIGN KEY (tenant_id, legacy_sale_id, company_id, branch_id)
        REFERENCES sales(tenant_id, id, company_id, branch_id) ON DELETE RESTRICT,
    CONSTRAINT uq_legacy_sale_document_mapping
        UNIQUE (tenant_id, legacy_sale_id, document_type, document_id)
);

CREATE INDEX ix_legacy_sale_document_mapping_legacy
    ON legacy_sale_document_mappings (tenant_id, legacy_sale_id);
CREATE INDEX ix_legacy_sale_document_mapping_document
    ON legacy_sale_document_mappings (tenant_id, document_type, document_id);
