-- Phase 1 / Slice 2. Commercial-only documents; no inventory, treasury or accounting tables are touched.
CREATE SEQUENCE sales_document_number_seq START WITH 1;
CREATE TABLE sales_documents (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
 company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT, branch_id BIGINT NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,
 document_type VARCHAR(16) NOT NULL, document_number VARCHAR(48) NOT NULL, customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
 contact_id BIGINT NOT NULL REFERENCES contacts(id) ON DELETE RESTRICT, status VARCHAR(16) NOT NULL, currency VARCHAR(3) NOT NULL DEFAULT 'IRR',
 subtotal NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK(subtotal>=0), discount_total NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK(discount_total>=0), final_amount NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK(final_amount>=0), notes VARCHAR(2000),
 issued_at TIMESTAMPTZ, cancelled_at TIMESTAMPTZ, expired_at TIMESTAMPTZ, created_by BIGINT, created_by_email VARCHAR(255), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT ck_sales_document_type CHECK(document_type IN ('QUOTATION','PROFORMA')), CONSTRAINT ck_sales_document_status CHECK(status IN ('DRAFT','ISSUED','CANCELLED','EXPIRED')),
 CONSTRAINT uq_sales_document_number UNIQUE(tenant_id, document_number)
);
CREATE INDEX ix_sales_documents_scope ON sales_documents(tenant_id,company_id,branch_id,document_type,created_at DESC);
CREATE TABLE sales_document_lines (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, document_id BIGINT NOT NULL REFERENCES sales_documents(id) ON DELETE CASCADE, tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
 product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT, product_sku VARCHAR(100) NOT NULL, product_name VARCHAR(255) NOT NULL, quantity NUMERIC(14,3) NOT NULL CHECK(quantity>0), unit_price NUMERIC(18,2) NOT NULL CHECK(unit_price>=0), discount NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK(discount>=0), line_total NUMERIC(18,2) NOT NULL CHECK(line_total>=0), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX ix_sales_document_lines_document ON sales_document_lines(document_id);
CREATE TABLE sales_document_audit_history (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, document_id BIGINT NOT NULL REFERENCES sales_documents(id) ON DELETE CASCADE, tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT, action VARCHAR(48) NOT NULL, actor_id BIGINT, actor_email VARCHAR(255), old_value JSONB, new_value JSONB, occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX ix_sales_document_audit_history ON sales_document_audit_history(tenant_id,document_id,occurred_at DESC);
