-- Phase 1 / Slice 4. Delivery owns physical issue; no financial posting.
CREATE SEQUENCE sales_delivery_number_seq START WITH 1;
CREATE TABLE sales_deliveries (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
 order_id BIGINT NOT NULL REFERENCES sales_orders(id) ON DELETE RESTRICT,
 company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
 branch_id BIGINT NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,
 customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
 contact_id BIGINT NOT NULL REFERENCES contacts(id) ON DELETE RESTRICT,
 delivery_number VARCHAR(48) NOT NULL, status VARCHAR(16) NOT NULL,
 notes VARCHAR(2000), confirmed_at TIMESTAMPTZ, cancelled_at TIMESTAMPTZ,
 created_by BIGINT, created_by_email VARCHAR(255), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT ck_sales_delivery_status CHECK(status IN ('DRAFT','CONFIRMED','CANCELLED')),
 CONSTRAINT uq_sales_delivery_number UNIQUE(tenant_id,delivery_number)
);
CREATE INDEX ix_sales_deliveries_scope ON sales_deliveries(tenant_id,company_id,branch_id,status,created_at DESC);
CREATE TABLE sales_delivery_lines (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 delivery_id BIGINT NOT NULL REFERENCES sales_deliveries(id) ON DELETE CASCADE,
 order_line_id BIGINT NOT NULL REFERENCES sales_order_lines(id) ON DELETE RESTRICT,
 tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
 product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
 product_sku VARCHAR(100) NOT NULL, product_name VARCHAR(255) NOT NULL,
 ordered_quantity NUMERIC(14,3) NOT NULL CHECK(ordered_quantity>0), reserved_quantity NUMERIC(14,3) NOT NULL CHECK(reserved_quantity>=0),
 previously_delivered_quantity NUMERIC(14,3) NOT NULL DEFAULT 0 CHECK(previously_delivered_quantity>=0), delivery_quantity NUMERIC(14,3) NOT NULL CHECK(delivery_quantity>0), backordered_quantity NUMERIC(14,3) NOT NULL DEFAULT 0 CHECK(backordered_quantity>=0),
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT ck_sales_delivery_line_total CHECK(previously_delivered_quantity + delivery_quantity <= ordered_quantity)
);
CREATE INDEX ix_sales_delivery_lines_order_line ON sales_delivery_lines(tenant_id,order_line_id);
CREATE TABLE sales_delivery_audit_history (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 delivery_id BIGINT NOT NULL REFERENCES sales_deliveries(id) ON DELETE CASCADE,
 tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
 action VARCHAR(48) NOT NULL, actor_id BIGINT, actor_email VARCHAR(255), old_value JSONB, new_value JSONB,
 occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX ix_sales_delivery_audit_history ON sales_delivery_audit_history(tenant_id,delivery_id,occurred_at DESC);
