-- Phase 1 / Slice 5. Invoice owns receivable intent; Accounting owns posting truth.
CREATE SEQUENCE sales_invoice_number_seq START WITH 1;
CREATE TABLE sales_invoices (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
 order_id BIGINT NOT NULL REFERENCES sales_orders(id) ON DELETE RESTRICT,
 delivery_id BIGINT REFERENCES sales_deliveries(id) ON DELETE RESTRICT,
 company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
 branch_id BIGINT NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,
 customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
 contact_id BIGINT NOT NULL REFERENCES contacts(id) ON DELETE RESTRICT,
 invoice_number VARCHAR(48) NOT NULL, status VARCHAR(16) NOT NULL,
 currency VARCHAR(3) NOT NULL DEFAULT 'IRR', subtotal NUMERIC(18,2) NOT NULL DEFAULT 0,
 discount_total NUMERIC(18,2) NOT NULL DEFAULT 0, final_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
 receivable_posting_key VARCHAR(128), receivable_posted_at TIMESTAMPTZ,
 notes VARCHAR(2000), issued_at TIMESTAMPTZ, cancelled_at TIMESTAMPTZ,
 created_by BIGINT, created_by_email VARCHAR(255), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT ck_sales_invoice_status CHECK(status IN ('DRAFT','ISSUED','CANCELLED')),
 CONSTRAINT ck_sales_invoice_amounts CHECK(subtotal>=0 AND discount_total>=0 AND final_amount>=0),
 CONSTRAINT uq_sales_invoice_number UNIQUE(tenant_id,invoice_number),
 CONSTRAINT uq_sales_invoice_posting_key UNIQUE(tenant_id,receivable_posting_key)
);
CREATE INDEX ix_sales_invoices_scope ON sales_invoices(tenant_id,company_id,branch_id,status,created_at DESC);
CREATE TABLE sales_invoice_lines (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 invoice_id BIGINT NOT NULL REFERENCES sales_invoices(id) ON DELETE CASCADE,
 tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
 order_line_id BIGINT NOT NULL REFERENCES sales_order_lines(id) ON DELETE RESTRICT,
 delivery_line_id BIGINT NOT NULL REFERENCES sales_delivery_lines(id) ON DELETE RESTRICT,
 product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
 product_sku VARCHAR(100) NOT NULL, product_name VARCHAR(255) NOT NULL,
 quantity NUMERIC(14,3) NOT NULL CHECK(quantity>0), unit_price NUMERIC(18,2) NOT NULL CHECK(unit_price>=0),
 discount NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK(discount>=0), line_total NUMERIC(18,2) NOT NULL CHECK(line_total>=0),
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX ix_sales_invoice_lines_delivery ON sales_invoice_lines(tenant_id,delivery_line_id);
CREATE TABLE sales_invoice_audit_history (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 invoice_id BIGINT NOT NULL REFERENCES sales_invoices(id) ON DELETE CASCADE,
 tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
 action VARCHAR(48) NOT NULL, actor_id BIGINT, actor_email VARCHAR(255), old_value JSONB, new_value JSONB,
 occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX ix_sales_invoice_audit_history ON sales_invoice_audit_history(tenant_id,invoice_id,occurred_at DESC);
