alter table sales_receipts add column if not exists cheque_status varchar(24);
alter table sales_receipts add column if not exists accounting_posting_reference varchar(160);
alter table sales_receipts add constraint sales_receipts_cheque_status_ck check (cheque_status is null or cheque_status in ('PENDING_COLLECTION','CLEARED','RETURNED'));
create table if not exists customer_credit_restrictions (id bigint generated by default as identity primary key, tenant_id bigint not null references tenants(id), customer_id bigint not null references customers(id), receipt_id bigint not null references sales_receipts(id), reason varchar(500) not null, active boolean not null default true, created_at timestamptz not null default now(), resolved_at timestamptz);
create unique index if not exists customer_credit_restrictions_active_uq on customer_credit_restrictions(tenant_id,customer_id) where active;
