create table accounting_receivables (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    company_id bigint not null references companies(id),
    branch_id bigint not null references branches(id),
    counterparty_contact_id bigint not null references contacts(id),
    sales_invoice_id bigint not null,
    amount numeric(18,2) not null,
    currency varchar(3) not null,
    issued_at timestamptz not null,
    idempotency_key varchar(160) not null,
    created_at timestamptz not null default now(),
    unique (tenant_id, idempotency_key)
);
