-- P4-S2: tenant/company/branch-scoped accounting foundation.
-- This migration adds canonical master data only; it does not promote legacy
-- accounting evidence or create journal entries.

CREATE TABLE accounting_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    company_id BIGINT NOT NULL REFERENCES companies(id),
    branch_id BIGINT REFERENCES branches(id),
    parent_account_id BIGINT REFERENCES accounting_accounts(id),
    code VARCHAR(64) NOT NULL,
    name VARCHAR(255) NOT NULL,
    account_type VARCHAR(32) NOT NULL,
    is_postable BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_account_scope_code UNIQUE (tenant_id, company_id, branch_id, code),
    CONSTRAINT ck_account_type CHECK (account_type IN ('ASSET','LIABILITY','EQUITY','REVENUE','EXPENSE')),
    CONSTRAINT ck_account_not_self_parent CHECK (parent_account_id IS NULL OR parent_account_id <> id)
);

CREATE INDEX ix_account_scope ON accounting_accounts(tenant_id, company_id, branch_id, is_active);
CREATE INDEX ix_account_parent ON accounting_accounts(parent_account_id);

CREATE TABLE accounting_fiscal_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    company_id BIGINT NOT NULL REFERENCES companies(id),
    branch_id BIGINT REFERENCES branches(id),
    period_code VARCHAR(64) NOT NULL,
    period_name VARCHAR(255) NOT NULL,
    starts_on DATE NOT NULL,
    ends_on DATE NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    closed_at TIMESTAMPTZ,
    closed_by BIGINT,
    reopened_at TIMESTAMPTZ,
    reopened_by BIGINT,
    reopen_reason VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fiscal_period_scope_code UNIQUE (tenant_id, company_id, branch_id, period_code),
    CONSTRAINT ck_fiscal_period_dates CHECK (ends_on >= starts_on),
    CONSTRAINT ck_fiscal_period_status CHECK (status IN ('OPEN','CLOSED')),
    CONSTRAINT ck_fiscal_period_reopen_reason CHECK (status = 'OPEN' OR reopened_at IS NULL OR reopen_reason IS NOT NULL)
);

CREATE INDEX ix_fiscal_period_scope_dates
    ON accounting_fiscal_periods(tenant_id, company_id, branch_id, starts_on, ends_on);

CREATE TABLE accounting_fiscal_period_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    fiscal_period_id BIGINT NOT NULL REFERENCES accounting_fiscal_periods(id),
    event_type VARCHAR(16) NOT NULL,
    actor_id BIGINT,
    reason VARCHAR(1000),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_fiscal_period_event_type CHECK (event_type IN ('CLOSED','REOPENED')),
    CONSTRAINT ck_fiscal_period_reopen_event_reason CHECK (event_type <> 'REOPENED' OR reason IS NOT NULL)
);

CREATE INDEX ix_fiscal_period_events_period
    ON accounting_fiscal_period_events(tenant_id, fiscal_period_id, occurred_at);
