-- P4-S3: immutable, balanced canonical Journal/GL foundation.
-- Posting services must validate tenant/company/branch/account scope and open
-- fiscal periods. This migration does not create posting rules for domains.

CREATE TABLE accounting_journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
    branch_id BIGINT REFERENCES branches(id) ON DELETE RESTRICT,
    fiscal_period_id BIGINT NOT NULL REFERENCES accounting_fiscal_periods(id) ON DELETE RESTRICT,
    entry_type VARCHAR(16) NOT NULL DEFAULT 'ORIGINAL',
    posting_reference VARCHAR(160) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    currency_code VARCHAR(3) NOT NULL DEFAULT 'IRR',
    posted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    description VARCHAR(2000),
    reversal_of_id BIGINT REFERENCES accounting_journal_entries(id) ON DELETE RESTRICT,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_accounting_journal_scope_reference UNIQUE (tenant_id, posting_reference),
    CONSTRAINT uq_accounting_journal_scope_idempotency UNIQUE (tenant_id, idempotency_key),
    CONSTRAINT ck_accounting_journal_entry_type CHECK (entry_type IN ('ORIGINAL','REVERSAL','CORRECTION')),
    CONSTRAINT ck_accounting_journal_reversal_type CHECK (
        (entry_type = 'ORIGINAL' AND reversal_of_id IS NULL)
        OR (entry_type IN ('REVERSAL','CORRECTION') AND reversal_of_id IS NOT NULL)
    )
);

CREATE INDEX ix_accounting_journal_scope_period
    ON accounting_journal_entries(tenant_id, company_id, branch_id, fiscal_period_id, posted_at DESC);

CREATE TABLE accounting_journal_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_entry_id BIGINT NOT NULL REFERENCES accounting_journal_entries(id) ON DELETE RESTRICT,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    account_id BIGINT NOT NULL REFERENCES accounting_accounts(id) ON DELETE RESTRICT,
    line_number INTEGER NOT NULL,
    description VARCHAR(1000),
    debit_amount NUMERIC(18,0) NOT NULL DEFAULT 0,
    credit_amount NUMERIC(18,0) NOT NULL DEFAULT 0,
    CONSTRAINT uq_accounting_journal_line_number UNIQUE (journal_entry_id, line_number),
    CONSTRAINT ck_accounting_journal_line_number CHECK (line_number > 0),
    CONSTRAINT ck_accounting_journal_line_amounts CHECK (
        (debit_amount > 0 AND credit_amount = 0)
        OR (credit_amount > 0 AND debit_amount = 0)
    )
);

CREATE INDEX ix_accounting_journal_lines_account
    ON accounting_journal_lines(tenant_id, account_id, journal_entry_id);

CREATE OR REPLACE FUNCTION accounting_assert_balanced_journal()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_journal_id BIGINT;
    v_debit NUMERIC(18,0);
    v_credit NUMERIC(18,0);
BEGIN
    v_journal_id := COALESCE(NEW.journal_entry_id, OLD.journal_entry_id);
    SELECT COALESCE(SUM(debit_amount), 0), COALESCE(SUM(credit_amount), 0)
      INTO v_debit, v_credit
      FROM accounting_journal_lines
     WHERE journal_entry_id = v_journal_id;
    IF v_debit <> v_credit OR v_debit = 0 THEN
        RAISE EXCEPTION 'Accounting journal % must be non-zero and balanced (debit %, credit %)',
            v_journal_id, v_debit, v_credit;
    END IF;
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER accounting_journal_lines_balanced
AFTER INSERT OR UPDATE OR DELETE ON accounting_journal_lines
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION accounting_assert_balanced_journal();

CREATE CONSTRAINT TRIGGER accounting_journal_entry_balanced
AFTER INSERT ON accounting_journal_entries
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION accounting_assert_balanced_journal();

CREATE OR REPLACE FUNCTION accounting_reject_journal_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'Posted accounting journals are immutable';
END;
$$;

CREATE TRIGGER accounting_journal_entries_immutable
BEFORE UPDATE OR DELETE ON accounting_journal_entries
FOR EACH ROW EXECUTE FUNCTION accounting_reject_journal_mutation();

CREATE TRIGGER accounting_journal_lines_immutable
BEFORE UPDATE OR DELETE ON accounting_journal_lines
FOR EACH ROW EXECUTE FUNCTION accounting_reject_journal_mutation();
