-- P4-S6: effective-dated, tenant-scoped tax configuration.
-- Values are configuration only; no statutory rates are seeded here.
CREATE TABLE accounting_tax_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    company_id BIGINT REFERENCES companies(id) ON DELETE RESTRICT,
    branch_id BIGINT REFERENCES branches(id) ON DELETE RESTRICT,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(255) NOT NULL,
    policy_type VARCHAR(24) NOT NULL,
    rate NUMERIC(18,6) NOT NULL DEFAULT 0 CHECK (rate >= 0),
    exempt BOOLEAN NOT NULL DEFAULT FALSE,
    effective_from DATE NOT NULL,
    effective_to DATE,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_tax_policy_type CHECK (policy_type IN ('RATE','EXEMPTION','WITHHOLDING')),
    CONSTRAINT ck_tax_policy_dates CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT ck_tax_policy_exemption CHECK (NOT exempt OR policy_type = 'EXEMPTION'),
    CONSTRAINT uq_tax_policy_version UNIQUE (tenant_id, company_id, branch_id, code, effective_from)
);
CREATE INDEX ix_tax_policy_effective
    ON accounting_tax_policies(tenant_id, company_id, branch_id, code, effective_from DESC);
