-- Phase 5 CRM workflow foundation. Policy-neutral records only; scoring and
-- inactivity thresholds remain governed by the approved open decisions.
CREATE TABLE crm_leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    customer_id BIGINT,
    title VARCHAR(160) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    source VARCHAR(64),
    assigned_user_id BIGINT,
    notes VARCHAR(4000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_crm_lead_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT ck_crm_lead_status CHECK (status IN ('OPEN','QUALIFIED','CONVERTED','LOST','CLOSED'))
);
CREATE INDEX idx_crm_leads_tenant_status ON crm_leads (tenant_id, status);
CREATE INDEX idx_crm_leads_tenant_customer ON crm_leads (tenant_id, customer_id);

CREATE TABLE crm_opportunities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    customer_id BIGINT,
    lead_id BIGINT,
    title VARCHAR(160) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    expected_value NUMERIC(19,2),
    expected_close_date DATE,
    assigned_user_id BIGINT,
    notes VARCHAR(4000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_crm_opportunity_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_crm_opportunity_lead FOREIGN KEY (lead_id) REFERENCES crm_leads(id),
    CONSTRAINT ck_crm_opportunity_status CHECK (status IN ('OPEN','WON','LOST','CLOSED')),
    CONSTRAINT ck_crm_opportunity_value CHECK (expected_value IS NULL OR expected_value >= 0)
);
CREATE INDEX idx_crm_opportunities_tenant_status ON crm_opportunities (tenant_id, status);
CREATE INDEX idx_crm_opportunities_tenant_customer ON crm_opportunities (tenant_id, customer_id);

CREATE TABLE crm_follow_up_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    customer_id BIGINT,
    lead_id BIGINT,
    opportunity_id BIGINT,
    assigned_user_id BIGINT,
    due_at TIMESTAMPTZ,
    status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    outcome VARCHAR(32),
    outcome_note VARCHAR(4000),
    completed_at TIMESTAMPTZ,
    idempotency_key VARCHAR(160),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_crm_task_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_crm_task_lead FOREIGN KEY (lead_id) REFERENCES crm_leads(id),
    CONSTRAINT fk_crm_task_opportunity FOREIGN KEY (opportunity_id) REFERENCES crm_opportunities(id),
    CONSTRAINT ck_crm_task_status CHECK (status IN ('OPEN','COMPLETED','CANCELLED')),
    CONSTRAINT ck_crm_task_outcome CHECK (outcome IS NULL OR outcome IN ('PURCHASED','NOT_INTERESTED','CALL_LATER','ISSUE','OTHER')),
    CONSTRAINT uq_crm_task_idempotency UNIQUE (tenant_id, idempotency_key)
);
CREATE INDEX idx_crm_tasks_tenant_status_due ON crm_follow_up_tasks (tenant_id, status, due_at);
CREATE INDEX idx_crm_tasks_tenant_customer ON crm_follow_up_tasks (tenant_id, customer_id);
