CREATE TABLE crm_intelligence_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL UNIQUE,
    recency_weight NUMERIC(5,4) NOT NULL DEFAULT 0.35,
    frequency_weight NUMERIC(5,4) NOT NULL DEFAULT 0.25,
    monetary_weight NUMERIC(5,4) NOT NULL DEFAULT 0.25,
    trend_weight NUMERIC(5,4) NOT NULL DEFAULT 0.15,
    updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_crm_intelligence_weights CHECK (recency_weight >= 0 AND frequency_weight >= 0 AND monetary_weight >= 0 AND trend_weight >= 0 AND recency_weight + frequency_weight + monetary_weight + trend_weight = 1)
);
CREATE INDEX idx_crm_intelligence_config_tenant ON crm_intelligence_config (tenant_id);
