-- CRM extensions: relationships, configurable preferences, blacklist,
-- segments (marketing / saved filters), and dedicated manage permissions.

-- Configurable relation types (family, partner, guarantor, emergency contact…).
CREATE TABLE crm_relation_types (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_crm_relation_types PRIMARY KEY (id),
    CONSTRAINT uq_crm_relation_types_code UNIQUE (code)
);

INSERT INTO crm_relation_types (code, name, is_system, display_order) VALUES
    ('family',            'Family Member',     TRUE, 10),
    ('business-partner',  'Business Partner',  TRUE, 20),
    ('guarantor',         'Guarantor',         TRUE, 30),
    ('emergency-contact', 'Emergency Contact', TRUE, 40),
    ('company-contact',   'Company Contact',   TRUE, 50);

-- Customer-to-customer relationships.
CREATE TABLE customer_relations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id         BIGINT       NOT NULL,
    related_customer_id BIGINT       NOT NULL,
    relation_type_id    BIGINT       NOT NULL,
    note                VARCHAR(255),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version             BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_customer_relations PRIMARY KEY (id),
    CONSTRAINT fk_cr_customer FOREIGN KEY (customer_id)
        REFERENCES customers (id) ON DELETE CASCADE,
    CONSTRAINT fk_cr_related FOREIGN KEY (related_customer_id)
        REFERENCES customers (id) ON DELETE CASCADE,
    CONSTRAINT fk_cr_type FOREIGN KEY (relation_type_id) REFERENCES crm_relation_types (id),
    CONSTRAINT uq_customer_relations UNIQUE (customer_id, related_customer_id, relation_type_id),
    CONSTRAINT ck_customer_relations_not_self CHECK (customer_id <> related_customer_id)
);
CREATE INDEX idx_customer_relations_customer ON customer_relations (customer_id);
CREATE INDEX idx_customer_relations_related  ON customer_relations (related_customer_id);

-- Configurable preference fields (same dynamic-field pattern as user profiles):
-- definitions are data, values live in customers.preferences (JSONB).
CREATE TABLE crm_preference_definitions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    pref_key      VARCHAR(64)  NOT NULL,
    label         VARCHAR(100) NOT NULL,
    field_type    VARCHAR(16)  NOT NULL,   -- TEXT | NUMBER | DATE | BOOLEAN | SELECT
    required      BOOLEAN      NOT NULL DEFAULT FALSE,
    min_length    INTEGER,
    max_length    INTEGER,
    pattern       VARCHAR(255),
    options       JSONB,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_crm_preference_definitions PRIMARY KEY (id),
    CONSTRAINT uq_crm_preference_definitions_key UNIQUE (pref_key)
);

INSERT INTO crm_preference_definitions (pref_key, label, field_type, options, display_order) VALUES
    ('favorite_brand',      'Favorite Brand',            'SELECT', '["Apple","Samsung","Xiaomi","Huawei","Nokia","Other"]', 10),
    ('favorite_model',      'Favorite Model',            'TEXT',   NULL, 20),
    ('budget_range',        'Budget Range',              'SELECT', '["Economy","Mid-range","Flagship","Unlimited"]', 30),
    ('preferred_color',     'Preferred Color',           'TEXT',   NULL, 40),
    ('preferred_storage',   'Preferred Storage',         'SELECT', '["64GB","128GB","256GB","512GB","1TB"]', 50),
    ('preferred_os',        'Preferred Operating System','SELECT', '["iOS","Android","Other"]', 60),
    ('purchase_frequency',  'Purchase Frequency',        'SELECT', '["Rare","Occasional","Frequent"]', 70),
    ('communication_pref',  'Communication Preference',  'SELECT', '["Call","SMS","Telegram","WhatsApp","Email"]', 80),
    ('preferred_payment',   'Preferred Payment Method',  'SELECT', '["Cash","Card","Installment"]', 90),
    ('contact_time',        'Preferred Contact Time',    'SELECT', '["Morning","Afternoon","Evening"]', 100);

ALTER TABLE customers ADD COLUMN preferences JSONB NOT NULL DEFAULT '{}'::jsonb;

-- Blacklist: configurable reasons + an auditable entry log. The status carrying
-- is_blacklist_state (unique) is the transition target; blacklisted statuses
-- stay visible (not hidden_by_default) so blocked customers remain searchable.
CREATE TABLE crm_blacklist_reasons (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_crm_blacklist_reasons PRIMARY KEY (id),
    CONSTRAINT uq_crm_blacklist_reasons_code UNIQUE (code)
);

INSERT INTO crm_blacklist_reasons (code, name, is_system, display_order) VALUES
    ('fraud',            'Fraud',                TRUE, 10),
    ('bad-debt',         'Unpaid Debt',          TRUE, 20),
    ('chargeback',       'Chargeback Abuse',     TRUE, 30),
    ('abusive-behavior', 'Abusive Behavior',     TRUE, 40),
    ('other',            'Other',                TRUE, 50);

ALTER TABLE customer_statuses ADD COLUMN is_blacklist_state BOOLEAN NOT NULL DEFAULT FALSE;
CREATE UNIQUE INDEX uq_customer_statuses_blacklist
    ON customer_statuses (is_blacklist_state) WHERE is_blacklist_state;
UPDATE customer_statuses SET is_blacklist_state = TRUE WHERE code = 'blacklisted';

CREATE TABLE customer_blacklist_entries (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id      BIGINT       NOT NULL,
    reason_id        BIGINT       NOT NULL,
    note             VARCHAR(500),
    created_by       BIGINT,
    created_by_email VARCHAR(255),
    lifted_at        TIMESTAMPTZ,
    lifted_by        BIGINT,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_customer_blacklist_entries PRIMARY KEY (id),
    CONSTRAINT fk_cbe_customer FOREIGN KEY (customer_id)
        REFERENCES customers (id) ON DELETE CASCADE,
    CONSTRAINT fk_cbe_reason FOREIGN KEY (reason_id) REFERENCES crm_blacklist_reasons (id)
);
CREATE INDEX idx_cbe_customer ON customer_blacklist_entries (customer_id);

-- Segments: stored customer filters (marketing lists / saved searches / report
-- inputs). The filter JSON mirrors the listing filter shape.
CREATE TABLE crm_segments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    filter      JSONB        NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_crm_segments PRIMARY KEY (id),
    CONSTRAINT uq_crm_segments_name UNIQUE (name)
);

INSERT INTO crm_segments (name, description, filter) VALUES
    ('Recent buyers (30 days)',  'Customers with a purchase event in the last 30 days',
     '{"eventType": "PURCHASE", "eventSinceDays": 30}'),
    ('Inactive (6 months)',      'No timeline activity for 180 days',
     '{"noEventSinceDays": 180}'),
    ('Repair customers',         'Customers with at least one repair request',
     '{"eventType": "REPAIR_REQUEST"}'),
    ('Installment customers',    'Customers with at least one installment purchase',
     '{"eventType": "INSTALLMENT"}');

-- Dedicated management permissions (spec: Manage Tags, Manage Status/config).
INSERT INTO permissions (module_id, action, code, name, is_system)
SELECT m.id, a.action, m.code || ':' || a.action, m.name || ' — ' || a.label, TRUE
FROM modules m
CROSS JOIN (VALUES
    ('manage-tags',   'Manage tags'),
    ('manage-config', 'Manage statuses, types, sources and rules')
) AS a(action, label)
WHERE m.code = 'customers';
