-- Preserve exact stockable identity through the existing purchase-to-sale flow.
-- All columns are nullable for Product-only and historical compatibility.

ALTER TABLE sales_order_lines ADD COLUMN serial_number VARCHAR(128);
ALTER TABLE sales_order_lines ADD COLUMN imei VARCHAR(64);

ALTER TABLE purchase_order_lines ADD COLUMN variant_id BIGINT;
ALTER TABLE purchase_order_lines
    ADD CONSTRAINT fk_purchase_order_line_variant_tenant
    FOREIGN KEY (tenant_id, variant_id) REFERENCES product_variants(tenant_id, id)
    ON DELETE RESTRICT;
CREATE INDEX ix_purchase_order_lines_variant
    ON purchase_order_lines(tenant_id, product_id, variant_id);

ALTER TABLE goods_receipt_lines ADD COLUMN variant_id BIGINT;
ALTER TABLE goods_receipt_lines
    ADD CONSTRAINT fk_goods_receipt_line_variant_tenant
    FOREIGN KEY (tenant_id, variant_id) REFERENCES product_variants(tenant_id, id)
    ON DELETE RESTRICT;
CREATE INDEX ix_goods_receipt_lines_variant
    ON goods_receipt_lines(tenant_id, product_id, variant_id);

CREATE TABLE goods_receipt_unit_identifiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    goods_receipt_line_id BIGINT NOT NULL REFERENCES goods_receipt_lines(id) ON DELETE CASCADE,
    serial_number VARCHAR(128),
    imei VARCHAR(64),
    hamta_activation_code VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_goods_receipt_unit_identifier_identity
        CHECK (serial_number IS NOT NULL OR imei IS NOT NULL),
    CONSTRAINT uq_goods_receipt_unit_identifier_serial
        UNIQUE (tenant_id, serial_number),
    CONSTRAINT uq_goods_receipt_unit_identifier_imei
        UNIQUE (tenant_id, imei)
);
CREATE INDEX ix_goods_receipt_unit_identifiers_line
    ON goods_receipt_unit_identifiers(tenant_id, goods_receipt_line_id);

ALTER TABLE sales_delivery_lines ADD COLUMN variant_id BIGINT;
ALTER TABLE sales_delivery_lines ADD COLUMN serial_number VARCHAR(128);
ALTER TABLE sales_delivery_lines ADD COLUMN imei VARCHAR(64);
ALTER TABLE sales_delivery_lines
    ADD CONSTRAINT fk_sales_delivery_line_variant_tenant
    FOREIGN KEY (tenant_id, variant_id) REFERENCES product_variants(tenant_id, id)
    ON DELETE RESTRICT;
CREATE INDEX ix_sales_delivery_lines_variant
    ON sales_delivery_lines(tenant_id, product_id, variant_id);

ALTER TABLE sales_invoice_lines ADD COLUMN variant_id BIGINT;
ALTER TABLE sales_invoice_lines
    ADD CONSTRAINT fk_sales_invoice_line_variant_tenant
    FOREIGN KEY (tenant_id, variant_id) REFERENCES product_variants(tenant_id, id)
    ON DELETE RESTRICT;
CREATE INDEX ix_sales_invoice_lines_variant
    ON sales_invoice_lines(tenant_id, product_id, variant_id);
