-- Supplier Management: configurable types/statuses/categories/tags/payment
-- terms/rating criteria/document types/duplicate rules, supplier registry with
-- channels, addresses, contact persons, bank accounts, ratings, documents and
-- an append-only log. Also repoints purchasing at this registry.

CREATE TABLE sup_types (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    description   VARCHAR(255),
    is_default    BOOLEAN      NOT NULL DEFAULT FALSE,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_sup_types PRIMARY KEY (id),
    CONSTRAINT uq_sup_types_code UNIQUE (code)
);
CREATE UNIQUE INDEX uq_sup_types_default ON sup_types (is_default) WHERE is_default;

INSERT INTO sup_types (code, name, is_default, is_system, display_order) VALUES
    ('distributor',      'Distributor',          TRUE,  TRUE,  10),
    ('mobile-supplier',   'Mobile Supplier',      FALSE, FALSE, 20),
    ('accessory-supplier','Accessory Supplier',   FALSE, FALSE, 30),
    ('sim-supplier',      'SIM Card Supplier',    FALSE, FALSE, 40),
    ('repair-parts',      'Repair Parts Supplier',FALSE, FALSE, 50),
    ('service-provider',  'Service Provider',     FALSE, FALSE, 60),
    ('importer',          'Importer',             FALSE, FALSE, 70),
    ('manufacturer',      'Manufacturer',         FALSE, FALSE, 80),
    ('wholesaler',        'Wholesaler',           FALSE, FALSE, 90);

CREATE TABLE sup_statuses (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code               VARCHAR(64)  NOT NULL,
    name               VARCHAR(100) NOT NULL,
    description        VARCHAR(255),
    is_blocking        BOOLEAN      NOT NULL DEFAULT FALSE,
    hidden_by_default  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_default         BOOLEAN      NOT NULL DEFAULT FALSE,
    is_archived_state  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_deleted_state   BOOLEAN      NOT NULL DEFAULT FALSE,
    is_blacklist_state BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system          BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order      INTEGER      NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version            BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_sup_statuses PRIMARY KEY (id),
    CONSTRAINT uq_sup_statuses_code UNIQUE (code)
);
CREATE UNIQUE INDEX uq_sup_statuses_default   ON sup_statuses (is_default)         WHERE is_default;
CREATE UNIQUE INDEX uq_sup_statuses_archived  ON sup_statuses (is_archived_state)  WHERE is_archived_state;
CREATE UNIQUE INDEX uq_sup_statuses_deleted   ON sup_statuses (is_deleted_state)   WHERE is_deleted_state;
CREATE UNIQUE INDEX uq_sup_statuses_blacklist ON sup_statuses (is_blacklist_state) WHERE is_blacklist_state;

INSERT INTO sup_statuses
    (code, name, is_blocking, hidden_by_default, is_default, is_archived_state, is_deleted_state, is_blacklist_state, is_system, display_order) VALUES
    ('active',      'Active',      FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, TRUE, 10),
    ('inactive',    'Inactive',    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 20),
    ('suspended',   'Suspended',   TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 30),
    ('blacklisted', 'Blacklisted', TRUE,  FALSE, FALSE, FALSE, FALSE, TRUE,  TRUE, 40),
    ('archived',    'Archived',    FALSE, TRUE,  FALSE, TRUE,  FALSE, FALSE, TRUE, 50),
    ('deleted',     'Deleted',     TRUE,  TRUE,  FALSE, FALSE, TRUE,  FALSE, TRUE, 60);

CREATE TABLE sup_categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_sup_categories PRIMARY KEY (id),
    CONSTRAINT uq_sup_categories_name UNIQUE (name)
);

INSERT INTO sup_categories (name) VALUES
    ('Apple Distributor'), ('Samsung Distributor'), ('Accessory Supplier'),
    ('Repair Supplier'), ('SIM Provider');

CREATE TABLE sup_tags (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(80) NOT NULL,
    color      VARCHAR(32),
    active     BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version    BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT pk_sup_tags PRIMARY KEY (id),
    CONSTRAINT uq_sup_tags_name UNIQUE (name)
);

INSERT INTO sup_tags (name, color) VALUES
    ('Preferred Supplier', 'green'), ('Fast Delivery', 'teal'), ('VIP', 'amber'),
    ('Exclusive', 'purple'), ('Local', 'blue'), ('International', 'indigo'),
    ('High Risk', 'red');

-- Payment terms as data: days for net terms, NULL for cash/installment styles.
CREATE TABLE sup_payment_terms (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    days          INTEGER,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_sup_payment_terms PRIMARY KEY (id),
    CONSTRAINT uq_sup_payment_terms_code UNIQUE (code)
);

INSERT INTO sup_payment_terms (code, name, days, is_system, display_order) VALUES
    ('cash',        'Cash',        0,    TRUE,  10),
    ('net-7',       '7 Days',      7,    FALSE, 20),
    ('net-15',      '15 Days',     15,   FALSE, 30),
    ('net-30',      '30 Days',     30,   FALSE, 40),
    ('net-60',      '60 Days',     60,   FALSE, 50),
    ('installment', 'Installment', NULL, FALSE, 60);

-- Rating criteria with configurable weights: the overall rating is the
-- weight-averaged score — the calculation rule is data.
CREATE TABLE sup_rating_criteria (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)   NOT NULL,
    name          VARCHAR(100)  NOT NULL,
    weight        NUMERIC(6,2)  NOT NULL DEFAULT 1,
    active        BOOLEAN       NOT NULL DEFAULT TRUE,
    is_system     BOOLEAN       NOT NULL DEFAULT FALSE,
    display_order INTEGER       NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version       BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT pk_sup_rating_criteria PRIMARY KEY (id),
    CONSTRAINT uq_sup_rating_criteria_code UNIQUE (code),
    CONSTRAINT ck_sup_rating_weight_positive CHECK (weight > 0)
);

INSERT INTO sup_rating_criteria (code, name, is_system, display_order) VALUES
    ('price',         'Price',           TRUE, 10),
    ('delivery',      'Delivery Speed',  TRUE, 20),
    ('quality',       'Product Quality', TRUE, 30),
    ('support',       'Support',         TRUE, 40),
    ('warranty',      'Warranty',        TRUE, 50),
    ('communication', 'Communication',   TRUE, 60),
    ('availability',  'Availability',    TRUE, 70);

CREATE TABLE sup_document_types (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_sup_document_types PRIMARY KEY (id),
    CONSTRAINT uq_sup_document_types_code UNIQUE (code)
);

INSERT INTO sup_document_types (code, name, display_order) VALUES
    ('contract', 'Contract', 10), ('business-license', 'Business License', 20),
    ('tax-certificate', 'Tax Certificate', 30), ('price-list', 'Price List', 40),
    ('invoice', 'Invoice', 50), ('certificate', 'Certificate', 60), ('other', 'Other', 70);

-- Which identifiers must be unique across suppliers ("when configured").
CREATE TABLE sup_duplicate_rules (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    identifier VARCHAR(32) NOT NULL,  -- TAX_NUMBER | NATIONAL_ID | ECONOMIC_CODE | REGISTRATION_NUMBER
    enabled    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version    BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT pk_sup_duplicate_rules PRIMARY KEY (id),
    CONSTRAINT uq_sup_duplicate_rules_identifier UNIQUE (identifier)
);

INSERT INTO sup_duplicate_rules (identifier, enabled) VALUES
    ('TAX_NUMBER', TRUE), ('NATIONAL_ID', TRUE),
    ('ECONOMIC_CODE', FALSE), ('REGISTRATION_NUMBER', FALSE);

CREATE SEQUENCE sup_code_seq START WITH 1001;

CREATE TABLE suppliers (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    supplier_code       VARCHAR(32)   NOT NULL,
    company_name        VARCHAR(160)  NOT NULL,
    display_name        VARCHAR(160)  NOT NULL,
    legal_name          VARCHAR(160),
    national_id         VARCHAR(32),
    economic_code       VARCHAR(32),
    tax_number          VARCHAR(64),
    registration_number VARCHAR(64),
    owner_name          VARCHAR(120),
    website             VARCHAR(255),
    country             VARCHAR(100),
    province            VARCHAR(100),
    city                VARCHAR(100),
    postal_code         VARCHAR(20),
    description         VARCHAR(2000),
    type_id             BIGINT        NOT NULL,
    status_id           BIGINT        NOT NULL,
    payment_term_id     BIGINT,
    credit_limit        NUMERIC(14,2),
    rating_avg          NUMERIC(4,2),
    source_customer_id  BIGINT,       -- provenance for records migrated from CRM
    archived_at         TIMESTAMPTZ,
    archived_by         BIGINT,
    deleted_at          TIMESTAMPTZ,
    deleted_by          BIGINT,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version             BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT pk_suppliers PRIMARY KEY (id),
    CONSTRAINT uq_suppliers_code UNIQUE (supplier_code),
    CONSTRAINT fk_suppliers_type   FOREIGN KEY (type_id)   REFERENCES sup_types (id),
    CONSTRAINT fk_suppliers_status FOREIGN KEY (status_id) REFERENCES sup_statuses (id),
    CONSTRAINT fk_suppliers_payment_term FOREIGN KEY (payment_term_id)
        REFERENCES sup_payment_terms (id)
);
CREATE INDEX idx_suppliers_status ON suppliers (status_id);
CREATE INDEX idx_suppliers_type   ON suppliers (type_id);
CREATE INDEX idx_suppliers_name   ON suppliers (lower(company_name));
CREATE INDEX idx_suppliers_city   ON suppliers (lower(city));
CREATE INDEX idx_suppliers_tax    ON suppliers (tax_number);
CREATE INDEX idx_suppliers_rating ON suppliers (rating_avg);

-- Supplier-level phones and emails.
CREATE TABLE sup_channels (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    supplier_id BIGINT       NOT NULL,
    kind        VARCHAR(16)  NOT NULL,   -- PHONE | EMAIL
    value       VARCHAR(255) NOT NULL,
    label       VARCHAR(60),
    is_default  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_sup_channels PRIMARY KEY (id),
    CONSTRAINT fk_sup_channels_supplier FOREIGN KEY (supplier_id)
        REFERENCES suppliers (id) ON DELETE CASCADE,
    CONSTRAINT ck_sup_channels_kind CHECK (kind IN ('PHONE', 'EMAIL'))
);
CREATE INDEX idx_sup_channels_supplier ON sup_channels (supplier_id);
CREATE INDEX idx_sup_channels_value    ON sup_channels (lower(value));
CREATE UNIQUE INDEX uq_sup_channels_default
    ON sup_channels (supplier_id, kind) WHERE is_default;

CREATE TABLE sup_addresses (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    supplier_id BIGINT       NOT NULL,
    label       VARCHAR(60),
    line        VARCHAR(300) NOT NULL,
    city        VARCHAR(100),
    province    VARCHAR(100),
    postal_code VARCHAR(20),
    is_default  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_sup_addresses PRIMARY KEY (id),
    CONSTRAINT fk_sup_addresses_supplier FOREIGN KEY (supplier_id)
        REFERENCES suppliers (id) ON DELETE CASCADE
);
CREATE INDEX idx_sup_addresses_supplier ON sup_addresses (supplier_id);
CREATE UNIQUE INDEX uq_sup_addresses_default
    ON sup_addresses (supplier_id) WHERE is_default;

-- Contact persons; at most one primary per supplier.
CREATE TABLE sup_contacts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    supplier_id       BIGINT       NOT NULL,
    full_name         VARCHAR(120) NOT NULL,
    position          VARCHAR(100),
    department        VARCHAR(100),
    phone             VARCHAR(32),
    mobile            VARCHAR(32),
    email             VARCHAR(255),
    preferred_method  VARCHAR(32),
    notes             VARCHAR(500),
    is_primary        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_sup_contacts PRIMARY KEY (id),
    CONSTRAINT fk_sup_contacts_supplier FOREIGN KEY (supplier_id)
        REFERENCES suppliers (id) ON DELETE CASCADE
);
CREATE INDEX idx_sup_contacts_supplier ON sup_contacts (supplier_id);
CREATE INDEX idx_sup_contacts_name     ON sup_contacts (lower(full_name));
CREATE UNIQUE INDEX uq_sup_contacts_primary
    ON sup_contacts (supplier_id) WHERE is_primary;

-- Bank accounts; extra JSONB keeps future banking fields schema-free.
CREATE TABLE sup_bank_accounts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    supplier_id    BIGINT       NOT NULL,
    bank_name      VARCHAR(100) NOT NULL,
    account_number VARCHAR(64),
    iban           VARCHAR(34),
    card_number    VARCHAR(20),
    account_holder VARCHAR(120),
    is_default     BOOLEAN      NOT NULL DEFAULT FALSE,
    extra          JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_sup_bank_accounts PRIMARY KEY (id),
    CONSTRAINT fk_sup_bank_accounts_supplier FOREIGN KEY (supplier_id)
        REFERENCES suppliers (id) ON DELETE CASCADE
);
CREATE INDEX idx_sup_bank_accounts_supplier ON sup_bank_accounts (supplier_id);
CREATE UNIQUE INDEX uq_sup_bank_accounts_default
    ON sup_bank_accounts (supplier_id) WHERE is_default;

CREATE TABLE sup_tag_links (
    supplier_id BIGINT NOT NULL,
    tag_id      BIGINT NOT NULL,
    CONSTRAINT pk_sup_tag_links PRIMARY KEY (supplier_id, tag_id),
    CONSTRAINT fk_stl_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id) ON DELETE CASCADE,
    CONSTRAINT fk_stl_tag      FOREIGN KEY (tag_id)      REFERENCES sup_tags (id) ON DELETE CASCADE
);

CREATE TABLE sup_category_links (
    supplier_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    CONSTRAINT pk_sup_category_links PRIMARY KEY (supplier_id, category_id),
    CONSTRAINT fk_scl_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id) ON DELETE CASCADE,
    CONSTRAINT fk_scl_category FOREIGN KEY (category_id) REFERENCES sup_categories (id) ON DELETE CASCADE
);

-- Current score per (supplier, criterion); overall average cached on suppliers.
CREATE TABLE sup_ratings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    supplier_id BIGINT       NOT NULL,
    criteria_id BIGINT       NOT NULL,
    score       NUMERIC(3,1) NOT NULL,
    note        VARCHAR(255),
    rated_by    BIGINT,
    rated_by_email VARCHAR(255),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_sup_ratings PRIMARY KEY (id),
    CONSTRAINT fk_sup_ratings_supplier FOREIGN KEY (supplier_id)
        REFERENCES suppliers (id) ON DELETE CASCADE,
    CONSTRAINT fk_sup_ratings_criteria FOREIGN KEY (criteria_id)
        REFERENCES sup_rating_criteria (id) ON DELETE CASCADE,
    CONSTRAINT uq_sup_ratings UNIQUE (supplier_id, criteria_id),
    CONSTRAINT ck_sup_ratings_score CHECK (score >= 0 AND score <= 5)
);

CREATE TABLE sup_documents (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    supplier_id       BIGINT       NOT NULL,
    doc_type_id       BIGINT,
    file_key          VARCHAR(255) NOT NULL,
    file_name         VARCHAR(255) NOT NULL,
    content_type      VARCHAR(128),
    file_size         BIGINT       NOT NULL,
    uploaded_by       BIGINT,
    uploaded_by_email VARCHAR(255),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_sup_documents PRIMARY KEY (id),
    CONSTRAINT fk_sup_documents_supplier FOREIGN KEY (supplier_id)
        REFERENCES suppliers (id) ON DELETE CASCADE,
    CONSTRAINT fk_sup_documents_type FOREIGN KEY (doc_type_id)
        REFERENCES sup_document_types (id)
);
CREATE INDEX idx_sup_documents_supplier ON sup_documents (supplier_id);

CREATE TABLE sup_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    supplier_id BIGINT       NOT NULL,
    action      VARCHAR(64)  NOT NULL,
    title       VARCHAR(255) NOT NULL,
    detail      JSONB,
    actor_id    BIGINT,
    actor_email VARCHAR(255),
    occurred_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_sup_logs PRIMARY KEY (id),
    CONSTRAINT fk_sup_logs_supplier FOREIGN KEY (supplier_id)
        REFERENCES suppliers (id) ON DELETE CASCADE
);
CREATE INDEX idx_sup_logs_supplier ON sup_logs (supplier_id, occurred_at DESC);

-- ---------------------------------------------------------------------------
-- Purchasing now references the supplier registry. Any CRM records already
-- used as purchase suppliers become supplier rows (provenance kept), then the
-- foreign key is repointed.
INSERT INTO suppliers (supplier_code, company_name, display_name, national_id, tax_number,
                       type_id, status_id, source_customer_id)
SELECT 'SUP-' || lpad(nextval('sup_code_seq')::text, 6, '0'),
       COALESCE(c.company_name, c.display_name),
       c.display_name,
       c.national_code,
       c.tax_number,
       (SELECT id FROM sup_types WHERE is_default),
       (SELECT id FROM sup_statuses WHERE is_default),
       c.id
FROM customers c
WHERE c.id IN (SELECT DISTINCT supplier_id FROM purchases);

ALTER TABLE purchases DROP CONSTRAINT fk_purchases_supplier;
UPDATE purchases p SET supplier_id = s.id
FROM suppliers s WHERE s.source_customer_id = p.supplier_id;
ALTER TABLE purchases ADD CONSTRAINT fk_purchases_supplier
    FOREIGN KEY (supplier_id) REFERENCES suppliers (id);

-- Module + permissions.
INSERT INTO modules (code, name, description, icon, path, display_order, enabled, is_system)
VALUES ('suppliers', 'Suppliers', 'Supplier registry, contacts, banking and evaluation',
        'mdi-truck-delivery', '/suppliers', 66, TRUE, FALSE);

INSERT INTO permissions (module_id, action, code, name, is_system)
SELECT m.id, a.action, m.code || ':' || a.action, m.name || ' — ' || a.label, TRUE
FROM modules m
CROSS JOIN (VALUES
    ('view',    'View'),
    ('create',  'Create'),
    ('edit',    'Edit'),
    ('delete',  'Delete'),
    ('export',  'Export'),
    ('import',  'Import'),
    ('archive', 'Archive'),
    ('restore', 'Restore'),
    ('purge',   'Permanent delete'),
    ('rate',    'Rate'),
    ('manage-config', 'Manage supplier configuration')
) AS a(action, label)
WHERE m.code = 'suppliers';
