package com.sami.app.sales.dto;
import com.sami.app.sales.domain.*; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.math.BigDecimal; import java.time.Instant; import java.util.*;
public final class SalesDtos { private SalesDtos(){}
 public record ItemRequest(@NotNull Long productId,@NotNull @DecimalMin("0.001") BigDecimal quantity,@NotNull @DecimalMin("0") BigDecimal unitPrice,@DecimalMin("0") BigDecimal costPrice,@DecimalMin("0") BigDecimal discount,@DecimalMin("0") BigDecimal tax,@Size(max=128) String serialNumber,@Size(max=32) String imei){}
 public record ServiceRequest(@NotBlank @Size(max=48) String serviceType,@Size(max=255) String description,@NotNull @DecimalMin("0") BigDecimal price,@DecimalMin("0") BigDecimal cost,Long employeeId){}
 public record SaleRequest(@NotNull Long companyId,@NotNull Long branchId,@NotNull Long customerId,@NotBlank @Size(max=32) String saleType,@Size(min=3,max=3) String currency,@Size(max=2000) String notes,@NotEmpty @Valid List<ItemRequest> items,@Valid List<ServiceRequest> services,Long expectedVersion,@Size(max=100) String idempotencyKey){}
 public record PaymentRequest(@NotBlank String method,@NotNull @DecimalMin(value="0.01") BigDecimal amount,@Size(max=160) String referenceNo,@Size(max=255) String providerReference){}
 public record DiscountRequest(@NotBlank String type,@NotNull @DecimalMin("0") BigDecimal amount,@NotBlank @Size(max=500) String reason){}
 public record DecisionRequest(boolean approved,@Size(max=500) String note){}
 public record CancelRequest(@NotBlank @Size(max=500) String reason){}
 public record ReturnLine(@NotNull Long saleItemId,@NotNull @DecimalMin("0.001") BigDecimal quantity){}
 public record ReturnRequest(@NotBlank @Size(max=500) String reason,@NotBlank String refundMethod,@NotEmpty @Valid List<ReturnLine> items){}
 public record ItemResponse(Long id,Long productId,String sku,String name,String serialNumber,String imei,BigDecimal quantity,BigDecimal returnedQuantity,BigDecimal unitPrice,BigDecimal costPrice,BigDecimal discount,BigDecimal tax,BigDecimal lineTotal,BigDecimal profit){ static ItemResponse from(SaleItem i){return new ItemResponse(i.getId(),i.getProductId(),i.getProductSku(),i.getProductName(),i.getSerialNumber(),i.getImei(),i.getQuantity(),i.getReturnedQuantity(),i.getUnitPrice(),i.getCostPrice(),i.getDiscount(),i.getTax(),i.getLineTotal(),i.getProfit());}}
 public record PaymentResponse(Long id,String method,String status,BigDecimal amount,BigDecimal reversedAmount,String referenceNo,Instant paidAt){ static PaymentResponse from(SalePayment p){return new PaymentResponse(p.getId(),p.getMethod(),p.getStatus(),p.getAmount(),p.getReversedAmount(),p.getReferenceNo(),p.getPaidAt());}}
 public record ServiceResponse(Long id,String serviceType,String description,BigDecimal price,BigDecimal cost,Long employeeId){static ServiceResponse from(SaleServiceLine s){return new ServiceResponse(s.getId(),s.getServiceType(),s.getDescription(),s.getPrice(),s.getCost(),s.getEmployeeId());}}
 public record SaleResponse(Long id,String invoiceNumber,Long companyId,Long branchId,Long customerId,Long sellerId,String saleType,String status,String currency,BigDecimal subtotal,BigDecimal discountTotal,BigDecimal taxTotal,BigDecimal costTotal,BigDecimal finalAmount,BigDecimal profit,BigDecimal commissionAmount,String notes,List<ItemResponse> items,List<ServiceResponse> services,List<PaymentResponse> payments,Instant createdAt,Instant confirmedAt,Instant completedAt,Instant cancelledAt,Long version){ public static SaleResponse from(Sale s){return new SaleResponse(s.getId(),s.getInvoiceNumber(),s.getCompanyId(),s.getBranchId(),s.getCustomerId(),s.getSellerId(),s.getSaleType(),s.getStatus().name(),s.getCurrency(),s.getSubtotal(),s.getDiscountTotal(),s.getTaxTotal(),s.getCostTotal(),s.getFinalAmount(),s.getProfit(),s.getCommissionAmount(),s.getNotes(),s.getItems().stream().map(ItemResponse::from).toList(),s.getServices().stream().map(ServiceResponse::from).toList(),s.getPayments().stream().map(PaymentResponse::from).toList(),s.getCreatedAt(),s.getConfirmedAt(),s.getCompletedAt(),s.getCancelledAt(),s.getVersion());}}
 public record AuditResponse(Long id,String action,Long actorId,String actorEmail,Map<String,Object> oldValue,Map<String,Object> newValue,Instant occurredAt){ public static AuditResponse from(SaleAuditHistory a){return new AuditResponse(a.getId(),a.getAction(),a.getActorId(),a.getActorEmail(),a.getOldValue(),a.getNewValue(),a.getOccurredAt());}}
 public record DashboardResponse(long drafts,long confirmed,long completed,long cancelled,BigDecimal revenue,BigDecimal profit){}
}
