-- Dashboard, KPI & Executive Cockpit — a generic, configuration-driven
-- visualization engine. Business data arrives through ReportingProvider beans
-- (SPI); this module contains no per-domain dashboard logic. Widget types,
-- chart types, data sources, refresh policies, statuses and visibilities are all
-- configurable rows, so new kinds never require code changes.

-- Dashboard lifecycle statuses (Draft/Active/Inactive/Archived seeded).
CREATE TABLE dash_statuses (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code              VARCHAR(64)  NOT NULL,
    name              VARCHAR(100) NOT NULL,
    is_default        BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active_state   BOOLEAN      NOT NULL DEFAULT FALSE,
    is_archived_state BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system         BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order     INTEGER      NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_dash_statuses PRIMARY KEY (id),
    CONSTRAINT uq_dash_statuses_code UNIQUE (code)
);
CREATE UNIQUE INDEX uq_dash_statuses_default  ON dash_statuses (is_default)        WHERE is_default;
CREATE UNIQUE INDEX uq_dash_statuses_archived ON dash_statuses (is_archived_state) WHERE is_archived_state;

INSERT INTO dash_statuses (code, name, is_default, is_active_state, is_archived_state, is_system, display_order) VALUES
    ('draft',    'Draft',    TRUE,  FALSE, FALSE, TRUE, 10),
    ('active',   'Active',   FALSE, TRUE,  FALSE, TRUE, 20),
    ('inactive', 'Inactive', FALSE, FALSE, FALSE, TRUE, 30),
    ('archived', 'Archived', FALSE, FALSE, TRUE,  TRUE, 40);

-- Dashboard visibilities (Private/Shared/Role/Executive/Department/Public).
CREATE TABLE dash_visibilities (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    is_default    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_dash_visibilities PRIMARY KEY (id),
    CONSTRAINT uq_dash_visibilities_code UNIQUE (code)
);
CREATE UNIQUE INDEX uq_dash_visibilities_default ON dash_visibilities (is_default) WHERE is_default;

INSERT INTO dash_visibilities (code, name, is_default, is_system, display_order) VALUES
    ('private',    'Private',    TRUE,  TRUE, 10),
    ('shared',     'Shared',     FALSE, TRUE, 20),
    ('role',       'Role',       FALSE, TRUE, 30),
    ('department', 'Department', FALSE, TRUE, 40),
    ('executive',  'Executive',  FALSE, TRUE, 50),
    ('public',     'Public',     FALSE, TRUE, 60);

-- KPI lifecycle statuses (Draft/Active/Inactive/Deprecated/Archived).
CREATE TABLE dash_kpi_statuses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code            VARCHAR(64)  NOT NULL,
    name            VARCHAR(100) NOT NULL,
    is_default      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active_state BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system       BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order   INTEGER      NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_dash_kpi_statuses PRIMARY KEY (id),
    CONSTRAINT uq_dash_kpi_statuses_code UNIQUE (code)
);
CREATE UNIQUE INDEX uq_dash_kpi_statuses_default ON dash_kpi_statuses (is_default) WHERE is_default;

INSERT INTO dash_kpi_statuses (code, name, is_default, is_active_state, is_system, display_order) VALUES
    ('draft',      'Draft',      TRUE,  FALSE, TRUE, 10),
    ('active',     'Active',     FALSE, TRUE,  TRUE, 20),
    ('inactive',   'Inactive',   FALSE, FALSE, TRUE, 30),
    ('deprecated', 'Deprecated', FALSE, FALSE, TRUE, 40),
    ('archived',   'Archived',   FALSE, FALSE, TRUE, 50);

-- Configurable widget types. is_system rows ship with the module; new types are
-- plain rows (chart_capable flags a type that renders a chart).
CREATE TABLE dash_widget_types (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    icon          VARCHAR(64),
    chart_capable BOOLEAN      NOT NULL DEFAULT FALSE,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_dash_widget_types PRIMARY KEY (id),
    CONSTRAINT uq_dash_widget_types_code UNIQUE (code)
);

INSERT INTO dash_widget_types (code, name, icon, chart_capable, is_system, display_order) VALUES
    ('kpi-card',           'KPI Card',           'mdi-card-text',        FALSE, TRUE, 10),
    ('chart',              'Chart',              'mdi-chart-line',       TRUE,  TRUE, 20),
    ('gauge',              'Gauge',              'mdi-gauge',            FALSE, TRUE, 30),
    ('progress',           'Progress Bar',       'mdi-progress-check',   FALSE, TRUE, 40),
    ('table',              'Table',              'mdi-table',            FALSE, TRUE, 50),
    ('pivot',              'Pivot Grid',         'mdi-table-pivot',      FALSE, TRUE, 60),
    ('leaderboard',        'Leaderboard',        'mdi-trophy',           FALSE, TRUE, 70),
    ('calendar',           'Calendar',           'mdi-calendar',         FALSE, TRUE, 80),
    ('map',                'Map',                'mdi-map',              FALSE, TRUE, 90),
    ('timeline',           'Timeline',           'mdi-timeline',         FALSE, TRUE, 100),
    ('notification-panel', 'Notification Panel', 'mdi-bell',             FALSE, TRUE, 110),
    ('activity-feed',      'Activity Feed',      'mdi-rss',              FALSE, TRUE, 120),
    ('heatmap',            'Heat Map',           'mdi-grid',             FALSE, TRUE, 130);

-- Configurable chart types.
CREATE TABLE dash_chart_types (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_dash_chart_types PRIMARY KEY (id),
    CONSTRAINT uq_dash_chart_types_code UNIQUE (code)
);

INSERT INTO dash_chart_types (code, name, is_system, display_order) VALUES
    ('line', 'Line Chart', TRUE, 10),           ('bar', 'Bar Chart', TRUE, 20),
    ('stacked-bar', 'Stacked Bar', TRUE, 30),   ('area', 'Area Chart', TRUE, 40),
    ('pie', 'Pie Chart', TRUE, 50),             ('donut', 'Donut Chart', TRUE, 60),
    ('radar', 'Radar', TRUE, 70),               ('scatter', 'Scatter', TRUE, 80),
    ('bubble', 'Bubble', TRUE, 90),             ('histogram', 'Histogram', TRUE, 100),
    ('treemap', 'Treemap', TRUE, 110),          ('waterfall', 'Waterfall', TRUE, 120);

-- Configurable data sources. provider_key resolves to a ReportingProvider bean;
-- rows whose provider is not yet registered are simply unavailable at runtime
-- (surfaced as a clear error), so future modules light up by registering a bean.
CREATE TABLE dash_data_sources (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    provider_key  VARCHAR(64)  NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_dash_data_sources PRIMARY KEY (id),
    CONSTRAINT uq_dash_data_sources_code UNIQUE (code)
);

INSERT INTO dash_data_sources (code, name, provider_key, is_system, display_order) VALUES
    ('manual',      'Manual / Static', 'manual', TRUE, 10),
    ('system',      'System Metrics',  'system', TRUE, 20),
    ('sales',       'Sales',           'sales',       FALSE, 30),
    ('inventory',   'Inventory',       'inventory',   FALSE, 40),
    ('accounting',  'Accounting',      'accounting',  FALSE, 50),
    ('treasury',    'Treasury',        'treasury',    FALSE, 60),
    ('repair',      'Repair',          'repair',      FALSE, 70),
    ('crm',         'CRM',             'crm',         FALSE, 80),
    ('installment', 'Installment',     'installment', FALSE, 90),
    ('hr',          'HR',              'hr',          FALSE, 100),
    ('marketing',   'Marketing',       'marketing',   FALSE, 110),
    ('workflow',    'Workflow',        'workflow',    FALSE, 120),
    ('custom-query','Custom Query',    'custom-query',FALSE, 130);

-- Configurable refresh policies. interval_seconds: 0 = manual only; small values
-- approximate real-time (the frontend polls at this cadence).
CREATE TABLE dash_refresh_policies (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code             VARCHAR(64)  NOT NULL,
    name             VARCHAR(100) NOT NULL,
    interval_seconds INTEGER      NOT NULL DEFAULT 0,
    is_default       BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system        BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order    INTEGER      NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_dash_refresh_policies PRIMARY KEY (id),
    CONSTRAINT uq_dash_refresh_policies_code UNIQUE (code)
);
CREATE UNIQUE INDEX uq_dash_refresh_policies_default ON dash_refresh_policies (is_default) WHERE is_default;

INSERT INTO dash_refresh_policies (code, name, interval_seconds, is_default, is_system, display_order) VALUES
    ('real-time', 'Real-Time',       15,    FALSE, TRUE, 10),
    ('minute',    'Every Minute',    60,    FALSE, TRUE, 20),
    ('five-min',  'Every 5 Minutes', 300,   FALSE, TRUE, 30),
    ('hourly',    'Hourly',          3600,  FALSE, TRUE, 40),
    ('daily',     'Daily',           86400, TRUE,  TRUE, 50),
    ('manual',    'Manual',          0,     FALSE, TRUE, 60),
    ('scheduled', 'Scheduled',       0,     FALSE, TRUE, 70);

-- KPI definitions. calculation_method / aggregation are technical strategy
-- selectors (validated against the code enums); formula is provider-specific.
CREATE TABLE kpi_definitions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code               VARCHAR(64)   NOT NULL,
    name               VARCHAR(150)  NOT NULL,
    description        VARCHAR(500),
    calculation_method VARCHAR(32)   NOT NULL DEFAULT 'PROVIDER',
    formula            VARCHAR(1000),
    aggregation        VARCHAR(16)   NOT NULL DEFAULT 'LAST',
    data_source_id     BIGINT,
    refresh_policy_id  BIGINT,
    target_value       NUMERIC(18,4),
    unit               VARCHAR(32),
    status_id          BIGINT        NOT NULL,
    owner_id           BIGINT,
    created_by         BIGINT,
    created_by_email   VARCHAR(255),
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version            BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT pk_kpi_definitions PRIMARY KEY (id),
    CONSTRAINT uq_kpi_definitions_code UNIQUE (code),
    CONSTRAINT fk_kpi_status      FOREIGN KEY (status_id)         REFERENCES dash_kpi_statuses (id),
    CONSTRAINT fk_kpi_datasource  FOREIGN KEY (data_source_id)    REFERENCES dash_data_sources (id),
    CONSTRAINT fk_kpi_refresh     FOREIGN KEY (refresh_policy_id) REFERENCES dash_refresh_policies (id),
    CONSTRAINT fk_kpi_owner       FOREIGN KEY (owner_id)          REFERENCES users (id)
);
CREATE INDEX idx_kpi_status ON kpi_definitions (status_id);

-- Configurable threshold levels per KPI (Excellent/Good/Warning/Critical/...).
CREATE TABLE kpi_thresholds (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    kpi_id     BIGINT        NOT NULL,
    level_name VARCHAR(64)   NOT NULL,
    color      VARCHAR(32),
    min_value  NUMERIC(18,4),
    max_value  NUMERIC(18,4),
    sort_order INTEGER       NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version    BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT pk_kpi_thresholds PRIMARY KEY (id),
    CONSTRAINT fk_kpi_thresholds_kpi FOREIGN KEY (kpi_id) REFERENCES kpi_definitions (id) ON DELETE CASCADE
);
CREATE INDEX idx_kpi_thresholds_kpi ON kpi_thresholds (kpi_id);

-- Historical KPI calculation store (supports trend analysis & recalculation).
CREATE TABLE kpi_values (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    kpi_id          BIGINT        NOT NULL,
    value           NUMERIC(18,4) NOT NULL,
    period_key      VARCHAR(32)   NOT NULL DEFAULT 'ALL',
    threshold_level VARCHAR(64),
    computed_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT pk_kpi_values PRIMARY KEY (id),
    CONSTRAINT fk_kpi_values_kpi FOREIGN KEY (kpi_id) REFERENCES kpi_definitions (id) ON DELETE CASCADE
);
CREATE INDEX idx_kpi_values_kpi ON kpi_values (kpi_id, computed_at DESC);
CREATE UNIQUE INDEX uq_kpi_values_period ON kpi_values (kpi_id, period_key, computed_at);

-- Dashboards. owner_id is null for system/executive dashboards; role_id targets
-- a role-based dashboard; company_id/branch_id are forward-compat (multi-tenant).
CREATE TABLE dashboards (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code             VARCHAR(64)  NOT NULL,
    name             VARCHAR(150) NOT NULL,
    description      VARCHAR(500),
    owner_id         BIGINT,
    role_id          BIGINT,
    status_id        BIGINT       NOT NULL,
    visibility_id    BIGINT       NOT NULL,
    is_default       BOOLEAN      NOT NULL DEFAULT FALSE,
    company_id       BIGINT,
    branch_id        BIGINT,
    created_by       BIGINT,
    created_by_email VARCHAR(255),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_dashboards PRIMARY KEY (id),
    CONSTRAINT uq_dashboards_code UNIQUE (code),
    CONSTRAINT fk_dashboards_status     FOREIGN KEY (status_id)     REFERENCES dash_statuses (id),
    CONSTRAINT fk_dashboards_visibility FOREIGN KEY (visibility_id) REFERENCES dash_visibilities (id),
    CONSTRAINT fk_dashboards_owner      FOREIGN KEY (owner_id)      REFERENCES users (id),
    CONSTRAINT fk_dashboards_role       FOREIGN KEY (role_id)       REFERENCES roles (id)
);
CREATE INDEX idx_dashboards_owner ON dashboards (owner_id);
CREATE INDEX idx_dashboards_role  ON dashboards (role_id);

CREATE TABLE dashboard_widgets (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    dashboard_id        BIGINT       NOT NULL,
    code                VARCHAR(64)  NOT NULL,
    widget_type_id      BIGINT       NOT NULL,
    chart_type_id       BIGINT,
    kpi_id              BIGINT,
    title               VARCHAR(150) NOT NULL,
    description         VARCHAR(500),
    data_source_id      BIGINT,
    refresh_policy_id   BIGINT,
    position_x          INTEGER      NOT NULL DEFAULT 0,
    position_y          INTEGER      NOT NULL DEFAULT 0,
    width               INTEGER      NOT NULL DEFAULT 3,
    height              INTEGER      NOT NULL DEFAULT 2,
    required_permission VARCHAR(100),
    config              JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version             BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_dashboard_widgets PRIMARY KEY (id),
    CONSTRAINT uq_dashboard_widgets_code UNIQUE (dashboard_id, code),
    CONSTRAINT fk_dw_dashboard   FOREIGN KEY (dashboard_id)      REFERENCES dashboards (id) ON DELETE CASCADE,
    CONSTRAINT fk_dw_type        FOREIGN KEY (widget_type_id)    REFERENCES dash_widget_types (id),
    CONSTRAINT fk_dw_chart_type  FOREIGN KEY (chart_type_id)     REFERENCES dash_chart_types (id),
    CONSTRAINT fk_dw_kpi         FOREIGN KEY (kpi_id)            REFERENCES kpi_definitions (id),
    CONSTRAINT fk_dw_datasource  FOREIGN KEY (data_source_id)    REFERENCES dash_data_sources (id),
    CONSTRAINT fk_dw_refresh     FOREIGN KEY (refresh_policy_id) REFERENCES dash_refresh_policies (id),
    CONSTRAINT ck_dw_size CHECK (width > 0 AND height > 0)
);
CREATE INDEX idx_dw_dashboard ON dashboard_widgets (dashboard_id);

-- Sharing: a dashboard can be shared with users or roles, optionally editable.
CREATE TABLE dashboard_shares (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    dashboard_id   BIGINT      NOT NULL,
    target_type    VARCHAR(16) NOT NULL,   -- USER | ROLE
    target_user_id BIGINT,
    target_role_id BIGINT,
    can_edit       BOOLEAN     NOT NULL DEFAULT FALSE,
    created_by     BIGINT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dashboard_shares PRIMARY KEY (id),
    CONSTRAINT fk_ds_dashboard FOREIGN KEY (dashboard_id)   REFERENCES dashboards (id) ON DELETE CASCADE,
    CONSTRAINT fk_ds_user      FOREIGN KEY (target_user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_ds_role      FOREIGN KEY (target_role_id) REFERENCES roles (id) ON DELETE CASCADE,
    CONSTRAINT ck_ds_target CHECK (
        (target_type = 'USER' AND target_user_id IS NOT NULL) OR
        (target_type = 'ROLE' AND target_role_id IS NOT NULL))
);
CREATE INDEX idx_ds_dashboard ON dashboard_shares (dashboard_id);
CREATE INDEX idx_ds_user      ON dashboard_shares (target_user_id);
CREATE INDEX idx_ds_role      ON dashboard_shares (target_role_id);

-- Favorites (personalization).
CREATE TABLE dashboard_favorites (
    user_id      BIGINT      NOT NULL,
    dashboard_id BIGINT      NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dashboard_favorites PRIMARY KEY (user_id, dashboard_id),
    CONSTRAINT fk_df_user      FOREIGN KEY (user_id)      REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_df_dashboard FOREIGN KEY (dashboard_id) REFERENCES dashboards (id) ON DELETE CASCADE
);

-- Saved filters (personalization / filter engine).
CREATE TABLE dashboard_saved_filters (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    owner_id   BIGINT       NOT NULL,
    name       VARCHAR(100) NOT NULL,
    filter     JSONB        NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version    BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_dashboard_saved_filters PRIMARY KEY (id),
    CONSTRAINT fk_dsf_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_dsf_owner ON dashboard_saved_filters (owner_id);

-- Append-only audit trail (no FK to entities: survives deletes).
CREATE TABLE dashboard_audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    entity_type VARCHAR(32)  NOT NULL,   -- DASHBOARD | WIDGET | KPI
    entity_id   BIGINT,
    action      VARCHAR(64)  NOT NULL,
    old_values  JSONB,
    new_values  JSONB,
    actor_id    BIGINT,
    actor_email VARCHAR(255),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_dashboard_audit_log PRIMARY KEY (id)
);
CREATE INDEX idx_dash_audit_entity ON dashboard_audit_log (entity_type, entity_id);

-- Module + granular permissions.
INSERT INTO modules (code, name, description, icon, path, display_order, enabled, is_system)
VALUES ('dashboards', 'Dashboards', 'Dashboards, KPIs and the executive cockpit',
        'mdi-view-dashboard-variant', '/dashboards', 15, TRUE, TRUE);

INSERT INTO permissions (module_id, action, code, name, is_system)
SELECT m.id, a.action, m.code || ':' || a.action, m.name || ' — ' || a.label, TRUE
FROM modules m
CROSS JOIN (VALUES
    ('view',           'View'),
    ('create',         'Create'),
    ('edit',           'Edit'),
    ('delete',         'Delete'),
    ('manage-widgets', 'Manage widgets'),
    ('manage-kpis',    'Manage KPIs'),
    ('share',          'Share'),
    ('export',         'Export reports'),
    ('manage-config',  'Manage dashboard configuration')
) AS a(action, label)
WHERE m.code = 'dashboards';

-- A seeded, self-contained Executive Cockpit so the module is usable out of the
-- box. Widgets use only the built-in `system` and `manual` providers (no
-- coupling to business modules).
INSERT INTO dashboards (code, name, description, status_id, visibility_id, is_default, created_by_email)
SELECT 'executive-cockpit', 'Executive Cockpit',
       'Company-wide overview. Add widgets backed by business reporting providers as modules register them.',
       (SELECT id FROM dash_statuses WHERE code = 'active'),
       (SELECT id FROM dash_visibilities WHERE code = 'executive'),
       TRUE, 'system';

INSERT INTO dashboard_widgets (dashboard_id, code, widget_type_id, title, data_source_id, refresh_policy_id,
                               position_x, position_y, width, height, config)
SELECT d.id, w.code, (SELECT id FROM dash_widget_types WHERE code = w.wtype),
       w.title,
       (SELECT id FROM dash_data_sources WHERE code = w.dsource),
       (SELECT id FROM dash_refresh_policies WHERE code = w.refresh),
       w.px, w.py, w.width, w.height, w.config::jsonb
FROM dashboards d
CROSS JOIN (VALUES
    ('total-dashboards', 'kpi-card', 'Total Dashboards',  'system', 'five-min', 0, 0, 3, 2, '{"metric":"dashboards.count","icon":"mdi-view-dashboard","color":"primary"}'),
    ('total-kpis',       'kpi-card', 'Defined KPIs',      'system', 'five-min', 3, 0, 3, 2, '{"metric":"kpis.count","icon":"mdi-speedometer","color":"info"}'),
    ('total-widgets',    'kpi-card', 'Total Widgets',     'system', 'five-min', 6, 0, 3, 2, '{"metric":"widgets.count","icon":"mdi-widgets","color":"success"}'),
    ('welcome',          'kpi-card', 'Getting Started',   'manual', 'manual',   9, 0, 3, 2, '{"value":0,"label":"Register providers to power live widgets","icon":"mdi-information","color":"secondary"}')
) AS w(code, wtype, title, dsource, refresh, px, py, width, height, config)
WHERE d.code = 'executive-cockpit';
