-- Business Process Automation (RPA & Workflow) — a generic, configuration-driven
-- automation engine for the whole ERP. Rules are data: their trigger, condition
-- tree, execution policy and action steps live in JSONB, and new Trigger/Action
-- providers register as Spring beans (SPI) without touching the engine. Business
-- modules only publish domain events and expose services; this module consumes
-- those events and orchestrates behaviour through configurable rules.

-- Configurable lifecycle statuses (Draft/Testing/Active/Paused/Disabled/Archived).
CREATE TABLE automation_statuses (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code              VARCHAR(64)  NOT NULL,
    name              VARCHAR(100) NOT NULL,
    is_default        BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active_state   BOOLEAN      NOT NULL DEFAULT FALSE,   -- rules in this state execute
    is_archived_state BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system         BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order     INTEGER      NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_automation_statuses PRIMARY KEY (id),
    CONSTRAINT uq_automation_statuses_code UNIQUE (code)
);
CREATE UNIQUE INDEX uq_automation_statuses_default  ON automation_statuses (is_default)        WHERE is_default;
CREATE UNIQUE INDEX uq_automation_statuses_archived ON automation_statuses (is_archived_state) WHERE is_archived_state;

INSERT INTO automation_statuses (code, name, is_default, is_active_state, is_archived_state, is_system, display_order) VALUES
    ('draft',    'Draft',    TRUE,  FALSE, FALSE, TRUE, 10),
    ('testing',  'Testing',  FALSE, FALSE, FALSE, TRUE, 20),
    ('active',   'Active',   FALSE, TRUE,  FALSE, TRUE, 30),
    ('paused',   'Paused',   FALSE, FALSE, FALSE, TRUE, 40),
    ('disabled', 'Disabled', FALSE, FALSE, FALSE, TRUE, 50),
    ('archived', 'Archived', FALSE, FALSE, TRUE,  TRUE, 60);

-- Automation rule: the unit of configuration. trigger_type is a canonical key
-- (e.g. crm.customer.CREATED, or a wildcard crm.customer.*); trigger_config,
-- condition_config and execution_policy are open JSON so new capabilities never
-- require a schema change. company_id/branch_id are forward-compat multi-tenant
-- scoping columns (nullable, no FK yet — mirrors dashboards).
CREATE TABLE automation_rules (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code             VARCHAR(64)  NOT NULL,
    name             VARCHAR(160) NOT NULL,
    description      VARCHAR(2000),
    category         VARCHAR(64),
    priority         INTEGER      NOT NULL DEFAULT 100,
    company_id       BIGINT,
    branch_id        BIGINT,
    status_id        BIGINT       NOT NULL,
    trigger_type     VARCHAR(128) NOT NULL,
    trigger_config   JSONB        NOT NULL DEFAULT '{}'::jsonb,
    condition_config JSONB        NOT NULL DEFAULT '{}'::jsonb,
    execution_policy JSONB        NOT NULL DEFAULT '{}'::jsonb,
    allow_recursion  BOOLEAN      NOT NULL DEFAULT FALSE,
    max_executions   INTEGER,
    execution_count  BIGINT       NOT NULL DEFAULT 0,
    created_by       BIGINT,
    created_by_email VARCHAR(255),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_automation_rules PRIMARY KEY (id),
    CONSTRAINT uq_automation_rules_code UNIQUE (code),
    CONSTRAINT fk_automation_rules_status FOREIGN KEY (status_id) REFERENCES automation_statuses (id)
);
CREATE INDEX idx_automation_rules_trigger ON automation_rules (trigger_type);
CREATE INDEX idx_automation_rules_status  ON automation_rules (status_id);
CREATE INDEX idx_automation_rules_scope   ON automation_rules (company_id, branch_id);

-- Ordered action steps. action_type resolves to an ActionProvider bean; config
-- and step_condition are open JSON. run_mode/continue_on_error/delay/retry drive
-- sequential/parallel/conditional/delayed/retry workflow execution.
CREATE TABLE automation_actions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    rule_id           BIGINT       NOT NULL,
    step_order        INTEGER      NOT NULL DEFAULT 0,
    action_type       VARCHAR(128) NOT NULL,
    name              VARCHAR(160),
    config            JSONB        NOT NULL DEFAULT '{}'::jsonb,
    step_condition    JSONB,
    run_mode          VARCHAR(32)  NOT NULL DEFAULT 'SEQUENTIAL',  -- SEQUENTIAL | PARALLEL
    continue_on_error BOOLEAN      NOT NULL DEFAULT FALSE,
    delay_seconds     INTEGER      NOT NULL DEFAULT 0,
    retry_count       INTEGER      NOT NULL DEFAULT 0,
    timeout_seconds   INTEGER,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_automation_actions PRIMARY KEY (id),
    CONSTRAINT fk_automation_actions_rule FOREIGN KEY (rule_id) REFERENCES automation_rules (id) ON DELETE CASCADE
);
CREATE INDEX idx_automation_actions_rule ON automation_actions (rule_id, step_order);

-- One execution of a rule (append-only history).
CREATE TABLE automation_executions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    execution_number VARCHAR(40)  NOT NULL,
    rule_id          BIGINT       NOT NULL,
    trigger_type     VARCHAR(128) NOT NULL,
    trigger_ref      VARCHAR(160),
    entity_type      VARCHAR(64),
    entity_id        BIGINT,
    status           VARCHAR(32)  NOT NULL,   -- RUNNING | SUCCEEDED | FAILED | SKIPPED
    context          JSONB,
    result           JSONB,
    error            VARCHAR(2000),
    started_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    ended_at         TIMESTAMPTZ,
    duration_ms      BIGINT,
    executed_by      BIGINT,
    executed_by_email VARCHAR(255),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_automation_executions PRIMARY KEY (id),
    CONSTRAINT uq_automation_executions_number UNIQUE (execution_number),
    CONSTRAINT fk_automation_executions_rule FOREIGN KEY (rule_id) REFERENCES automation_rules (id)
);
CREATE INDEX idx_automation_executions_rule ON automation_executions (rule_id, started_at DESC);
CREATE INDEX idx_automation_executions_status ON automation_executions (status);

CREATE SEQUENCE automation_execution_seq START 1;

-- Per-action step log within an execution (append-only).
CREATE TABLE automation_execution_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    execution_id BIGINT       NOT NULL,
    step_order   INTEGER      NOT NULL DEFAULT 0,
    action_type  VARCHAR(128),
    status       VARCHAR(32)  NOT NULL,   -- SUCCEEDED | FAILED | SKIPPED
    message      VARCHAR(1000),
    detail       JSONB,
    occurred_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_automation_execution_logs PRIMARY KEY (id),
    CONSTRAINT fk_automation_execution_logs_exec FOREIGN KEY (execution_id) REFERENCES automation_executions (id) ON DELETE CASCADE
);
CREATE INDEX idx_automation_exec_logs_exec ON automation_execution_logs (execution_id, step_order);

-- Failure / retry queue for rules that error out.
CREATE TABLE automation_failures (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    rule_id       BIGINT       NOT NULL,
    execution_id  BIGINT,
    reason        VARCHAR(2000),
    payload       JSONB,
    retry_count   INTEGER      NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ,
    resolved      BOOLEAN      NOT NULL DEFAULT FALSE,
    resolved_at   TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_automation_failures PRIMARY KEY (id),
    CONSTRAINT fk_automation_failures_rule FOREIGN KEY (rule_id) REFERENCES automation_rules (id) ON DELETE CASCADE
);
CREATE INDEX idx_automation_failures_open ON automation_failures (resolved, next_retry_at);

-- Append-only audit trail (old/new snapshots), matching the dashboard pattern.
CREATE TABLE automation_audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    entity_type VARCHAR(32)  NOT NULL,   -- RULE | EXECUTION
    entity_id   BIGINT,
    action      VARCHAR(64)  NOT NULL,
    old_values  JSONB,
    new_values  JSONB,
    actor_id    BIGINT,
    actor_email VARCHAR(255),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_automation_audit_log PRIMARY KEY (id)
);
CREATE INDEX idx_automation_audit_entity ON automation_audit_log (entity_type, entity_id);

-- Module + granular permissions.
INSERT INTO modules (code, name, description, icon, path, display_order, enabled, is_system)
VALUES ('automation', 'Automation', 'Business process automation, rules and workflows',
        'mdi-cog-transfer-outline', '/automation', 110, TRUE, TRUE);

INSERT INTO permissions (module_id, action, code, name, is_system)
SELECT m.id, a.action, m.code || ':' || a.action, m.name || ' — ' || a.label, TRUE
FROM modules m
CROSS JOIN (VALUES
    ('view',          'View'),
    ('create',        'Create'),
    ('edit',          'Edit'),
    ('delete',        'Delete'),
    ('execute',       'Execute'),
    ('manage-status', 'Manage status'),
    ('manage-config', 'Manage configuration')
) AS a(action, label)
WHERE m.code = 'automation';
