-- Dynamic Forms & Custom Metadata — extend the ERP without a software update.
-- Business modules never implement a metadata engine: they register the entities
-- they allow to be extended, and this module owns field definitions, typed
-- value storage (searchable/sortable/reportable), versioned forms and
-- role/company/branch/device/stage-aware layouts.
--
-- Storage decision: values live in a TYPED EAV table rather than one JSONB blob,
-- because the spec requires custom fields to be searchable, filterable, sortable
-- and reportable — that needs real indexable columns per storage kind.

-- Configurable field-type catalogue. `handler_key` resolves to a
-- FieldTypeHandler bean; `storage_kind` decides which value column is used.
CREATE TABLE meta_field_types (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code            VARCHAR(64)  NOT NULL,
    name            VARCHAR(100) NOT NULL,
    handler_key     VARCHAR(64)  NOT NULL,
    storage_kind    VARCHAR(16)  NOT NULL,   -- TEXT | NUMBER | BOOLEAN | DATE | JSON
    supports_options BOOLEAN     NOT NULL DEFAULT FALSE,
    is_reference    BOOLEAN      NOT NULL DEFAULT FALSE,
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    is_system       BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order   INTEGER      NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_meta_field_types PRIMARY KEY (id),
    CONSTRAINT uq_meta_field_types_code UNIQUE (code),
    CONSTRAINT ck_meta_field_types_storage CHECK (storage_kind IN ('TEXT','NUMBER','BOOLEAN','DATE','JSON'))
);

INSERT INTO meta_field_types (code, name, handler_key, storage_kind, supports_options, is_reference, is_system, display_order) VALUES
    ('text',        'Text',            'text',      'TEXT',    FALSE, FALSE, TRUE, 10),
    ('textarea',    'Long text',       'text',      'TEXT',    FALSE, FALSE, TRUE, 20),
    ('integer',     'Integer',         'number',    'NUMBER',  FALSE, FALSE, TRUE, 30),
    ('decimal',     'Decimal',         'number',    'NUMBER',  FALSE, FALSE, TRUE, 40),
    ('boolean',     'Yes / No',        'boolean',   'BOOLEAN', FALSE, FALSE, TRUE, 50),
    ('date',        'Date',            'date',      'DATE',    FALSE, FALSE, TRUE, 60),
    ('datetime',    'Date and time',   'date',      'DATE',    FALSE, FALSE, TRUE, 70),
    ('select',      'Single select',   'select',    'TEXT',    TRUE,  FALSE, TRUE, 80),
    ('multiselect', 'Multi select',    'multiselect','JSON',   TRUE,  FALSE, TRUE, 90),
    ('email',       'Email',           'email',     'TEXT',    FALSE, FALSE, TRUE, 100),
    ('phone',       'Phone',           'phone',     'TEXT',    FALSE, FALSE, TRUE, 110),
    ('url',         'URL',             'url',       'TEXT',    FALSE, FALSE, TRUE, 120),
    ('reference',   'Reference',       'reference', 'NUMBER',  FALSE, TRUE,  TRUE, 130),
    ('json',        'Structured (JSON)','json',     'JSON',    FALSE, FALSE, TRUE, 140);

-- Which ERP entities accept custom fields. A business module "registers its
-- requirement" by inserting a row (or shipping one in its own migration).
CREATE TABLE meta_entities (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    module_code   VARCHAR(64)  NOT NULL,
    entity_code   VARCHAR(64)  NOT NULL,
    label         VARCHAR(160) NOT NULL,
    description   VARCHAR(1000),
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_meta_entities PRIMARY KEY (id),
    CONSTRAINT uq_meta_entities_target UNIQUE (module_code, entity_code)
);

INSERT INTO meta_entities (module_code, entity_code, label, description, is_system, display_order) VALUES
    ('crm',        'customer', 'Customer', 'CRM customer master record',      TRUE, 10),
    ('products',   'product',  'Product',  'Product catalogue item',          TRUE, 20),
    ('suppliers',  'supplier', 'Supplier', 'Supplier registry record',        TRUE, 30),
    ('purchasing', 'purchase', 'Purchase', 'Purchase document',               TRUE, 40),
    ('users',      'user',     'User',     'User account and profile',        TRUE, 50);

-- Custom field definitions, tenant/company/branch scoped.
CREATE TABLE meta_fields (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    entity_id        BIGINT       NOT NULL,
    code             VARCHAR(64)  NOT NULL,
    label            VARCHAR(160) NOT NULL,
    help_text        VARCHAR(1000),
    field_type_id    BIGINT       NOT NULL,
    required         BOOLEAN      NOT NULL DEFAULT FALSE,
    default_value    VARCHAR(2000),
    min_value        NUMERIC(18,4),
    max_value        NUMERIC(18,4),
    min_length       INTEGER,
    max_length       INTEGER,
    pattern          VARCHAR(500),
    options          JSONB        NOT NULL DEFAULT '[]'::jsonb,
    reference_entity VARCHAR(128),
    searchable       BOOLEAN      NOT NULL DEFAULT TRUE,
    sortable         BOOLEAN      NOT NULL DEFAULT FALSE,
    reportable       BOOLEAN      NOT NULL DEFAULT TRUE,
    localized        BOOLEAN      NOT NULL DEFAULT FALSE,
    view_permission  VARCHAR(128),
    edit_permission  VARCHAR(128),
    quality_rule_code VARCHAR(64),           -- delegate deep validation to module 2
    display_order    INTEGER      NOT NULL DEFAULT 0,
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    tenant_id        BIGINT,
    company_id       BIGINT,
    branch_id        BIGINT,
    created_by       BIGINT,
    created_by_email VARCHAR(255),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_meta_fields PRIMARY KEY (id),
    CONSTRAINT uq_meta_fields_code UNIQUE (entity_id, code),
    CONSTRAINT fk_meta_fields_entity FOREIGN KEY (entity_id) REFERENCES meta_entities (id) ON DELETE CASCADE,
    CONSTRAINT fk_meta_fields_type   FOREIGN KEY (field_type_id) REFERENCES meta_field_types (id)
);
CREATE INDEX idx_meta_fields_entity ON meta_fields (entity_id, display_order);
CREATE INDEX idx_meta_fields_scope  ON meta_fields (tenant_id, company_id, branch_id);

-- Per-locale labels/help so custom fields localize like the rest of the UI.
CREATE TABLE meta_field_translations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    field_id   BIGINT       NOT NULL,
    locale     VARCHAR(16)  NOT NULL,
    label      VARCHAR(160) NOT NULL,
    help_text  VARCHAR(1000),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version    BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_meta_field_translations PRIMARY KEY (id),
    CONSTRAINT uq_meta_field_translations UNIQUE (field_id, locale),
    CONSTRAINT fk_meta_field_translations_field FOREIGN KEY (field_id) REFERENCES meta_fields (id) ON DELETE CASCADE
);

-- Typed EAV value storage: one row per (record, field). Typed columns keep the
-- values indexable, so custom fields participate in search/sort/reporting.
CREATE TABLE meta_field_values (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    field_id      BIGINT       NOT NULL,
    module_code   VARCHAR(64)  NOT NULL,
    entity_code   VARCHAR(64)  NOT NULL,
    record_id     BIGINT       NOT NULL,
    value_text    VARCHAR(4000),
    value_number  NUMERIC(24,6),
    value_boolean BOOLEAN,
    value_date    TIMESTAMPTZ,
    value_json    JSONB,
    tenant_id     BIGINT,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_meta_field_values PRIMARY KEY (id),
    CONSTRAINT uq_meta_field_values UNIQUE (field_id, record_id),
    CONSTRAINT fk_meta_field_values_field FOREIGN KEY (field_id) REFERENCES meta_fields (id) ON DELETE CASCADE
);
CREATE INDEX idx_meta_values_record ON meta_field_values (module_code, entity_code, record_id);
CREATE INDEX idx_meta_values_text   ON meta_field_values (field_id, value_text);
CREATE INDEX idx_meta_values_number ON meta_field_values (field_id, value_number);
CREATE INDEX idx_meta_values_date   ON meta_field_values (field_id, value_date);

-- Dynamic forms. A form belongs to an entity; its content is versioned so
-- historical records stay renderable against the version they were captured on.
CREATE TABLE meta_forms (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    entity_id     BIGINT       NOT NULL,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(160) NOT NULL,
    description   VARCHAR(1000),
    is_default    BOOLEAN      NOT NULL DEFAULT FALSE,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    tenant_id     BIGINT,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_meta_forms PRIMARY KEY (id),
    CONSTRAINT uq_meta_forms_code UNIQUE (code),
    CONSTRAINT fk_meta_forms_entity FOREIGN KEY (entity_id) REFERENCES meta_entities (id) ON DELETE CASCADE
);

-- An immutable published snapshot of a form's schema (sections + fields).
CREATE TABLE meta_form_versions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    form_id      BIGINT       NOT NULL,
    version_no   INTEGER      NOT NULL,
    status       VARCHAR(32)  NOT NULL DEFAULT 'DRAFT',   -- DRAFT | PUBLISHED | ARCHIVED
    schema_json  JSONB        NOT NULL DEFAULT '{}'::jsonb,
    change_note  VARCHAR(1000),
    published_at TIMESTAMPTZ,
    published_by BIGINT,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version      BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_meta_form_versions PRIMARY KEY (id),
    CONSTRAINT uq_meta_form_versions UNIQUE (form_id, version_no),
    CONSTRAINT fk_meta_form_versions_form FOREIGN KEY (form_id) REFERENCES meta_forms (id) ON DELETE CASCADE,
    CONSTRAINT ck_meta_form_versions_status CHECK (status IN ('DRAFT','PUBLISHED','ARCHIVED'))
);
CREATE INDEX idx_meta_form_versions_form ON meta_form_versions (form_id, version_no DESC);

-- Layout variants selected at render time by role / company / branch / device /
-- workflow stage. Most specific match wins (see LayoutResolver).
CREATE TABLE meta_form_layouts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    form_version_id BIGINT       NOT NULL,
    target_type     VARCHAR(32)  NOT NULL,   -- DEFAULT | ROLE | COMPANY | BRANCH | DEVICE | STAGE
    target_value    VARCHAR(128),
    layout_json     JSONB        NOT NULL DEFAULT '{}'::jsonb,
    priority        INTEGER      NOT NULL DEFAULT 100,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_meta_form_layouts PRIMARY KEY (id),
    CONSTRAINT fk_meta_form_layouts_version FOREIGN KEY (form_version_id) REFERENCES meta_form_versions (id) ON DELETE CASCADE,
    CONSTRAINT ck_meta_form_layouts_target CHECK (target_type IN ('DEFAULT','ROLE','COMPANY','BRANCH','DEVICE','STAGE'))
);
CREATE INDEX idx_meta_form_layouts_version ON meta_form_layouts (form_version_id, priority);

-- Which form version a record was captured with — the key to keeping historical
-- records renderable after the form evolves.
CREATE TABLE meta_record_form_versions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    module_code     VARCHAR(64) NOT NULL,
    entity_code     VARCHAR(64) NOT NULL,
    record_id       BIGINT      NOT NULL,
    form_version_id BIGINT      NOT NULL,
    captured_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    version         BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT pk_meta_record_form_versions PRIMARY KEY (id),
    CONSTRAINT uq_meta_record_form_versions UNIQUE (module_code, entity_code, record_id),
    CONSTRAINT fk_meta_record_form_versions_version FOREIGN KEY (form_version_id) REFERENCES meta_form_versions (id)
);

-- Append-only audit trail.
CREATE TABLE meta_audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    entity_type VARCHAR(32)  NOT NULL,   -- FIELD | FORM | FORM_VERSION | LAYOUT | VALUE
    entity_id   BIGINT,
    action      VARCHAR(64)  NOT NULL,
    old_values  JSONB,
    new_values  JSONB,
    actor_id    BIGINT,
    actor_email VARCHAR(255),
    ip_address  VARCHAR(64),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_meta_audit_log PRIMARY KEY (id)
);
CREATE INDEX idx_meta_audit_entity ON meta_audit_log (entity_type, entity_id);

-- Module + granular permissions.
INSERT INTO modules (code, name, description, icon, path, display_order, enabled, is_system)
VALUES ('metadata', 'Custom Fields & Forms', 'Custom fields, dynamic forms, layouts and metadata',
        'mdi-form-select', '/metadata', 140, TRUE, TRUE);

INSERT INTO permissions (module_id, action, code, name, is_system)
SELECT m.id, a.action, m.code || ':' || a.action, m.name || ' — ' || a.label, TRUE
FROM modules m
CROSS JOIN (VALUES
    ('view',            'View metadata'),
    ('create',          'Create custom fields'),
    ('edit',            'Edit custom fields'),
    ('delete',          'Delete custom fields'),
    ('manage-forms',    'Manage dynamic forms'),
    ('publish',         'Publish form versions'),
    ('manage-layouts',  'Manage form layouts'),
    ('write-values',    'Write custom field values'),
    ('export',          'Export metadata')
) AS a(action, label)
WHERE m.code = 'metadata';
