-- =====================================================================
-- V21 — Customer Portal & Self-Service (module 14)
--
-- Secure customer-facing access to their own data.
--
-- THE CENTRAL RULE: this module owns NO business data. It owns portal
-- accounts, sessions, requests, messages and audit. Everything a customer
-- sees about installments, repairs, warranties, invoices or trade-ins is
-- fetched at read time from the owning module through the
-- PortalDataProvider SPI. Dashboard widgets are rows whose provider_key
-- resolves a bean; a widget with no registered provider is reported as
-- unavailable rather than silently empty.
--
-- SECURITY MODEL. A portal account is NOT a staff `users` row. Customers
-- authenticate in a separate realm with their own principal, their own
-- sessions table and their own token audience, so a portal token can never
-- satisfy a staff endpoint and a customer can never hold an RBAC role.
-- Customer-facing capabilities are configured in portal_capabilities,
-- deliberately disjoint from the staff `permissions` table.
--
-- Account lockout lives here (failed_attempts / locked_until) because it is
-- portal-account lifecycle state, not shared infrastructure — this is the
-- first internet-facing login surface in the system.
-- =====================================================================


-- ---------------------------------------------------------------------
-- Account lifecycle. Flag-driven: `allows_login` is the single gate, so
-- suspending an account cannot be bypassed by a code path that forgot a case.
-- ---------------------------------------------------------------------
CREATE TABLE portal_account_statuses (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                  VARCHAR(64)  NOT NULL,
    name                  VARCHAR(100) NOT NULL,
    is_default            BOOLEAN      NOT NULL DEFAULT FALSE,
    allows_login          BOOLEAN      NOT NULL DEFAULT FALSE,
    requires_verification BOOLEAN      NOT NULL DEFAULT FALSE,
    is_locked_state       BOOLEAN      NOT NULL DEFAULT FALSE,
    is_suspended_state    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_archived_state     BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system             BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order         INTEGER      NOT NULL DEFAULT 0,
    tenant_id             BIGINT,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version               BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_portal_account_statuses PRIMARY KEY (id),
    CONSTRAINT fk_portal_statuses_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_portal_statuses_code_global ON portal_account_statuses (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_portal_statuses_code_tenant ON portal_account_statuses (tenant_id, code) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_portal_statuses_default_global ON portal_account_statuses ((TRUE)) WHERE is_default AND tenant_id IS NULL;

INSERT INTO portal_account_statuses (code, name, is_default, allows_login, requires_verification,
                                     is_locked_state, is_suspended_state, is_archived_state,
                                     is_system, display_order) VALUES
    ('pending-verification', 'Pending Verification', TRUE,  FALSE, TRUE,  FALSE, FALSE, FALSE, TRUE, 10),
    ('active',               'Active',               FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, TRUE, 20),
    ('suspended',            'Suspended',            FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, TRUE, 30),
    ('locked',               'Locked',               FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, TRUE, 40),
    ('disabled',             'Disabled',             FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 50),
    ('archived',             'Archived',             FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  TRUE, 60);


-- ---------------------------------------------------------------------
-- Authentication methods. handler_key resolves a PortalAuthMethod bean.
--
-- `requires_delivery` marks methods that must send a code somewhere. Such a
-- method is refused at runtime unless an OtpDeliveryChannel bean is
-- registered — the portal will not issue a code it can only write to a log.
-- ---------------------------------------------------------------------
CREATE TABLE portal_auth_methods (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code              VARCHAR(64)  NOT NULL,
    name              VARCHAR(100) NOT NULL,
    handler_key       VARCHAR(64)  NOT NULL,
    config            JSONB        NOT NULL DEFAULT '{}'::jsonb,
    enabled           BOOLEAN      NOT NULL DEFAULT FALSE,
    is_primary_method BOOLEAN      NOT NULL DEFAULT FALSE,
    requires_delivery BOOLEAN      NOT NULL DEFAULT FALSE,
    is_second_factor  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system         BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order     INTEGER      NOT NULL DEFAULT 0,
    tenant_id         BIGINT,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_portal_auth_methods PRIMARY KEY (id),
    CONSTRAINT fk_portal_auth_methods_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_portal_auth_methods_code_global ON portal_auth_methods (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_portal_auth_methods_code_tenant ON portal_auth_methods (tenant_id, code) WHERE tenant_id IS NOT NULL;

-- Only password is enabled: it is the only method with a working implementation
-- and no external delivery dependency. The rest are catalogued and disabled so
-- enabling one is a configuration change once its bean and gateway exist.
INSERT INTO portal_auth_methods (code, name, handler_key, enabled, is_primary_method,
                                 requires_delivery, is_second_factor, is_system, display_order) VALUES
    ('password',      'Password',           'password',      TRUE,  TRUE,  FALSE, FALSE, TRUE, 10),
    ('otp-sms',       'OTP via SMS',        'otp-sms',       FALSE, TRUE,  TRUE,  TRUE,  TRUE, 20),
    ('otp-email',     'Email Verification', 'otp-email',     FALSE, TRUE,  TRUE,  TRUE,  TRUE, 30),
    ('authenticator', 'Authenticator App',  'authenticator', FALSE, FALSE, FALSE, TRUE,  TRUE, 40),
    ('passkey',       'Passkey',            'passkey',       FALSE, TRUE,  FALSE, FALSE, TRUE, 50);


-- ---------------------------------------------------------------------
-- Customer-facing capabilities.
--
-- Deliberately a SEPARATE table from the staff `permissions`: a customer must
-- never hold an RBAC permission code, and the two vocabularies must not be
-- able to drift into each other.
-- ---------------------------------------------------------------------
CREATE TABLE portal_capabilities (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(120) NOT NULL,
    description   VARCHAR(500),
    granted_by_default BOOLEAN NOT NULL DEFAULT FALSE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    tenant_id     BIGINT,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_portal_capabilities PRIMARY KEY (id),
    CONSTRAINT fk_portal_capabilities_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_portal_capabilities_code_global ON portal_capabilities (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_portal_capabilities_code_tenant ON portal_capabilities (tenant_id, code) WHERE tenant_id IS NOT NULL;

INSERT INTO portal_capabilities (code, name, description, granted_by_default, is_system, display_order) VALUES
    ('profile:view',      'View profile',        'See own profile details',              TRUE,  TRUE, 10),
    ('profile:edit',      'Edit profile',        'Change permitted profile fields',      TRUE,  TRUE, 20),
    ('documents:view',    'View documents',      'See documents shared with them',       TRUE,  TRUE, 30),
    ('documents:download','Download documents',  'Download own documents',               TRUE,  TRUE, 40),
    ('documents:upload',  'Upload documents',    'Upload requested documents',           TRUE,  TRUE, 50),
    ('requests:submit',   'Submit requests',     'Raise self-service requests',          TRUE,  TRUE, 60),
    ('messages:use',      'Messaging',           'Exchange secure messages with staff',  TRUE,  TRUE, 70),
    ('installments:view', 'View installments',   'See own installment contracts',        TRUE,  TRUE, 80),
    ('repairs:view',      'View repairs',        'Track own repairs',                    TRUE,  TRUE, 90),
    ('warranty:view',     'View warranty',       'See own warranty status',              TRUE,  TRUE, 100),
    ('purchases:view',    'View purchases',      'See own purchase history',             TRUE,  TRUE, 110),
    ('devices:manage',    'Manage devices',      'Manage trusted devices and sessions',  TRUE,  TRUE, 120);


-- ---------------------------------------------------------------------
-- Dashboard widgets.
--
-- provider_key resolves a PortalDataProvider bean contributed by the module
-- that OWNS the data. Most are seeded disabled because their module does not
-- exist yet; the catalogue reports which have a registered provider, so an
-- operator sees "no provider" rather than an empty panel.
-- ---------------------------------------------------------------------
CREATE TABLE portal_widgets (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                VARCHAR(64)  NOT NULL,
    name                VARCHAR(120) NOT NULL,
    provider_key        VARCHAR(64)  NOT NULL,
    required_capability VARCHAR(64),
    config              JSONB        NOT NULL DEFAULT '{}'::jsonb,
    enabled             BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order       INTEGER      NOT NULL DEFAULT 0,
    is_system           BOOLEAN      NOT NULL DEFAULT FALSE,
    tenant_id           BIGINT,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version             BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_portal_widgets PRIMARY KEY (id),
    CONSTRAINT fk_portal_widgets_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_portal_widgets_code_global ON portal_widgets (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_portal_widgets_code_tenant ON portal_widgets (tenant_id, code) WHERE tenant_id IS NOT NULL;

INSERT INTO portal_widgets (code, name, provider_key, required_capability, enabled, display_order, is_system) VALUES
    ('profile',               'My Profile',            'portal.profile',      'profile:view',      TRUE,  10,  TRUE),
    ('documents',             'My Documents',          'portal.documents',    'documents:view',    TRUE,  20,  TRUE),
    ('requests',              'My Requests',           'portal.requests',     'requests:submit',   TRUE,  30,  TRUE),
    ('messages',              'Messages',              'portal.messages',     'messages:use',      TRUE,  40,  TRUE),
    ('notifications',         'Notifications',         'portal.notifications', NULL,               TRUE,  50,  TRUE),
    -- Awaiting their owning module; no provider bean exists yet.
    ('outstanding-installments','Outstanding Installments','installments.outstanding','installments:view', FALSE, 60,  TRUE),
    ('upcoming-due-dates',    'Upcoming Due Dates',    'installments.upcoming','installments:view', FALSE, 70,  TRUE),
    ('purchase-history',      'Purchase History',      'sales.purchases',     'purchases:view',    FALSE, 80,  TRUE),
    ('invoices',              'Invoices',              'sales.invoices',      'purchases:view',    FALSE, 90,  TRUE),
    ('repair-status',         'Repair Status',         'repair.status',       'repairs:view',      FALSE, 100, TRUE),
    ('warranty-status',       'Warranty Status',       'warranty.status',     'warranty:view',     FALSE, 110, TRUE),
    ('trade-in-history',      'Trade-In History',      'tradein.history',     'purchases:view',    FALSE, 120, TRUE),
    ('reward-points',         'Reward Points',         'loyalty.points',      NULL,                FALSE, 130, TRUE);


-- ---------------------------------------------------------------------
-- Self-service request types and lifecycle.
-- ---------------------------------------------------------------------
CREATE TABLE portal_request_types (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                VARCHAR(64)  NOT NULL,
    name                VARCHAR(120) NOT NULL,
    description         VARCHAR(500),
    requires_attachment BOOLEAN      NOT NULL DEFAULT FALSE,
    allows_attachment   BOOLEAN      NOT NULL DEFAULT TRUE,
    sla_hours           INTEGER,
    target_module       VARCHAR(64),
    enabled             BOOLEAN      NOT NULL DEFAULT TRUE,
    is_system           BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order       INTEGER      NOT NULL DEFAULT 0,
    tenant_id           BIGINT,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version             BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_portal_request_types PRIMARY KEY (id),
    CONSTRAINT fk_portal_request_types_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_portal_request_types_code_global ON portal_request_types (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_portal_request_types_code_tenant ON portal_request_types (tenant_id, code) WHERE tenant_id IS NOT NULL;

INSERT INTO portal_request_types (code, name, description, requires_attachment, sla_hours, target_module, enabled, is_system, display_order) VALUES
    ('profile-update',      'Profile Update',       'Request a change to profile details',    FALSE, 48,  'crm',          TRUE, TRUE, 10),
    ('document-request',    'Document Request',     'Request a copy of a document',           FALSE, 48,  NULL,           TRUE, TRUE, 20),
    ('invoice-copy',        'Invoice Copy',         'Request a duplicate invoice',            FALSE, 24,  'sales',        TRUE, TRUE, 30),
    ('installment-inquiry', 'Installment Inquiry',  'Question about an installment plan',     FALSE, 24,  'installments', TRUE, TRUE, 40),
    ('early-settlement',    'Early Settlement',     'Request to settle a contract early',     FALSE, 72,  'installments', TRUE, TRUE, 50),
    ('repair-request',      'Repair Request',       'Request a device repair',                FALSE, 24,  'repair',       TRUE, TRUE, 60),
    ('warranty-request',    'Warranty Request',     'Raise a warranty claim',                 TRUE,  48,  'warranty',     TRUE, TRUE, 70),
    ('appointment',         'Appointment Request',  'Request an in-store appointment',        FALSE, 24,  NULL,           TRUE, TRUE, 80),
    ('complaint',           'Complaint',            'Raise a complaint',                      FALSE, 24,  'crm',          TRUE, TRUE, 90),
    ('suggestion',          'Suggestion',           'Submit a suggestion',                    FALSE, NULL,'crm',          TRUE, TRUE, 100);

CREATE TABLE portal_request_statuses (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code              VARCHAR(64)  NOT NULL,
    name              VARCHAR(100) NOT NULL,
    is_default        BOOLEAN      NOT NULL DEFAULT FALSE,
    is_open_state     BOOLEAN      NOT NULL DEFAULT FALSE,
    awaits_customer   BOOLEAN      NOT NULL DEFAULT FALSE,
    is_resolved_state BOOLEAN      NOT NULL DEFAULT FALSE,
    is_closed_state   BOOLEAN      NOT NULL DEFAULT FALSE,
    allows_reply      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system         BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order     INTEGER      NOT NULL DEFAULT 0,
    tenant_id         BIGINT,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_portal_request_statuses PRIMARY KEY (id),
    CONSTRAINT fk_portal_req_statuses_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_portal_req_statuses_code_global ON portal_request_statuses (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_portal_req_statuses_code_tenant ON portal_request_statuses (tenant_id, code) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_portal_req_statuses_default_global ON portal_request_statuses ((TRUE)) WHERE is_default AND tenant_id IS NULL;

INSERT INTO portal_request_statuses (code, name, is_default, is_open_state, awaits_customer,
                                     is_resolved_state, is_closed_state, allows_reply, is_system, display_order) VALUES
    ('submitted',        'Submitted',         TRUE,  TRUE,  FALSE, FALSE, FALSE, TRUE,  TRUE, 10),
    ('in-review',        'In Review',         FALSE, TRUE,  FALSE, FALSE, FALSE, TRUE,  TRUE, 20),
    ('awaiting-customer','Awaiting Customer', FALSE, TRUE,  TRUE,  FALSE, FALSE, TRUE,  TRUE, 30),
    ('resolved',         'Resolved',          FALSE, FALSE, FALSE, TRUE,  FALSE, TRUE,  TRUE, 40),
    ('rejected',         'Rejected',          FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, TRUE, 50),
    ('closed',           'Closed',            FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, TRUE, 60);


-- ---------------------------------------------------------------------
-- Notification types.
-- ---------------------------------------------------------------------
CREATE TABLE portal_notification_types (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code           VARCHAR(64)  NOT NULL,
    name           VARCHAR(120) NOT NULL,
    is_marketing   BOOLEAN      NOT NULL DEFAULT FALSE,
    is_security    BOOLEAN      NOT NULL DEFAULT FALSE,
    opt_out_allowed BOOLEAN     NOT NULL DEFAULT TRUE,
    enabled        BOOLEAN      NOT NULL DEFAULT TRUE,
    is_system      BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order  INTEGER      NOT NULL DEFAULT 0,
    tenant_id      BIGINT,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_portal_notification_types PRIMARY KEY (id),
    CONSTRAINT fk_portal_notif_types_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_portal_notif_types_code_global ON portal_notification_types (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_portal_notif_types_code_tenant ON portal_notification_types (tenant_id, code) WHERE tenant_id IS NOT NULL;

-- Security alerts cannot be opted out of.
INSERT INTO portal_notification_types (code, name, is_marketing, is_security, opt_out_allowed, is_system, display_order) VALUES
    ('installment-due',   'Installment Due',       FALSE, FALSE, TRUE,  TRUE, 10),
    ('repair-status',     'Repair Status Changed', FALSE, FALSE, TRUE,  TRUE, 20),
    ('warranty-expiring', 'Warranty Expiring',     FALSE, FALSE, TRUE,  TRUE, 30),
    ('document-ready',    'Document Ready',        FALSE, FALSE, TRUE,  TRUE, 40),
    ('approval-required', 'Approval Required',     FALSE, FALSE, FALSE, TRUE, 50),
    ('security-alert',    'Security Alert',        FALSE, TRUE,  FALSE, TRUE, 60),
    ('marketing',         'Marketing Messages',    TRUE,  FALSE, TRUE,  TRUE, 70);


-- =====================================================================
-- Accounts, credentials, sessions
-- =====================================================================
CREATE SEQUENCE portal_request_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE portal_accounts (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id           BIGINT       NOT NULL,
    username              VARCHAR(160) NOT NULL,
    mobile_number         VARCHAR(32),
    email                 VARCHAR(255),
    password_hash         VARCHAR(255),
    preferred_language    VARCHAR(16)  NOT NULL DEFAULT 'fa',
    preferred_timezone    VARCHAR(64)  NOT NULL DEFAULT 'Asia/Tehran',
    status_id             BIGINT       NOT NULL,
    registered_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    verified_at           TIMESTAMPTZ,
    last_login_at         TIMESTAMPTZ,
    last_login_ip         VARCHAR(64),
    -- Lockout is portal-account lifecycle state; this is the first
    -- internet-facing login surface in the system.
    failed_attempts       INTEGER      NOT NULL DEFAULT 0,
    locked_until          TIMESTAMPTZ,
    must_change_password  BOOLEAN      NOT NULL DEFAULT FALSE,
    marketing_opt_in      BOOLEAN      NOT NULL DEFAULT FALSE,
    invited_by            BIGINT,
    tenant_id             BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version               BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_portal_accounts PRIMARY KEY (id),
    CONSTRAINT uq_portal_accounts_username UNIQUE (tenant_id, username),
    -- One portal account per customer: two accounts for one customer would
    -- make "own data only" ambiguous.
    CONSTRAINT uq_portal_accounts_customer UNIQUE (tenant_id, customer_id),
    CONSTRAINT fk_portal_accounts_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT,
    CONSTRAINT fk_portal_accounts_status   FOREIGN KEY (status_id) REFERENCES portal_account_statuses (id),
    CONSTRAINT fk_portal_accounts_tenant   FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_portal_accounts_customer ON portal_accounts (customer_id);
CREATE INDEX idx_portal_accounts_tenant   ON portal_accounts (tenant_id);
CREATE UNIQUE INDEX uq_portal_accounts_mobile ON portal_accounts (tenant_id, mobile_number) WHERE mobile_number IS NOT NULL;

CREATE TABLE portal_account_capabilities (
    account_id    BIGINT NOT NULL,
    capability_id BIGINT NOT NULL,
    granted_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_portal_account_capabilities PRIMARY KEY (account_id, capability_id),
    CONSTRAINT fk_pac_account    FOREIGN KEY (account_id) REFERENCES portal_accounts (id) ON DELETE CASCADE,
    CONSTRAINT fk_pac_capability FOREIGN KEY (capability_id) REFERENCES portal_capabilities (id) ON DELETE CASCADE
);

-- Enrolled second factors and passkeys. Secrets are stored hashed, never plain.
CREATE TABLE portal_credentials (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id   BIGINT       NOT NULL,
    method_id    BIGINT       NOT NULL,
    secret_hash  VARCHAR(512),
    label        VARCHAR(160),
    enrolled_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_used_at TIMESTAMPTZ,
    revoked_at   TIMESTAMPTZ,
    tenant_id    BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version      BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_portal_credentials PRIMARY KEY (id),
    CONSTRAINT fk_portal_credentials_account FOREIGN KEY (account_id) REFERENCES portal_accounts (id) ON DELETE CASCADE,
    CONSTRAINT fk_portal_credentials_method  FOREIGN KEY (method_id) REFERENCES portal_auth_methods (id),
    CONSTRAINT fk_portal_credentials_tenant  FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_portal_credentials_account ON portal_credentials (account_id);

-- One-time codes. The code itself is stored hashed, like every other secret here.
CREATE TABLE portal_otp_challenges (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id      BIGINT       NOT NULL,
    purpose         VARCHAR(64)  NOT NULL,
    code_hash       VARCHAR(128) NOT NULL,
    delivery_key    VARCHAR(64)  NOT NULL,
    delivery_target VARCHAR(255) NOT NULL,
    attempts        INTEGER      NOT NULL DEFAULT 0,
    max_attempts    INTEGER      NOT NULL DEFAULT 5,
    expires_at      TIMESTAMPTZ  NOT NULL,
    consumed_at     TIMESTAMPTZ,
    tenant_id       BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_portal_otp_challenges PRIMARY KEY (id),
    CONSTRAINT fk_portal_otp_account FOREIGN KEY (account_id) REFERENCES portal_accounts (id) ON DELETE CASCADE,
    CONSTRAINT fk_portal_otp_tenant  FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_portal_otp_account ON portal_otp_challenges (account_id, purpose);

-- Sessions are per-device so a customer can see and revoke them individually,
-- and so locking an account can kill live sessions rather than waiting for expiry.
CREATE TABLE portal_sessions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id         BIGINT       NOT NULL,
    token_hash         VARCHAR(128) NOT NULL,
    device_label       VARCHAR(160),
    device_fingerprint VARCHAR(255),
    ip_address         VARCHAR(64),
    user_agent         VARCHAR(500),
    is_trusted         BOOLEAN      NOT NULL DEFAULT FALSE,
    issued_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_seen_at       TIMESTAMPTZ,
    expires_at         TIMESTAMPTZ  NOT NULL,
    revoked_at         TIMESTAMPTZ,
    revoked_reason     VARCHAR(255),
    tenant_id          BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version            BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_portal_sessions PRIMARY KEY (id),
    CONSTRAINT uq_portal_sessions_token UNIQUE (token_hash),
    CONSTRAINT fk_portal_sessions_account FOREIGN KEY (account_id) REFERENCES portal_accounts (id) ON DELETE CASCADE,
    CONSTRAINT fk_portal_sessions_tenant  FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_portal_sessions_account ON portal_sessions (account_id, revoked_at);


-- =====================================================================
-- Requests, messaging, documents, notifications
-- =====================================================================
CREATE TABLE portal_requests (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    request_number    VARCHAR(32)  NOT NULL,
    account_id        BIGINT       NOT NULL,
    type_id           BIGINT       NOT NULL,
    status_id         BIGINT       NOT NULL,
    subject           VARCHAR(255) NOT NULL,
    body              TEXT,
    related_module    VARCHAR(64),
    related_entity    VARCHAR(64),
    related_record_id BIGINT,
    assigned_to       BIGINT,
    sla_due_at        TIMESTAMPTZ,
    resolved_at       TIMESTAMPTZ,
    resolved_by       BIGINT,
    resolution        VARCHAR(2000),
    tenant_id         BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_portal_requests PRIMARY KEY (id),
    CONSTRAINT uq_portal_requests_number UNIQUE (tenant_id, request_number),
    CONSTRAINT fk_portal_requests_account FOREIGN KEY (account_id) REFERENCES portal_accounts (id) ON DELETE CASCADE,
    CONSTRAINT fk_portal_requests_type    FOREIGN KEY (type_id) REFERENCES portal_request_types (id),
    CONSTRAINT fk_portal_requests_status  FOREIGN KEY (status_id) REFERENCES portal_request_statuses (id),
    CONSTRAINT fk_portal_requests_tenant  FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_portal_requests_account ON portal_requests (account_id, created_at DESC);
CREATE INDEX idx_portal_requests_status  ON portal_requests (tenant_id, status_id);

-- Threaded messages on a request, and standalone secure conversations.
-- `is_internal` keeps staff-only notes out of the customer's view.
CREATE TABLE portal_messages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    request_id   BIGINT,
    account_id   BIGINT       NOT NULL,
    parent_id    BIGINT,
    author_kind  VARCHAR(16)  NOT NULL,
    author_id    BIGINT,
    author_name  VARCHAR(160),
    subject      VARCHAR(255),
    body         TEXT         NOT NULL,
    is_internal  BOOLEAN      NOT NULL DEFAULT FALSE,
    read_at      TIMESTAMPTZ,
    tenant_id    BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version      BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_portal_messages PRIMARY KEY (id),
    CONSTRAINT ck_portal_messages_author CHECK (author_kind IN ('CUSTOMER', 'STAFF', 'SYSTEM')),
    -- Only staff may write internal notes.
    CONSTRAINT ck_portal_messages_internal CHECK (NOT is_internal OR author_kind <> 'CUSTOMER'),
    CONSTRAINT fk_portal_messages_request FOREIGN KEY (request_id) REFERENCES portal_requests (id) ON DELETE CASCADE,
    CONSTRAINT fk_portal_messages_account FOREIGN KEY (account_id) REFERENCES portal_accounts (id) ON DELETE CASCADE,
    CONSTRAINT fk_portal_messages_parent  FOREIGN KEY (parent_id) REFERENCES portal_messages (id) ON DELETE CASCADE,
    CONSTRAINT fk_portal_messages_tenant  FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_portal_messages_account ON portal_messages (account_id, created_at DESC);
CREATE INDEX idx_portal_messages_request ON portal_messages (request_id);

-- Attachments reference the files module by UUID. No bytes here.
CREATE TABLE portal_attachments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    request_id  BIGINT,
    message_id  BIGINT,
    account_id  BIGINT       NOT NULL,
    file_uuid   UUID         NOT NULL,
    caption     VARCHAR(255),
    uploaded_by_kind VARCHAR(16) NOT NULL DEFAULT 'CUSTOMER',
    tenant_id   BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_portal_attachments PRIMARY KEY (id),
    CONSTRAINT ck_portal_attachments_parent CHECK (request_id IS NOT NULL OR message_id IS NOT NULL),
    CONSTRAINT fk_portal_attach_request FOREIGN KEY (request_id) REFERENCES portal_requests (id) ON DELETE CASCADE,
    CONSTRAINT fk_portal_attach_message FOREIGN KEY (message_id) REFERENCES portal_messages (id) ON DELETE CASCADE,
    CONSTRAINT fk_portal_attach_account FOREIGN KEY (account_id) REFERENCES portal_accounts (id) ON DELETE CASCADE,
    CONSTRAINT fk_portal_attach_tenant  FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);

-- Explicit grant of a managed file to a customer.
--
-- This is the ONLY way a portal account may read a file: the portal never
-- infers access from a file's contents or its owning module. Revocable, and
-- every download is audited.
CREATE TABLE portal_document_grants (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id    BIGINT       NOT NULL,
    file_uuid     UUID         NOT NULL,
    title         VARCHAR(255),
    source_module VARCHAR(64),
    source_entity VARCHAR(64),
    source_record_id BIGINT,
    granted_by    BIGINT,
    granted_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    revoked_at    TIMESTAMPTZ,
    download_count INTEGER     NOT NULL DEFAULT 0,
    last_downloaded_at TIMESTAMPTZ,
    requires_signature BOOLEAN NOT NULL DEFAULT FALSE,
    signed_at     TIMESTAMPTZ,
    signature_ref VARCHAR(255),
    tenant_id     BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_portal_document_grants PRIMARY KEY (id),
    CONSTRAINT uq_portal_document_grants UNIQUE (account_id, file_uuid),
    CONSTRAINT fk_portal_grants_account FOREIGN KEY (account_id) REFERENCES portal_accounts (id) ON DELETE CASCADE,
    CONSTRAINT fk_portal_grants_tenant  FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_portal_grants_account ON portal_document_grants (account_id, revoked_at);

CREATE TABLE portal_notifications (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id        BIGINT       NOT NULL,
    type_id           BIGINT       NOT NULL,
    title             VARCHAR(255) NOT NULL,
    body              VARCHAR(2000),
    related_module    VARCHAR(64),
    related_record_id BIGINT,
    read_at           TIMESTAMPTZ,
    tenant_id         BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_portal_notifications PRIMARY KEY (id),
    CONSTRAINT fk_portal_notif_account FOREIGN KEY (account_id) REFERENCES portal_accounts (id) ON DELETE CASCADE,
    CONSTRAINT fk_portal_notif_type    FOREIGN KEY (type_id) REFERENCES portal_notification_types (id),
    CONSTRAINT fk_portal_notif_tenant  FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_portal_notifications_account ON portal_notifications (account_id, read_at, created_at DESC);

-- Audit records device and IP per the spec, on every portal action.
CREATE TABLE portal_audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id   BIGINT,
    entity_type  VARCHAR(64)  NOT NULL,
    entity_id    BIGINT,
    action       VARCHAR(64)  NOT NULL,
    old_values   JSONB,
    new_values   JSONB,
    actor_kind   VARCHAR(16)  NOT NULL DEFAULT 'CUSTOMER',
    actor_id     BIGINT,
    actor_label  VARCHAR(255),
    ip_address   VARCHAR(64),
    device_label VARCHAR(255),
    user_agent   VARCHAR(500),
    tenant_id    BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version      BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_portal_audit_log PRIMARY KEY (id),
    CONSTRAINT fk_portal_audit_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
);
CREATE INDEX idx_portal_audit_account ON portal_audit_log (account_id, created_at DESC);


-- ---------------------------------------------------------------------
-- Staff-side module + permissions (administering the portal).
-- Customer-facing capabilities live in portal_capabilities and are NOT
-- permissions — a customer never holds an RBAC permission code.
-- ---------------------------------------------------------------------
INSERT INTO modules (code, name, description, icon, path, display_order, enabled, is_system)
VALUES ('portal', 'Customer Portal', 'Customer self-service accounts, requests and documents',
        'mdi-account-box-outline', '/portal', 170, TRUE, TRUE);

INSERT INTO permissions (module_id, action, code, name, is_system)
SELECT m.id, a.action, m.code || ':' || a.action, m.name || ' — ' || a.label, TRUE
FROM modules m
CROSS JOIN (VALUES
    ('view',            'View portal accounts'),
    ('create',          'Create and invite portal accounts'),
    ('edit',            'Edit portal accounts'),
    ('delete',          'Delete portal accounts'),
    ('manage-access',   'Suspend, lock and grant capabilities'),
    ('handle-requests', 'Handle self-service requests'),
    ('share-documents', 'Share documents with customers'),
    ('export',          'Export portal reports')
) AS a(action, label)
WHERE m.code = 'portal';
