-- =====================================================================
-- V23 — Business Calendar & Working Time Management (module 8)
--
-- Defines WHEN the business operates: working weeks, shifts, holidays and
-- one-off exceptions. It performs no scheduling of its own — the master
-- scheduler (V24) asks this module whether a proposed appointment window
-- is legal, and every other module routes date arithmetic through it
-- rather than reimplementing "is tomorrow a working day".
--
-- CALENDAR SYSTEMS. Iran runs on the Solar Hijri (Jalali) calendar while
-- imported data and integrations arrive as Gregorian. PostgreSQL and
-- java.time both lack a Persian chronology — java.time.chrono ships
-- HijrahChronology, which is the Islamic LUNAR calendar and drifts ~11
-- days a year against the solar one, so it is emphatically not a
-- substitute. Storage is therefore always a Gregorian DATE (the one
-- unambiguous wire format), and conversion is a Java SPI keyed by
-- `calendar_systems.handler_key`. Adding a third system is a row plus a
-- bean, never a migration.
--
-- RECURRING HOLIDAYS. Nowruz is 1 Farvardin every year, which lands on a
-- different Gregorian date annually. A recurring holiday therefore stores
-- its month/day in the system named by `calendar_system_id` and is
-- resolved to a concrete Gregorian date per query year. Storing the
-- Gregorian date would silently break in year two.
-- =====================================================================


-- ---------------------------------------------------------------------
-- Which chronologies the installation understands. `handler_key` resolves
-- to a CalendarSystem bean; a row whose key has no bean is inert rather
-- than fatal, matching the files/automation registries.
-- ---------------------------------------------------------------------
CREATE TABLE calendar_systems (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code           VARCHAR(64)  NOT NULL,
    name           VARCHAR(100) NOT NULL,
    handler_key    VARCHAR(64)  NOT NULL,
    -- Number of months; drives UI pickers without hardcoding 12.
    months_in_year SMALLINT     NOT NULL DEFAULT 12,
    is_default     BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order  INTEGER      NOT NULL DEFAULT 0,
    tenant_id      BIGINT,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_calendar_systems PRIMARY KEY (id),
    CONSTRAINT fk_calendar_systems_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_calendar_systems_code_global ON calendar_systems (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_calendar_systems_code_tenant ON calendar_systems (tenant_id, code) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_calendar_systems_default_global ON calendar_systems ((TRUE)) WHERE is_default AND tenant_id IS NULL;


-- ---------------------------------------------------------------------
-- A named working-time definition. Scoped to a company and optionally a
-- branch: NULL branch means "every branch of this company unless it has
-- its own". Resolution order is branch → company → tenant default, done
-- once in CalendarResolver so no caller repeats it.
-- ---------------------------------------------------------------------
CREATE TABLE business_calendars (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                VARCHAR(64)  NOT NULL,
    name                VARCHAR(255) NOT NULL,
    description         VARCHAR(500),

    company_id          BIGINT,
    branch_id           BIGINT,
    calendar_system_id  BIGINT       NOT NULL,

    timezone            VARCHAR(64)  NOT NULL DEFAULT 'Asia/Tehran',

    -- Default appointment granularity for schedules bound to this
    -- calendar. The scheduler may narrow it per resource, never widen it.
    slot_minutes        INTEGER      NOT NULL DEFAULT 30,

    is_default          BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active           BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order       INTEGER      NOT NULL DEFAULT 0,

    tenant_id           BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version             BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_business_calendars PRIMARY KEY (id),
    CONSTRAINT fk_business_calendars_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
    CONSTRAINT fk_business_calendars_branch FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE CASCADE,
    CONSTRAINT fk_business_calendars_system FOREIGN KEY (calendar_system_id) REFERENCES calendar_systems (id),
    CONSTRAINT fk_business_calendars_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT ck_business_calendars_slot CHECK (slot_minutes BETWEEN 1 AND 1440)
);
CREATE UNIQUE INDEX uq_business_calendars_code ON business_calendars (tenant_id, code);
CREATE UNIQUE INDEX uq_business_calendars_default ON business_calendars (tenant_id) WHERE is_default;
CREATE UNIQUE INDEX uq_business_calendars_branch ON business_calendars (branch_id) WHERE branch_id IS NOT NULL AND is_active;
CREATE INDEX ix_business_calendars_company ON business_calendars (company_id, is_active);


-- ---------------------------------------------------------------------
-- The weekly template. One row per weekday per calendar.
--
-- ISO-8601 numbering (1 = Monday … 7 = Sunday) is used deliberately: it
-- matches java.time.DayOfWeek.getValue() exactly, so no translation layer
-- can drift. Note the Iranian week is Saturday–Wednesday with Thursday
-- half-day and Friday the weekend, which the seed reflects.
-- ---------------------------------------------------------------------
CREATE TABLE calendar_working_days (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    calendar_id     BIGINT      NOT NULL,
    day_of_week     SMALLINT    NOT NULL,
    is_working_day  BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    version         BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT pk_calendar_working_days PRIMARY KEY (id),
    CONSTRAINT fk_calendar_working_days_calendar FOREIGN KEY (calendar_id) REFERENCES business_calendars (id) ON DELETE CASCADE,
    CONSTRAINT ck_calendar_working_days_dow CHECK (day_of_week BETWEEN 1 AND 7)
);
CREATE UNIQUE INDEX uq_calendar_working_days ON calendar_working_days (calendar_id, day_of_week);


-- ---------------------------------------------------------------------
-- Working windows within a day. Multiple shifts per weekday express a
-- lunch closure as two shifts rather than a nullable break pair, which
-- generalises to any number of gaps.
--
-- `day_of_week` NULL means the shift applies to every working day of the
-- calendar — the common case, entered once.
-- ---------------------------------------------------------------------
CREATE TABLE calendar_shifts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    calendar_id         BIGINT       NOT NULL,
    code                VARCHAR(64)  NOT NULL,
    name                VARCHAR(100) NOT NULL,
    day_of_week         SMALLINT,
    start_time          TIME         NOT NULL,
    end_time            TIME         NOT NULL,

    -- Capacity hint for the scheduler: how many concurrent appointments
    -- this window supports before a resource must be added. 0 = unlimited.
    max_concurrent      INTEGER      NOT NULL DEFAULT 0,

    is_overtime         BOOLEAN      NOT NULL DEFAULT FALSE,
    is_bookable         BOOLEAN      NOT NULL DEFAULT TRUE,
    is_active           BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order       INTEGER      NOT NULL DEFAULT 0,

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version             BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_calendar_shifts PRIMARY KEY (id),
    CONSTRAINT fk_calendar_shifts_calendar FOREIGN KEY (calendar_id) REFERENCES business_calendars (id) ON DELETE CASCADE,
    CONSTRAINT ck_calendar_shifts_dow CHECK (day_of_week IS NULL OR day_of_week BETWEEN 1 AND 7),
    -- Overnight shifts are modelled as two rows, so end must follow start.
    CONSTRAINT ck_calendar_shifts_order CHECK (end_time > start_time),
    CONSTRAINT ck_calendar_shifts_concurrent CHECK (max_concurrent >= 0)
);
CREATE UNIQUE INDEX uq_calendar_shifts_code ON calendar_shifts (calendar_id, code);
CREATE INDEX ix_calendar_shifts_lookup ON calendar_shifts (calendar_id, day_of_week) WHERE is_active;


-- ---------------------------------------------------------------------
-- Holiday classification. `is_working_day` lets a "holiday" still be a
-- working day (a commemorative day the shop stays open for), and
-- `blocks_appointments` is what the scheduler actually reads — the two
-- are separable: a branch may work an inventory-audit day without
-- accepting customer bookings.
-- ---------------------------------------------------------------------
CREATE TABLE holiday_types (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                 VARCHAR(64)  NOT NULL,
    name                 VARCHAR(100) NOT NULL,
    is_working_day       BOOLEAN      NOT NULL DEFAULT FALSE,
    blocks_appointments  BOOLEAN      NOT NULL DEFAULT TRUE,
    is_paid              BOOLEAN      NOT NULL DEFAULT TRUE,
    is_default           BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system            BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order        INTEGER      NOT NULL DEFAULT 0,
    tenant_id            BIGINT,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version              BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_holiday_types PRIMARY KEY (id),
    CONSTRAINT fk_holiday_types_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_holiday_types_code_global ON holiday_types (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_holiday_types_code_tenant ON holiday_types (tenant_id, code) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_holiday_types_default_global ON holiday_types ((TRUE)) WHERE is_default AND tenant_id IS NULL;


-- ---------------------------------------------------------------------
-- Holidays. Either a fixed Gregorian date (`holiday_date`) or an annual
-- recurrence expressed in `recurrence_system_id`'s chronology
-- (`recurrence_month` / `recurrence_day`). Exactly one form, enforced.
--
-- `calendar_id` NULL means the holiday applies to every calendar in the
-- tenant — national holidays are entered once.
-- ---------------------------------------------------------------------
CREATE TABLE holidays (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    calendar_id          BIGINT,
    holiday_type_id      BIGINT       NOT NULL,

    name                 VARCHAR(255) NOT NULL,
    description          VARCHAR(500),

    holiday_date         DATE,

    is_recurring         BOOLEAN      NOT NULL DEFAULT FALSE,
    recurrence_system_id BIGINT,
    recurrence_month     SMALLINT,
    recurrence_day       SMALLINT,

    -- Multi-day observances (Nowruz runs 1–4 Farvardin) without four rows.
    duration_days        INTEGER      NOT NULL DEFAULT 1,

    -- Half-day working: NULL means the type's is_working_day governs.
    half_day_start       TIME,
    half_day_end         TIME,

    is_active            BOOLEAN      NOT NULL DEFAULT TRUE,

    tenant_id            BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version              BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_holidays PRIMARY KEY (id),
    CONSTRAINT fk_holidays_calendar FOREIGN KEY (calendar_id) REFERENCES business_calendars (id) ON DELETE CASCADE,
    CONSTRAINT fk_holidays_type FOREIGN KEY (holiday_type_id) REFERENCES holiday_types (id),
    CONSTRAINT fk_holidays_recurrence_system FOREIGN KEY (recurrence_system_id) REFERENCES calendar_systems (id),
    CONSTRAINT fk_holidays_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT ck_holidays_duration CHECK (duration_days BETWEEN 1 AND 366),
    CONSTRAINT ck_holidays_month CHECK (recurrence_month IS NULL OR recurrence_month BETWEEN 1 AND 12),
    CONSTRAINT ck_holidays_day CHECK (recurrence_day IS NULL OR recurrence_day BETWEEN 1 AND 31),
    -- Exactly one of: a fixed date, or a complete recurrence rule.
    CONSTRAINT ck_holidays_form CHECK (
        (is_recurring = FALSE AND holiday_date IS NOT NULL
             AND recurrence_month IS NULL AND recurrence_day IS NULL)
        OR
        (is_recurring = TRUE AND recurrence_system_id IS NOT NULL
             AND recurrence_month IS NOT NULL AND recurrence_day IS NOT NULL)
    ),
    CONSTRAINT ck_holidays_half_day CHECK (
        (half_day_start IS NULL AND half_day_end IS NULL)
        OR (half_day_start IS NOT NULL AND half_day_end IS NOT NULL AND half_day_end > half_day_start)
    )
);
CREATE INDEX ix_holidays_date ON holidays (holiday_date) WHERE holiday_date IS NOT NULL AND is_active;
CREATE INDEX ix_holidays_recurring ON holidays (recurrence_month, recurrence_day) WHERE is_recurring AND is_active;
CREATE INDEX ix_holidays_calendar ON holidays (calendar_id, is_active);
CREATE INDEX ix_holidays_tenant ON holidays (tenant_id);


-- ---------------------------------------------------------------------
-- Date-specific overrides that ADD or REMOVE working time: late opening
-- for a stocktake, extra Friday trading before Nowruz, an unscheduled
-- closure. Distinct from holidays because an exception can make a
-- non-working day workable, which a holiday can never do.
--
-- Highest precedence in WorkingTimeService: exception > holiday > weekly
-- template.
-- ---------------------------------------------------------------------
CREATE TABLE calendar_exceptions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    calendar_id     BIGINT       NOT NULL,
    exception_date  DATE         NOT NULL,
    name            VARCHAR(255) NOT NULL,
    reason          VARCHAR(500),

    is_working_day  BOOLEAN      NOT NULL,
    -- NULL start/end on a working exception means "use the normal shifts".
    start_time      TIME,
    end_time        TIME,

    blocks_appointments BOOLEAN  NOT NULL DEFAULT FALSE,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,

    created_by      BIGINT,
    tenant_id       BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version         BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_calendar_exceptions PRIMARY KEY (id),
    CONSTRAINT fk_calendar_exceptions_calendar FOREIGN KEY (calendar_id) REFERENCES business_calendars (id) ON DELETE CASCADE,
    CONSTRAINT fk_calendar_exceptions_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT ck_calendar_exceptions_times CHECK (
        (start_time IS NULL AND end_time IS NULL)
        OR (start_time IS NOT NULL AND end_time IS NOT NULL AND end_time > start_time)
    )
);
CREATE UNIQUE INDEX uq_calendar_exceptions ON calendar_exceptions (calendar_id, exception_date);
CREATE INDEX ix_calendar_exceptions_date ON calendar_exceptions (exception_date) WHERE is_active;


-- =====================================================================
-- Seed
-- =====================================================================

INSERT INTO calendar_systems (code, name, handler_key, months_in_year, is_default, is_system, display_order)
VALUES
    ('PERSIAN',   'Solar Hijri (Jalali)', 'persian',   12, TRUE,  TRUE, 10),
    ('GREGORIAN', 'Gregorian',            'gregorian', 12, FALSE, TRUE, 20);

INSERT INTO holiday_types (code, name, is_working_day, blocks_appointments, is_paid, is_default, is_system, display_order)
VALUES
    ('PUBLIC',      'Public Holiday',      FALSE, TRUE,  TRUE,  TRUE,  TRUE, 10),
    ('RELIGIOUS',   'Religious Holiday',   FALSE, TRUE,  TRUE,  FALSE, TRUE, 20),
    ('NATIONAL',    'National Holiday',    FALSE, TRUE,  TRUE,  FALSE, TRUE, 30),
    ('COMPANY',     'Company Closure',     FALSE, TRUE,  TRUE,  FALSE, TRUE, 40),
    ('BRANCH',      'Branch Closure',      FALSE, TRUE,  FALSE, FALSE, TRUE, 50),
    ('OBSERVANCE',  'Observance',          TRUE,  FALSE, TRUE,  FALSE, TRUE, 60),
    ('MAINTENANCE', 'Scheduled Maintenance', TRUE, TRUE, TRUE,  FALSE, TRUE, 70);

-- Default calendar for the seeded company: Iranian working week.
INSERT INTO business_calendars (code, name, description, company_id, calendar_system_id,
                                timezone, slot_minutes, is_default, is_active, display_order)
SELECT 'DEFAULT', 'Default Business Calendar', 'Saturday–Thursday trading, Friday weekend',
       c.id, cs.id, 'Asia/Tehran', 30, TRUE, TRUE, 10
FROM companies c CROSS JOIN calendar_systems cs
WHERE c.code = 'DEFAULT' AND cs.code = 'PERSIAN';

-- ISO weekdays: 1 Mon, 2 Tue, 3 Wed, 4 Thu, 5 Fri, 6 Sat, 7 Sun.
-- Friday (5) is the Iranian weekend; every other day trades.
INSERT INTO calendar_working_days (calendar_id, day_of_week, is_working_day)
SELECT bc.id, d.dow, d.working
FROM business_calendars bc
CROSS JOIN (VALUES (1, TRUE), (2, TRUE), (3, TRUE), (4, TRUE),
                   (5, FALSE), (6, TRUE), (7, TRUE)) AS d(dow, working)
WHERE bc.code = 'DEFAULT';

INSERT INTO calendar_shifts (calendar_id, code, name, day_of_week, start_time, end_time,
                             max_concurrent, is_overtime, is_bookable, is_active, display_order)
SELECT bc.id, s.code, s.name, s.dow, s.st, s.et, 0, FALSE, TRUE, TRUE, s.ord
FROM business_calendars bc
CROSS JOIN (VALUES
    ('MORNING',   'Morning',        NULL::SMALLINT, TIME '09:00', TIME '13:00', 10),
    ('AFTERNOON', 'Afternoon',      NULL::SMALLINT, TIME '16:00', TIME '20:00', 20),
    ('THU_SHORT', 'Thursday Short', 4::SMALLINT,    TIME '09:00', TIME '13:00', 30)
) AS s(code, name, dow, st, et, ord)
WHERE bc.code = 'DEFAULT';

-- Recurring Persian national holidays. Dates are Farvardin/Khordad in the
-- Solar Hijri calendar and resolve to a different Gregorian day each year.
INSERT INTO holidays (calendar_id, holiday_type_id, name, is_recurring,
                      recurrence_system_id, recurrence_month, recurrence_day, duration_days)
SELECT NULL, ht.id, h.name, TRUE, cs.id, h.mon, h.day, h.dur
FROM holiday_types ht
CROSS JOIN calendar_systems cs
CROSS JOIN (VALUES
    ('Nowruz',                       1, 1,  4),
    ('Islamic Republic Day',         1, 12, 1),
    ('Sizdah Bedar (Nature Day)',    1, 13, 1),
    ('Death of Imam Khomeini',       3, 14, 1),
    ('Khordad National Uprising',    3, 15, 1)
) AS h(name, mon, day, dur)
WHERE ht.code = 'NATIONAL' AND cs.code = 'PERSIAN';


-- =====================================================================
-- Module registration and permissions
-- =====================================================================

INSERT INTO modules (code, name, description, icon, path, display_order, enabled, is_system)
VALUES ('calendar', 'Business Calendar', 'Working calendars, shifts and holidays',
        'mdi-calendar-clock-outline', '/calendar', 170, TRUE, TRUE);

INSERT INTO permissions (module_id, action, code, name, is_system)
SELECT m.id, a.action, m.code || ':' || a.action, m.name || ' — ' || a.label, TRUE
FROM modules m
CROSS JOIN (VALUES
    ('view',             'View calendars'),
    ('create',           'Create calendars'),
    ('edit',             'Edit calendars and shifts'),
    ('delete',           'Delete calendars'),
    ('manage-holidays',  'Manage holidays'),
    ('manage-exceptions','Manage calendar exceptions')
) AS a(action, label)
WHERE m.code = 'calendar';


-- =====================================================================
-- Post-migration assertions
-- =====================================================================

DO $$
DECLARE
    cal_id  BIGINT;
    dow_cnt BIGINT;
    sys_cnt BIGINT;
BEGIN
    SELECT id INTO cal_id FROM business_calendars WHERE code = 'DEFAULT';
    IF cal_id IS NULL THEN
        RAISE EXCEPTION 'V23: default business calendar was not created';
    END IF;

    SELECT count(*) INTO dow_cnt FROM calendar_working_days WHERE calendar_id = cal_id;
    IF dow_cnt <> 7 THEN
        RAISE EXCEPTION 'V23: expected 7 weekday rows for the default calendar, found %', dow_cnt;
    END IF;

    SELECT count(*) INTO sys_cnt FROM calendar_systems WHERE is_default;
    IF sys_cnt <> 1 THEN
        RAISE EXCEPTION 'V23: expected exactly 1 default calendar system, found %', sys_cnt;
    END IF;
END $$;
