-- =====================================================================
-- V24 — Enterprise Master Scheduler, Resource Reservation & Appointment
--       Management
--
-- Centralised scheduling of appointments, reservations and shared
-- resources. This is NOT the background job scheduler (V19, which runs
-- @Scheduled work) and NOT the business calendar (V23, which defines when
-- the business is open). This module books business activities INTO the
-- time V23 declares available.
--
-- ---------------------------------------------------------------------
-- THE CENTRAL DESIGN DECISION: double booking is prevented by the
-- database, not by service code.
--
-- The spec's "concurrent reservation requests" edge case cannot be solved
-- with a SELECT-then-INSERT availability check at any isolation level
-- below SERIALIZABLE: two transactions both read "free", both write, and
-- the technician is double-booked. Application-level locking would need a
-- lock per resource held across the whole booking transaction.
--
-- Instead `reservations` carries a GiST exclusion constraint over
-- (resource_id, [starts_at, ends_at)). Postgres rejects the second
-- overlapping insert outright, whatever the interleaving, and the service
-- translates that violation into a domain conflict. Correctness does not
-- depend on any caller remembering to check first.
--
-- The constraint is predicated on `holds_resource`, so cancelled and
-- no-show reservations stop occupying the slot without being deleted —
-- history is preserved, which "Reservation History" requires.
-- ---------------------------------------------------------------------
--
-- Behaviour is data throughout: statuses, appointment types, resource
-- categories, conflict policies and reminder channels are configuration
-- rows with behavioural flags. Adding "Video Consultation" is an INSERT.
-- =====================================================================

-- Required for an exclusion constraint mixing equality on a scalar with
-- range overlap; plain GiST cannot index bigint equality on its own.
CREATE EXTENSION IF NOT EXISTS btree_gist;


-- =====================================================================
-- Configuration
-- =====================================================================

-- ---------------------------------------------------------------------
-- Appointment lifecycle. `blocks_resource` is the flag the exclusion
-- constraint ultimately keys off: it is what makes a status occupy time.
-- ---------------------------------------------------------------------
CREATE TABLE schedule_statuses (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                  VARCHAR(64)  NOT NULL,
    name                  VARCHAR(100) NOT NULL,
    color                 VARCHAR(16),

    is_default            BOOLEAN      NOT NULL DEFAULT FALSE,
    is_draft_state        BOOLEAN      NOT NULL DEFAULT FALSE,
    is_confirmed_state    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_checked_in_state   BOOLEAN      NOT NULL DEFAULT FALSE,
    is_in_progress_state  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_completed_state    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_cancelled_state    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_no_show_state      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_archived_state     BOOLEAN      NOT NULL DEFAULT FALSE,

    -- Does an appointment in this status occupy its resources?
    blocks_resource       BOOLEAN      NOT NULL DEFAULT TRUE,
    allows_edit           BOOLEAN      NOT NULL DEFAULT TRUE,
    allows_cancel         BOOLEAN      NOT NULL DEFAULT TRUE,
    allows_check_in       BOOLEAN      NOT NULL DEFAULT FALSE,
    is_terminal           BOOLEAN      NOT NULL DEFAULT FALSE,
    counts_as_attended    BOOLEAN      NOT NULL DEFAULT FALSE,

    is_system             BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order         INTEGER      NOT NULL DEFAULT 0,
    tenant_id             BIGINT,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version               BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_schedule_statuses PRIMARY KEY (id),
    CONSTRAINT fk_schedule_statuses_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_schedule_statuses_code_global ON schedule_statuses (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_schedule_statuses_code_tenant ON schedule_statuses (tenant_id, code) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_schedule_statuses_default_global ON schedule_statuses ((TRUE)) WHERE is_default AND tenant_id IS NULL;


CREATE TABLE schedule_categories (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code           VARCHAR(64)  NOT NULL,
    name           VARCHAR(100) NOT NULL,
    description    VARCHAR(500),
    icon           VARCHAR(64),
    color          VARCHAR(16),
    is_default     BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order  INTEGER      NOT NULL DEFAULT 0,
    tenant_id      BIGINT,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_schedule_categories PRIMARY KEY (id),
    CONSTRAINT fk_schedule_categories_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_schedule_categories_code_global ON schedule_categories (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_schedule_categories_code_tenant ON schedule_categories (tenant_id, code) WHERE tenant_id IS NOT NULL;


-- ---------------------------------------------------------------------
-- What kind of appointment this is, and the rules that follow from it.
--
-- `subject_provider_key` binds the type to a ScheduleSubjectProvider SPI
-- bean: 'repair' resolves a repair order, 'trade_in' a valuation. A type
-- whose provider has no bean still books — it simply carries no linked
-- business record. That is what lets repair appointments be configured
-- today and become live the day a repair module ships, with no migration.
-- ---------------------------------------------------------------------
CREATE TABLE appointment_types (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                    VARCHAR(64)  NOT NULL,
    name                    VARCHAR(100) NOT NULL,
    description             VARCHAR(500),
    category_id             BIGINT,

    -- Timing. Buffers are reserved on the resource but are not customer
    -- time, which is why they are separate from duration.
    default_duration_minutes INTEGER     NOT NULL DEFAULT 30,
    min_duration_minutes     INTEGER     NOT NULL DEFAULT 15,
    max_duration_minutes     INTEGER     NOT NULL DEFAULT 480,
    preparation_minutes      INTEGER     NOT NULL DEFAULT 0,
    cleanup_minutes          INTEGER     NOT NULL DEFAULT 0,
    buffer_before_minutes    INTEGER     NOT NULL DEFAULT 0,
    buffer_after_minutes     INTEGER     NOT NULL DEFAULT 0,

    -- Booking rules.
    requires_customer        BOOLEAN     NOT NULL DEFAULT FALSE,
    requires_supplier        BOOLEAN     NOT NULL DEFAULT FALSE,
    requires_resource        BOOLEAN     NOT NULL DEFAULT TRUE,
    requires_approval        BOOLEAN     NOT NULL DEFAULT FALSE,
    allows_waiting_list      BOOLEAN     NOT NULL DEFAULT TRUE,
    allows_self_service      BOOLEAN     NOT NULL DEFAULT FALSE,
    allows_overbooking       BOOLEAN     NOT NULL DEFAULT FALSE,
    enforce_working_hours    BOOLEAN     NOT NULL DEFAULT TRUE,

    -- How far ahead bookings open, and how late they may be made/cancelled.
    max_advance_days         INTEGER     NOT NULL DEFAULT 90,
    min_notice_minutes       INTEGER     NOT NULL DEFAULT 0,
    cancellation_notice_minutes INTEGER  NOT NULL DEFAULT 0,

    -- Minutes after start_time before an arrival counts as late; and after
    -- which an unarrived appointment may be auto-marked no-show.
    late_threshold_minutes   INTEGER     NOT NULL DEFAULT 15,
    no_show_threshold_minutes INTEGER    NOT NULL DEFAULT 30,

    subject_provider_key     VARCHAR(64),
    module_code              VARCHAR(64),
    color                    VARCHAR(16),

    is_default               BOOLEAN     NOT NULL DEFAULT FALSE,
    is_system                BOOLEAN     NOT NULL DEFAULT FALSE,
    is_active                BOOLEAN     NOT NULL DEFAULT TRUE,
    display_order            INTEGER     NOT NULL DEFAULT 0,

    tenant_id                BIGINT,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    version                  BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT pk_appointment_types PRIMARY KEY (id),
    CONSTRAINT fk_appointment_types_category FOREIGN KEY (category_id) REFERENCES schedule_categories (id) ON DELETE SET NULL,
    CONSTRAINT fk_appointment_types_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT ck_appointment_types_duration CHECK (
        default_duration_minutes > 0
        AND min_duration_minutes > 0
        AND max_duration_minutes >= min_duration_minutes
        AND default_duration_minutes BETWEEN min_duration_minutes AND max_duration_minutes),
    CONSTRAINT ck_appointment_types_buffers CHECK (
        preparation_minutes >= 0 AND cleanup_minutes >= 0
        AND buffer_before_minutes >= 0 AND buffer_after_minutes >= 0)
);
CREATE UNIQUE INDEX uq_appointment_types_code_global ON appointment_types (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_appointment_types_code_tenant ON appointment_types (tenant_id, code) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_appointment_types_default_global ON appointment_types ((TRUE)) WHERE is_default AND tenant_id IS NULL;


CREATE TABLE resource_categories (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                 VARCHAR(64)  NOT NULL,
    name                 VARCHAR(100) NOT NULL,
    description          VARCHAR(500),
    icon                 VARCHAR(64),

    -- A human resource is schedulable against skills and shifts; a room is
    -- not. Services read these, never the category code.
    is_human             BOOLEAN      NOT NULL DEFAULT FALSE,
    is_physical_space    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_equipment         BOOLEAN      NOT NULL DEFAULT FALSE,
    supports_capacity    BOOLEAN      NOT NULL DEFAULT FALSE,
    requires_skill_match BOOLEAN      NOT NULL DEFAULT FALSE,

    is_default           BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system            BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active            BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order        INTEGER      NOT NULL DEFAULT 0,
    tenant_id            BIGINT,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version              BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_resource_categories PRIMARY KEY (id),
    CONSTRAINT fk_resource_categories_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_resource_categories_code_global ON resource_categories (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_resource_categories_code_tenant ON resource_categories (tenant_id, code) WHERE tenant_id IS NOT NULL;


CREATE TABLE resource_statuses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code            VARCHAR(64)  NOT NULL,
    name            VARCHAR(100) NOT NULL,
    color           VARCHAR(16),
    -- `allows_booking` is the operative flag: a resource in Maintenance
    -- keeps its existing reservations but accepts no new ones.
    allows_booking  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_available    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_default      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system       BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order   INTEGER      NOT NULL DEFAULT 0,
    tenant_id       BIGINT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_resource_statuses PRIMARY KEY (id),
    CONSTRAINT fk_resource_statuses_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_resource_statuses_code_global ON resource_statuses (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_resource_statuses_code_tenant ON resource_statuses (tenant_id, code) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_resource_statuses_default_global ON resource_statuses ((TRUE)) WHERE is_default AND tenant_id IS NULL;


-- ---------------------------------------------------------------------
-- How a booking conflict is handled. `handler_key` resolves to a
-- ConflictResolutionStrategy bean, so "suggest the next free slot" and
-- "escalate to a manager" are configuration, not branches in a service.
-- ---------------------------------------------------------------------
CREATE TABLE conflict_policies (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code               VARCHAR(64)  NOT NULL,
    name               VARCHAR(100) NOT NULL,
    description        VARCHAR(500),
    handler_key        VARCHAR(64)  NOT NULL,
    -- Reject outright, or record and continue with a warning.
    is_blocking        BOOLEAN      NOT NULL DEFAULT TRUE,
    suggests_alternatives BOOLEAN   NOT NULL DEFAULT FALSE,
    requires_approval  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_default         BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system          BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active          BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order      INTEGER      NOT NULL DEFAULT 0,
    tenant_id          BIGINT,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version            BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_conflict_policies PRIMARY KEY (id),
    CONSTRAINT fk_conflict_policies_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_conflict_policies_code_global ON conflict_policies (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_conflict_policies_code_tenant ON conflict_policies (tenant_id, code) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_conflict_policies_default_global ON conflict_policies ((TRUE)) WHERE is_default AND tenant_id IS NULL;


-- ---------------------------------------------------------------------
-- Reminder delivery channels. `handler_key` resolves to a ReminderChannel
-- bean. Every channel is seeded INACTIVE because no notification module
-- exists yet (module 5 in the platform map) — the catalogue is complete
-- and the wiring is a one-line flip when it lands. An active channel with
-- no bean logs and is skipped; it never fails a booking.
-- ---------------------------------------------------------------------
CREATE TABLE reminder_channels (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code           VARCHAR(64)  NOT NULL,
    name           VARCHAR(100) NOT NULL,
    handler_key    VARCHAR(64)  NOT NULL,
    requires_phone BOOLEAN      NOT NULL DEFAULT FALSE,
    requires_email BOOLEAN      NOT NULL DEFAULT FALSE,
    is_default     BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active      BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order  INTEGER      NOT NULL DEFAULT 0,
    tenant_id      BIGINT,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_reminder_channels PRIMARY KEY (id),
    CONSTRAINT fk_reminder_channels_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_reminder_channels_code_global ON reminder_channels (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_reminder_channels_code_tenant ON reminder_channels (tenant_id, code) WHERE tenant_id IS NOT NULL;


-- =====================================================================
-- Resources
-- =====================================================================

CREATE TABLE resources (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    resource_code       VARCHAR(64)  NOT NULL,
    name                VARCHAR(255) NOT NULL,
    description         VARCHAR(500),

    category_id         BIGINT       NOT NULL,
    status_id           BIGINT       NOT NULL,

    company_id          BIGINT,
    branch_id           BIGINT,

    -- A resource may follow its own calendar (a technician's roster);
    -- NULL inherits the branch calendar via WorkingTimeProvider.
    calendar_id         BIGINT,

    -- Set when the resource IS a system user (technician, salesperson).
    -- Nullable because rooms and benches are nobody.
    user_id             BIGINT,

    -- How many appointments this resource serves at once. 1 is the norm;
    -- a training room might be 12.
    capacity            INTEGER      NOT NULL DEFAULT 1,

    -- Higher wins when the allocator picks among equally free resources.
    priority            INTEGER      NOT NULL DEFAULT 0,

    -- Free-form skills, matched when the category requires it. A tag list
    -- rather than a table because skills are configuration-light and this
    -- module must not become an HR system.
    skills              JSONB,

    is_bookable_online  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active           BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order       INTEGER      NOT NULL DEFAULT 0,

    tenant_id           BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version             BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_resources PRIMARY KEY (id),
    CONSTRAINT fk_resources_category FOREIGN KEY (category_id) REFERENCES resource_categories (id),
    CONSTRAINT fk_resources_status FOREIGN KEY (status_id) REFERENCES resource_statuses (id),
    CONSTRAINT fk_resources_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE SET NULL,
    CONSTRAINT fk_resources_branch FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE SET NULL,
    CONSTRAINT fk_resources_calendar FOREIGN KEY (calendar_id) REFERENCES business_calendars (id) ON DELETE SET NULL,
    CONSTRAINT fk_resources_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_resources_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT ck_resources_capacity CHECK (capacity >= 1)
);
CREATE UNIQUE INDEX uq_resources_code ON resources (tenant_id, resource_code);
CREATE INDEX ix_resources_branch ON resources (branch_id, is_active);
CREATE INDEX ix_resources_category ON resources (category_id, is_active);
CREATE INDEX ix_resources_user ON resources (user_id) WHERE user_id IS NOT NULL;
CREATE INDEX ix_resources_skills ON resources USING gin (skills) WHERE skills IS NOT NULL;


-- =====================================================================
-- Schedules (appointments)
-- =====================================================================

CREATE TABLE schedules (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    schedule_number     VARCHAR(32)  NOT NULL,
    title               VARCHAR(255) NOT NULL,
    description         VARCHAR(2000),

    category_id         BIGINT,
    appointment_type_id BIGINT       NOT NULL,
    status_id           BIGINT       NOT NULL,

    company_id          BIGINT,
    branch_id           BIGINT,
    calendar_id         BIGINT,

    -- Generic binding to the originating business record, resolved through
    -- the ScheduleSubjectProvider SPI. Deliberately NOT a foreign key:
    -- the repair and trade-in modules do not exist yet, and this module
    -- must not acquire a hard dependency on them when they do.
    module_code         VARCHAR(64),
    related_entity_type VARCHAR(64),
    related_entity_id   BIGINT,

    customer_id         BIGINT,
    supplier_id         BIGINT,

    starts_at           TIMESTAMPTZ  NOT NULL,
    ends_at             TIMESTAMPTZ  NOT NULL,
    duration_minutes    INTEGER      GENERATED ALWAYS AS
                            ((EXTRACT(EPOCH FROM (ends_at - starts_at)) / 60)::INTEGER) STORED,

    -- Higher is more important; drives waiting-list promotion order.
    priority            INTEGER      NOT NULL DEFAULT 0,

    -- Attendance.
    checked_in_at       TIMESTAMPTZ,
    checked_out_at      TIMESTAMPTZ,
    arrived_late        BOOLEAN      NOT NULL DEFAULT FALSE,
    late_by_minutes     INTEGER,
    completion_notes    VARCHAR(2000),

    cancelled_at        TIMESTAMPTZ,
    cancellation_reason VARCHAR(500),
    cancelled_by        BIGINT,

    confirmed_at        TIMESTAMPTZ,
    -- Set when the booking came from a self-service surface rather than
    -- staff, which reporting and no-show policy treat differently.
    source_channel      VARCHAR(32)  NOT NULL DEFAULT 'STAFF',

    created_by          BIGINT,
    created_by_email    VARCHAR(255),

    tenant_id           BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version             BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_schedules PRIMARY KEY (id),
    CONSTRAINT fk_schedules_category FOREIGN KEY (category_id) REFERENCES schedule_categories (id) ON DELETE SET NULL,
    CONSTRAINT fk_schedules_type FOREIGN KEY (appointment_type_id) REFERENCES appointment_types (id),
    CONSTRAINT fk_schedules_status FOREIGN KEY (status_id) REFERENCES schedule_statuses (id),
    CONSTRAINT fk_schedules_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE SET NULL,
    CONSTRAINT fk_schedules_branch FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE SET NULL,
    CONSTRAINT fk_schedules_calendar FOREIGN KEY (calendar_id) REFERENCES business_calendars (id) ON DELETE SET NULL,
    CONSTRAINT fk_schedules_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE SET NULL,
    CONSTRAINT fk_schedules_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id) ON DELETE SET NULL,
    CONSTRAINT fk_schedules_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT ck_schedules_window CHECK (ends_at > starts_at),
    CONSTRAINT ck_schedules_checkout CHECK (checked_out_at IS NULL OR checked_in_at IS NOT NULL)
);
CREATE UNIQUE INDEX uq_schedules_number ON schedules (tenant_id, schedule_number);
CREATE INDEX ix_schedules_window ON schedules (starts_at, ends_at);
CREATE INDEX ix_schedules_branch_day ON schedules (branch_id, starts_at);
CREATE INDEX ix_schedules_customer ON schedules (customer_id, starts_at) WHERE customer_id IS NOT NULL;
CREATE INDEX ix_schedules_supplier ON schedules (supplier_id, starts_at) WHERE supplier_id IS NOT NULL;
CREATE INDEX ix_schedules_status ON schedules (status_id, starts_at);
CREATE INDEX ix_schedules_related ON schedules (module_code, related_entity_type, related_entity_id)
    WHERE related_entity_id IS NOT NULL;
CREATE INDEX ix_schedules_tenant ON schedules (tenant_id);

CREATE SEQUENCE schedule_number_seq START WITH 1000 INCREMENT BY 1;


-- ---------------------------------------------------------------------
-- Reservations: a resource occupied for a span.
--
-- A schedule normally produces one reservation per required resource
-- (technician + repair bench). `schedule_id` is nullable so a resource can
-- also be blocked WITHOUT an appointment — maintenance, annual leave, a
-- room held for a private event — which the "resource goes out of service"
-- edge case needs.
--
-- `starts_at`/`ends_at` here include the appointment type's preparation,
-- cleanup and buffer minutes. That is why they are stored separately from
-- the schedule's own window rather than being derived: the resource is
-- genuinely busy longer than the customer is present, and the overlap
-- check must use the longer span.
-- ---------------------------------------------------------------------
CREATE TABLE reservations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    reservation_number  VARCHAR(32)  NOT NULL,
    schedule_id         BIGINT,
    resource_id         BIGINT       NOT NULL,
    status_id           BIGINT       NOT NULL,

    starts_at           TIMESTAMPTZ  NOT NULL,
    ends_at             TIMESTAMPTZ  NOT NULL,
    duration_minutes    INTEGER      GENERATED ALWAYS AS
                            ((EXTRACT(EPOCH FROM (ends_at - starts_at)) / 60)::INTEGER) STORED,

    -- Denormalised from the status so the exclusion constraint has an
    -- immutable column to predicate on. Kept in step by ReservationService
    -- whenever the status changes; the assertion at the end of this
    -- migration and a unit test both guard the invariant.
    holds_resource      BOOLEAN      NOT NULL DEFAULT TRUE,

    purpose             VARCHAR(500),
    priority            INTEGER      NOT NULL DEFAULT 0,
    is_maintenance      BOOLEAN      NOT NULL DEFAULT FALSE,

    customer_id         BIGINT,
    supplier_id         BIGINT,
    employee_user_id    BIGINT,

    released_at         TIMESTAMPTZ,
    release_reason      VARCHAR(500),

    created_by          BIGINT,
    tenant_id           BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version             BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_reservations PRIMARY KEY (id),
    CONSTRAINT fk_reservations_schedule FOREIGN KEY (schedule_id) REFERENCES schedules (id) ON DELETE CASCADE,
    CONSTRAINT fk_reservations_resource FOREIGN KEY (resource_id) REFERENCES resources (id) ON DELETE CASCADE,
    CONSTRAINT fk_reservations_status FOREIGN KEY (status_id) REFERENCES schedule_statuses (id),
    CONSTRAINT fk_reservations_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE SET NULL,
    CONSTRAINT fk_reservations_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id) ON DELETE SET NULL,
    CONSTRAINT fk_reservations_employee FOREIGN KEY (employee_user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_reservations_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT ck_reservations_window CHECK (ends_at > starts_at)
);
CREATE UNIQUE INDEX uq_reservations_number ON reservations (tenant_id, reservation_number);
CREATE INDEX ix_reservations_resource_window ON reservations (resource_id, starts_at, ends_at);
CREATE INDEX ix_reservations_schedule ON reservations (schedule_id) WHERE schedule_id IS NOT NULL;
CREATE INDEX ix_reservations_tenant ON reservations (tenant_id);

-- -------------------------------------------------------------------
-- THE constraint. Two live reservations may never overlap on the same
-- resource. '[)' makes the range half-open so a 10:00–11:00 booking and
-- an 11:00–12:00 booking do NOT collide — back-to-back appointments are
-- the normal case and must remain legal.
--
-- Released, cancelled and no-show rows set holds_resource = FALSE and
-- drop out of the constraint while staying in the table for history.
-- -------------------------------------------------------------------
ALTER TABLE reservations ADD CONSTRAINT ex_reservations_no_double_booking
    EXCLUDE USING gist (
        resource_id WITH =,
        tstzrange(starts_at, ends_at, '[)') WITH &&
    ) WHERE (holds_resource);


-- ---------------------------------------------------------------------
-- Waiting list. An entry is a standing request for a slot that was not
-- free; promotion turns it into a real schedule.
-- ---------------------------------------------------------------------
CREATE TABLE waiting_list_entries (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    entry_number        VARCHAR(32)  NOT NULL,
    appointment_type_id BIGINT       NOT NULL,

    customer_id         BIGINT,
    supplier_id         BIGINT,
    branch_id           BIGINT,
    -- Optional: the specific resource asked for. NULL means any suitable.
    resource_id         BIGINT,

    -- The window the requester will accept.
    desired_from        TIMESTAMPTZ  NOT NULL,
    desired_to          TIMESTAMPTZ  NOT NULL,
    duration_minutes    INTEGER      NOT NULL,

    priority            INTEGER      NOT NULL DEFAULT 0,
    notes               VARCHAR(500),

    -- Lifecycle. Promotion is recorded rather than deleting the row, so
    -- "how long did people wait" remains answerable.
    is_active           BOOLEAN      NOT NULL DEFAULT TRUE,
    promoted_at         TIMESTAMPTZ,
    promoted_schedule_id BIGINT,
    promoted_manually   BOOLEAN      NOT NULL DEFAULT FALSE,
    expires_at          TIMESTAMPTZ,
    cancelled_at        TIMESTAMPTZ,
    cancellation_reason VARCHAR(500),

    created_by          BIGINT,
    tenant_id           BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version             BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_waiting_list_entries PRIMARY KEY (id),
    CONSTRAINT fk_waiting_list_type FOREIGN KEY (appointment_type_id) REFERENCES appointment_types (id),
    CONSTRAINT fk_waiting_list_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE,
    CONSTRAINT fk_waiting_list_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id) ON DELETE CASCADE,
    CONSTRAINT fk_waiting_list_branch FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE SET NULL,
    CONSTRAINT fk_waiting_list_resource FOREIGN KEY (resource_id) REFERENCES resources (id) ON DELETE SET NULL,
    CONSTRAINT fk_waiting_list_schedule FOREIGN KEY (promoted_schedule_id) REFERENCES schedules (id) ON DELETE SET NULL,
    CONSTRAINT fk_waiting_list_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT ck_waiting_list_window CHECK (desired_to > desired_from),
    CONSTRAINT ck_waiting_list_duration CHECK (duration_minutes > 0)
);
CREATE UNIQUE INDEX uq_waiting_list_number ON waiting_list_entries (tenant_id, entry_number);
-- The promotion query: highest priority first, then longest waiting.
CREATE INDEX ix_waiting_list_queue ON waiting_list_entries (appointment_type_id, priority DESC, created_at ASC)
    WHERE is_active;
CREATE INDEX ix_waiting_list_window ON waiting_list_entries (desired_from, desired_to) WHERE is_active;


-- ---------------------------------------------------------------------
-- Reminder rules per appointment type, and the materialised instances.
-- ---------------------------------------------------------------------
CREATE TABLE appointment_type_reminders (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    appointment_type_id BIGINT      NOT NULL,
    channel_id          BIGINT      NOT NULL,
    -- Minutes before the appointment start.
    offset_minutes      INTEGER     NOT NULL,
    -- When true the offset counts business hours via the calendar rather
    -- than wall-clock, which is the spec's "Business Day Reminder".
    use_business_time   BOOLEAN     NOT NULL DEFAULT FALSE,
    template_code       VARCHAR(64),
    is_active           BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    version             BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT pk_appointment_type_reminders PRIMARY KEY (id),
    CONSTRAINT fk_atr_type FOREIGN KEY (appointment_type_id) REFERENCES appointment_types (id) ON DELETE CASCADE,
    CONSTRAINT fk_atr_channel FOREIGN KEY (channel_id) REFERENCES reminder_channels (id) ON DELETE CASCADE,
    CONSTRAINT ck_atr_offset CHECK (offset_minutes >= 0)
);
CREATE UNIQUE INDEX uq_atr ON appointment_type_reminders (appointment_type_id, channel_id, offset_minutes);


CREATE TABLE schedule_reminders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    schedule_id     BIGINT       NOT NULL,
    channel_id      BIGINT       NOT NULL,
    scheduled_for   TIMESTAMPTZ  NOT NULL,
    sent_at         TIMESTAMPTZ,
    -- PENDING | SENT | FAILED | SKIPPED | CANCELLED
    delivery_state  VARCHAR(32)  NOT NULL DEFAULT 'PENDING',
    attempts        INTEGER      NOT NULL DEFAULT 0,
    last_error      VARCHAR(1000),
    recipient       VARCHAR(255),
    tenant_id       BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_schedule_reminders PRIMARY KEY (id),
    CONSTRAINT fk_schedule_reminders_schedule FOREIGN KEY (schedule_id) REFERENCES schedules (id) ON DELETE CASCADE,
    CONSTRAINT fk_schedule_reminders_channel FOREIGN KEY (channel_id) REFERENCES reminder_channels (id),
    CONSTRAINT fk_schedule_reminders_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT ck_schedule_reminders_attempts CHECK (attempts >= 0)
);
-- The due-reminder sweep, which V19's shared scheduler will drive.
CREATE INDEX ix_schedule_reminders_due ON schedule_reminders (scheduled_for)
    WHERE delivery_state = 'PENDING';
CREATE INDEX ix_schedule_reminders_schedule ON schedule_reminders (schedule_id);


-- ---------------------------------------------------------------------
-- Audit trail. Old/new values as JSONB, matching the knowledge module's
-- kb_audit_log shape so reporting can treat them uniformly.
-- ---------------------------------------------------------------------
CREATE TABLE schedule_audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    entity_type  VARCHAR(64)  NOT NULL,
    entity_id    BIGINT       NOT NULL,
    action       VARCHAR(64)  NOT NULL,
    old_values   JSONB,
    new_values   JSONB,
    actor_id     BIGINT,
    actor_email  VARCHAR(255),
    actor_ip     VARCHAR(64),
    tenant_id    BIGINT       NOT NULL DEFAULT tenancy_default_tenant_id(),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version      BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_schedule_audit_log PRIMARY KEY (id),
    CONSTRAINT fk_schedule_audit_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE INDEX ix_schedule_audit_entity ON schedule_audit_log (entity_type, entity_id, created_at DESC);
CREATE INDEX ix_schedule_audit_tenant ON schedule_audit_log (tenant_id, created_at DESC);


-- =====================================================================
-- Seed
-- =====================================================================

INSERT INTO schedule_statuses (code, name, color, is_default, is_draft_state, is_confirmed_state,
        is_checked_in_state, is_in_progress_state, is_completed_state, is_cancelled_state,
        is_no_show_state, is_archived_state, blocks_resource, allows_edit, allows_cancel,
        allows_check_in, is_terminal, counts_as_attended, is_system, display_order)
VALUES
    ('DRAFT',       'Draft',       '#9E9E9E', TRUE,  TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  TRUE,  FALSE, FALSE, FALSE, TRUE, 10),
    ('SCHEDULED',   'Scheduled',   '#2196F3', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  TRUE,  TRUE,  TRUE,  FALSE, FALSE, TRUE, 20),
    ('CONFIRMED',   'Confirmed',   '#00897B', FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  TRUE,  TRUE,  TRUE,  FALSE, FALSE, TRUE, 30),
    ('PENDING',     'Pending',     '#FB8C00', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  TRUE,  TRUE,  FALSE, FALSE, FALSE, TRUE, 40),
    ('CHECKED_IN',  'Checked In',  '#43A047', FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, TRUE,  FALSE, FALSE, TRUE,  TRUE, 50),
    ('IN_PROGRESS', 'In Progress', '#3949AB', FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, TRUE,  TRUE, 60),
    ('COMPLETED',   'Completed',   '#2E7D32', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  TRUE,  TRUE, 70),
    ('CANCELLED',   'Cancelled',   '#E53935', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, TRUE, 80),
    ('NO_SHOW',     'No Show',     '#8E24AA', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, TRUE, 90),
    ('ARCHIVED',    'Archived',    '#607D8B', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, TRUE, 100);

-- Only DRAFT is flagged is_default; it is also the only non-blocking
-- pre-terminal state, so an unsaved draft never holds a technician.
UPDATE schedule_statuses SET blocks_resource = FALSE WHERE code = 'DRAFT';

INSERT INTO schedule_categories (code, name, description, icon, color, is_default, is_system, display_order)
VALUES
    ('CUSTOMER', 'Customer Appointment', 'Customer-facing bookings',      'mdi-account-clock',   '#2196F3', TRUE,  TRUE, 10),
    ('SERVICE',  'Service & Repair',     'Device intake, repair, return', 'mdi-wrench-clock',    '#FB8C00', FALSE, TRUE, 20),
    ('SUPPLIER', 'Supplier',             'Supplier visits and deliveries','mdi-truck-delivery',  '#00897B', FALSE, TRUE, 30),
    ('INTERNAL', 'Internal',             'Meetings, training, audits',    'mdi-account-group',   '#5E35B1', FALSE, TRUE, 40);

INSERT INTO resource_categories (code, name, description, is_human, is_physical_space, is_equipment,
        supports_capacity, requires_skill_match, is_default, is_system, display_order)
VALUES
    ('TECHNICIAN',        'Technician',        'Repair and inspection staff',  TRUE,  FALSE, FALSE, FALSE, TRUE,  FALSE, TRUE, 10),
    ('SALESPERSON',       'Salesperson',       'Sales floor staff',            TRUE,  FALSE, FALSE, FALSE, FALSE, TRUE,  TRUE, 20),
    ('EMPLOYEE',          'Employee',          'General staff',                TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 30),
    ('SERVICE_COUNTER',   'Service Counter',   'Customer service position',    FALSE, TRUE,  FALSE, TRUE,  FALSE, FALSE, TRUE, 40),
    ('MEETING_ROOM',      'Meeting Room',      'Bookable room',                FALSE, TRUE,  FALSE, TRUE,  FALSE, FALSE, TRUE, 50),
    ('REPAIR_BENCH',      'Repair Bench',      'Workshop position',            FALSE, TRUE,  TRUE,  FALSE, FALSE, FALSE, TRUE, 60),
    ('INSPECTION_STATION','Inspection Station','Warranty and trade-in checks', FALSE, TRUE,  TRUE,  FALSE, FALSE, FALSE, TRUE, 70),
    ('VEHICLE',           'Vehicle',           'Delivery and courier vehicles',FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, TRUE, 80),
    ('WAREHOUSE_DOCK',    'Warehouse Dock',    'Goods in/out bay',             FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, TRUE, 90),
    ('CUSTOM',            'Custom Resource',   'Anything else',                FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 100);

INSERT INTO resource_statuses (code, name, color, allows_booking, is_available, is_default, is_system, display_order)
VALUES
    ('AVAILABLE',      'Available',      '#2E7D32', TRUE,  TRUE,  TRUE,  TRUE, 10),
    ('RESERVED',       'Reserved',       '#FB8C00', TRUE,  FALSE, FALSE, TRUE, 20),
    ('BUSY',           'Busy',           '#E53935', FALSE, FALSE, FALSE, TRUE, 30),
    ('MAINTENANCE',    'Maintenance',    '#8E24AA', FALSE, FALSE, FALSE, TRUE, 40),
    ('OUT_OF_SERVICE', 'Out of Service', '#B71C1C', FALSE, FALSE, FALSE, TRUE, 50),
    ('INACTIVE',       'Inactive',       '#607D8B', FALSE, FALSE, FALSE, TRUE, 60);

INSERT INTO conflict_policies (code, name, description, handler_key, is_blocking,
        suggests_alternatives, requires_approval, is_default, is_system, display_order)
VALUES
    ('PREVENT',      'Prevent Double Booking', 'Reject the request outright',            'prevent',      TRUE,  FALSE, FALSE, TRUE,  TRUE, 10),
    ('SUGGEST',      'Suggest Alternatives',   'Reject, returning the next free slots',  'suggest',      TRUE,  TRUE,  FALSE, FALSE, TRUE, 20),
    ('REPLACE',      'Resource Replacement',   'Retry on another suitable resource',     'replace',      TRUE,  TRUE,  FALSE, FALSE, TRUE, 30),
    ('WARN',         'Conflict Warning',       'Allow, recording a warning',             'warn',         FALSE, FALSE, FALSE, FALSE, TRUE, 40),
    ('APPROVAL',     'Manager Approval',       'Hold pending approval',                  'approval',     TRUE,  FALSE, TRUE,  FALSE, TRUE, 50);

-- Every channel inactive: no notification module exists yet, so the
-- catalogue is complete but nothing is wired. Activating one is a flip.
INSERT INTO reminder_channels (code, name, handler_key, requires_phone, requires_email,
        is_default, is_system, is_active, display_order)
VALUES
    ('EMAIL',    'Email',            'email',    FALSE, TRUE,  TRUE,  TRUE, FALSE, 10),
    ('SMS',      'SMS',              'sms',      TRUE,  FALSE, FALSE, TRUE, FALSE, 20),
    ('PUSH',     'Push Notification','push',     FALSE, FALSE, FALSE, TRUE, FALSE, 30),
    ('WHATSAPP', 'WhatsApp',         'whatsapp', TRUE,  FALSE, FALSE, TRUE, FALSE, 40),
    ('TELEGRAM', 'Telegram',         'telegram', FALSE, FALSE, FALSE, TRUE, FALSE, 50),
    ('IN_APP',   'In-App',           'in_app',   FALSE, FALSE, FALSE, TRUE, FALSE, 60);

-- Appointment types for a mobile phone retail business. Types whose
-- subject_provider_key names an unbuilt module book normally and simply
-- carry no linked record until that module ships.
INSERT INTO appointment_types (code, name, description, category_id, default_duration_minutes,
        min_duration_minutes, max_duration_minutes, preparation_minutes, cleanup_minutes,
        buffer_before_minutes, buffer_after_minutes, requires_customer, requires_supplier,
        requires_resource, requires_approval, allows_waiting_list, allows_self_service,
        allows_overbooking, enforce_working_hours, max_advance_days, min_notice_minutes,
        cancellation_notice_minutes, late_threshold_minutes, no_show_threshold_minutes,
        subject_provider_key, module_code, color, is_default, is_system, is_active, display_order)
SELECT t.code, t.name, t.descr, sc.id, t.dur, t.mind, t.maxd, t.prep, t.clean, t.bufb, t.bufa,
       t.reqcust, t.reqsup, TRUE, t.reqappr, TRUE, t.selfsvc, FALSE, TRUE,
       t.adv, t.notice, t.cancel, 15, 30, t.provider, t.module, t.color, t.isdef, TRUE, TRUE, t.ord
FROM (VALUES
    ('REPAIR_INTAKE',    'Repair Device Intake',   'Customer drops a device for repair',   'SERVICE',  30, 15, 120, 5,  5,  0, 10, TRUE,  FALSE, FALSE, TRUE,  90, 60,  120, 'repair',   'repair',    '#FB8C00', TRUE,  10),
    ('REPAIR_DELIVERY',  'Repair Delivery',        'Customer collects a repaired device',  'SERVICE',  20, 10, 60,  0,  5,  0, 5,  TRUE,  FALSE, FALSE, TRUE,  90, 30,  60,  'repair',   'repair',    '#F4511E', FALSE, 20),
    ('WARRANTY_INSPECT', 'Warranty Inspection',    'Warranty claim assessment',            'SERVICE',  45, 30, 120, 10, 10, 0, 10, TRUE,  FALSE, FALSE, FALSE, 60, 120, 240, 'warranty', 'warranty',  '#6D4C41', FALSE, 30),
    ('TRADE_IN_EVAL',    'Trade-In Evaluation',    'Device valuation for trade-in',        'SERVICE',  30, 20, 90,  5,  5,  0, 5,  TRUE,  FALSE, FALSE, TRUE,  60, 60,  120, 'trade_in', 'trade_in',  '#00ACC1', FALSE, 40),
    ('CONSULTATION',     'Customer Consultation',  'Product advice and VIP consultation',  'CUSTOMER', 30, 15, 120, 0,  0,  0, 5,  TRUE,  FALSE, FALSE, TRUE,  90, 30,  60,  NULL,       'crm',       '#2196F3', FALSE, 50),
    ('SUPPLIER_MEETING', 'Supplier Meeting',       'Supplier visit or negotiation',        'SUPPLIER', 60, 30, 240, 10, 10, 0, 0,  FALSE, TRUE,  FALSE, FALSE, 180, 0,  0,   NULL,       'purchasing','#00897B', FALSE, 60),
    ('DELIVERY',         'Delivery Appointment',   'Inbound goods delivery',               'SUPPLIER', 60, 30, 240, 0,  15, 0, 0,  FALSE, TRUE,  FALSE, FALSE, 120, 0,  0,   NULL,       'purchasing','#26A69A', FALSE, 70),
    ('PICKUP',           'Pickup Appointment',     'Customer order collection',            'CUSTOMER', 15, 10, 60,  0,  0,  0, 0,  TRUE,  FALSE, FALSE, TRUE,  60, 15,  30,  NULL,       'sales',     '#7CB342', FALSE, 80),
    ('INTERNAL_MEETING', 'Internal Meeting',       'Staff meeting',                        'INTERNAL', 60, 15, 480, 0,  0,  0, 0,  FALSE, FALSE, FALSE, FALSE, 180, 0,  0,   NULL,       NULL,        '#5E35B1', FALSE, 90),
    ('TRAINING',         'Store Training',         'Staff training session',               'INTERNAL', 120,30, 480, 15, 15, 0, 0,  FALSE, FALSE, FALSE, FALSE, 365, 0,  0,   NULL,       'knowledge', '#8E24AA', FALSE, 100),
    ('INVENTORY_AUDIT',  'Inventory Counting',     'Stock count / audit window',           'INTERNAL', 240,60, 480, 30, 30, 0, 0,  FALSE, FALSE, TRUE,  FALSE, 365, 0,  0,   NULL,       'inventory', '#546E7A', FALSE, 110)
) AS t(code, name, descr, cat, dur, mind, maxd, prep, clean, bufb, bufa, reqcust, reqsup, reqappr, selfsvc, adv, notice, cancel, provider, module, color, isdef, ord)
JOIN schedule_categories sc ON sc.code = t.cat;

-- Default reminder rules on customer-facing types: 24 hours and 2 hours
-- ahead by email. Inactive channels mean nothing is sent yet.
INSERT INTO appointment_type_reminders (appointment_type_id, channel_id, offset_minutes, use_business_time, is_active)
SELECT at.id, rc.id, o.mins, FALSE, TRUE
FROM appointment_types at
JOIN reminder_channels rc ON rc.code = 'EMAIL'
CROSS JOIN (VALUES (1440), (120)) AS o(mins)
WHERE at.code IN ('REPAIR_INTAKE', 'REPAIR_DELIVERY', 'WARRANTY_INSPECT',
                  'TRADE_IN_EVAL', 'CONSULTATION', 'PICKUP');


-- =====================================================================
-- Module registration and permissions
-- =====================================================================

-- Module code is 'appointments', not 'scheduler': V19 already registered
-- 'scheduler' for the background job runner. Keeping them distinct in the
-- permission namespace enforces the separation the spec calls for, so
-- 'scheduler:view' can never be mistaken for the right to read bookings.
INSERT INTO modules (code, name, description, icon, path, display_order, enabled, is_system)
VALUES ('appointments', 'Appointments & Resources',
        'Appointments, resource reservations and the waiting list',
        'mdi-calendar-account-outline', '/appointments', 180, TRUE, TRUE);

INSERT INTO permissions (module_id, action, code, name, is_system)
SELECT m.id, a.action, m.code || ':' || a.action, m.name || ' — ' || a.label, TRUE
FROM modules m
CROSS JOIN (VALUES
    ('view',              'View appointments'),
    ('create',            'Create appointments'),
    ('edit',              'Modify appointments'),
    ('cancel',            'Cancel appointments'),
    ('reserve',           'Reserve resources'),
    ('manage-resources',  'Manage resources'),
    ('check-in',          'Check customers in and out'),
    ('view-utilization',  'View resource utilisation'),
    ('manage-waiting-list','Manage the waiting list'),
    ('export',            'Export scheduling reports')
) AS a(action, label)
WHERE m.code = 'appointments';


-- =====================================================================
-- Post-migration assertions
--
-- The exclusion constraint is the module's core guarantee, so it is
-- proved here rather than assumed: if a future migration or a manual
-- edit ever drops it, this fails loudly on the next fresh deploy.
-- =====================================================================

DO $$
DECLARE
    has_exclusion BOOLEAN;
    default_status_count BIGINT;
    type_count BIGINT;
BEGIN
    SELECT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ex_reservations_no_double_booking' AND contype = 'x'
    ) INTO has_exclusion;
    IF NOT has_exclusion THEN
        RAISE EXCEPTION 'V24: the double-booking exclusion constraint is missing';
    END IF;

    SELECT count(*) INTO default_status_count FROM schedule_statuses WHERE is_default;
    IF default_status_count <> 1 THEN
        RAISE EXCEPTION 'V24: expected exactly 1 default schedule status, found %', default_status_count;
    END IF;

    SELECT count(*) INTO type_count FROM appointment_types WHERE is_active;
    IF type_count < 1 THEN
        RAISE EXCEPTION 'V24: no appointment types were seeded';
    END IF;

    -- A terminal status must never hold a resource, or cancelled bookings
    -- would keep blocking the slot they were cancelled from.
    IF EXISTS (SELECT 1 FROM schedule_statuses WHERE is_terminal AND blocks_resource) THEN
        RAISE EXCEPTION 'V24: a terminal status is flagged as blocking its resource';
    END IF;
END $$;
