-- =====================================================================
-- V25 — Module lifecycle status
--
-- Makes module implementation status DATA rather than an inference.
--
-- THE PROBLEM THIS FIXES. The frontend decided whether a module was
-- "implemented" by asking its own router whether a static Vue route
-- existed for the module's path. That conflates two independent facts:
--
--     "no frontend route exists"  ⟹  "this module is not implemented"
--
-- which is wrong in both directions. Modules such as files, knowledge,
-- portal and appointments have complete schemas, services, endpoints and
-- tests but no screens; they reported themselves as un-started. A module
-- created at runtime in the admin panel, with no backend at all, reported
-- exactly the same thing. The status was never data — it was a build-time
-- property of the frontend bundle.
--
-- THE MODEL. Backend and frontend readiness are tracked as SEPARATE axes,
-- because that is what the real states look like. Overall status is
-- derived from the two unless an administrator pins it explicitly.
--
-- Derivation is data-driven via `lifecycle_rank`, not by matching status
-- codes in Java: overall is the LEAST advanced of the two axes (a module
-- is only as usable as its weakest half), except that a terminal state
-- (deprecated, retired) on either axis dominates. Reordering the lifecycle
-- or inserting a new stage is therefore a data change.
--
-- Tier S per docs/tenancy.md: a NULL tenant_id row is a platform-wide
-- default every tenant inherits.
-- =====================================================================


-- ---------------------------------------------------------------------
-- The configurable lifecycle stages.
--
-- `applies_to_backend` / `applies_to_frontend` exist because two stages
-- are axis-specific by nature: BACKEND_READY is meaningless as a frontend
-- state and FRONTEND_READY as a backend one. The admin UI offers only the
-- values valid for the axis being edited, so the pair cannot be set to a
-- nonsensical combination.
-- ---------------------------------------------------------------------
CREATE TABLE module_statuses (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                 VARCHAR(64)  NOT NULL,
    name                 VARCHAR(100) NOT NULL,
    description          VARCHAR(500),
    color                VARCHAR(16),
    icon                 VARCHAR(64),

    -- Ordering along the lifecycle. Lower is earlier/less advanced. Gaps
    -- are deliberate so a stage can be inserted between two others
    -- without renumbering.
    lifecycle_rank       INTEGER      NOT NULL,

    applies_to_backend   BOOLEAN      NOT NULL DEFAULT TRUE,
    applies_to_frontend  BOOLEAN      NOT NULL DEFAULT TRUE,

    -- May a user open the module at all? A PLANNED module still appears
    -- in the menu (so the roadmap is visible) but need not be navigable.
    is_navigable         BOOLEAN      NOT NULL DEFAULT TRUE,

    -- Should the placeholder screen be shown instead of real content?
    -- Read from the FRONTEND axis: it is a statement about the UI.
    shows_placeholder    BOOLEAN      NOT NULL DEFAULT TRUE,

    -- Fit to appear in a production deployment.
    is_production_ready  BOOLEAN      NOT NULL DEFAULT FALSE,

    -- End of life; dominates derivation of the overall status.
    is_terminal          BOOLEAN      NOT NULL DEFAULT FALSE,

    -- Seed values for a newly created module, per axis.
    is_default_backend   BOOLEAN      NOT NULL DEFAULT FALSE,
    is_default_frontend  BOOLEAN      NOT NULL DEFAULT FALSE,

    is_system            BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order        INTEGER      NOT NULL DEFAULT 0,

    tenant_id            BIGINT,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version              BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_module_statuses PRIMARY KEY (id),
    CONSTRAINT fk_module_statuses_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT ck_module_statuses_axis CHECK (applies_to_backend OR applies_to_frontend)
);
CREATE UNIQUE INDEX uq_module_statuses_code_global ON module_statuses (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX uq_module_statuses_code_tenant ON module_statuses (tenant_id, code) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_module_statuses_default_backend ON module_statuses ((TRUE))
    WHERE is_default_backend AND tenant_id IS NULL;
CREATE UNIQUE INDEX uq_module_statuses_default_frontend ON module_statuses ((TRUE))
    WHERE is_default_frontend AND tenant_id IS NULL;
CREATE INDEX ix_module_statuses_rank ON module_statuses (lifecycle_rank);


INSERT INTO module_statuses (code, name, description, color, icon, lifecycle_rank,
        applies_to_backend, applies_to_frontend, is_navigable, shows_placeholder,
        is_production_ready, is_terminal, is_default_backend, is_default_frontend,
        is_system, display_order)
VALUES
    ('PLANNED',         'Planned',
     'Scheduled for future development; no work started',
     '#9E9E9E', 'mdi-calendar-clock',      10, TRUE,  TRUE,  TRUE,  TRUE,  FALSE, FALSE, TRUE,  TRUE,  TRUE, 10),

    ('IN_DEVELOPMENT',  'In Development',
     'Actively being built',
     '#FB8C00', 'mdi-hammer-wrench',       20, TRUE,  TRUE,  TRUE,  TRUE,  FALSE, FALSE, FALSE, FALSE, TRUE, 20),

    ('BACKEND_READY',   'Backend Ready',
     'Server-side implementation complete; user interface still pending',
     '#00897B', 'mdi-server-network',      40, TRUE,  FALSE, TRUE,  TRUE,  FALSE, FALSE, FALSE, FALSE, TRUE, 30),

    ('FRONTEND_READY',  'Frontend Ready',
     'User interface complete; server-side implementation still pending',
     '#3949AB', 'mdi-monitor-dashboard',   40, FALSE, TRUE,  TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 40),

    ('BETA',            'Beta',
     'Usable and feature-complete, undergoing validation',
     '#8E24AA', 'mdi-test-tube',           60, TRUE,  TRUE,  TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 50),

    ('ACTIVE',          'Active',
     'Released and fully supported',
     '#2E7D32', 'mdi-check-circle',        80, TRUE,  TRUE,  TRUE,  FALSE, TRUE,  FALSE, FALSE, FALSE, TRUE, 60),

    ('DEPRECATED',      'Deprecated',
     'Still available but scheduled for removal',
     '#E53935', 'mdi-alert-circle',        90, TRUE,  TRUE,  TRUE,  FALSE, TRUE,  TRUE,  FALSE, FALSE, TRUE, 70),

    ('RETIRED',         'Retired',
     'Withdrawn from service',
     '#607D8B', 'mdi-archive-off',        100, TRUE,  TRUE,  FALSE, TRUE,  FALSE, TRUE,  FALSE, FALSE, TRUE, 80);


-- ---------------------------------------------------------------------
-- Lifecycle columns on modules.
--
-- Added nullable, backfilled, then constrained — the standard safe
-- sequence, and the one V16 used for tenant_id. Nothing about an existing
-- row changes meaning: `enabled` still controls menu visibility and
-- `is_system` still protects the admin modules.
-- ---------------------------------------------------------------------
ALTER TABLE modules
    ADD COLUMN backend_status_id   BIGINT,
    ADD COLUMN frontend_status_id  BIGINT,
    -- NULL means "derive from the two axes"; a value pins it explicitly.
    ADD COLUMN overall_status_id   BIGINT,
    ADD COLUMN release_version     VARCHAR(32),
    ADD COLUMN progress_percentage SMALLINT     NOT NULL DEFAULT 0,
    ADD COLUMN development_notes   VARCHAR(2000),
    -- Distinct from `enabled`: an administrator disables a module, whereas
    -- availability reflects whether it is fit to be used at all in this
    -- deployment. Keeping them apart means turning a module off for one
    -- installation does not rewrite its lifecycle record.
    ADD COLUMN is_available        BOOLEAN      NOT NULL DEFAULT TRUE,
    ADD COLUMN is_production_ready BOOLEAN      NOT NULL DEFAULT FALSE;

ALTER TABLE modules
    ADD CONSTRAINT ck_modules_progress CHECK (progress_percentage BETWEEN 0 AND 100);


-- =====================================================================
-- Backfill
--
-- A one-time snapshot of reality as of this migration, NOT logic: from
-- here on these are ordinary editable fields owned by administrators.
--
-- Codes are named explicitly because this is data about specific existing
-- rows — there is no rule that could infer, for example, that `knowledge`
-- has a finished backend and no screens. Every module keeps working
-- whatever value it receives; the values only change what is displayed.
-- =====================================================================

-- Baseline: every existing module has a working backend (it has been
-- running in production paths and has seeded permissions), and no
-- frontend until proven otherwise.
UPDATE modules SET
    backend_status_id  = (SELECT id FROM module_statuses WHERE code = 'BACKEND_READY' AND tenant_id IS NULL),
    frontend_status_id = (SELECT id FROM module_statuses WHERE code = 'PLANNED'       AND tenant_id IS NULL),
    progress_percentage = 50
WHERE backend_status_id IS NULL;

-- Modules that additionally have complete Vue screens today. Verified
-- against frontend/src/router/index.ts at the time of this migration.
UPDATE modules SET
    backend_status_id  = (SELECT id FROM module_statuses WHERE code = 'ACTIVE' AND tenant_id IS NULL),
    frontend_status_id = (SELECT id FROM module_statuses WHERE code = 'ACTIVE' AND tenant_id IS NULL),
    progress_percentage = 100,
    is_production_ready = TRUE
WHERE code IN ('dashboard', 'dashboards', 'users', 'roles', 'permissions',
               'modules', 'products', 'customers', 'suppliers', 'purchasing');

-- Modules whose backend is complete and verified end-to-end but which
-- have no screens yet.
UPDATE modules SET
    progress_percentage = 60
WHERE code IN ('automation', 'licensing', 'data-quality', 'metadata',
               'files', 'scheduler', 'knowledge', 'organization', 'calendar', 'appointments');

-- Built but never exercised against a running system; honest about it.
UPDATE modules SET
    backend_status_id = (SELECT id FROM module_statuses WHERE code = 'IN_DEVELOPMENT' AND tenant_id IS NULL),
    progress_percentage = 35
WHERE code = 'portal';

-- Navigation scaffolds seeded by V4 with no implementation on either side:
-- no Java package, no tables, and disabled. The baseline above assumed a
-- working backend, which is true of every module that came later but not
-- of these — left uncorrected they would claim 50% progress for code that
-- does not exist, reintroducing the dishonesty this migration removes.
UPDATE modules SET
    backend_status_id  = (SELECT id FROM module_statuses WHERE code = 'PLANNED' AND tenant_id IS NULL),
    frontend_status_id = (SELECT id FROM module_statuses WHERE code = 'PLANNED' AND tenant_id IS NULL),
    progress_percentage = 0,
    is_production_ready = FALSE
WHERE code IN ('categories', 'orders', 'reports', 'settings');

ALTER TABLE modules
    ALTER COLUMN backend_status_id  SET NOT NULL,
    ALTER COLUMN frontend_status_id SET NOT NULL;

ALTER TABLE modules
    ADD CONSTRAINT fk_modules_backend_status  FOREIGN KEY (backend_status_id)  REFERENCES module_statuses (id),
    ADD CONSTRAINT fk_modules_frontend_status FOREIGN KEY (frontend_status_id) REFERENCES module_statuses (id),
    ADD CONSTRAINT fk_modules_overall_status  FOREIGN KEY (overall_status_id)  REFERENCES module_statuses (id);

CREATE INDEX ix_modules_backend_status ON modules (backend_status_id);
CREATE INDEX ix_modules_frontend_status ON modules (frontend_status_id);


-- =====================================================================
-- Post-migration assertions
-- =====================================================================

DO $$
DECLARE
    unassigned        BIGINT;
    default_backend   BIGINT;
    default_frontend  BIGINT;
    bad_axis          BIGINT;
BEGIN
    SELECT count(*) INTO unassigned FROM modules
    WHERE backend_status_id IS NULL OR frontend_status_id IS NULL;
    IF unassigned > 0 THEN
        RAISE EXCEPTION 'V25: % module(s) left without a lifecycle status', unassigned;
    END IF;

    SELECT count(*) INTO default_backend FROM module_statuses
    WHERE is_default_backend AND tenant_id IS NULL;
    IF default_backend <> 1 THEN
        RAISE EXCEPTION 'V25: expected exactly 1 default backend status, found %', default_backend;
    END IF;

    SELECT count(*) INTO default_frontend FROM module_statuses
    WHERE is_default_frontend AND tenant_id IS NULL;
    IF default_frontend <> 1 THEN
        RAISE EXCEPTION 'V25: expected exactly 1 default frontend status, found %', default_frontend;
    END IF;

    -- A module must never hold a status that does not apply to its axis.
    SELECT count(*) INTO bad_axis FROM modules m
    JOIN module_statuses bs ON bs.id = m.backend_status_id
    JOIN module_statuses fs ON fs.id = m.frontend_status_id
    WHERE NOT bs.applies_to_backend OR NOT fs.applies_to_frontend;
    IF bad_axis > 0 THEN
        RAISE EXCEPTION 'V25: % module(s) hold a status invalid for their axis', bad_axis;
    END IF;
END $$;
