-- Products table: sample catalogue entity.
CREATE TABLE products (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name           VARCHAR(255)  NOT NULL,
    sku            VARCHAR(64)   NOT NULL,
    description    VARCHAR(2000),
    price          NUMERIC(12,2) NOT NULL,
    stock_quantity INTEGER       NOT NULL DEFAULT 0,
    active         BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ   NOT NULL,
    updated_at     TIMESTAMPTZ   NOT NULL,
    version        BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT uq_products_sku UNIQUE (sku),
    CONSTRAINT ck_products_price_non_negative CHECK (price >= 0),
    CONSTRAINT ck_products_stock_non_negative CHECK (stock_quantity >= 0)
);

CREATE INDEX idx_products_name ON products (lower(name));
CREATE INDEX idx_products_active ON products (active);
