-- User Management module: configurable statuses, extensible profiles,
-- audit log, and lifecycle (archive / soft-delete) columns.

-- Configurable user statuses. Behavior lives in flags, never in names/code:
--   allows_login       gates authentication
--   hidden_by_default  excluded from listings unless explicitly requested
--   is_default         assigned on registration, reactivation and restore (unique)
--   is_archived_state  the status the "archive" operation targets (unique)
--   is_deleted_state   the status the "soft delete" operation targets (unique)
CREATE TABLE user_statuses (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code              VARCHAR(64)  NOT NULL,
    name              VARCHAR(100) NOT NULL,
    description       VARCHAR(255),
    allows_login      BOOLEAN      NOT NULL DEFAULT FALSE,
    hidden_by_default BOOLEAN      NOT NULL DEFAULT FALSE,
    is_default        BOOLEAN      NOT NULL DEFAULT FALSE,
    is_archived_state BOOLEAN      NOT NULL DEFAULT FALSE,
    is_deleted_state  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system         BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order     INTEGER      NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_user_statuses PRIMARY KEY (id),
    CONSTRAINT uq_user_statuses_code UNIQUE (code)
);

CREATE UNIQUE INDEX uq_user_statuses_default  ON user_statuses (is_default)        WHERE is_default;
CREATE UNIQUE INDEX uq_user_statuses_archived ON user_statuses (is_archived_state) WHERE is_archived_state;
CREATE UNIQUE INDEX uq_user_statuses_deleted  ON user_statuses (is_deleted_state)  WHERE is_deleted_state;

INSERT INTO user_statuses
    (code, name, description, allows_login, hidden_by_default, is_default, is_archived_state, is_deleted_state, is_system, display_order) VALUES
    ('active',    'Active',    'Fully operational account',                     TRUE,  FALSE, TRUE,  FALSE, FALSE, TRUE, 10),
    ('inactive',  'Inactive',  'Account disabled; cannot log in',               FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 20),
    ('suspended', 'Suspended', 'Temporarily blocked pending review',            FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 30),
    ('archived',  'Archived',  'Retired account, hidden from default listings', FALSE, TRUE,  FALSE, TRUE,  FALSE, TRUE, 40),
    ('deleted',   'Deleted',   'Soft-deleted account awaiting restore or purge',FALSE, TRUE,  FALSE, FALSE, TRUE,  TRUE, 50);

-- Users move from the enabled boolean to a status FK, and gain lifecycle columns.
ALTER TABLE users
    ADD COLUMN status_id   BIGINT,
    ADD COLUMN archived_at TIMESTAMPTZ,
    ADD COLUMN archived_by BIGINT,
    ADD COLUMN deleted_at  TIMESTAMPTZ,
    ADD COLUMN deleted_by  BIGINT;

UPDATE users SET status_id = (SELECT id FROM user_statuses WHERE is_default) WHERE enabled;
UPDATE users SET status_id = (SELECT id FROM user_statuses WHERE code = 'inactive') WHERE status_id IS NULL;

ALTER TABLE users ALTER COLUMN status_id SET NOT NULL;
ALTER TABLE users ADD CONSTRAINT fk_users_status FOREIGN KEY (status_id) REFERENCES user_statuses (id);
CREATE INDEX idx_users_status_id ON users (status_id);
ALTER TABLE users DROP COLUMN enabled;

-- One profile per user. Standard fields are real (constrainable, indexable)
-- columns; future fields land in custom_fields (JSONB), described and validated
-- via profile_field_definitions — no schema change required.
CREATE TABLE user_profiles (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT       NOT NULL,
    first_name    VARCHAR(80),
    last_name     VARCHAR(80),
    display_name  VARCHAR(160),
    national_code VARCHAR(32),
    employee_code VARCHAR(32),
    phone_number  VARCHAR(32),
    gender        VARCHAR(16),
    birth_date    DATE,
    avatar_key    VARCHAR(255),
    address       VARCHAR(500),
    notes         VARCHAR(2000),
    custom_fields JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_user_profiles PRIMARY KEY (id),
    CONSTRAINT uq_user_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_user_profiles_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
);

-- Uniqueness only applies to values that are present.
CREATE UNIQUE INDEX uq_user_profiles_phone         ON user_profiles (phone_number)  WHERE phone_number  IS NOT NULL;
CREATE UNIQUE INDEX uq_user_profiles_employee_code ON user_profiles (employee_code) WHERE employee_code IS NOT NULL;
CREATE UNIQUE INDEX uq_user_profiles_national_code ON user_profiles (national_code) WHERE national_code IS NOT NULL;

-- Existing users get a profile carrying their current display name.
INSERT INTO user_profiles (user_id, display_name)
SELECT id, full_name FROM users;

-- Configurable custom profile fields (key, type, validation), editable at runtime.
CREATE TABLE profile_field_definitions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    field_key     VARCHAR(64)  NOT NULL,
    label         VARCHAR(100) NOT NULL,
    field_type    VARCHAR(16)  NOT NULL,   -- TEXT | NUMBER | DATE | BOOLEAN | SELECT
    required      BOOLEAN      NOT NULL DEFAULT FALSE,
    min_length    INTEGER,
    max_length    INTEGER,
    pattern       VARCHAR(255),
    options       JSONB,                   -- SELECT choices, e.g. ["A","B"]
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_profile_field_definitions PRIMARY KEY (id),
    CONSTRAINT uq_profile_field_definitions_key UNIQUE (field_key)
);

-- Append-only audit trail. Deliberately NO foreign keys: audit history must
-- survive a permanent user delete, so identifying emails are snapshotted.
CREATE TABLE user_audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT,
    user_email  VARCHAR(255),
    action      VARCHAR(64)  NOT NULL,
    actor_id    BIGINT,
    actor_email VARCHAR(255),
    old_values  JSONB,
    new_values  JSONB,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_user_audit_log PRIMARY KEY (id)
);

CREATE INDEX idx_user_audit_log_user_id    ON user_audit_log (user_id);
CREATE INDEX idx_user_audit_log_created_at ON user_audit_log (created_at);

-- Lifecycle permissions beyond the standard six, under the existing users module.
INSERT INTO permissions (module_id, action, code, name, is_system)
SELECT m.id, a.action, m.code || ':' || a.action, m.name || ' — ' || a.label, TRUE
FROM modules m
CROSS JOIN (VALUES
    ('archive', 'Archive'),
    ('restore', 'Restore'),
    ('purge',   'Permanent delete')
) AS a(action, label)
WHERE m.code = 'users';
