-- Customer Management (CRM): configurable types/statuses/sources/tags,
-- customers with multi-value contacts and addresses, notes, an append-only
-- timeline event store, duplicate-detection rules, and merge support.

-- Configurable customer types. Purely data; no type code appears in logic.
CREATE TABLE customer_types (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    description   VARCHAR(255),
    is_default    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_customer_types PRIMARY KEY (id),
    CONSTRAINT uq_customer_types_code UNIQUE (code)
);
CREATE UNIQUE INDEX uq_customer_types_default ON customer_types (is_default) WHERE is_default;

INSERT INTO customer_types (code, name, description, is_default, is_system, display_order) VALUES
    ('individual', 'Individual',         'A private person',                       TRUE,  TRUE,  10),
    ('business',   'Business',           'A company or organization',              FALSE, TRUE,  20),
    ('vip',        'VIP',                'High-value customer',                    FALSE, FALSE, 30),
    ('supplier',   'Supplier Customer',  'Also sells products to the store',       FALSE, FALSE, 40),
    ('employee',   'Employee',           'Staff member buying as a customer',      FALSE, FALSE, 50),
    ('temporary',  'Temporary Customer', 'One-off or not yet fully registered',    FALSE, FALSE, 60);

-- Configurable customer statuses; behavior lives in flags (same pattern as
-- user_statuses). is_blocking is the flag future transaction modules consult
-- before selling/lending to a customer.
CREATE TABLE customer_statuses (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code              VARCHAR(64)  NOT NULL,
    name              VARCHAR(100) NOT NULL,
    description       VARCHAR(255),
    is_blocking       BOOLEAN      NOT NULL DEFAULT FALSE,
    hidden_by_default BOOLEAN      NOT NULL DEFAULT FALSE,
    is_default        BOOLEAN      NOT NULL DEFAULT FALSE,
    is_archived_state BOOLEAN      NOT NULL DEFAULT FALSE,
    is_deleted_state  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system         BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order     INTEGER      NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_customer_statuses PRIMARY KEY (id),
    CONSTRAINT uq_customer_statuses_code UNIQUE (code)
);
CREATE UNIQUE INDEX uq_customer_statuses_default  ON customer_statuses (is_default)        WHERE is_default;
CREATE UNIQUE INDEX uq_customer_statuses_archived ON customer_statuses (is_archived_state) WHERE is_archived_state;
CREATE UNIQUE INDEX uq_customer_statuses_deleted  ON customer_statuses (is_deleted_state)  WHERE is_deleted_state;

INSERT INTO customer_statuses
    (code, name, description, is_blocking, hidden_by_default, is_default, is_archived_state, is_deleted_state, is_system, display_order) VALUES
    ('active',      'Active',      'Normal customer',                            FALSE, FALSE, TRUE,  FALSE, FALSE, TRUE, 10),
    ('inactive',    'Inactive',    'Dormant customer',                           FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 20),
    ('blocked',     'Blocked',     'Transactions blocked pending review',        TRUE,  FALSE, FALSE, FALSE, FALSE, TRUE, 30),
    ('blacklisted', 'Blacklisted', 'Permanently blocked from doing business',    TRUE,  FALSE, FALSE, FALSE, FALSE, TRUE, 40),
    ('archived',    'Archived',    'Retired record, hidden from default lists',  FALSE, TRUE,  FALSE, TRUE,  FALSE, TRUE, 50),
    ('deleted',     'Deleted',     'Soft-deleted, awaiting restore or purge',    TRUE,  TRUE,  FALSE, FALSE, TRUE,  TRUE, 60);

-- Configurable acquisition sources.
CREATE TABLE customer_sources (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_customer_sources PRIMARY KEY (id),
    CONSTRAINT uq_customer_sources_code UNIQUE (code)
);

INSERT INTO customer_sources (code, name, is_system, display_order) VALUES
    ('walk-in',       'Walk-in',       TRUE,  10),
    ('website',       'Website',       FALSE, 20),
    ('instagram',     'Instagram',     FALSE, 30),
    ('telegram',      'Telegram',      FALSE, 40),
    ('divar',         'Divar',         FALSE, 50),
    ('referral',      'Referral',      FALSE, 60),
    ('advertisement', 'Advertisement', FALSE, 70),
    ('unknown',       'Unknown',       TRUE,  80);

-- Dynamic tags.
CREATE TABLE customer_tags (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(80)  NOT NULL,
    color      VARCHAR(32),
    description VARCHAR(255),
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version    BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_customer_tags PRIMARY KEY (id),
    CONSTRAINT uq_customer_tags_name UNIQUE (name)
);

INSERT INTO customer_tags (name, color) VALUES
    ('VIP', 'amber'), ('Wholesale', 'indigo'), ('Installment Customer', 'teal'),
    ('Repair Customer', 'blue'), ('High Risk', 'red'), ('Returning Customer', 'green'),
    ('Loyal Customer', 'purple');

-- Customer code sequence; prefix/padding are application configuration.
CREATE SEQUENCE customer_code_seq START WITH 1001;

-- The customer record. Identity fields are indexed but NOT uniquely constrained:
-- duplicate policy is data (crm_duplicate_rules), enforced in the service, so a
-- disabled rule really is disabled. merged_into_id marks records absorbed by a
-- merge — they stay resolvable forever but leave listings and duplicate checks.
CREATE TABLE customers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_code   VARCHAR(32)  NOT NULL,
    first_name      VARCHAR(80),
    last_name       VARCHAR(80),
    display_name    VARCHAR(160) NOT NULL,
    national_code   VARCHAR(32),
    passport_number VARCHAR(32),
    birth_date      DATE,
    gender          VARCHAR(16),
    occupation      VARCHAR(120),
    company_name    VARCHAR(160),
    tax_number      VARCHAR(64),
    avatar_key      VARCHAR(255),
    type_id         BIGINT       NOT NULL,
    status_id       BIGINT       NOT NULL,
    source_id       BIGINT,
    merged_into_id  BIGINT,
    archived_at     TIMESTAMPTZ,
    archived_by     BIGINT,
    deleted_at      TIMESTAMPTZ,
    deleted_by      BIGINT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_customers PRIMARY KEY (id),
    CONSTRAINT uq_customers_code UNIQUE (customer_code),
    CONSTRAINT fk_customers_type   FOREIGN KEY (type_id)   REFERENCES customer_types (id),
    CONSTRAINT fk_customers_status FOREIGN KEY (status_id) REFERENCES customer_statuses (id),
    CONSTRAINT fk_customers_source FOREIGN KEY (source_id) REFERENCES customer_sources (id),
    CONSTRAINT fk_customers_merged FOREIGN KEY (merged_into_id) REFERENCES customers (id)
);
CREATE INDEX idx_customers_status        ON customers (status_id);
CREATE INDEX idx_customers_type          ON customers (type_id);
CREATE INDEX idx_customers_national_code ON customers (national_code);
CREATE INDEX idx_customers_passport      ON customers (passport_number);
CREATE INDEX idx_customers_display_name  ON customers (lower(display_name));
CREATE INDEX idx_customers_merged_into   ON customers (merged_into_id);

-- Phones and emails: one table, discriminated by kind; at most one default per
-- (customer, kind). Modification history goes to customer_events.
CREATE TABLE customer_contacts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id BIGINT       NOT NULL,
    kind        VARCHAR(16)  NOT NULL,   -- PHONE | EMAIL
    value       VARCHAR(255) NOT NULL,
    label       VARCHAR(60),
    is_default  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_customer_contacts PRIMARY KEY (id),
    CONSTRAINT fk_customer_contacts_customer FOREIGN KEY (customer_id)
        REFERENCES customers (id) ON DELETE CASCADE,
    CONSTRAINT ck_customer_contacts_kind CHECK (kind IN ('PHONE', 'EMAIL'))
);
CREATE INDEX idx_customer_contacts_customer ON customer_contacts (customer_id);
CREATE INDEX idx_customer_contacts_value    ON customer_contacts (lower(value));
CREATE UNIQUE INDEX uq_customer_contacts_default
    ON customer_contacts (customer_id, kind) WHERE is_default;

CREATE TABLE customer_addresses (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id BIGINT       NOT NULL,
    label       VARCHAR(60),
    line        VARCHAR(300) NOT NULL,
    city        VARCHAR(100),
    province    VARCHAR(100),
    postal_code VARCHAR(20),
    is_default  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_customer_addresses PRIMARY KEY (id),
    CONSTRAINT fk_customer_addresses_customer FOREIGN KEY (customer_id)
        REFERENCES customers (id) ON DELETE CASCADE
);
CREATE INDEX idx_customer_addresses_customer ON customer_addresses (customer_id);
CREATE INDEX idx_customer_addresses_city     ON customer_addresses (lower(city));
CREATE UNIQUE INDEX uq_customer_addresses_default
    ON customer_addresses (customer_id) WHERE is_default;

CREATE TABLE customer_tag_links (
    customer_id BIGINT NOT NULL,
    tag_id      BIGINT NOT NULL,
    CONSTRAINT pk_customer_tag_links PRIMARY KEY (customer_id, tag_id),
    CONSTRAINT fk_ctl_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE,
    CONSTRAINT fk_ctl_tag      FOREIGN KEY (tag_id)      REFERENCES customer_tags (id) ON DELETE CASCADE
);

-- Notes: author snapshotted; PRIVATE notes are visible to their author only.
CREATE TABLE customer_notes (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id  BIGINT       NOT NULL,
    author_id    BIGINT,
    author_email VARCHAR(255),
    priority     VARCHAR(16)  NOT NULL DEFAULT 'NORMAL',   -- LOW | NORMAL | HIGH
    visibility   VARCHAR(16)  NOT NULL DEFAULT 'PUBLIC',   -- PUBLIC | PRIVATE
    body         VARCHAR(4000) NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version      BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_customer_notes PRIMARY KEY (id),
    CONSTRAINT fk_customer_notes_customer FOREIGN KEY (customer_id)
        REFERENCES customers (id) ON DELETE CASCADE
);
CREATE INDEX idx_customer_notes_customer ON customer_notes (customer_id);

-- The 360° timeline. Append-only and OPEN: event_type is a free string so
-- future modules (sales, repairs, installments, payments…) record their own
-- event types here through CustomerEventService without any CRM change.
CREATE TABLE customer_events (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id   BIGINT       NOT NULL,
    event_type    VARCHAR(64)  NOT NULL,
    title         VARCHAR(255) NOT NULL,
    detail        JSONB,
    source_module VARCHAR(64)  NOT NULL DEFAULT 'crm',
    actor_id      BIGINT,
    actor_email   VARCHAR(255),
    occurred_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_customer_events PRIMARY KEY (id),
    CONSTRAINT fk_customer_events_customer FOREIGN KEY (customer_id)
        REFERENCES customers (id) ON DELETE CASCADE
);
CREATE INDEX idx_customer_events_customer ON customer_events (customer_id, occurred_at DESC);
CREATE INDEX idx_customer_events_type     ON customer_events (event_type);

-- Duplicate-detection policy as data: each identifier can be toggled at runtime.
CREATE TABLE crm_duplicate_rules (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    identifier VARCHAR(32) NOT NULL,   -- PHONE | EMAIL | NATIONAL_CODE | PASSPORT
    enabled    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version    BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT pk_crm_duplicate_rules PRIMARY KEY (id),
    CONSTRAINT uq_crm_duplicate_rules_identifier UNIQUE (identifier)
);

INSERT INTO crm_duplicate_rules (identifier, enabled) VALUES
    ('PHONE', TRUE), ('EMAIL', TRUE), ('NATIONAL_CODE', TRUE), ('PASSPORT', TRUE);

-- Module + permissions: standard six plus CRM-specific lifecycle/merge actions.
INSERT INTO modules (code, name, description, icon, path, display_order, enabled, is_system)
VALUES ('customers', 'Customers', 'Customer relationship management', 'mdi-account-heart', '/customers', 65, TRUE, FALSE);

INSERT INTO permissions (module_id, action, code, name, is_system)
SELECT m.id, a.action, m.code || ':' || a.action, m.name || ' — ' || a.label, TRUE
FROM modules m
CROSS JOIN (VALUES
    ('view',    'View'),
    ('create',  'Create'),
    ('edit',    'Edit'),
    ('delete',  'Delete'),
    ('export',  'Export'),
    ('import',  'Import'),
    ('archive', 'Archive'),
    ('restore', 'Restore'),
    ('purge',   'Permanent delete'),
    ('merge',   'Merge')
) AS a(action, label)
WHERE m.code = 'customers';
