-- Purchasing: configurable statuses/types/reasons/identifier-types/warehouses,
-- purchase documents with items, receipts, returns, serialized identifiers,
-- attachments, approval rules and an append-only purchase log.

-- Configurable purchase statuses. Structural roles are unique flagged rows;
-- behavior lives in allows_editing / allows_receiving / is_terminal.
CREATE TABLE pur_statuses (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                VARCHAR(64)  NOT NULL,
    name                VARCHAR(100) NOT NULL,
    description         VARCHAR(255),
    allows_editing      BOOLEAN      NOT NULL DEFAULT FALSE,
    allows_receiving    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_terminal         BOOLEAN      NOT NULL DEFAULT FALSE,
    is_draft_state      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_pending_state    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_approved_state   BOOLEAN      NOT NULL DEFAULT FALSE,
    is_partial_state    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_completed_state  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_cancelled_state  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_rejected_state   BOOLEAN      NOT NULL DEFAULT FALSE,
    is_system           BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order       INTEGER      NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version             BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_pur_statuses PRIMARY KEY (id),
    CONSTRAINT uq_pur_statuses_code UNIQUE (code)
);
CREATE UNIQUE INDEX uq_pur_statuses_draft     ON pur_statuses (is_draft_state)     WHERE is_draft_state;
CREATE UNIQUE INDEX uq_pur_statuses_pending   ON pur_statuses (is_pending_state)   WHERE is_pending_state;
CREATE UNIQUE INDEX uq_pur_statuses_approved  ON pur_statuses (is_approved_state)  WHERE is_approved_state;
CREATE UNIQUE INDEX uq_pur_statuses_partial   ON pur_statuses (is_partial_state)   WHERE is_partial_state;
CREATE UNIQUE INDEX uq_pur_statuses_completed ON pur_statuses (is_completed_state) WHERE is_completed_state;
CREATE UNIQUE INDEX uq_pur_statuses_cancelled ON pur_statuses (is_cancelled_state) WHERE is_cancelled_state;
CREATE UNIQUE INDEX uq_pur_statuses_rejected  ON pur_statuses (is_rejected_state)  WHERE is_rejected_state;

INSERT INTO pur_statuses
    (code, name, allows_editing, allows_receiving, is_terminal,
     is_draft_state, is_pending_state, is_approved_state, is_partial_state,
     is_completed_state, is_cancelled_state, is_rejected_state, is_system, display_order) VALUES
    ('draft',              'Draft',              TRUE,  FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 10),
    ('pending-approval',   'Pending Approval',   FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 20),
    ('approved',           'Approved',           FALSE, TRUE,  FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, TRUE, 30),
    ('partially-received', 'Partially Received', FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, TRUE, 40),
    ('completed',          'Completed',          FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, FALSE, TRUE, 50),
    ('cancelled',          'Cancelled',          FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  FALSE, TRUE, 60),
    ('rejected',           'Rejected',           FALSE, FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,  TRUE, 70);

-- Configurable purchase types; number_prefix drives document numbering.
CREATE TABLE pur_types (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    description   VARCHAR(255),
    number_prefix VARCHAR(16)  NOT NULL DEFAULT 'PUR',
    is_default    BOOLEAN      NOT NULL DEFAULT FALSE,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_pur_types PRIMARY KEY (id),
    CONSTRAINT uq_pur_types_code UNIQUE (code)
);
CREATE UNIQUE INDEX uq_pur_types_default ON pur_types (is_default) WHERE is_default;

INSERT INTO pur_types (code, name, number_prefix, is_default, is_system, display_order) VALUES
    ('normal',       'Normal Purchase',       'PUR',     TRUE,  TRUE,  10),
    ('urgent',       'Urgent Purchase',       'PUR-URG', FALSE, FALSE, 20),
    ('mobile',       'Mobile Phone Purchase', 'PUR-MOB', FALSE, FALSE, 30),
    ('accessory',    'Accessory Purchase',    'PUR-ACC', FALSE, FALSE, 40),
    ('repair-parts', 'Repair Parts Purchase', 'PUR-REP', FALSE, FALSE, 50),
    ('sim-card',     'SIM Card Purchase',     'PUR-SIM', FALSE, FALSE, 60),
    ('internal',     'Internal Purchase',     'PUR-INT', FALSE, FALSE, 70),
    ('asset',        'Asset Purchase',        'PUR-AST', FALSE, FALSE, 80);

-- Configurable cancellation reasons.
CREATE TABLE pur_cancel_reasons (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_pur_cancel_reasons PRIMARY KEY (id),
    CONSTRAINT uq_pur_cancel_reasons_code UNIQUE (code)
);

INSERT INTO pur_cancel_reasons (code, name, is_system, display_order) VALUES
    ('supplier-unavailable', 'Supplier Unavailable', TRUE, 10),
    ('price-changed',        'Price Changed',        TRUE, 20),
    ('no-longer-needed',     'No Longer Needed',     TRUE, 30),
    ('ordered-by-mistake',   'Ordered by Mistake',   TRUE, 40),
    ('other',                'Other',                TRUE, 50);

-- Configurable identifier types for serialized units. satisfies_serial /
-- satisfies_imei back the per-item requirement flags.
CREATE TABLE pur_identifier_types (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code             VARCHAR(64)  NOT NULL,
    name             VARCHAR(100) NOT NULL,
    satisfies_serial BOOLEAN      NOT NULL DEFAULT FALSE,
    satisfies_imei   BOOLEAN      NOT NULL DEFAULT FALSE,
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    is_system        BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order    INTEGER      NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_pur_identifier_types PRIMARY KEY (id),
    CONSTRAINT uq_pur_identifier_types_code UNIQUE (code)
);

INSERT INTO pur_identifier_types (code, name, satisfies_serial, satisfies_imei, is_system, display_order) VALUES
    ('imei',          'IMEI',          FALSE, TRUE,  TRUE, 10),
    ('imei2',         'IMEI 2',        FALSE, TRUE,  TRUE, 20),
    ('serial',        'Serial Number', TRUE,  FALSE, TRUE, 30),
    ('barcode',       'Barcode',       FALSE, FALSE, TRUE, 40),
    ('internal-code', 'Internal Code', FALSE, FALSE, TRUE, 50);

-- Reference warehouses (destination hints only; the Inventory module owns the
-- real warehouse registry and stock).
CREATE TABLE pur_warehouses (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_pur_warehouses PRIMARY KEY (id),
    CONSTRAINT uq_pur_warehouses_code UNIQUE (code)
);

INSERT INTO pur_warehouses (code, name, display_order) VALUES ('main', 'Main Warehouse', 10);

-- Amount-based approval rules: a submitted purchase whose total reaches any
-- active threshold needs approval; otherwise it auto-approves. Multi-level /
-- department rules extend this table later without redesign.
CREATE TABLE pur_approval_rules (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(100)  NOT NULL,
    min_amount  NUMERIC(14,2) NOT NULL,
    active      BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version     BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT pk_pur_approval_rules PRIMARY KEY (id)
);

INSERT INTO pur_approval_rules (name, min_amount) VALUES
    ('Manager approval above 1,000', 1000.00);

CREATE SEQUENCE pur_number_seq START WITH 1;

-- The purchase document. Supplier references the CRM registry (single source
-- of customer/supplier truth); no supplier data is duplicated here.
CREATE TABLE purchases (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    purchase_number  VARCHAR(40)   NOT NULL,
    type_id          BIGINT        NOT NULL,
    status_id        BIGINT        NOT NULL,
    supplier_id      BIGINT        NOT NULL,
    warehouse_id     BIGINT,
    notes            VARCHAR(2000),
    total_amount     NUMERIC(14,2) NOT NULL DEFAULT 0,
    submitted_at     TIMESTAMPTZ,
    approved_at      TIMESTAMPTZ,
    approved_by      BIGINT,
    cancelled_at     TIMESTAMPTZ,
    cancelled_by     BIGINT,
    cancel_reason_id BIGINT,
    cancel_note      VARCHAR(500),
    created_by       BIGINT,
    created_by_email VARCHAR(255),
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version          BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT pk_purchases PRIMARY KEY (id),
    CONSTRAINT uq_purchases_number UNIQUE (purchase_number),
    CONSTRAINT fk_purchases_type      FOREIGN KEY (type_id)      REFERENCES pur_types (id),
    CONSTRAINT fk_purchases_status    FOREIGN KEY (status_id)    REFERENCES pur_statuses (id),
    CONSTRAINT fk_purchases_supplier  FOREIGN KEY (supplier_id)  REFERENCES customers (id),
    CONSTRAINT fk_purchases_warehouse FOREIGN KEY (warehouse_id) REFERENCES pur_warehouses (id),
    CONSTRAINT fk_purchases_cancel_reason FOREIGN KEY (cancel_reason_id) REFERENCES pur_cancel_reasons (id)
);
CREATE INDEX idx_purchases_supplier ON purchases (supplier_id);
CREATE INDEX idx_purchases_status   ON purchases (status_id);
CREATE INDEX idx_purchases_type     ON purchases (type_id);
CREATE INDEX idx_purchases_created  ON purchases (created_at);

CREATE TABLE purchase_items (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    purchase_id       BIGINT        NOT NULL,
    product_id        BIGINT        NOT NULL,
    description       VARCHAR(500),
    quantity          NUMERIC(12,3) NOT NULL,
    unit              VARCHAR(32)   NOT NULL DEFAULT 'piece',
    unit_price        NUMERIC(12,2) NOT NULL,
    discount          NUMERIC(12,2) NOT NULL DEFAULT 0,
    expected_delivery DATE,
    requires_serial   BOOLEAN       NOT NULL DEFAULT FALSE,
    requires_imei     BOOLEAN       NOT NULL DEFAULT FALSE,
    received_quantity NUMERIC(12,3) NOT NULL DEFAULT 0,
    returned_quantity NUMERIC(12,3) NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version           BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT pk_purchase_items PRIMARY KEY (id),
    CONSTRAINT fk_pi_purchase FOREIGN KEY (purchase_id) REFERENCES purchases (id) ON DELETE CASCADE,
    CONSTRAINT fk_pi_product  FOREIGN KEY (product_id)  REFERENCES products (id),
    CONSTRAINT ck_pi_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_pi_price_non_negative CHECK (unit_price >= 0),
    CONSTRAINT ck_pi_discount_non_negative CHECK (discount >= 0),
    CONSTRAINT ck_pi_received_bounds CHECK (received_quantity >= 0 AND received_quantity <= quantity),
    CONSTRAINT ck_pi_returned_bounds CHECK (returned_quantity >= 0 AND returned_quantity <= received_quantity)
);
CREATE INDEX idx_pi_purchase ON purchase_items (purchase_id);
CREATE INDEX idx_pi_product  ON purchase_items (product_id);

-- Receipts: multiple per purchase; lines record what arrived when.
CREATE TABLE purchase_receipts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    purchase_id      BIGINT       NOT NULL,
    note             VARCHAR(500),
    created_by       BIGINT,
    created_by_email VARCHAR(255),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_purchase_receipts PRIMARY KEY (id),
    CONSTRAINT fk_pr_purchase FOREIGN KEY (purchase_id) REFERENCES purchases (id) ON DELETE CASCADE
);
CREATE INDEX idx_pr_purchase ON purchase_receipts (purchase_id);

CREATE TABLE purchase_receipt_items (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    receipt_id       BIGINT        NOT NULL,
    purchase_item_id BIGINT        NOT NULL,
    quantity         NUMERIC(12,3) NOT NULL,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version          BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT pk_purchase_receipt_items PRIMARY KEY (id),
    CONSTRAINT fk_pri_receipt FOREIGN KEY (receipt_id) REFERENCES purchase_receipts (id) ON DELETE CASCADE,
    CONSTRAINT fk_pri_item    FOREIGN KEY (purchase_item_id) REFERENCES purchase_items (id) ON DELETE CASCADE,
    CONSTRAINT ck_pri_quantity_positive CHECK (quantity > 0)
);

-- Identifiers of serialized received units (IMEI, serial, …). Values are
-- globally unique per identifier type — duplicate serials are impossible.
CREATE TABLE purchase_unit_identifiers (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    receipt_item_id    BIGINT       NOT NULL,
    unit_index         INTEGER      NOT NULL,
    identifier_type_id BIGINT       NOT NULL,
    value              VARCHAR(128) NOT NULL,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_purchase_unit_identifiers PRIMARY KEY (id),
    CONSTRAINT fk_pui_receipt_item FOREIGN KEY (receipt_item_id)
        REFERENCES purchase_receipt_items (id) ON DELETE CASCADE,
    CONSTRAINT fk_pui_type FOREIGN KEY (identifier_type_id) REFERENCES pur_identifier_types (id),
    CONSTRAINT uq_pui_type_value UNIQUE (identifier_type_id, value)
);
CREATE INDEX idx_pui_value ON purchase_unit_identifiers (value);

-- Supplier returns: multiple per purchase, partial or complete.
CREATE TABLE purchase_returns (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    purchase_id      BIGINT       NOT NULL,
    reason           VARCHAR(500) NOT NULL,
    created_by       BIGINT,
    created_by_email VARCHAR(255),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_purchase_returns PRIMARY KEY (id),
    CONSTRAINT fk_pret_purchase FOREIGN KEY (purchase_id) REFERENCES purchases (id) ON DELETE CASCADE
);
CREATE INDEX idx_pret_purchase ON purchase_returns (purchase_id);

CREATE TABLE purchase_return_items (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    return_id        BIGINT        NOT NULL,
    purchase_item_id BIGINT        NOT NULL,
    quantity         NUMERIC(12,3) NOT NULL,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version          BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT pk_purchase_return_items PRIMARY KEY (id),
    CONSTRAINT fk_preti_return FOREIGN KEY (return_id) REFERENCES purchase_returns (id) ON DELETE CASCADE,
    CONSTRAINT fk_preti_item   FOREIGN KEY (purchase_item_id) REFERENCES purchase_items (id) ON DELETE CASCADE,
    CONSTRAINT ck_preti_quantity_positive CHECK (quantity > 0)
);

-- Unlimited attachments via the FileStorage port (any content type).
CREATE TABLE purchase_attachments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    purchase_id      BIGINT       NOT NULL,
    file_key         VARCHAR(255) NOT NULL,
    file_name        VARCHAR(255) NOT NULL,
    content_type     VARCHAR(128),
    file_size        BIGINT       NOT NULL,
    uploaded_by      BIGINT,
    uploaded_by_email VARCHAR(255),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_purchase_attachments PRIMARY KEY (id),
    CONSTRAINT fk_pa_purchase FOREIGN KEY (purchase_id) REFERENCES purchases (id) ON DELETE CASCADE
);
CREATE INDEX idx_pa_purchase ON purchase_attachments (purchase_id);

-- Append-only purchase history (submit, approve, receive, cancel, return…).
CREATE TABLE purchase_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    purchase_id BIGINT       NOT NULL,
    action      VARCHAR(64)  NOT NULL,
    title       VARCHAR(255) NOT NULL,
    detail      JSONB,
    actor_id    BIGINT,
    actor_email VARCHAR(255),
    occurred_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_purchase_logs PRIMARY KEY (id),
    CONSTRAINT fk_pl_purchase FOREIGN KEY (purchase_id) REFERENCES purchases (id) ON DELETE CASCADE
);
CREATE INDEX idx_pl_purchase ON purchase_logs (purchase_id, occurred_at DESC);

-- Module + permissions.
INSERT INTO modules (code, name, description, icon, path, display_order, enabled, is_system)
VALUES ('purchasing', 'Purchasing', 'Purchase orders, receiving and supplier returns',
        'mdi-cart-arrow-down', '/purchases', 68, TRUE, FALSE);

INSERT INTO permissions (module_id, action, code, name, is_system)
SELECT m.id, a.action, m.code || ':' || a.action, m.name || ' — ' || a.label, TRUE
FROM modules m
CROSS JOIN (VALUES
    ('view',    'View'),
    ('create',  'Create'),
    ('edit',    'Edit'),
    ('delete',  'Delete'),
    ('export',  'Export'),
    ('import',  'Import'),
    ('approve', 'Approve'),
    ('receive', 'Receive'),
    ('cancel',  'Cancel'),
    ('return',  'Supplier return'),
    ('manage-config', 'Manage purchasing configuration')
) AS a(action, label)
WHERE m.code = 'purchasing';
