package com.sami.app.purchasing;
import com.sami.app.common.exception.ApiException;
import com.sami.app.common.exception.ErrorCode;
import com.sami.app.accounting.publicapi.PayablePostingPort; import com.sami.app.common.tenancy.TenantContext; import com.sami.app.organization.service.*; import com.sami.app.purchasing.service.SupplierInvoiceService; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import org.springframework.jdbc.core.JdbcTemplate; import java.math.*; import java.util.*; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class SupplierInvoiceServiceBehaviorTest { @Mock JdbcTemplate jdbc; @Mock TenantContext tenants; @Mock OrganizationScopeService scope; @Mock FoundationAuditService audit; @Mock PayablePostingPort payable; SupplierInvoiceService service;
 @BeforeEach void setup(){service=new SupplierInvoiceService(jdbc,tenants,scope,audit,Optional.of(payable));lenient().when(tenants.requireTenantId()).thenReturn(7L);lenient().when(jdbc.queryForList(anyString(),eq(7L),eq(9L))).thenReturn(List.of(Map.of("id",1L)));}
 @Test void alreadyIssuedIsIdempotent(){Map<String,Object> row=new HashMap<>(Map.of("status","ISSUED","company_id",1L,"branch_id",2L));when(jdbc.queryForMap(anyString(),any(Object[].class))).thenReturn(row);assertEquals("ISSUED",service.issue(9L).get("status"));verifyNoInteractions(payable);}
 @Test void payableSuccessIssuesDraftAndAudits(){Map<String,Object> draft=invoiceRow("DRAFT"),issued=invoiceRow("ISSUED");issued.put("payable_posting_reference","PAYABLE-4");stubIssueRows(draft,issued);when(payable.createPayable(any())).thenReturn("PAYABLE-4");assertEquals("ISSUED",service.issue(9L).get("status"));verify(payable).createPayable(argThat(c->c.supplierInvoiceId().equals(9L)&&c.amount().equals(BigDecimal.TEN)));verify(audit,atLeastOnce()).record(eq(7L),eq(1L),eq(2L),eq("SUPPLIER_INVOICE"),eq(9L),anyString(),any(),anyMap());}
 @Test void payableFailureLeavesDraft(){Map<String,Object> draft=invoiceRow("DRAFT");stubIssueRows(draft,draft);when(payable.createPayable(any())).thenThrow(new IllegalStateException("failed"));assertThrows(IllegalStateException.class,()->service.issue(9L));verify(payable).createPayable(any());}
 @Test void tenantScopedLookupRejectsInvoiceFromAnotherTenant(){when(jdbc.queryForMap(anyString(),any(Object[].class))).thenThrow(new RuntimeException("not found"));ApiException ex=assertThrows(ApiException.class,()->service.issue(9L));assertEquals(ErrorCode.RESOURCE_NOT_FOUND,ex.getErrorCode());verifyNoInteractions(payable);}
 @Test void organizationScopeRejectsCompanyOrBranch(){Map<String,Object> row=invoiceRow("DRAFT");when(jdbc.queryForMap(anyString(),any(Object[].class))).thenReturn(row);doThrow(new ApiException(ErrorCode.ACCESS_DENIED,"scope")).when(scope).requireScope(1L,2L);ApiException ex=assertThrows(ApiException.class,()->service.issue(9L));assertEquals(ErrorCode.ACCESS_DENIED,ex.getErrorCode());verifyNoInteractions(payable);}
 @Test void invalidPurchaseOrderIsRejectedBeforePosting(){Map<String,Object> invoice=invoiceRow("DRAFT");when(jdbc.queryForMap(anyString(),any(Object[].class))).thenAnswer(i->{String q=i.getArgument(0);return q.contains("supplier_invoices")?invoice:Map.of("company_id",9L,"branch_id",9L,"supplier_id",3L);});ApiException ex=assertThrows(ApiException.class,()->service.issue(9L));assertEquals(ErrorCode.ACCESS_DENIED,ex.getErrorCode());verifyNoInteractions(payable);}
 @Test void unconfirmedOrMissingGoodsReceiptIsRejected(){Map<String,Object> invoice=invoiceRow("DRAFT");when(jdbc.queryForMap(anyString(),any(Object[].class))).thenAnswer(i->{String q=i.getArgument(0);if(q.contains("supplier_invoices"))return invoice;throw new RuntimeException("receipt not confirmed");});ApiException ex=assertThrows(ApiException.class,()->service.issue(9L));assertEquals(ErrorCode.RESOURCE_NOT_FOUND,ex.getErrorCode());verifyNoInteractions(payable);}
 @Test void supplierMismatchIsRejected(){Map<String,Object> invoice=invoiceRow("DRAFT");Map<String,Object> order=new HashMap<>(Map.of("company_id",1L,"branch_id",2L,"supplier_id",44L));when(jdbc.queryForMap(anyString(),any(Object[].class))).thenAnswer(i->{String q=i.getArgument(0);if(q.contains("supplier_invoices"))return invoice;return order;});ApiException ex=assertThrows(ApiException.class,()->service.issue(9L));assertEquals(ErrorCode.VALIDATION_FAILED,ex.getErrorCode());verifyNoInteractions(payable);}
 @Test void invalidLifecycleIsRejected(){Map<String,Object> cancelled=invoiceRow("CANCELLED");when(jdbc.queryForMap(anyString(),any(Object[].class))).thenReturn(cancelled);ApiException ex=assertThrows(ApiException.class,()->service.issue(9L));assertEquals(ErrorCode.VALIDATION_FAILED,ex.getErrorCode());verifyNoInteractions(payable);}
 @Test void auditCapturesPayableAndIssueEvents(){Map<String,Object> draft=invoiceRow("DRAFT"),issued=invoiceRow("ISSUED");issued.put("payable_posting_reference","PAY-9");stubIssueRows(draft,issued);when(payable.createPayable(any())).thenReturn("PAY-9");service.issue(9L);verify(audit).record(eq(7L),eq(1L),eq(2L),eq("SUPPLIER_INVOICE"),eq(9L),eq("PAYABLE_POSTED"),isNull(),anyMap());verify(audit).record(eq(7L),eq(1L),eq(2L),eq("SUPPLIER_INVOICE"),eq(9L),eq("ISSUED"),isNull(),anyMap());}
 private Map<String,Object> invoiceRow(String status){return new HashMap<>(Map.of("status",status,"company_id",1L,"branch_id",2L,"supplier_id",3L,"total",BigDecimal.TEN,"purchase_order_id",4L,"goods_receipt_id",5L));}
 private void stubIssueRows(Map<String,Object> invoice,Map<String,Object> finalInvoice){Map<String,Object> source=Map.of("company_id",1L,"branch_id",2L,"supplier_id",3L,"received_quantity",BigDecimal.ONE,"product_id",8L);int[] calls={0};when(jdbc.queryForMap(anyString(),any(Object[].class))).thenAnswer(inv->{String q=inv.getArgument(0);if(q.contains("supplier_invoices"))return calls[0]++==0?invoice:finalInvoice;return source;});when(jdbc.queryForList(argThat(q->q.contains("supplier_invoice_lines")),any(Object[].class))).thenReturn(List.of(Map.of("goods_receipt_line_id",6L,"quantity",BigDecimal.ONE)));}
}
